### ISSUE TITLE
Example file name

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-bids#1]
Is there a particular reason the example file is called 'plot_mne_sample'? is there a final intention to plot something?

**Comment by jasmainak** [comment]
Hey, it's a [requirement from sphinx gallery](https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-examples-matching-a-pattern). Maybe later, we can update this example to plot some quality assurance figure. Like histogram of different types of files in the dataset etc.

**Comment by choldgraf** [comment]
FWIW it doesn't *have* to be `plot_`. It just needs to match some regex pattern. E.g., with Matplotlib I set it so that it matches any filename that *doesn't* have the letters `sgskip` in it:

https://github.com/matplotlib/matplotlib/blob/master/doc/conf.py#L102

**Comment by jasmainak** [comment]
haha, I know @choldgraf :) I added the feature in sphinx-gallery and I'm glad it works so well ;) I can change it if you insist :)

**Comment by choldgraf** [comment]
haha - I'm not gonna push one way or the other. but if you think it looks nicer not to have `plot_` in every example I won't stop you :-D
