### ISSUE TITLE
preprocessed EEG data from Fieldtrip to Bids

### ISSUE THREAD

**Issue by OosterveldCas** [mne-tools/mne-bids#1004]
Hi, I am trying to convert my EEG data into a bids format but keep running into two errors that I can't seem to get around.
A little information about the dataset:
- It's preprocessed with Fieldtrip in Matlab, the file is .mat
- I'm converting it one subject at a time and one group at a time (experimental vs control); so just one file with one subject in one condition
- The data is divided in cells, each cell contains EEG data from a certain time-frame (resulting in one row with 21 columns)

I have tried doing the following:

`#Sampling frequency (Hz)
sfreq = 1000 
#Definition of channel types and names.
ch_types = ['eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg','eeg']
ch_names = ['Fp1','Fp2','F3','F4','C3','C4','P3','P4','O1','O2','F7','F8','T7','T8','P7','P8','Fz','Cz','Pz','Oz','FC1','FC2','CP1','CP2','FC5','FC6','CP5','CP6','TP9','TP10','POz','ECG','VEOG','EMGfront','EMGtemp','FCz']
#Creation of info object
info = mne.create_info(ch_names=ch_names, sfreq=sfreq, ch_types=ch_types)

filename = '/directory/data_trialsmxm_3s.mat'

myepochs = mne.io.read_epochs_fieldtrip(filename, info, data_name= 'data_trialsmxm_3s')
`

But I either get this error:

`RuntimeError                              Traceback (most recent call last)
<ipython-input-4-47d25a9660fa> in <module>
      9 filename = '/Users/casoosterveld/Desktop/Masters Thesis StarLab/DMT_clean4Entheon/S10DL/DMT/data_trialsmxm_3s.mat'
     10 
---> 11 myepochs = mne.io.read_epochs_fieldtrip(filename, info, data_name= 'data_trialsmxm_3s')
     12 

~/opt/anaconda3/lib/python3.8/site-packages/mne/io/fieldtrip/fieldtrip.py in read_epochs_fieldtrip(fname, info, data_name, trialinfo_column)
    118     ft_struct = ft_struct[data_name]
    119 
--> 120     _validate_ft_struct(ft_struct)
    121 
    122     info = _create_info(ft_struct, info)  # create info structure

~/opt/anaconda3/lib/python3.8/site-packages/mne/io/fieldtrip/utils.py in _validate_ft_struct(ft_struct)
     34     """Run validation checks on the ft_structure."""
     35     if isinstance(ft_struct, list):
---> 36         raise RuntimeError('Loading of data in cell arrays is not supported')
     37 
     38 

RuntimeError: Loading of data in cell arrays is not supported
`

Which made me think I should convert the cells into regular arrays in MatLab, which always gives me the "KeyError" for the the name of the datafile.

Any help would be highly appreciated!

**Comment by sappelhoff** [comment]
Sounds like you should use fieldtrip's data2bids functionality 🤔

https://github.com/fieldtrip/fieldtrip/blob/master/data2bids.m
