### ISSUE TITLE
Manufacturers list does not include an extension for the EGI device

### ISSUE THREAD

**Issue by anandsaini024** [mne-tools/mne-bids#1005]
While using write_raw_bids() for the .mff data file (EGI Device), it throws an error because ``mne-bids`` infers the manufacturer information from the file extension. In my case the when it looks for extension in the files, it is '.bin'.

The manufactures [list](https://github.com/mne-tools/mne-bids/blob/14dde8535d0538537b04fde1c9f1b4dc854239ea/mne_bids/config.py#:~:text=eeg_manufacturers%20%3D%20%7B,%27Neuroscan%27%7D) does not include the manufacturer's details in the dictionary for EGI devices.

Although If the file format is non-standard for the manufacturer, it is required to update the manufacturer field in the sidecars manually. However, reporting this as you probably would want to include the EGI in the manufacturers list as well.

The error:

---------------------------------------------------------------------------
KeyError    Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 write_raw_bids(raw, bids_path, format='BrainVision', allow_preload=True, overwrite=True)

File <decorator-gen-593>:24, in write_raw_bids(raw, bids_path, events_data, event_id, anonymize, format, symlink, empty_room, allow_preload, montage, acpc_aligned, overwrite, verbose)

File c:\users\asaini\desktop\..\venv\lib\site-packages\mne_bids\write.py:1668, in write_raw_bids(***failed resolving arguments***)
   1663 make_dataset_description(bids_path.root, name=" ", overwrite=False)
   1665 _sidecar_json(raw, task=bids_path.task, manufacturer=manufacturer,
   1666               fname=sidecar_path.fpath, datatype=bids_path.datatype,
   1667               emptyroom_fname=associated_er_path, overwrite=overwrite)
-> 1668 _channels_tsv(raw, channels_path.fpath, overwrite)
   1670 # create parent directories if needed
   1671 _mkdir_p(os.path.dirname(data_path))

File c:\users\asaini\desktop\..\venv\lib\site-packages\mne_bids\write.py:110, in _channels_tsv(raw, fname, overwrite)
    108 # get the manufacturer from the file in the Raw object
    109 _, ext = _parse_ext(raw.filenames[0])
--> 110 manufacturer = MANUFACTURERS[ext]
    112 ignored_channels = IGNORED_CHANNELS.get(manufacturer, list())
    114 status, ch_type, description = list(), list(), list()

KeyError: '.bin'

**Comment by adam2392** [comment]
If it's readable by MNE, we can prolly add it? 

Wdyt @hoechenberger @sappelhoff

**Comment by mscheltienne** [comment]
I think it was read with [`read_raw_egi`](https://mne.tools/stable/generated/mne.io.read_raw_egi.html), which fills the `raw._filenames` list with the `.bin` file.

**Comment by sappelhoff** [comment]
> If it's readable by MNE, we can prolly add it? 
> 
> Wdyt @hoechenberger @sappelhoff 

Agreed!

**Comment by adam2392** [comment]
want to submit a PR? @anandsaini024 or @mscheltienne

**Comment by sappelhoff** [comment]
closed in #1006
