### ISSUE TITLE
Place processed .fif files in the correct location

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#101]
Currently if you convert a .fif file which has been processed by MaxFilter the processing info is ignored and the file is just placed in the usual place. However we expect that the file actually go in the `derivatives` folder (I believe as a sub-folder of `meg`).
They also have a `proc-` tag in their name to indicate the processing done.
Finally, I think we should be able to pull out at least some processing information from the file as `raw.info['proc_histroy']` has at least some information about that processing was done (I don't know anything about the processing step, so I don't really know what the data I am looking at means...)

**Comment by jasmainak** [comment]
The BIDS spec stipulates that "minimally processed" files need not be placed in the `derivatives/` folder. Since `MaxFilter` is ubiquitously applied for Elekta data, it is not necessarily placed in the derivatives.

That being said, it'd be good to include processing information from `raw.info['proc_history']` into the `SoftwareFilters` field.

**Comment by monkeyman192** [comment]
I thought the specification literally has the tsss and sss MaxFilter processing listed as being placed in derivatives (its in the appendix for the elekta specific data)

**Comment by jasmainak** [comment]
huh, indeed. You are right. I guess this was changed at some point. Which means it needs to be tackled in the derivatives :-)

**Comment by jasmainak** [comment]
moving this to next release as it seems there needs to be some movement in bids derivatives spec for this ...

**Comment by hoechenberger** [comment]
This will be addressed once we start adding derivatives support, which is still not really specified. But things have started to move again on the BIDS side, so …
