### ISSUE TITLE
`write_raw_bids` shoudn't write stim channels to `electrodes.tsv`

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-bids#1022]
I suppose I will label this as a bug, as the current behaviour is inconsistent with the BIDS standard, per discussion in #1006 

`write_raw_bids` shouldn't write stim channels to the `electrodes.tsv` sidecar file, because stim channels don't have associated electrodes.

I can amend the code in `_write_electrodes_tsv`, and submit a PR. I will suggest something like:
```
if ch['kind'] == FIFF.FIFFV_STIM_CH:
    continue
```
at the beginning of this for loop:
https://github.com/mne-tools/mne-bids/blob/54d50f61e01424081793db7ef3f68659319056cc/mne_bids/dig.py#L140-L152

**Comment by hoechenberger** [comment]
+1 on fixing this, I like your proposal!

**Comment by scott-huberty** [comment]
Okay! included a `logger.debug` message and submitted a PR!
