### ISSUE TITLE
DOC: Document a good example of make_dataset_description

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids#1024]
We should modify the `sample` dataset example to use this, showing at least the following fields:
```
make_dataset_description(
    path=...,
    name=...,
    authors=[...],
    how_to_acknowledge='...',
    data_license='CC-BY-SA',  # or whatever the best one is now, prob. commented out b/c it's not appropriate for 'sample'
    ethics_approvals=['...'],
    references_and_links=['...'],
    overwrite=True)
```
If someone knows of a good example to follow for this, I can make a PR.

I ask because I'm making my first BIDS-compatible dataset (FINALLY!) and I was hoping to find this in the SG cross-refs for https://mne.tools/mne-bids/stable/generated/mne_bids.make_dataset_description.html#mne_bids.make_dataset_description, but no dice...

**Comment by larsoner** [comment]
cc @sappelhoff @hoechenberger I assume one of you knows a good example to follow, perhaps even a link to a GH repo with a call to a command I can just lift these from...?

**Comment by larsoner** [comment]
Should I just adapt https://github.com/sappelhoff/bids-examples/blob/master/ds000248/dataset_description.json so that the example actually produces a `dataset_description.json` like this?

And maybe also the `README` like this?

https://github.com/sappelhoff/bids-examples/blob/master/ds000248/README

**Comment by sappelhoff** [comment]
> I ask because I'm making my first BIDS-compatible dataset (FINALLY!)

:tada: 

> Should I just adapt https://github.com/sappelhoff/bids-examples/blob/master/ds000248/dataset_description.json so that the example actually produces a dataset_description.json like this?
And maybe also the README like this?

sounds reasonable to me!
