### ISSUE TITLE
complete `.zenodo.json` metadata

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1025]
Our `.zenodo.json` file controls which contributors get listed in the [Zenodo code archive](https://zenodo.org/record/6359371):

https://github.com/mne-tools/mne-bids/blob/13d2b975393f5ba55f4b3a7a8bee4a164c08fa1a/.zenodo.json#L1-L4

I feel like adding the contributors that are currently not listed to that file in a PR, and making that a "custom" (to add new contributors also to the zenodo metadata). I think that's a nice "reward" for contributions. Any objections?

**Comment by hoechenberger** [comment]
No objections.
