### ISSUE TITLE
[BUG] parsing scans.tsv is currently too restrictive for BrainVision files

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#1033]
#### Describe the bug
After reading through the BIDS spec for the `_scans.tsv` to check that this is indeed an error, it doesn't specify which filename should be used in the tsv. This is particularly ambiguous when it comes to BrainVision where the data are stored across three different files: `.vhdr`, `.vmrk`, and `.eeg`. By default, mne-bids assumes the file in the `_scans.tsv` will be `.vhdr`, but it could be `.eeg` or `.vmrk` as well. We currently only test for whether it's `.vhdr` [here](https://github.com/mne-tools/mne-bids/blob/main/mne_bids/tests/data/tiny_bids/sub-01/ses-eeg/sub-01_ses-eeg_scans.tsv#L2). 

However, after reading a BIDS dataset, we found that it could also have the `.eeg` as seen [here](https://openneuro.org/datasets/ds003688/versions/1.0.7/file-display/sub-45:ses-iemu:sub-45_ses-iemu_scans.tsv).

**Comment by sappelhoff** [comment]
[convenience link to "scans.tsv"](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#scans-file)

good point ... do you think it'd make sense to add a recommendation to the BIDS spec along the lines that if a data format consists of multiple files (BrainVision, EEGLAB, ...), then the file which is typically read in should be listed in scans.tsv.

- For BrainVision: vhdr (and not vmrk, eeg)
- For EEGLAB: set (and not fdt)
- ...

?

And agreed that we should improve the checks in mne-bids to be more inclusive.

**Comment by teonbrooks** [comment]
Yes, I think that would be nice to have included but it would likely need to go in the iEEG and EEG specific BIDS specs since this section is for modality-agnostic. 
also, I wonder if there's a way to see to make to broadcast to other developers about this recommendation if it's accepted.

**Comment by sappelhoff** [comment]
See my proposal in https://github.com/bids-standard/bids-specification/pull/1178

>  also, I wonder if there's a way to see to make to broadcast to other developers about this recommendation if it's accepted.

not really, I would hope that they read the changelog when BIDS 1.8 is released in september
