### ISSUE TITLE
How to display the visual difference between two groups using GLM?

### ISSUE THREAD

**Issue by G21R** [mne-tools/mne-bids#1036]
I am working with the birds data format for nirx group analysis. I apologize for my English.I would like to know if it is possible to calculate the contrast for two different groups of the same experiment? I have two different groups (Those who do well in math and those who do poorly) they are undergoing one experiment. But how do I get visual information about the contrast and differences of these two groups?

**Comment by G21R** [comment]
I want to get something like that.The photo shows information about the contrast between different events in the same group. But as I wrote above, I need to get a contrast between two different groups (preferably both for the same events and for different ones). I use the GLM model. Unfortunately, I have not found information on how to calculate the contrast between two different groups in one study. Please help me in any way you can
![image](https://user-images.githubusercontent.com/101802504/182674040-24f36eed-d020-4d6a-a310-09554e9e08d3.png)

**Comment by adam2392** [comment]
Hi @G21R this repo is dedicated to reading and writing of BIDS datasets. 

The GH issues is dedicated also to bugs or feature requests. 

Your problem seems to be an implementation question. Perhaps it is best asked in the discourse forum or in office hours. 

Thanks!

**Comment by larsoner** [comment]
Indeed https://mne.discourse.group/ seems like an appropriate place
