### ISSUE TITLE
BIDS channel type issue

### ISSUE THREAD

**Issue by arnodelorme** [mne-tools/mne-bids#1046]
bids_path = BIDSPath(root='../ds003061')

Channels 65 to 79 are not EEG (and marked as such in the BIDS repo). Yet MNE thinks 2 of these channels are EEG.

https://openneuro.org/datasets/ds003061

**Comment by adam2392** [comment]
Hi @arnodelorme

Is this an error when you read the file? BIDSPath is just a class for creating file paths in bids datasets. I'm guessing maybe when you run read_raw_bids(?)

is it possible for you to upload a code segment and also the MNE and related package versions? E.g. a Minimal working example for the error. 

output of 'mne sys_info' will show you the relevant versions.

**Comment by adam2392** [comment]
Hi @arnodelorme

Is this an error when you read the file? BIDSPath is just a class for creating file paths in bids datasets. I'm guessing maybe when you run read_raw_bids(?)

is it possible for you to upload a code segment and also the MNE and related package versions? E.g. a Minimal working example for the error. 

output of 'mne sys_info' will show you the relevant versions.

**Comment by arnodelorme** [comment]
Of course

```python
import os
import os.path as op
import mne
from mne.datasets import sample
from mne_bids import BIDSPath, read_raw_bids, print_dir_tree, make_report, inspect_dataset, mark_channels

bids_path = BIDSPath(root='ds003061', datatype='eeg', suffix = 'eeg')
res = bids_path.match()
rawraw = read_raw_bids(bids_path=res[0], verbose=False)
```

ds003061 is available from https://openneuro.org/datasets/ds003061

**Comment by arnodelorme** [comment]
Sys info

```

Platform:         macOS-10.16-x86_64-i386-64bit
Python:           3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
Executable:       /Users/arno/miniconda3/envs/p38env/bin/python
CPU:              i386: 16 cores
Memory:           Unavailable (requires "psutil" package)
mne:              1.1.0
numpy:            1.19.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:            1.4.1
matplotlib:       3.3.3 {backend=module://ipykernel.pylab.backend_inline}

sklearn:          0.24.1
numba:            Not found
nibabel:          Not found
nilearn:          Not found
dipy:             Not found
cupy:             Not found
pandas:           1.2.1
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              Not found
qtpy:             Not found
ipympl:           Not found
pyqtgraph:        Not found
pooch:            v1.6.0

mne_bids:         0.10
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   Not found
mne_connectivity: Not found
mne_icalabel:     Not found   
```

**Comment by hoechenberger** [comment]
@arnodelorme 
`*_channels.tsv` (and `_electrodes.tsv`) only contain a small subset of the channels present in the data. Hence, I would argue that the dataset is corrupted or incomplete, and the only reason the BIDS validator doesn't complain is because it lacks that capability of actually loading and inspecting the data.

One could argue that MNE-BIDS should handle things more gracefully here (or raise an exception); but ultimately I'd say the dataset needs to be fixed.

> and marked as such in the BIDS repo

But where?

**Comment by arnodelorme** [comment]
Yes, but this is the actual file. You can see that GSR1 and 2 have the type GSR and that TEMP has the type TEMP which are regular BIDS types.

https://openneuro.org/datasets/ds003061/versions/1.1.1/file-display/sub-001:eeg:sub-001_task-P300_run-1_channels.tsv

```
name	type	units
Fp1	EEG	microV
AF7	EEG	microV
AF3	EEG	microV
F1	EEG	microV
F3	EEG	microV
F5	EEG	microV
F7	EEG	microV
FT7	EEG	microV
FC5	EEG	microV
FC3	EEG	microV
FC1	EEG	microV
C1	EEG	microV
C3	EEG	microV
C5	EEG	microV
T7	EEG	microV
TP7	EEG	microV
CP5	EEG	microV
CP3	EEG	microV
CP1	EEG	microV
P1	EEG	microV
P3	EEG	microV
P5	EEG	microV
P7	EEG	microV
P9	EEG	microV
PO7	EEG	microV
PO3	EEG	microV
O1	EEG	microV
Iz	EEG	microV
Oz	EEG	microV
POz	EEG	microV
Pz	EEG	microV
CPz	EEG	microV
Fpz	EEG	microV
Fp2	EEG	microV
AF8	EEG	microV
AF4	EEG	microV
AFz	EEG	microV
Fz	EEG	microV
F2	EEG	microV
F4	EEG	microV
F6	EEG	microV
F8	EEG	microV
FT8	EEG	microV
FC6	EEG	microV
FC4	EEG	microV
FC2	EEG	microV
FCz	EEG	microV
Cz	EEG	microV
C2	EEG	microV
C4	EEG	microV
C6	EEG	microV
T8	EEG	microV
TP8	EEG	microV
CP6	EEG	microV
CP4	EEG	microV
CP2	EEG	microV
P2	EEG	microV
P4	EEG	microV
P6	EEG	microV
P8	EEG	microV
P10	EEG	microV
PO8	EEG	microV
PO4	EEG	microV
O2	EEG	microV
EXG1	MISC	n/a
EXG2	MISC	n/a
EXG3	MISC	n/a
EXG4	MISC	n/a
EXG5	MISC	n/a
EXG6	MISC	n/a
EXG7	MISC	n/a
EXG8	MISC	n/a
GSR1	GSR	n/a
GSR2	GSR	n/a
Erg1	MISC	n/a
Erg2	MISC	n/a
Resp	RESP	n/a
Plet	MISC	n/a
Temp	TEMP	n/a
```

**Comment by hoechenberger** [comment]
> Yes, but this is the actual file. You can see that GSR1 and 2 have the type GSR and that TEMP has the type TEMP which are regular BIDS types.
> 
> https://openneuro.org/datasets/ds003061/versions/1.1.1/file-display/sub-001:eeg:sub-001_task-P300_run-1_channels.tsv

Oh, right.

I only looked at the TSV in my web browser and didn't realize there was a scrollbar on the right, so I only saw the first few channels 🤦

**Comment by hoechenberger** [comment]
We currently use the following channel type mapping from BIDS to MNE:
https://github.com/mne-tools/mne-bids/blob/16a7b0c1a4348256f6781f539cd82c0acf444de3/mne_bids/utils.py#L77-L83

We need to add `TEMP` and `GSR` here.

I don't believe MNE has "proper" support for these, so we should map them to `misc`.
@larsoner @agramfort WDYT?

@sappelhoff I don't think we should silently apply the BIDS datatype's channel type to channels for which we don't have a proper BIDS -> MNE mapping defined; instead, we should default to `misc`. WDYT?

**Comment by hoechenberger** [comment]
> RESP='resp',

Either this is a bug, or we have incorrect documentation in MNE – `RESP` is **not** "respiration"

https://github.com/mne-tools/mne-python/blob/8baaa7675ea34d3b98dd2875ad8b5efaf6d44d16/mne/io/pick.py#L400-L402

We'd need to check the FIFF specs.

**Comment by hoechenberger** [comment]
… says "respiration monitoring" here:

https://github.com/mne-tools/fiff-constants/blob/30d89d420d50c9e465f46524d4901795dac66741/DictionaryTypes.txt#L257

@larsoner What's correct now..? Is "resp" for "response" or for "respiration"?

**Comment by agramfort** [comment]
for some reason my answer from yesterday never appeared here. Let me paste it here:

this data contains channels with type "temp" and "GSR"

I don't think its part of the standard. Cf https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv

Type of channel; MUST use the channel types listed below. Note that the type MUST be in upper-case.  

Must be one of: "MEGMAG", "MEGGRADAXIAL", "MEGGRADPLANAR", "MEGREFMAG", "MEGREFGRADAXIAL", "MEGREFGRADPLANAR", "MEGOTHER", "EEG", "ECOG", "SEEG", "DBS", "VEOG", "HEOG", "EOG", "ECG", "EMG", "TRIG", "AUDIO", "PD", "EYEGAZE", "PUPIL", "MISC", "SYSCLOCK", "ADC", "DAC", "HLU", "FITERR", "OTHER".

mne_bids converts them to EEG when it does not understand the type. You should get warnings when attempting to read the files with:

```python
from mne_bids import BIDSPath, read_raw_bids

bp = BIDSPath(
    root='./',
    subject='001',
    task='P300',
    run='1',
    datatype='eeg',
    suffix='eeg',
    extension='.set',
)

raw = read_raw_bids(bp)
```

**Comment by hoechenberger** [comment]
> I don't think its part of the standard.


It is, you need to scroll down a little:

![image](https://user-images.githubusercontent.com/2046265/183889941-a7ec7d3d-16f7-4426-9960-6fb6aeb3d6bb.jpeg)

**Comment by larsoner** [comment]
> @larsoner What's correct now..? Is "resp" for "response" or for "respiration"?

the `fif-constants` should be the gold standard, and it's "respiration" there, too:

https://github.com/mne-tools/fiff-constants/blob/aae5960007ee8a67dfc07535ea37d421d37dfe1b/DictionaryTypes.txt#L257

So our docs are wrong, can you make a quick PR to fix them?

**Comment by larsoner** [comment]
Okay great!

**Comment by agramfort** [comment]
next channel type we should add is temp (temperature in celsius)

**Comment by hoechenberger** [comment]
@arnodelorme 
With #1052, we now set the type of all "unknown" and yet-unsupported BIDS channel types to "misc" when reading the data with MNE-BIDS.

This ensures that the temperature and GSR channels in your dataset will not show up as "eeg" channels anymore (but as "misc").

The next step for us is to amend the FIFF standard and add a proper EDA/GSR and temperature channel type. We're tracking this at https://github.com/mne-tools/mne-python/issues/11055

**Comment by arnodelorme** [comment]
Wonderful. Thanks

**Comment by hoechenberger** [comment]
@arnodelorme Tenoerature and GSR channels should now work as expected when combining the development versions of MNE-Python and MNE-BIDS. 

Well, no quite, as we still have an issue with plotting. But loading and processing the data should all be good!

**Comment by arnodelorme** [comment]
You can scroll down this page to see the official BIDS channel types.

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv
