### ISSUE TITLE
Add "description" entity to BIDSPath

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#1049]
See https://openneuro.org/datasets/ds003775/versions/1.0.0/file-display/derivatives:cleaned_data:sub-001:ses-t1:eeg:sub-001_ses-t1_task-resteyesc_desc-cleaned_eeg.set

File is called `sub-001_ses-t1_task-resteyesc_desc-cleaned_eeg.set`
What is this `desc` thing? Currently I cannot load this file with mne-bids as we have no such thing...

ping @sappelhoff @hoechenberger

**Comment by agramfort** [comment]
actually it's documented at https://bids-specification.readthedocs.io/en/stable/99-appendices/09-entities.html#desc ... I am renaming the issue title

**Comment by adam2392** [comment]
The desc keyword would enable some BIDS pathing through derivatives.

**Comment by agramfort** [comment]
can you take a stab at the PR to support this entity?

**Comment by hoechenberger** [comment]
I'm surprised we don't already support this, I remember us discussing a while back if we could use it for derivatives. Definitely should be added.

**Comment by sappelhoff** [comment]
apparently we also discussed this earlier in:

- #449

**Comment by agramfort** [comment]
can you take stab at it ?

**Comment by hoechenberger** [comment]
Yes I can take a look.
