### ISSUE TITLE
BUG: Handling subjects that don't start with sub- ?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids#1065]
For this dataset:

https://openneuro.org/datasets/ds001971/versions/1.1.1/file-display/participants.tsv

<img width="470" alt="Screen Shot 2022-09-10 at 2 20 43 PM" src="https://user-images.githubusercontent.com/2365790/189496648-be16858a-b137-4af8-82fc-122f36abbef2.png">

I can't load it with MNE-BIDS (via MNE-BIDS-Pipeline):
```
  File "/Users/larsoner/python/mne-bids-pipeline/config.py", line 3453, in _load_data
    raw = read_raw_bids(bids_path=bids_path,

  File "<decorator-gen-612>", line 12, in read_raw_bids

  File "/Users/larsoner/python/mne-bids/mne_bids/read.py", line 793, in read_raw_bids
    raw = _handle_participants_reading(

  File "/Users/larsoner/python/mne-bids/mne_bids/read.py", line 200, in _handle_participants_reading
    row_ind = _safe_index(subjects, subject, allow_all=True)

  File "/Users/larsoner/python/mne-bids/mne_bids/read.py", line 194, in _safe_index
    raise ValueError(f'{exc}{extra}') from None

ValueError: 'sub-001' is not in list. Did you mean one of ['CQ2', 'BT4', 'CQ1', 'CQ3', 'CP9', 'CA7', 'CB6', 'BV2', 'CP8', 'CP1', 'CP2', 'CO9', 'CP5', 'CL1', 'BL7', 'CO3', 'CE2', 'CV6', 'CJ2', 'CY8']?
```

Because it seems like there is a mismatch between the `participant_id` and the filenames:

<img width="612" alt="Screen Shot 2022-09-10 at 2 21 38 PM" src="https://user-images.githubusercontent.com/2365790/189496713-4e832f4d-1765-4a19-8d18-fec4ab08c640.png">

Is this a bug with MNE-BIDS, or with the dataset? If it's with the dataset, it's also a bug with the validator since it's green on OpenNeuro (other than a warning about not all subjects having the same files), right?

**Comment by hoechenberger** [comment]
It's a bug with the dataset, IMHO it doesn't conform to BIDS this way

**Comment by hoechenberger** [comment]
Our error message isn't very helpful though ....

**Comment by larsoner** [comment]
So we should open an issue/comment on OpenNeuro, and also on the BIDS-Validator, then?

**Comment by sappelhoff** [comment]
> So we should open an issue/comment on OpenNeuro, and also on the BIDS-Validator, then?

That'd be great!

**Comment by hoechenberger** [comment]
I just checked the specs:

<img width="687" alt="Screen Shot 2022-09-10 at 20 41 12" src="https://user-images.githubusercontent.com/2046265/189497301-96f5caa9-55eb-4243-8ed1-239e31bb28c1.png">

https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file

So implementing a fix for the validator should be quite trivial – it simply needs to check

```javascript
participant.startsWith('sub-')`
```
for each entry in the `participant_id` column

**Comment by larsoner** [comment]
Hah! On openneuro:

> By richard.hoechenberger@gmail.com - over 1 year ago
> Hello, currently, `participants.tsv` contains two `participant_id` columns, of which only the first seems to be the "correct" one in BIDS terms. Two columns with identical names will cause problems with many software packages, which rely on unique descriptors. Do you think you could update the dataset? Let me know if I can help you.
Best wishes,
Richard

> So implementing a first quick fix for the validator should be quite trivial – it simply needs to check

@hoechenberger do you want to open one for the BIDS-Validator as well if you haven't already? It seems like it should have caught this and at least warned (if not raised an error) when they ran it...

**Comment by hoechenberger** [comment]
> Hah! [On openneuro](https://openneuro.org/datasets/ds001971/versions/1.1.1):
> 
> > By [richard.hoechenberger@gmail.com](mailto:richard.hoechenberger@gmail.com) - over 1 year ago

Hahaha, damn … 

> @hoechenberger do you want to open one for the BIDS-Validator as well if you haven't already? It seems like it should have caught this and at least warned (if not raised an error) when they ran it...

I'll happily leave this to you if you have time :)

So I think this is actually **two** things that need to be addressed in the validator:

1. ensure column names in TSVs are unique
2. ensure subject IDs start with `sub-`

**Comment by larsoner** [comment]
Closing for https://github.com/bids-standard/bids-validator/issues/1530
