### ISSUE TITLE
`key_press_event` is deprecated, needs to be replaced in our code

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1068]
see: https://github.com/mne-tools/mne-bids/actions/runs/3145484445/jobs/5112832235#step:14:1665

**Comment by hoechenberger** [comment]
I wonder if we shouldn't just remove the Inspector (the source of the warnings) … does anyone actually use it?
I put a lot of time and energy into its creation but I feel it's kind of obsolete these days…

**Comment by adam2392** [comment]
If it gets integrated with the mne qt browser that would become super slick.

**Comment by sappelhoff** [comment]
>  I put a lot of time and energy into its creation but I feel it's kind of obsolete these days…

hurts to read this ^^

I wouldn't purge that code, I am hopeful somebody finds it useful (although I personally haven't used it yet).
