### ISSUE TITLE
non-eeg channels are dropped from eeg files

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#107]
I noticed that the EMG channel type wasn't included in the list of types, so I was going to make a nice easy PR to fix it...
**But** then, as I was writing a test I discovered that if I set the type of channel to EMG in an eeg file (was testing edf data since part of the test already modifies a channel so I figured I'd piggyback off that), this channel is dropped.
I narrowed the reason down to the `infer_eeg_placement_scheme` function, which will drop any non-eeg channels because of `raw.pick`.
I can fix this, but I was wondering whether this was in fact the intended behaviour or not?

Now that I think about it, I am pretty sure if there is MEG data which contains EEG data, this function will actually remove all MEG channel info, rendering the data completely wrong, so I guess that this behaviour is indeed unintended.

**Comment by monkeyman192** [comment]
ok, having more of a test this happens in all data, so the current output from FIF data has only EEG channels listed which is obviously wrong. PR incoming :)

**Comment by sappelhoff** [comment]
wow, that's a bad bug! Thanks for the catch!
