### ISSUE TITLE
Add support for Curry .cdt input files

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids#1070]
### Describe the problem

It seems, bids conversion does not support Curry files (.cdt). Is there any reason for this and would anything speak against adding support for it?

### Describe your solution

One could extend the `ALLOWED_INPUT_EXTENSIONS` in `mne_bids.confg`.

### Describe possible alternatives

The alternative is an additional conversion step into the supported file-formats (not practical).

**Comment by adam2392** [comment]
IIUC, the only reason any file system to be read in isn't supported is entirely due to guardrails from user feeding in data we don't know how to convert. 

Curry is pretty popular system and if it has a reader in mne then I think that's good to include. 

Would you be up to just modifying the necessary code and adding a unit test?

**Comment by dengemann** [comment]
Thanks for the quick reply. MNE has a functional curry reader and yes, I can work on that!

**Comment by dengemann** [comment]
After pulling MNE and mne-bids from main and install all requirements, I am having some difficulties with pytest which seems to be collecting tests forever. Did anyone recently have to deal with this?

**Comment by hoechenberger** [comment]
Yes, I had this yesterday. One thing to check is your network activity -- could it be that it's downloading the testing data, which may take a while on a slow connection?

**Comment by dengemann** [comment]
Have it already installed, at least mne.dataset.testing ... but you are right, it's trying to install it once more.

**Comment by sappelhoff** [comment]
I had the same problem ... took 1-2 minutes or so :shrug:

**Comment by sappelhoff** [comment]
also note that current CI and test issues will be solved with https://github.com/mne-tools/mne-bids/pull/1071

**Comment by drammock** [comment]
These days the testing dataset is versioned and you need the latest version to run the tests. That may be why it's downloading even though you already have it.

**Comment by dengemann** [comment]
all good, now fighting with tests :D

**Comment by larsoner** [comment]
>> I am having some difficulties with pytest which seems to be collecting tests forever. Did anyone recently have to deal with this?

> I had the same problem ... took 1-2 minutes or so ￼

Which test suite were you running where this happened? I just added a check that we have `download=False` in all MNE-Python tests at least and it seems to be passing locally at least.

I'll try opening a PR here to check the same thing.

**Comment by larsoner** [comment]
> Which test suite were you running where this happened?

... Looks like it was most likely MNE-BIDS, see https://github.com/mne-tools/mne-python/pull/11213 and https://github.com/mne-tools/mne-bids/pull/1073
