### ISSUE TITLE
MAINT: New release?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids#1074]
It has been ~6 months, time for a release? Also it might be necessary to work with the imminent 1.2 release, not sure. But it's generally better if `mne-*` release before `mne` itself. mne-connectivity and mne-realtime have released recently. WDYT?

**Comment by hoechenberger** [comment]
I'm always happy whenever I see new releases! Let's do it!

**Comment by hoechenberger** [comment]
I simply moved all open issues tagged for 0.11 to the 0.12 milestone. ;)

**Comment by larsoner** [comment]
Who volunteers to do it? Not me :)

**Comment by hoechenberger** [comment]
I see @sappelhoff thumb-up'd your suggestion, so I guess it's all on him now 😁

**Comment by sappelhoff** [comment]
I can do it soon :+1:

**Comment by sappelhoff** [comment]
done :tada: 

- https://pypi.org/project/mne-bids/
- https://github.com/mne-tools/mne-bids/releases/tag/v0.11

cc @larsoner @hoechenberger

**Comment by hoechenberger** [comment]
Great!
