### ISSUE TITLE
We're not writing all annotations if events are passed to write_raw_bids() as well

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#1084]
### Description of the problem

This problem came up in https://mne.discourse.group/t/mne-bids-structure-one-subject-is-different/5687/

The user concatenated raws, which creates an `edge` annotation. However, after writing the data via `write_raw_bids()`, the annotation didn't show up in `events.tsv`. Turns out the user passed `events` and `event_id` to `write_raw_bids()` too, which caused this issue to surface.

### Steps to reproduce

In the following code, the concatenated raw has an edge and a bad annotation, but they don't end up in the `events.tsv` sidecar:

```Python
# %%
import pandas as pd
import mne
import mne_bids

sample_dir = mne.datasets.sample.data_path()
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname)
raw_concat = mne.concatenate_raws([raw.copy(), raw])
events = mne.find_events(raw_concat)
event_id = {
    'Auditory/Left': 1,
    'Auditory/Right': 2,
    'Visual/Left': 3,
    'Visual/Right': 4,
    'Smiley': 5,
    'Button': 32
}

# %%
bp = mne_bids.BIDSPath(
    subject='sample',
    task='sample',
    suffix='meg',
    extension='.fif',
    datatype='meg',
    root='/tmp/bids-root'
)
mne_bids.write_raw_bids(
    raw_concat,
    bids_path=bp,
    events=events,
    event_id=event_id,
    overwrite=True,
    allow_preload=True,
    format='FIF'
)

# %%
events_tsv_path = (
    bp
    .copy()
    .update(suffix='events', extension='.tsv')
)
events_tsv = pd.read_csv(events_tsv_path, sep='\t')
print(events_tsv['trial_type'].unique())
```

### Expected results

We should see 642 events in `events.tsv`, including the edge and bad annotations.

### Actual results

The edge and bad annotations are missing from the `events.tsv` sidecar.

### Additional information

The problem occurs here:
https://github.com/mne-tools/mne-bids/blob/9231836b227dceecec5f73b498a32591ef2f31ef/mne_bids/read.py#L159-L163

While in line 162 we explicitly try to include edge and bad annotations, the documentation of `events_from_annotations()` also states that any annotations that do not appear in `event_id` will simply be dropped.

IMHO the cleanest solution here would be to force users to always supply an event_id dictionary. Currently it's optional if no `events` are passed, which causes us to generate arbitrary event codes for annotations – which at least one user complained about not too long ago. Of course this would break lots of existing code.

We could of course also add special handling for all annotations for which no event_id mapping has been supplied, and we simply generate some new (arbitrary) event codes.

@sappelhoff @agramfort WDYT?

**Comment by hoechenberger** [comment]
Another option would be to keep the behavior as-is if only annotations are present (and no `events` and `event_id` are passed), and we **only** enforce all annotations to be listed in `event_id` if `events` **and** annoations are passed.

This should break significantly less existing user code!!

**Comment by hoechenberger** [comment]
Just for clarification, simply not passing `events` and `event_id` to `write_raw_bids()` **does** write the annotations. It's just the combination of the two that causes issues, as annotations whose description doesn't appear in `event_id` will not be written.

**Comment by agramfort** [comment]
we have discussed this before and we had decided that we should write
anything that is present in the files.
so to me it's a bug fix

**Comment by hoechenberger** [comment]
Yes but the question is simply **how** to fix it! It's clear the it's a bug :)

**Comment by sappelhoff** [comment]
Thanks for investigating, Richard!

> We could of course also add special handling for all annotations for which no event_id mapping has been supplied, and we simply generate some new (arbitrary) event codes.

I like this fix:

- keep current behavior BUT
- generate new (arbitrary) event codes for annots that have no `event_id` mapping AND
- warn if we do that, that users please use complete their `event_id` instead of relying on the auto-procedure

> Another option would be to keep the behavior as-is if only annotations are present (and no events and event_id are passed), and we only enforce all annotations to be listed in event_id if events and annoations are passed.

I would also be fine with this fix.

**Comment by hoechenberger** [comment]
> keep current behavior BUT
> generate new (arbitrary) event codes for annots that have no event_id mapping AND
> warn if we do that, that users please use complete their event_id instead of relying on the auto-procedure

I'm in favor of this one! This will make things more explicit to users

**Comment by hoechenberger** [comment]
I can try to take a look sometime later today. I think this is actually an important issue and warrants a quick patch release, as users might actually be losing data in the conversion process!

**Comment by sappelhoff** [comment]
Just for the procedure of a patch release we would:

1. `git cherry-pick` commits from `main` that we want to release and put them on `maint/v0.11`
2. bump version, update changelog, etc. on `maint/v0.11`
3. build dist and push to pypi on `maint/v0.11`
4. build docs on `v0.11` and update stable docs in `gh-pages` branch

right?

**Comment by hoechenberger** [comment]
Yeah or just release 0.12 for simplicity hehe

**Comment by larsoner** [comment]
> Just for the procedure of a patch release we would:

This sounds like what I do for MNE-Python, yeah
