### ISSUE TITLE
Metadata issues in ds004107

### ISSUE THREAD

**Issue by ftadel** [mne-tools/mne-bids#1096]
I found some weird inconsistencies in the metadata of this dataset:
https://openneuro.org/datasets/ds004107/versions/1.0.0

I copy here the three comments at the bottom of the page:

Comment 1:

> The file T1w.json include the description of anatomical landmarks LPA/RPA/NAS.
> Conceptually, these points are supposed to be properties of the anatomy, and should not change between two MEG scans.
> The way they are set here seem to provide different anatomical landmarks for the two meg sessions.
>
> Following the BIDS specification, I think there is no way to parse this information and use it in an automatic importer.
> In my understanding, the anatomical landmarks should be fixed in the T1w.json, and should vary in the coordsystem.json.
> Or am I missing something?
> https://openneuro.org/crn/datasets/ds004107/snapshots/1.0.0/files/sub-mind002:ses-01:anat:sub-mind002_ses-01_T1w.json

Comment 2:

> When opening the file with MNE-matlab, the sampling frequency (1793Hz) does not match the metadata documented in the _meg.json (1250 Hz).
> >> [ fid, tree ] = fiff_open('ds004107/sub-mind002/ses-01/meg/sub-mind002_ses-01_task-auditory_meg.fif');
> >> [ info, meas ] = fiff_read_meas_info(fid, tree);
> >> info.sfreq
> ans =
>    1.7929e+03
> 
> Which one is correct?
>
> As a consequence, the "sample" column in the _events.tsv is questionnable.

Comment 3:

> Last question: there seem to be long delays between the STIM triggers and the events (between 60ms and 160ms).
> Can you please explain where this is coming from?
> 
> Example: sub-mind002/ses-01/meg, task-auditory, first event "left/noise".
> Latency in channel STI014: 8.4004s
> Latency in events.tsv: 8.5816s
> => 166ms later

It is mentioned that the dataset was created using mne-bids.

**Comment by hoechenberger** [comment]
Hello,

This seems to be an issue with the dataset, none with MNE-BIDS... What do you propose we do?

Regarding the first comment, it is absolutely fine and actually expected that the landmark positioning changes between runs. Adding landmarks per session is mandated by BIDS, and we support dealing with this -- see the `kind` parameter of `get_head_mri_trans()`.

Could you please be more specific -- where exactly does MNE-BIDS  to work for you here?

Thanks!

Richard

**Comment by jasmainak** [comment]
@hoechenberger do you mean that the anatomical landmarks change because they are computed on the fly based on the digitized fiducials which change from session to session? In principle, they should not change if there is a single T1 image for the different MEG sessions ...

**Comment by jasmainak** [comment]
> As a consequence, the "sample" column in the _events.tsv is questionnable.

I believe the MNE-BIDS approach is to treat the sidecars as the truth ... they can be used to override mistakes in the fif file. Unlike fMRI, the MEG validator does not have extensive checks to compare the sidecars and the file metadata. For this reason, the sidecars take precedence ...

**Comment by ftadel** [comment]
> I believe the MNE-BIDS approach is to treat the sidecars as the truth ... they can be used to override mistakes in the fif file. Unlike fMRI, the MEG BIDS validator does not have extensive checks to compare the sidecars and the file metadata. For this reason, the sidecars take precedence ...

> where exactly does MNE-BIDS not work for you here?

I am not myself a MNE-BIDS user.
I am reporting inconsistencies observed in ds004107, which seems to mention that the metadata were generated with MNE-BIDS:
https://openneuro.org/datasets/ds004107/versions/1.0.0/file-display/README

If MNE-BIDS created the _meg.json that indicates a sampling rate of 1250Hz, this should be checked carefully.
The logic of multiple anatomical landmarks associated to one single T1w image is questionable.

**Comment by larsoner** [comment]
> When opening the file with MNE-matlab, the sampling frequency (1793Hz) does not match the metadata documented in the _meg.json (1250 Hz).

>> [ fid, tree ] = fiff_open('ds004107/sub-mind002/ses-01/meg/sub-mind002_ses-01_task-auditory_meg.fif');
>> [ info, meas ] = fiff_read_meas_info(fid, tree);
>> info.sfreq
>> ans =
>> 1.7929e+03

I cannot replicate this in Python:

```Python
>>> import mne
>>> raw = mne.io.read_raw_fif('/home/larsoner/mne_data/ds004107/sub-mind002/ses-01/meg/sub-mind002_ses-01_task-auditory_meg.fif')
r>>> raw.info['sfreq']
1250.0
```

Or in MATLAB:

```MATLAB
>> [ fid, tree ] = fiff_open('/home/larsoner/mne_data/ds004107/sub-mind002/ses-01/meg/sub-mind002_ses-01_task-auditory_meg.fif');
>> [ info, meas ] = fiff_read_meas_info(fid, tree);
	Read a total of 3 projection items:
		PCA-v1 (1 x 102) idle
		PCA-v2 (1 x 102) idle
		PCA-v3 (1 x 102) idle
>> info.sfreq

ans =

        1250
```
Is it possible the file is corrupted?

**Comment by ftadel** [comment]
The only problem here was me, sorry :)

**Comment by hoechenberger** [comment]
No, don't worry, it's important to communicate these issues 👍
