### ISSUE TITLE
ENH: fix manufacturer checking in _channels_tsv()

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids#1101]
### Description of the problem

in `write_bids_raw`, `allow_preload=True` should allow writing EEG files from unsupported manufacturers / files formats (e.g. EGI .raw).
Yet, _channels_tsv() makes strong assumptions about extensions e.g. when looking up ignored channels.
Could it make sense to implement `IGNOREd_CHANNELS` as a default dict or only look that up if the extension is known?

### Steps to reproduce

```Python

import tempfile
import mne
from mne_bids import write_raw_bids, BIDSPath

fname = mne.datasets.testing.data_path() / 'montage' / 'egi_dig_test.raw'

raw = mne.io.read_raw_egi(fname)

with tempfile.TemporaryDirectory() as tmpdir:
    bp = BIDSPath(subject='1', root=tmpdir, datatype='eeg', task='foo')

    write_raw_bids(raw, bp, format='BrainVision', allow_preload=True)
```

### Expected results

converting to BrainVision from EGI .raw (once preloaded)

### Actual results

```
channels_tsv(raw, fname, overwrite)
    113 # get the manufacturer from the file in the Raw object
    114 _, ext = _parse_ext(raw.filenames[0])
--> 115 manufacturer = MANUFACTURERS[ext]
    117 ignored_channels = IGNORED_CHANNELS.get(manufacturer, list())
    119 status, ch_type, description = list(), list(), list()

KeyError: '.raw'
```

### Additional information

Platform:         Linux
Python:           3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0]
mne:              1.2.0
numpy:            1.23.4 {unknown linalg bindings (threadpoolctl module not found: No module named 'threadpoolctl')}
scipy:            1.9.1

**Comment by dengemann** [comment]
I can actually add a reproducible example based on MNE testing files, will do in a bit

**Comment by hoechenberger** [comment]
We need to convert the format, can you try with passing the `format` parameter to `write_raw_bids()`?

**Comment by dengemann** [comment]
@hoechenberger added reproducible example on top

**Comment by hoechenberger** [comment]
Thanks!

You we should clearly skip this check if the data has already been preloaded. That would be the solution to the entire problem, right?

**Comment by dengemann** [comment]
That's also my understanding.

**Comment by hoechenberger** [comment]
@dengemann In your example, you forgot to actually preload the data. Here's the "corrected" MWE (which still produces the same error):

```python

import tempfile
import mne
from mne_bids import write_raw_bids, BIDSPath

fname = mne.datasets.testing.data_path() / 'montage' / 'egi_dig_test.raw'

raw = mne.io.read_raw_egi(fname, preload=True)

with tempfile.TemporaryDirectory() as tmpdir:
    bp = BIDSPath(
        subject='1', task='foo', suffix='eeg', extension='.vhdr',
        datatype='eeg', root=tmpdir
    )
    write_raw_bids(raw, bp, format='BrainVision', allow_preload=True)
```

Produces
```python
Writing '/var/folders/2k/nkw3dkx97ssdv08xmdgfnjkc0000gn/T/tmprycdflf0/dataset_description.json'...
Writing '/var/folders/2k/nkw3dkx97ssdv08xmdgfnjkc0000gn/T/tmprycdflf0/sub-1/eeg/sub-1_task-foo_eeg.json'...
Traceback (most recent call last):
  File "/private/tmp/mwe-bids.py", line 15, in <module>
    write_raw_bids(raw, bp, format='BrainVision', allow_preload=True)
  File "<decorator-gen-620>", line 12, in write_raw_bids
  File "/Users/hoechenberger/Development/mne-bids/mne_bids/write.py", line 1861, in write_raw_bids
    _channels_tsv(raw, channels_path.fpath, overwrite)
  File "/Users/hoechenberger/Development/mne-bids/mne_bids/write.py", line 115, in _channels_tsv
    manufacturer = MANUFACTURERS[ext]
KeyError: '.raw'
```

We can deduce 2 things here:

1. The error message is not helpful **at all**
2. If the data has been preloaded, the original format shouldn't matter, but currently does
