### ISSUE TITLE
Cut 0.12 release

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#1105]
In preparation for the MNE-Python 1.3 release alongside with new standalone installers that will also feature the M E-BIDS-Pipeline, we should soon make a new release of MNE-BIDS (within the next two weeks or so?)

**Comment by hoechenberger** [comment]
@sappelhoff Do you tun I you'd have time to cut a release within the next few days? Otherwise I could try to give it a shot, but I'm on a tight schedule :/

**Comment by sappelhoff** [comment]
I'm on vacation and have some time on my hands, so I can do it 👍 

Anything we should wait for / get in first?

**Comment by hoechenberger** [comment]
Great!

I don't think we have any blockers. 👍

**Comment by sappelhoff** [comment]
should be done now, pending conda:

- https://github.com/conda-forge/mne-bids-feedstock/pull/28
