### ISSUE TITLE
circlci security breach

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1116]
a note for us to look into this, perhaps we need to make some changes with our tokens: https://circleci.com/blog/january-4-2023-security-alert/

**Comment by sappelhoff** [comment]
Okay I checked, I think this mostly involved two things:

- revoking OAuth access of circleci for the org
- rotating our secrets
    - that's only the ssh key we use for deployment (for mne-bids at least): https://github.com/mne-tools/mne-bids/blob/4c32752f40ef39056bb08df87d5ffd318d7d4131/.circleci/config.yml#L82
    
    
I'll take care of rotating the ssh key now, the org-wide thing is better left to others like @larsoner, I believe.

**Comment by hoechenberger** [comment]
Is there a way to mark such security issues non-public until resolved? Asking for a friend 😇

**Comment by drammock** [comment]
> Is there a way to mark such security issues non-public until resolved? Asking for a friend innocent

https://github.com/mne-tools/mne-python/blob/main/SECURITY.md

> if you think you have found a security vulnerability in MNE-Python, please do not report it as a GitHub issue, in order to keep the vulnerability confidential. Instead, please report it to [mne-core-dev-team@groups.io](mailto:mne-core-dev-team@groups.io)

**Comment by hoechenberger** [comment]
Yes, but I thought I've seen tools (was it dependabot? I don't remember) also create "private" security reports somehow. I don't remember any details though...

**Comment by sappelhoff** [comment]
> if you think you have found a security vulnerability in MNE-Python, please do not report it as a GitHub issue, in order to keep the vulnerability confidential. Instead, please report it to [mne-core-dev-team@groups.io](mailto:mne-core-dev-team@groups.io)

oups, in that case I have violated our security guidelines. I somehow assumed the CircleCI breach being publicly communicated about would make it fine to discuss in a public issue. I'll do better next time, sorry.

**Comment by larsoner** [comment]
>  somehow assumed the CircleCI breach being publicly communicated about would make it fine to discuss in a public issue

FWIW this was also my sense when I got an email about it, but I guess it can't hurt to be extra careful next time and use that email instead!

**Comment by hoechenberger** [comment]
This wasn't meant to criticize anytime, I was just genuinely curious :) thanks for looking into this issue, @sappelhoff!!!

**Comment by drammock** [comment]
> I thought I've seen tools (was it dependabot? I don't remember) also create "private" security reports

Dependabot is a GitHub-provided service, so it can do things that mere users cannot.

**Comment by hoechenberger** [comment]
That makes sense!!
