### ISSUE TITLE
CI: `inspect_annotations` tests failing due to Matplotlib deprecation

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1118]
https://github.com/mne-tools/mne-bids/actions/runs/4200671427/jobs/7286926594#step:18:308

> E   matplotlib._api.deprecation.MatplotlibDeprecationWarning: The circles attribute was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Any custom property styling may be lost.

**Comment by drammock** [comment]
please pin matplotlib to <3.7 for now. This is a change we've known about for a few weeks, and it's possible (but not trivial) for us to adapt to it. I'll do my best to remember to unpin on mne-bids when it's fixed. Crossref: https://github.com/mne-tools/mne-python/pull/11409

**Comment by sappelhoff** [comment]
Thank you @drammock
