### ISSUE TITLE
mne_bids.path.BIDSPath.fpath ignores value of 'check'

### ISSUE THREAD

**Issue by kaare-mikkelsen** [mne-tools/mne-bids#1123]
### Description of the problem

I am structuring my derivative folders according to BIDS structure, and using mne-bids to identify files in there, even if the data types are no longer standard BIDS types.

### Steps to reproduce

Python
For example:

This correctly identifies 4 files for me:
`hypnoFiles = mb.find_matching_paths(root=hypnoDerivPath,extensions='.npz',subjects=subject)`

However, calling fpath on any of these files throws up an error, even when check=False:

```python
hypnoData = []
for hypnoFile in hypnoFiles:
    hypnoFile.update(check=False)
    print(hypnoFile.fpath)
```

### Expected results

I expect hypnoFile.fpath to print the location of the file when check=False. 

### Actual results

This is the error:
```
ValueError                                Traceback (most recent call last)
c:\Users\au207178\OneDrive - Aarhus universitet\forskning\sleepInOrbit\pipeline1.py in line 15
     162 for hypnoFile in hypnoFiles:
     163     hypnoFile.update(check=False)
---> 164     print(hypnoFile.fpath)
     166 #extract sleep features
     167 sleepFeatures=pd.DataFrame()

File c:\Users\au207178\Anaconda3\envs\cuda11\lib\site-packages\mne_bids\path.py:600, in BIDSPath.fpath(self)
    592 else:
    593     # if suffix and/or extension is missing, and root is
    594     # not None, then BIDSPath will infer the dataset
    595     # else, return the relative path with the basename
    596     if (self.suffix is None or self.extension is None) and \
    597             self.root is not None:
    598         # get matching BIDSPaths inside the bids root
    599         matching_paths = \
--> 600             _get_matching_bidspaths_from_filesystem(self)
    602         # FIXME This will break
    603         # FIXME e.g. with FIFF data split across multiple files.
    604         # if extension is not specified and no unique file path
    605         # return filepath of the actual dataset for MEG/EEG/iEEG data
    606         if self.suffix is None or self.suffix in ALLOWED_DATATYPES:
    607             # now only use valid datatype extension
...
   1885     msg = (f'Found data of more than one recording datatype. Please '
   1886            f'pass the `suffix` parameter to specify which data to load. '
   1887            f'Found the following modalitiess: {modalities}')

ValueError: No electrophysiological data found.
```

### Additional information

However, all information for locating the file is clearly available to fpath:

`print(os.path.join(hypnoFile.directory,hypnoFile.basename+hypnoFile.extension))`

Works fine as a workaraound.

**Comment by agramfort** [comment]
how can we replicate this?

**Comment by agramfort** [comment]
I can replicate with this self contained code snippet:

```python
from pathlib import Path
import numpy as np
import mne_bids

A = np.random.rand(5,5)
fname = Path("./bids_data/sub-001/ses-001/sub-001_ses-001_task-sleep_desc-hypnogram.npz")
fname.parent.mkdir(parents=True, exist_ok=True)
np.savez_compressed(fname, A=A)

root = './bids_data'
bp = mne_bids.find_matching_paths(root=root)[0]
bp.update(check=False)
print(bp.basename + bp.extension)

bp.fpath  # Crash for no good reason
```

I agree this should work

**Comment by drammock** [comment]
Spent a while looking at this issue today. I can reproduce, but I'm not sure it's actually a bug. On current `main` if I change @agramfort's example to have 

```py
fname = Path("./bids_data/sub-001/ses-001/eeg/sub-001_ses-001_task-sleep_desc-hypnogram.npz")
#                    this is what I added ↑↑↑
```
then the example succeeds. In fact it works as long as there is *any* data type subdir in the path there (I tested with `hypnogram` and `foobar`).

If I'm [reading the spec right](https://bids-specification.readthedocs.io/en/stable/common-principles.html#filesystem-structure), putting a data file within `ses-001` but *not* within a "data type" dir is invalid (though I confess it's not 100% clearly spelled out).

[A couple sections earlier in the spec](https://bids-specification.readthedocs.io/en/stable/common-principles.html#compulsory-optional-and-additional-data-and-metadata) there is an example about vendor-specific eye tracking data that also indicates that the additional file(s) go *within a data type subdir*:

> [...] there will be cases that do not fit. In such cases one can include additional files and subdirectories to the existing directory structure following common sense. For example one may want to include eye tracking data in a vendor specific format that is not covered by this standard. The most sensible place to put it is next to the continuous recording file with the same naming scheme but different extensions.

So in this case, I'd say that the `.npz` file containing the hypnogram should go in an `eeg` subfolder (or a dedicated `hypnogram` folder --- and as I said above, if I put it there, the MWE succeeds). I concede that it's a bit annoying that it fails, but (again, assuming I'm reading the spec right!) I think technically it shouldn't be a supported case, so +1 to close as `wontfix`.
