### ISSUE TITLE
automatically deploy the documentation

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#113]
for reference:

> @sappelhoff if you have time, it would be great to deploy successful CircleCI builds automatically once it's built. I think MNE does it here. It will save us the effort of running make install every time we change the doc

https://github.com/mne-tools/mne-python/blob/master/.circleci/config.yml#L213

**Comment by sappelhoff** [comment]
@jasmainak can you tell me a bit more about the logic how we host and build our docs? I can see that we have a `gh-pages` branch but before I spend 30 minutes to dig into the why and how, it'd be cool if you took 3 minutes to briefly describe :-)

**Comment by jasmainak** [comment]
Basically, the built docs are stored in the `gh-pages` branch and not on `master`. Every time you do [`make install`](https://github.com/mne-tools/mne-bids/blob/master/doc/Makefile#L135-L152), you clone the last commit of this branch in a separate folder, copy over your `_build` folder to this folder, then commit the changes and push it back. Now you need to basically do this on CircleCI and configure the git username etc.
