### ISSUE TITLE
BIDS `sample` and `value` columns will be considered "arbitrary" columns soon

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1130]
as discussed in:

- https://github.com/bids-standard/bids-specification/pull/1441

and implemented in:

- https://github.com/bids-standard/bids-specification/pull/1457

the currently OPTIONAL `sample` and `value` columns in `*_events.tsv` files will be demoted to "arbitrary" columns in BIDS 1.9.0.

Practically this means, that `mne-bids` should write entries into `*_events.json`, defining how **we** use `sample` and `value`.

Otherwise, datasets produced by mne-bids might soon generate a "warning" (not an error 😉 ) that `sample` and `value` are undefined.

**Comment by agramfort** [comment]
thanks for the update. I guess we will need a few PRs :)
