### ISSUE TITLE
Problem loading mne-bids when MNE 1.0.0 and above is installed

### ISSUE THREAD

**Issue by nw-duncan** [mne-tools/mne-bids#1131]
It seems that changes to MNE from version 1.0.0 onward prevent mne-bids from importing properly. 

Firstly, `mne.preprocessing.annotate_flat` has been deprecated. This is called in _inspect.py_ through `from mne.preprocessing import annotate_flat`. This can be fixed by changing to `from mne.preprocessing import annotate_amplitude`.

Secondly, MNE no longer has external resources included. This breaks `from mne.external.tempita import Template` in _report.py_. This can be fixed by changing to `from tempita import Template` and adding tempita to the required package list. 

I don't know if these changes would break compatibility with older MNE versions and so didn't want to submit a pull request with the changes.

**Comment by hoechenberger** [comment]
Hello @nw-duncan! Could you tell us which version of MNE-BIDS you're using? With 0.12, the problems you described *should* not appear.

**Comment by nw-duncan** [comment]
Oh, that's embarrassing. 

I was forgetting the --upgrade flag in pip so was still on 0.9. 

I've done the upgrade now and there are no problems. 

Sorry for that!
