### ISSUE TITLE
doc build fails: "tut-ieeg-localize" moved

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1134]
Our doc build is failing with a warning because the reference to `tut-ieeg-localize` cannot be found anymore. Was this something in MNE-Python that has now moved? @alexrockhill do you know more? :-)

> /home/circleci/project/doc/auto_examples/convert_ieeg_to_bids.rst:1083: WARNING: undefined label: 'tut-ieeg-localize'

https://app.circleci.com/pipelines/github/mne-tools/mne-bids/5179/workflows/d0b5cc9b-cda4-436b-9e96-1edeea651d21/jobs/7347

**Comment by larsoner** [comment]
It nows lives in a separate repo with a different intersphinx

https://mne.tools/mne-gui-addons/auto_examples/locate_ieeg_micro.html#locating-micro-scale-intracranial-electrode-contacts
