### ISSUE TITLE
EEGLab bug writing HDF5 persisting in MNE-BIDS

### ISSUE THREAD

**Issue by christinerogers** [mne-tools/mne-bids#1151]
### Description of the problem

Opening this issue as a follow-on from #652 which was resolved/closed with a workaround recommendation #653 specific to Matlab .SET files -- as discussed with @sappelhoff in the BIDS Maintainers meeting July 13, 2023

Given .Set is one of only 4 supported file types for BIDS EEG and is extremely widespread (with EEGLab use) in the community -- 
Although the workaround is effective, my MCIN group (makers of [EEG2BIDS converter](github.com/aces/eeg2bids) and [EEGNet.org](https://eegnet.org) at McGill University would ideally like to see a solution factored into MNE-BIDS if possible

Thanks, and let us know if details / examples would help, or how we can get involved.  

cc @larsoner for EEGNet Technical Committee and MCIN developers @jeffersoncasimir @laemtl 
  

### Steps to reproduce

```Python
please see #652
```

### Expected results

please see #652

### Actual results

please see #652

### Additional information

please see #652

**Comment by larsoner** [comment]
Based on a very quick reading it seems like there was a fix put in https://github.com/mne-tools/mne-bids/pull/653 that has been merged and released. Is there an updated minimal example we can work from to fix the issue?

**Comment by sappelhoff** [comment]
@christinerogers we would indeed need a detailed report of the issues you are facing, including MWEs, please

**Comment by sappelhoff** [comment]
closing, as no reproducible error has been reported -- feel free to reply with instructions on how to reproduce an error /  a problem, so that we can fix it. 

In the meantime, I assume that #1187 fixes some problems.
