### ISSUE TITLE
Export to EEGLAB format?

### ISSUE THREAD

**Issue by laemtl** [mne-tools/mne-bids#1152]
I try to write a raw object using 
```
raw = mne.io.read_raw_eeglab(input_fname=file, preload=False, verbose=True)
write_raw_bids(raw, bids_basename, allow_preload=False, overwrite=False, verbose=False)
```                 
and I got the following error: 
```
Cannot write file - The data has already been loaded from disk. To write it to BIDS, pass "allow_preload=True" and the "format" parameter.
```

When I set allow_preload to True, I then get
`For preloaded data, you must set the "format" parameter to one of: BrainVision, EDF, or FIF
`

The issue is I don't see an option of EEGLAB/set file. 

Is this a know issue? Am I doing something wrong?

**Comment by hoechenberger** [comment]
U sing think we support writing to EEGLAB. You can try to write to BraunVision instead

**Comment by agramfort** [comment]
what is the content of bids_basename and bids_basename.format ?

**Comment by hoechenberger** [comment]
> For preloaded data, you must set the "format" parameter to one of: BrainVision, EDF, or FIF

You will have to pick one of those. No EEGLAB support so far. Sorry!

**Comment by sappelhoff** [comment]
We can consider adding support for exporting to EEGLAB, using this library: https://github.com/jackz314/eeglabio

**Comment by sappelhoff** [comment]
> Full support for .SET would help us make open-source BIDS converter tools like [EEG2BIDS](https://github.com/aces/eeg2bids) accessible for many more BIDS-compliant cases, especially for researchers looking to move away from manufacturer-driven data formats like BV.

3 comments on this:

1. The EEGLAB data format is not "RECOMMENDED" under BIDS, it's merely "accepted" based on its wide distribution
2. it's a MATLAB file in disguise
3. The mne-bids devs (to my knowledge) don't work actively with the EEGLAB format themselves

that maybe explains why so far there have been only little efforts to support this file format.

Having that said, we'd welcome contributions in the form of PRs (perhaps by @laemtl) to allow export to EEGLAB.

What do you think @hoechenberger @agramfort ?

**Comment by hoechenberger** [comment]
Isn't Matlab simply HDF5 these days? Hence I don't see why (modern) EEGLAB shouldn't be fully supported by BIDS (and hence MNE-BIDS)

**Comment by sappelhoff** [comment]
@christinerogers @laemtl @jeffersoncasimir

Please see this issue as a list of To Dos as to improve EEGLAB functionality of mne-bids: 

- https://github.com/mne-tools/mne-bids/issues/654

We'd be happy to review PRs to improve the state of the art. And perhaps working on these "smaller" items can be done in parallel to the present issue of also **exporting** to the EEGLAB format.
