### ISSUE TITLE
MNE-BIDS 0.13 release

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1153]
A release of MNE-BIDS has been requested: https://mne.discourse.group/t/mne-bids-0-13-release-date/7291/2

Our last release has been in December 2022, so I feel like cutting a release now is reasonable.

I'll migrate issues from the [0.13 milestone](https://github.com/mne-tools/mne-bids/milestone/14) to a new 0.14 milestone.

Please comment here if you need some particular thing to be fixed before the release.

cc @agramfort @hoechenberger @larsoner

**Comment by hoechenberger** [comment]
All green from my end

**Comment by agramfort** [comment]
ok green for me too !

**Comment by sappelhoff** [comment]
we should probably wait for the MNE-Python 1.5 release:

- https://github.com/mne-tools/mne-python/issues/11843

... and then support `mne>=1.4`

**Comment by sappelhoff** [comment]
conda-forge:

- https://github.com/conda-forge/mne-bids-feedstock/pull/29
