### ISSUE TITLE
doc build failure: pydata-sphinx-theme

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1164]
https://app.circleci.com/pipelines/github/mne-tools/mne-bids/5425/workflows/e5a6eec0-3e7c-4e84-b93b-f447438ed56a/jobs/7610

> AttributeError: 'TocTree' object has no attribute 'get_toctree_ancestors'

This is probably related to:

- https://github.com/pydata/pydata-sphinx-theme/pull/1406

and will likely be fixed with a new release of pydata-sphinx-theme.

Let's keep an eye on it and wait a couple of days.

**Comment by sappelhoff** [comment]
alternatively, we can fix this by pinning sphinx to <7.1 temporarily (in case the pydata-sphinx-theme release is taking longer than we're comfortable with)

**Comment by drammock** [comment]
Theme release is overdue. I would say it's immanent except that the are a couple release blocking issues we still haven't managed to fix. I recommend pinning sphinx for now

**Comment by sappelhoff** [comment]
pinned in https://github.com/mne-tools/mne-bids/commit/7ba64ac9397c18e40c3bd70a9632cfb68bb89892

to be unpinned once the theme release is completed.
