### ISSUE TITLE
read_raw_bids not accepting extra params (clean_names for CTF)

### ISSUE THREAD

**Issue by jstout211** [mne-tools/mne-bids#1167]
### Description of the problem

clean_names does not seem to be transmitting through to the mne.io.read_raw_ctf function.

### Steps to reproduce

```Python
In Terminal:
datalad install https://github.com/OpenNeuroDatasets/ds004215.git
cd ds004215
datalad get sub-ON02811/ses-01/meg/*airpuff*

In python:
import mne_bids
bids_root=os.getcwd()  #assuming you are in the top directory of the data repo
subject = 'ON02811'
bids_path = mne_bids.BIDSPath(root=bids_root, subject = subject, session='01', task='airpuff', run='01', datatype='meg')

mne_bids.read_raw_bids(bids_path, extra_params=dict(preload=True, clean_names=True), verbose=False).ch_names[0:10]

# Versus - the standard import
# mne.io.read_raw_ctf(bids_path.fpath, clean_names=True, verbose=False).ch_names[0:10]
```

### Expected results

['SCLK01', 'BG1', 'BG2', 'BG3', 'BP1', 'BP2', 'BP3', 'BR1', 'BR2', 'BR3']

### Actual results

['SCLK01-177',
 'BG1-1609',
 'BG2-1609',
 'BG3-1609',
 'BP1-1609',
 'BP2-1609',
 'BP3-1609',
 'BR1-1609',
 'BR2-1609',
 'BR3-1609']

### Additional information

(MEG_workshop) [stoutjd@MH02183085LT extras]$ mne sys_info
Platform             Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-glibc2.28
Python               3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
Executable           /home/stoutjd/miniconda3/envs/MEG_workshop/bin/python3.11
CPU                  x86_64 (12 cores)
Memory               15.3 GB

Core
├☑ mne               1.5.1
├☑ numpy             1.24.4 (OpenBLAS 0.3.24 with 8 threads)
├☑ scipy             1.11.2
├☑ matplotlib        3.7.2 (backend=QtAgg)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.3.0
├☑ numba             0.57.1
├☑ nibabel           5.1.0
├☑ nilearn           0.10.1
├☑ dipy              1.7.0
├☑ openmeeg          2.5.6
├☑ pandas            2.1.0
└☐ unavailable       cupy

Visualization (optional)
├☑ pyvista           0.42.2 (OpenGL 4.6 (Core Profile) Mesa 22.3.0 via Mesa Intel(R) UHD Graphics (CML GT2))
├☑ pyvistaqt         0.0.0
├☑ vtk               9.2.6
Qt: Session management error: None of the authentication protocols specified are supported
├☑ qtpy              2.4.0 (PyQt5=5.15.8)
├☑ pyqtgraph         0.13.3
├☑ mne-qt-browser    0.5.2
├☑ ipywidgets        8.1.1
├☑ trame_client      2.11.3
├☑ trame_server      2.11.7
├☑ trame_vtk         2.5.8
├☑ trame_vuetify     2.3.1
└☐ unavailable       ipympl

Ecosystem (optional)
├☑ mne-bids          0.13
└☐ unavailable       mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

**Comment by agramfort** [comment]
to me your BIDS dataset should have cleaned channels names in channels.tsv

that's the spirit of BIDS. You have a clean input then the processing
becomes dumb :)

makes sense?

**Comment by hoechenberger** [comment]
I agree; in fact, I'm not sure why we'd even want to support the `extra_params` argument. To allow for preloading, we could add a `preload` parameter. But for everything else -- that should be handled through BIDS itself.
