### ISSUE TITLE
get_entity_vals() does not support the 'recording' entity

### ISSUE THREAD

**Issue by moritz-gerster** [mne-tools/mne-bids#1172]
### Describe the problem

```Python
get_entity_vals(load_root, "recording")

ValueError: `key` must be one of: subject, task, session, run, processing, space, acquisition, split, description, suffix. Got: recording
```

### Describe your solution

I would expect that `get_entity_vals()` works for all entities. Not sure why 'recording' is excluded.

### Describe possible alternatives

Maybe also add the 'extension' and 'datatype' entity?

**Comment by hoechenberger** [comment]
@moritz-gerster Would you like to try fixing this in a PR?

**Comment by moritz-gerster** [comment]
I am sorry @hoechenberger, I am currently too busy to do it..

**Comment by hoechenberger** [comment]
> Maybe also add the 'extension' and 'datatype' entity?

These are not entities. 

We should add `recording` though

**Comment by Deadr4x** [comment]
Hello would this be good as my first issue? I would like to contribute.

**Comment by agramfort** [comment]
yes !

**Comment by Deadr4x** [comment]
I did setup the project locally and managed to replicate the error message. Will look into that.

**Comment by sappelhoff** [comment]
@Deadr4x are you still interested in contributing this pull request? Else, I will take over. :-)
