### ISSUE TITLE
maint: linters, CIs, packaging metadata

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1174]
I would say this is ready to go. 

In follow-up PRs we should

- [x] Drop flake8 (https://github.com/mne-tools/mne-bids/pull/1203)
- [x] Add yamllint (https://github.com/mne-tools/mne-bids/pull/1203)
- ~~Add codespell~~
- [x] Move from setup.cfg to pyproject.toml, which was added in this PR (https://github.com/mne-tools/mne-bids/pull/1202)
- [x] Update the dev docs to mention how to use git pre-commit

_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-bids/issues/1173#issuecomment-1736861096_

**Comment by sappelhoff** [comment]
Also switching to hatchling and hatchling-vcs. See:

- https://effigies.gitlab.io/posts/python-packaging-2023/
- https://github.com/effigies/cookiecutter-packaging

See also:

- https://github.com/mne-tools/mne-python/issues/12169

**Comment by sappelhoff** [comment]
note: also revamp MANIFEST.in file (https://github.com/mne-tools/mne-bids/blob/d9d26e54343c5635583a2a297032082d4ed555f6/MANIFEST.in#L1) ... only relevant if staying with setuptools

**Comment by sappelhoff** [comment]
@hoechenberger should we just remove black and rely on `ruff format`?

**Comment by hoechenberger** [comment]
I would say so. It works beautifully with MNE

**Comment by sappelhoff** [comment]
putting off switching to hatching and vcs to a later point in time, #1203 is the last PR in this series for now
