### ISSUE TITLE
certain COILS in pick.py will raise a bug soon

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#119]
These two coils

https://github.com/mne-tools/mne-bids/blob/1c4056427546127cf08a7fd6a668bb50bd13d703/mne_bids/pick.py#L30-L31

... are no longer part of FIFF in MNE-Python since https://github.com/mne-tools/mne-python/commit/517d3815a4ff519ecf9d09b9d714e87fa0ae92a8

what are they used for @monkeyman192 ? Can I remove them while doing #118 ?

At least removing them does not make our tests fail.

**Comment by monkeyman192** [comment]
When writing this file essentially looked through the constants.py file in MNE and added any that I could tell the type of from the name or comment. If it iant used in MNE any more than its completely safe to remove

**Comment by hstojic** [comment]
I get an error that might be related to this:
`ValueError: Unknown coil of type 201609 for channel MLC11`

I'm trying to convert CTF system data to BIDS and this error comes from `pick.py` file
Any suggestions how to resolve it?

**Comment by monkeyman192** [comment]
That doesn't look like a valid coil type from MNE at all.
see this previous issue: https://github.com/mne-tools/mne-bids/issues/95
@sappelhoff I think maybe we should have a small PR to remove the channels you mentioned from `pick.py` so we don't have to wait on #118

**Comment by jasmainak** [comment]
@hstojic do you have time to make a fix? You know best the data you are working with ...

a patch is most welcome.
