### ISSUE TITLE
FutureWarning: with copy=False --> set default explicity

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1190]
https://github.com/mne-tools/mne-bids/actions/runs/6845626385/job/18611114921#step:20:510

> FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning

affects all get_data calls for Epochs

**Comment by drammock** [comment]
cross-ref https://github.com/mne-tools/mne-python/pull/12121

**Comment by larsoner** [comment]
I'll take a look.

@sappelhoff WDYT about cutting a MNE-BIDS point release today or tomorrow so the `copy=False` fix can make it into the 1.6 installers?

**Comment by sappelhoff** [comment]
sure, I can make a `0.13.1` release once the `copy=False` fix is in 👍

**Comment by larsoner** [comment]
... actually it looks like the failure is just in a *test* not in the code itself so I don't think a release will be necessary

**Comment by sappelhoff** [comment]
even better :-)
