### ISSUE TITLE
Q: Release?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids#1192]
It would be good to cut a MNE-BIDS release before the MNE-Python 1.6 release because it looks like the `mne.io`->`mne._fiff` stuff isn't in the latest release (e.g., see [circleci main failure in MNE](https://app.circleci.com/pipelines/github/mne-tools/mne-python/21889/workflows/b613fb80-7a0e-4c45-b2cc-02b8f0d9e589/jobs/61509)). Any chance to cut one in the next couple of days?

**Comment by sappelhoff** [comment]
Yes, I will make a release tomorrow :+1:

**Comment by sappelhoff** [comment]
@larsoner should be done ✅
