### ISSUE TITLE
Add copyright holder to each file, and remove individual authors

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1194]
Using:

> Copyright the MNE-BIDS contributors.

following:

- https://github.com/mne-tools/mne-python/pull/12221

**Comment by sappelhoff** [comment]
I edited the issue title to also encompass removing individual authors from the file.

See discussions:

- https://blog.scikit-learn.org/updates/authorship-info/ 
- https://github.com/mne-tools/mne-python/issues/11605

**Comment by hoechenberger** [comment]
Let's do it exactly as scikit-learn does it:

```
# Authors: The MNE-BIDS developers
# SPDX-License-Identifier: BSD-3-Clause
```
