### ISSUE TITLE
MAINT: update release protocol --> versioning scheme

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1197]
For future releases, we should follow https://semver.org/ more closely and always add the patch version as well. That is, `0.14` would be `0.14.0`.

See discussion here:

- https://github.com/mne-tools/mne-installers/pull/227#discussion_r1399679112

**Comment by sappelhoff** [comment]
We should also add an "automated workflow to publish to pypi" upon making a GH release based on a tag.

**Comment by hoechenberger** [comment]
> We should also add an "automated workflow to publish to pypi" upon making a GH release based on a tag.

Maybe it's a good time to tackle this now as we'll need to release 0.15 sometime soon anyway

**Comment by sappelhoff** [comment]
I added GitHub as a "trusted publisher" on PyPI:

![image](https://github.com/mne-tools/mne-bids/assets/9084751/8aaaa7b2-776b-41a8-83e2-8fdab8aacf4f)


following:

- https://docs.pypi.org/trusted-publishers/adding-a-publisher/
- https://github.com/mne-tools/mne-python/blob/main/.github/workflows/release.yml
