### ISSUE TITLE
update warnings in MNE

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#12]
Currently MNE throws warnings if the `raw` file is not ending with `-raw.fif`. However, the new [BIDS specification](https://docs.google.com/document/d/1FWex_kSPWVh_f4rKgd5rxJmxlboAPtQlmBc1gyZlRZM/edit#) is not the same as the filenames end with `_meg.fif` now and `sss` or `tsss` go under `_proc-tsss` etc. We should update the warnings.

**Comment by agramfort** [comment]
+1

**Comment by teonbrooks** [comment]
I just raised an issue in the BIDS spec with the file naming convention [here](https://docs.google.com/document/d/1FWex_kSPWVh_f4rKgd5rxJmxlboAPtQlmBc1gyZlRZM/edit?disco=AAAABUyplSM) about the tag being `_meg`. This might pose issues with derivative files (e.g. epochs, evoked). I will wait til this is resolved before making the issue on mne

**Comment by jasmainak** [comment]
I think this issue will be hard to address until we have BIDS derivatives fleshed out as well. Therefore, moving it to `0.2`

**Comment by teonbrooks** [comment]
I actually think this should become a mne-python issue. it's not a fault of mne-bids

**Comment by sappelhoff** [comment]
> I actually think this should become a mne-python issue. it's not a fault of mne-bids

+1 !

Perhaps revive https://github.com/mne-tools/mne-python/issues/4950 ?

**Comment by jasmainak** [comment]
Sounds good. Although it's quite a bit of work I think. You would need to update the MNE datasets too because otherwise the MNE examples will start throwing warning everywhere ...
