### ISSUE TITLE
After switch to hatchling&hatch-vcs: heading in documentation is taking up too much space

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1205]
see: https://mne.tools/mne-bids/dev/index.html

**now:**

![image](https://github.com/mne-tools/mne-bids/assets/9084751/3f31fbfc-1231-4148-a2f9-8e80b6143664)

---

**before:**

![image](https://github.com/mne-tools/mne-bids/assets/9084751/5c9ad7f8-2478-4c6c-a08c-f005636edaac)

**Comment by hoechenberger** [comment]
I think you need to report this upstream to the theme authors.

**Comment by sappelhoff** [comment]
cc @drammock what do you think? Reporting at https://github.com/pydata/pydata-sphinx-theme? Or do you know an easy fix off the top of your head?

**Comment by drammock** [comment]
what is the behavior that you want? do you want the version string truncated? Or more space allocated so that it all fits?  Or something else?

**Comment by sappelhoff** [comment]
I think the default behavior that I would have expected is to allocate more space until some sort of "cap", and then for the version string to be truncated.
