### ISSUE TITLE
InvalidDistribution: Metadata is missing required fields: Name, Version.

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1237]
Any idea why the CI fails for us here since today? There was no new release of twine, yet it just started to complain now via `twine check`.

https://github.com/mne-tools/mne-bids/actions/runs/8305286633/job/22731989944#step:7:1

... we DO define name and version in pyproject.toml: https://github.com/mne-tools/mne-bids/blob/ebb14288f15d50010c494a51cb2a0704937a80bc/pyproject.toml#L6

<img width="972" alt="image" src="https://github.com/mne-tools/mne-bids/assets/9084751/701cfeb6-24b3-4319-83e1-cbd69ffbc156">

**Comment by sappelhoff** [comment]
Maybe it has to do with the recent release of Hatch 🤔  https://github.com/pypa/hatch/releases/tag/hatch-v1.9.4

**Comment by sappelhoff** [comment]
or rather: hatching? 🤔 

https://pypi.org/project/hatchling/#history

<img width="793" alt="image" src="https://github.com/mne-tools/mne-bids/assets/9084751/c47b0cc7-12df-4944-883f-2d29dc9a3592">

**Comment by sappelhoff** [comment]
@ofek do you perhaps have an idea? 🤔

**Comment by hoechenberger** [comment]
@sappelhoff `hatchling` 1.22.2 fixes a "regression when loading metadata from source distributions", so I would think that this addresses the issue here.

**Comment by ofek** [comment]
No issue, the ecosystem was just not quite prepared for metadata 2.3 https://github.com/pypa/hatch/issues/1329#issuecomment-2002293127
