### ISSUE TITLE
MAINT: remove ref-names from git_archive.txt?

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1246]
https://github.com/mne-tools/mne-bids/blob/e8eb7a7f30a0d6784c24810d2e82c5888c6fadad/.git_archival.txt#L4

Just came across this issue: https://github.com/pypa/setuptools_scm/issues/806#issuecomment-2058284222

**Comment by hoechenberger** [comment]
There's a warning in the docs now:

https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives

Since we have `describe-name`, removing `ref-names` should be okay for us
