### ISSUE TITLE
Request for New Version Release on pip

### ISSUE THREAD

**Issue by bruAristimunha** [mne-tools/mne-bids#1247]
Hello maintainers!

I've noticed that the latest changes in the source code have not yet been reflected in the pip package. These changes would be beneficial to braindecode and moabb.

We are having users with problems installing moabb/braindecode, and we cannot update mne_bids dependencies on moabb to resolve the issues because  mne_bids is not compatible with the last version of mne.

Could you please release the new version of this package on pip? It seems that the current source code solves the problems.

Thank you for your time and consideration.

FYI @agramfort and @brunaafl

**Comment by hoechenberger** [comment]
Hello,

could you please share the error you're seeing and which versions of MNE-Python and MNE-BIDS you're using?

**Comment by bruAristimunha** [comment]
Hey @hoechenberger,

Sure!

The error was first reported in braindecode:
https://github.com/braindecode/braindecode/issues/598

Then we discovered that it came from moabb:

https://github.com/NeuroTechX/moabb/pull/586

The problem arises
because braindecode has no upper limit for the version of our dependencies, and moabb has.

**Comment by bruAristimunha** [comment]
Report here too: https://github.com/NeuroTechX/moabb/issues/598

**Comment by hoechenberger** [comment]
I don't understand, at least in the 2nd issue you posted, it's said that the problem is that MNE-BIDS 0.13 is not compatible with MNE-Python 1.7.

But the latest release of MNE-BIDS is 0.14. So I'm confused.

**Comment by hoechenberger** [comment]
I checked the MOABB dependencies and they specify MNE <= 1.6 and MNE-BIDS 0.13

So you're destroying MOABB's dependency chain if you're installing MNE 1.7 with it

**Comment by bruAristimunha** [comment]
Exactly!

**Comment by hoechenberger** [comment]
Yeah but then there's really nothing the MNE-BIDS team can do to help you here ... or am I missing something?

**Comment by hoechenberger** [comment]
Ah. Is it this EDF issue here that's causing the pain?

https://github.com/NeuroTechX/moabb/pull/586#issuecomment-2093108052

**Comment by bruAristimunha** [comment]
Exactly yes, I am copying @brunaalf if you need more details :)

**Comment by hoechenberger** [comment]
@sappelhoff Woukd you have time to cut a new release anytime soon?

**Comment by sappelhoff** [comment]
I started migrating some issues over to the milestone for the release AFTER the impending on: https://github.com/mne-tools/mne-bids/milestone/17

However I think there are some issues we do need to solve before a release, like: #1250

**Comment by sappelhoff** [comment]
@bruAristimunha mne-bids 0.15.0 has just been released! https://pypi.org/project/mne-bids/0.15.0/#history
