### ISSUE TITLE
Add descriptions for onset and duration in `event.json` file

### ISSUE THREAD

**Issue by JuliusWelzel** [mne-tools/mne-bids#1254]
### Describe the problem

As currently implemented, the `events.json` file being written does not contain information about the two required columns "onset" and "duration" in the `.json` file.

As those columns are REQURIED, I would propose adding some background information to the `.json` file every time events are written for people who are not familiar with the structure of the `events.tsv` files in.REQUIRED

### Describe your solution

Addiing this to the _events_json_ function

```
  "onset": {
        "Requirement Level": "REQUIRED",
        "Data type": "number",
        "Description": (
            "Onset (in seconds) of the event from the beginning of the first data point. "
            "Negative onsets account for events before the first stored data point. "
            "This column must appear first in the file."
        )
    },
    "duration": {
        "Data type": "number or 'n/a'",
        "Description": (
            "Duration of the event in seconds from onset. Must be zero, positive, or 'n/a' if unavailable. "
            "A zero value indicates an impulse event.\n"
            "This column must appear second in the file."
        )
    }

```

Adding

### Describe possible alternatives

As the documentation about this is specific on the BIDS website, it does not has to be implemented.

**Comment by agramfort** [comment]
no objection
