### ISSUE TITLE
The 'More' dropdown doesn't render properly on macOS with Safari

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-bids#1295]
### Description of the problem

I'm willing to help fix this, but I don't have a ton of experience customizing sphinx themes, and it may be a little while until I have time to dig into this.

https://github.com/user-attachments/assets/354095c3-712f-4634-8639-a62f54fd807b

### Steps to reproduce

```Python
See video (I'm using Safari on macOS Sonoma 14.5)
```

### Expected results

I wanna see the dropdown!

### Actual results

Can't see the dropdown 🙁 

### Additional information

See video.

**Comment by drammock** [comment]
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#navigation-bar-dropdown-links

Controlled by this variable in `doc/conf.py`

```py
html_theme_options = {
  "header_links_before_dropdown": 5
}
```
(which is currently not set, and so is using the theme default value of 5).  IDK why the dropdown is not showing, but the 2 things I'd try are updating the sphinx theme, and setting the above var to 6 (in the MNE-BIDS case, there are only 6 total top-level nav items (count the `.. toctree` entries in `doc/index.rst`), so currently in the dropdown there's only 1 (invisible) item which seems a bit pointless).

**Comment by scott-huberty** [comment]
Thanks @drammock ! 🙏 I agree that a drop-down with only 1 item is potentially unnecessary. I’ll try it out and report back here or via PR.
