### ISSUE TITLE
examples using non fif systems

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#13]
So far, the examples cover fif file. It would be cool to include examples for CTF and/or KIT systems.

We could use these as reference:

https://box.bic.mni.mcgill.ca/s/omega?path=%2FContributions%20(in%20BIDS%20format)%2Fsample_BIDS_omega

and

https://box.bic.mni.mcgill.ca/s/omega?path=%2FContributions%20(in%20BIDS%20format)%2Fsample_BIDS_auditory

**Comment by teonbrooks** [comment]
@jasmainak do you know if there is a way to access these files without a login?

**Comment by jasmainak** [comment]
hmm ... I don't think so. Perhaps @giuomar may know if there is

**Comment by sappelhoff** [comment]
>@jasmainak do you know if there is a way to access these files without a login?
>>hmm ... I don't think so. Perhaps @giuomar may know if there is


@guiomar

**Comment by guiomar** [comment]
Hi!

These datasets are now available at OpenNeuro:

MEG-BIDS OMEGA Resting State sample
https://openneuro.org/datasets/ds000247

MEG-BIDS Brainstorm Auditory data sample
https://openneuro.org/datasets/ds000246

Cheers!

**Comment by sappelhoff** [comment]
Perhaps we can re-purpose one of the existing examples to work with the CTF data of the Brainstorm Auditory data? Either

- https://mne-tools.github.io/mne-bids/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py

or 

- https://mne-tools.github.io/mne-bids/auto_examples/convert_ds000117.html#sphx-glr-auto-examples-convert-ds000117-py

**Comment by jasmainak** [comment]
I would suggest one more example. Just to demonstrate we can use variety of systems ... okay with brainstorm auditory data

we should cache the data though (not sure if we're doing it now) in the CIs to reduce build time.

**Comment by jasmainak** [comment]
@teonbrooks @sappelhoff keep this open or close? We have some examples on EEG systems now.

**Comment by jasmainak** [comment]
In any case, I am moving the milestone for this issue so we can zero in on the really crucial issues for the release
