### ISSUE TITLE
ch_type_mapping has no entry for `chpi`

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-bids#1323]
### Description of the problem

MEGIN systems store chpi information in a channel called 'CHPI00X', which is read by `mne` as ch_type `chpi`. However, this entry is missing in the mne to bids conversion dictionary.

This leads to 

```python
  File ~/anaconda3/lib/python3.11/site-packages/mne_bids/write.py:150 in _channels_tsv
    ch_type.append(map_chs[_channel_type])

KeyError: 'chpi'
```

### Steps to reproduce

Choose a raw file that contains cHPI channels

```Python
In [18]: mne.channel_type(raw.info, 330)
Out[18]: 'chpi'
```

then try to call `write_raw_bids` using that file or use the command line interface

```
write_raw_bids(raw=raw,  # raw containing CHPI MEGIN channels
		bids_path=bids_subj,
		overwrite=True,
		verbose=True)
```

### Solution

`chpi` should be added to the channel mapping dictionary, probably as `MEGOTHER` or `MISC`?

Somewhere after https://github.com/mne-tools/mne-bids/blob/a99fe4dbe0609c1206e8156965f384741658b743/mne_bids/utils.py#L62

### Additional information

I'm using `mne==1.8.0` and `mne_bids=='0.16.0.dev49+ga99fe4d'`

**Comment by sappelhoff** [comment]
thanks for the report, would you mind elaborating what this means?

> MEGIN systems store chpi information

We'd be happy to receive a PR as a fix.

**Comment by skjerns** [comment]
Not sure what you mean, but `cHPI` is "continuous head position indicators", it's stored in additional MEG channels (usually 5 of them for redundancy), and they get the `ch_type=chpi` assigned by MNE.

I can do a PR, but I would need to know which ch_type they would get according to MNE-BIDS: `MEGOTHER` or `MISC`? And also cannot promise when I can work on it, as writing a test is also required (the fix itself is miniscule)

**Comment by sappelhoff** [comment]
Ah thanks! 

>  I would need to know which ch_type they would get according to MNE-BIDS: MEGOTHER or MISC?

If these channels contain (or are primarily used for) brain data, then MEGOTHER, else I would say MISC.

> And also cannot promise when I can work on it, as writing a test is also required (the fix itself is miniscule)

No problem, perhaps you could open a PR and push the fix, and then wait with adding the test until you have time.

**Comment by sappelhoff** [comment]
Yes, that seems even more appropriate. We just need to get the mapping between user, mne, and bids right.
