### ISSUE TITLE
Warning given for missing events, even if task=='rest'

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-bids#1324]
### Description of the problem

If no events are included, `mne_bids` gives a warning that events are missing.

https://github.com/mne-tools/mne-bids/blob/a99fe4dbe0609c1206e8156965f384741658b743/mne_bids/read.py#L232-L237

However, this warning also triggers on `write_raw_bids`, even if the `task="rest"`.

### Steps to reproduce

```Python
bids_subj = BIDSPath(subject='01',
                     datatype='meg',
                     task=f'rest01',
                     root=bids_root_path)
raw = mne.io.read_raw_fif(f'file.fif')
write_raw_bids(raw=raw,
                bids_path=bids_subj,
                overwrite=True,
                verbose=True
                )
```

### Expected results

No warning is given, because task='rest'

### Actual results

Warning is given.

I assume the task is stripped somewhere and the warning therefore given?

### Additional information

mne=0.18.0, dev branch of mne_bids

**Comment by sappelhoff** [comment]
Thanks! A fix would be welcome 🙏

**Comment by skjerns** [comment]
Sure! It was actually quite easy. See #1327
