### ISSUE TITLE
Loading TSV with missing column values is not possible

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-bids#1329]
### Description of the problem

Not sure if this is a bug or abiding rules, but when using different tools one after the other (e.g. first `mne-bids`, then `heudiconv`), it can happen that some TSV files have columns added that not all other tools populate.

I found nothing in the [official guidelines](https://bids-specification.readthedocs.io/en/stable/common-principles.html#tabular-files) stating that each cell in a TSV must be populated, so this should actually be a valid TSV, even if comment of the second row is missing. However, one can debate if that should be allowed, or whether it's a mistake of other BIDS tools to not populate empty cells when they add a column.

```tsv
filename  acq_time  comment
a1.edf  01.01.2020  asd
a2.edf  01.01.2020  
a3.edf  01.01.2020  asd
```

In this case, `mne-bids` is not able to read these TSV files anymore.

### Steps to reproduce

Create a TSV file with this content

```Python
filename  acq_time  operator  randstr
meg/sub-01_task-rest1_meg.fif  2024-02-02T15:02:49.685215Z
meg/sub-01_task-main_split-01_meg.fif  2024-02-02T15:15:03.625270Z
meg/sub-01_task-main_split-02_meg.fif  2024-02-02T15:15:03.625270Z
meg/sub-01_task-rest2_meg.fif  2024-02-02T15:46:22.520498Z
anat/sub-01_T1w_orig.nii.gz  2024-02-02T17:09:14.110000  skjerns  0337ded6
```

load the TSV file with `mne-bids` (which internally uses `np.loadtxt`, so we can just use that instead)

`np.loadtxt('scans.tsv')`

### Expected results

The file still loads and puts `NaN` at all positions where the columns were missing.

### Actual results

`ValueError: the number of columns changed from 4 to 2 at row 2; use `usecols` to select a subset and avoid this error`

### Additional information

dev version of mne-bids and mne=0.18

**Comment by hoechenberger** [comment]
Hello, I'd say this example violates the spec, as it states on the page you linked to:

> Missing and non-applicable values MUST be coded as n/a.

**Comment by skjerns** [comment]
> Hello,
> 
> > ```
> > filename  acq_time  comment
> > a1.edf  01.01.2020  asd
> > a2.edf  01.01.2020  
> > a3.edf  01.01.2020  asd
> > ```
> 
> I'd say this example violates the spec, as it states on the page you linked to:
> 
> > Missing and non-applicable values MUST be coded as n/a.

Agree!
