### ISSUE TITLE
Write a participants.json file

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#133]
The BIDS-validator raises a warning for each column in a TSV file that has a non-custom label. Custom labels are all those labels that are explicitly defined in the specification, such as `duration` and `onset` in the events.tsv file.

We are getting the following warning:

```
	1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
		./participants.tsv
			Evidence: Columns: age, sex, group not defined, please define in: /participants.json

```

So whenever we write age, sex, or group to our participants TSV file, we should also create an accompanying JSON file that elaborates on these column labels.

**Comment by monkeyman192** [comment]
I feel this shouldn't be needed for `age` `sex` and `group`. After looking at the specification it's fairly vague about this point as it only says
> As with all other tabular data, those additional phenotypic information files can be accompanied by a JSON file describing the columns in detail.

The 3 extra columns we write are very obvious what they are. I feel if anything the specification should maybe be updated to indicate that these 3 columns are the *recommended* ones and have the validator not require descriptions for.

If we do write a json it would be very basic though I guess...
```json
{
 "age": "The age of the participant",
 "sex": "The gender of the participant",
 "group": "Group within the project the participant belongs to"
}
```

**Comment by jasmainak** [comment]
I disagree. The specification is quite explicit and it says:

> The purpose of this file is to describe properties of participants such as age, handedness, sex, etc. In case of single 
session studies this file has one compulsory column participant_id that consists of 
sub-<participant_label>

Let's just add the `json` ...

**Comment by sappelhoff** [comment]
also, the JSON should be explicit about the levels of the factors we are introducing and the units for continuous variables. See this example:

```json
{
    "age": {
        "Description": "age of the participant",
        "Units": "years"
    },
    "group": {
        "Description": "group the participant belonged to in the experimental paradigm",
        "Levels": {
            "examplea": "blabla",
            "exampleb": "loremipsum"
        }
    },
    "sex": {
        "Description": "sex of the participant",
        "Levels": {
            "m": "male",
            "f": "female"
        }
    }
}
```
