### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by lbazan** [mne-tools/mne-bids#143]
Hi MNE-BIDS team

Please add the LICENSE file in the pypi source.

Cheers

**Comment by jasmainak** [comment]
The license is already visible in `pypi`

![license](https://user-images.githubusercontent.com/15852194/48981132-ae53e480-f09f-11e8-8559-40a04ef065aa.png)

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-bids/pull/145

we'll close when PR is merged
