### ISSUE TITLE
Add Requirements 

### ISSUE THREAD

**Issue by lbazan** [mne-tools/mne-bids#144]
Hi MNE-BIDS

the package needs numpy, pandas, six, shutil,
scipy, json.

Please add requirements.

Cheers

**Comment by jasmainak** [comment]
Thanks, but we have the dependencies mentioned in the `readme`.

**Comment by teonbrooks** [comment]
@jasmainak, should we include the requirements in the `setup.py ` to be more explicit? it would then download those packages if not present

**Comment by jasmainak** [comment]
maybe but will `pandas` and `matplotlib` install properly if it's already installed using `conda` ?

**Comment by monkeyman192** [comment]
> maybe but will pandas and matplotlib install properly if it's already installed using conda ?

If you do `pip install -U <packages>` then it will attempt to update them if possible, but if not just continues (iirc)

**Comment by jasmainak** [comment]
hmm ... I have had reports of `pip` corrupting the anaconda installation. So unless there is some clear evidence that this does not happen, we should keep it as it is.
