### ISSUE TITLE
No module named mne - test failed

### ISSUE THREAD

**Issue by lbazan** [mne-tools/mne-bids#147]
mne-bids-0.1]$ python3 setup.py test
running test
running egg_info
writing mne_bids.egg-info/PKG-INFO
writing dependency_links to mne_bids.egg-info/dependency_links.txt
writing top-level names to mne_bids.egg-info/top_level.txt
reading manifest file 'mne_bids.egg-info/SOURCES.txt'
writing manifest file 'mne_bids.egg-info/SOURCES.txt'
running build_ext
mne_bids (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: mne_bids (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: mne_bids
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 468, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/home/lbazan/rpmbuild/SOURCES/mne-bids-0.1/mne_bids/__init__.py", line 6, in <module>
    from .mne_bids import write_raw_bids  # noqa
  File "/home/lbazan/rpmbuild/SOURCES/mne-bids-0.1/mne_bids/mne_bids.py", line 22, in <module>
    from mne import Epochs
ModuleNotFoundError: No module named 'mne'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>

**Comment by lbazan** [comment]
mne-bids-0.1]$ python3 -m unittest
E
======================================================================
ERROR: mne_bids (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: mne_bids
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 468, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/home/lbazan/rpmbuild/SOURCES/mne-bids-0.1/mne_bids/__init__.py", line 6, in <module>
    from .mne_bids import write_raw_bids  # noqa
  File "/home/lbazan/rpmbuild/SOURCES/mne-bids-0.1/mne_bids/mne_bids.py", line 22, in <module>
    from mne import Epochs
ModuleNotFoundError: No module named 'mne'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

**Comment by monkeyman192** [comment]
Generally this just means you don't have mne installed.
Make sure if you have multiple versions of python installed that `mne` is installed for that particular version (so if python3.7 is called using `python3` then you can do `python3 -m pip install mne` to install it)

**Comment by jasmainak** [comment]
I never use the `Makefile` ... maybe @agramfort can suggest something

**Comment by lbazan** [comment]
[lbazan@ilbr SPECS]$ rpmbuild -ba python-mne-bids.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.ecmnXR
+ umask 022
+ cd /home/lbazan/rpmbuild/BUILD
+ cd /home/lbazan/rpmbuild/BUILD
+ rm -rf mne-bids-0.1
+ /usr/bin/gzip -dc /home/lbazan/rpmbuild/SOURCES/mne-bids-0.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd mne-bids-0.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm -rf mne-bids.egg-info
+ find CONTRIBUTING.md LICENSE Makefile README.md appveyor.yml bin doc examples mne_bids setup.py -type f -name '*.py' -exec sed -i '/^#![ ]*\/usr\/bin\/.*$/ d' '{}' ';'
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.l2L1jy
+ umask 022
+ cd /home/lbazan/rpmbuild/BUILD
+ cd mne-bids-0.1
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ LDFLAGS='-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
running build
running build_py
creating build
creating build/lib
creating build/lib/mne_bids
copying mne_bids/pick.py -> build/lib/mne_bids
copying mne_bids/mne_bids.py -> build/lib/mne_bids
copying mne_bids/io.py -> build/lib/mne_bids
copying mne_bids/utils.py -> build/lib/mne_bids
copying mne_bids/datasets.py -> build/lib/mne_bids
copying mne_bids/config.py -> build/lib/mne_bids
copying mne_bids/__init__.py -> build/lib/mne_bids
creating build/lib/mne_bids/commands
copying mne_bids/commands/mne_bids_raw_to_bids.py -> build/lib/mne_bids/commands
copying mne_bids/commands/__init__.py -> build/lib/mne_bids/commands
running build_scripts
creating build/scripts-3.7
copying and adjusting bin/mne_bids -> build/scripts-3.7
changing mode of build/scripts-3.7/mne_bids from 644 to 755
+ sleep 1
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ LDFLAGS='-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
running build
running build_py
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/mne_bids -> build/scripts-2.7
changing mode of build/scripts-2.7/mne_bids from 644 to 755
+ sleep 1
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.5Vqjfm
+ umask 022
+ cd /home/lbazan/rpmbuild/BUILD
+ '[' /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64 '!=' / ']'
+ rm -rf /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64
++ dirname /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64
+ mkdir -p /home/lbazan/rpmbuild/BUILDROOT
+ mkdir /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64
+ cd mne-bids-0.1
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ LDFLAGS='-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ /usr/bin/python2 setup.py install -O1 --skip-build --root /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64
running install
running install_lib
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/pick.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/mne_bids.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/io.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/utils.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/datasets.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
copying build/lib/mne_bids/config.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/commands/mne_bids_raw_to_bids.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/commands/__init__.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/__init__.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/pick.py to pick.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py to mne_bids.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/io.py to io.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/utils.py to utils.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/datasets.py to datasets.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/config.py to config.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py to mne_bids_raw_to_bids.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/commands/__init__.py to __init__.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py to __init__.pyc
writing byte-compilation script '/tmp/tmpT21MSQ.py'
/usr/bin/python2 -O /tmp/tmpT21MSQ.py
removing /tmp/tmpT21MSQ.py
running install_egg_info
running egg_info
creating mne_bids.egg-info
writing mne_bids.egg-info/PKG-INFO
writing top-level names to mne_bids.egg-info/top_level.txt
writing dependency_links to mne_bids.egg-info/dependency_links.txt
writing manifest file 'mne_bids.egg-info/SOURCES.txt'
reading manifest file 'mne_bids.egg-info/SOURCES.txt'
writing manifest file 'mne_bids.egg-info/SOURCES.txt'
Copying mne_bids.egg-info to /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids-0.1-py2.7.egg-info
running install_scripts
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin
copying build/scripts-2.7/mne_bids -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin
changing mode of /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin/mne_bids to 755
+ rm -rf /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin/mne_bids
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ LDFLAGS='-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ /usr/bin/python3 setup.py install -O1 --skip-build --root /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64
running install
running install_lib
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/pick.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/mne_bids.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/io.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/utils.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/datasets.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
copying build/lib/mne_bids/config.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
creating /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/commands/mne_bids_raw_to_bids.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/commands/__init__.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/commands
copying build/lib/mne_bids/__init__.py -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/pick.py to pick.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/mne_bids.py to mne_bids.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/io.py to io.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/utils.py to utils.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/datasets.py to datasets.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/config.py to config.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py to mne_bids_raw_to_bids.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/commands/__init__.py to __init__.cpython-37.pyc
byte-compiling /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids/__init__.py to __init__.cpython-37.pyc
writing byte-compilation script '/tmp/tmpg_x4azt4.py'
/usr/bin/python3 /tmp/tmpg_x4azt4.py
removing /tmp/tmpg_x4azt4.py
running install_egg_info
running egg_info
writing mne_bids.egg-info/PKG-INFO
writing dependency_links to mne_bids.egg-info/dependency_links.txt
writing top-level names to mne_bids.egg-info/top_level.txt
reading manifest file 'mne_bids.egg-info/SOURCES.txt'
writing manifest file 'mne_bids.egg-info/SOURCES.txt'
Copying mne_bids.egg-info to /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7/site-packages/mne_bids-0.1-py3.7.egg-info
running install_scripts
copying build/scripts-3.7/mne_bids -> /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin
changing mode of /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/bin/mne_bids to 755
+ /usr/lib/rpm/find-debuginfo.sh -j4 --strict-build-id -m -i --build-id-seed 0.1-2.fc29 --unique-debug-suffix -0.1-2.fc29.x86_64 --unique-debug-src-base python-mne-bids-0.1-2.fc29.x86_64 --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 -S debugsourcefiles.list /home/lbazan/rpmbuild/BUILD/mne-bids-0.1
find: 'debug': No such file or directory
+ '[' noarch = noarch ']'
+ case "${QA_CHECK_RPATHS:-}" in
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1 1
Bytecompiling .py files below /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python3.7 using /usr/bin/python3.7
Bytecompiling .py files below /home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.K5NcKd
+ umask 022
+ cd /home/lbazan/rpmbuild/BUILD
+ cd mne-bids-0.1
+ export PYTHONPATH=/home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64//usr/lib/python2.7/site-packages
+ PYTHONPATH=/home/lbazan/rpmbuild/BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64//usr/lib/python2.7/site-packages
+ pytest-2.7 mne_bids
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /home/lbazan/rpmbuild/BUILD/mne-bids-0.1, inifile:
plugins: cov-2.5.1
collected 0 items / 6 errors                                                                                                                         

======================================================================= ERRORS =======================================================================
__________________________________________________ ERROR collecting mne_bids/tests/test_commands.py __________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_commands.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_commands.py:6: in <module>
    from mne_bids.commands import mne_bids_raw_to_bids
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
__________________________________________________ ERROR collecting mne_bids/tests/test_datasets.py __________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_datasets.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_datasets.py:9: in <module>
    from mne_bids.datasets import fetch_faces_data, fetch_brainvision_testing_data
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
_____________________________________________________ ERROR collecting mne_bids/tests/test_io.py _____________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_io.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_io.py:7: in <module>
    from mne_bids.io import _parse_ext, _read_raw
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
__________________________________________________ ERROR collecting mne_bids/tests/test_mne_bids.py __________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_mne_bids.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_mne_bids.py:24: in <module>
    from mne_bids import make_bids_basename, make_bids_folders, write_raw_bids
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
____________________________________________________ ERROR collecting mne_bids/tests/test_pick.py ____________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_pick.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_pick.py:8: in <module>
    from mne_bids.pick import coil_type
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
___________________________________________________ ERROR collecting mne_bids/tests/test_utils.py ____________________________________________________
ImportError while importing test module '/home/lbazan/rpmbuild/BUILD/mne-bids-0.1/mne_bids/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_bids/tests/test_utils.py:16: in <module>
    from mne_bids.utils import (make_bids_folders, make_bids_basename,
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/__init__.py:6: in <module>
    from .mne_bids import write_raw_bids  # noqa
../../BUILDROOT/python-mne-bids-0.1-2.fc29.x86_64/usr/lib/python2.7/site-packages/mne_bids/mne_bids.py:25: in <module>
    from mne.io import BaseRaw
E   ImportError: cannot import name BaseRaw
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================== 6 error in 3.08 seconds ===============================================================
error: Bad exit status from /var/tmp/rpm-tmp.K5NcKd (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.K5NcKd (%check)

**Comment by jasmainak** [comment]
@lbazan you need to first install `mne`. Please follow the installation instructions. If you don't explain what you want to do, we cannot help.

**Comment by agramfort** [comment]
@lbazan the debian/linux packaging of MNE-Python is lagging behind. mne-bids needs mne 0.17 which was just release last week on pypi

any help to package mne in fedora/debian is more than welcome.
