### ISSUE TITLE
Removing MATPLOTLIB dependency 

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#158]
After #122 is merged, we should remove MATPLOTLIB

1. from our documented dependencies
2. from the CIs
3. add it as a "doc dependency"
4. add it to circleCI for building the docs

**Comment by jasmainak** [comment]
what's the benefit of this? `mne` already requires it, no?

**Comment by jasmainak** [comment]
okay then, PR is welcome :)
