### ISSUE TITLE
[docs] Convert all docstring to rst

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#159]
So I was having a look at the docs that are automatically created, and I noticed that they don't quite look correct (see for example [here](https://mne-tools.github.io/mne-bids/generated/mne_bids.mne_bids.write_raw_bids.html#mne_bids.mne_bids.write_raw_bids)).
Primarily the newlines are not conserved.
Apparently if the docstrings are completely in rst format then it will look correct so I think we should try fix up the docstrings a little so that they are rendered correctly.

**Comment by jasmainak** [comment]
yes I think this should be fixed! I noticed this before but was too lazy to fix it because it was already a long PR ...

**Comment by jasmainak** [comment]
This renders beautifully on master:
![master](https://user-images.githubusercontent.com/15852194/53854333-0e0f3500-3f97-11e9-89c9-5c2a32a21579.png)

So, I presume this issue has been fixed. @monkeyman192 feel free to reopen if you disagree.

**Comment by monkeyman192** [comment]
oh yep, thanks! I must have forgotten to add the `close` message on whatever PR it was I fixed this in...
