### ISSUE TITLE
[mne] deprecation of mne.find_events

### ISSUE THREAD

**Issue by dominikwelke** [mne-tools/mne-bids#164]
`mne.find_events` will be deprecated in future releases of mne. this will cause trouble, since `mne_bids.utils._read_events` is using this function if no event structure is provided.

quick-and-dirty solution would be an error-message that tells you to supply an event-structure.
better would be to switch to `mne.events_from_annotations` as the mne-developers suggest

**Comment by agramfort** [comment]
yes

>

**Comment by dominikwelke** [comment]
thanks for cleaifying @sappelhoff. 

under the current 0.18.dev mne.find_events is already breaking with my brainvision data

**Comment by jasmainak** [comment]
@dominikwelke a PR to fix it would be very welcome

**Comment by jasmainak** [comment]
see #167

**Comment by jasmainak** [comment]
closed by #167
