### ISSUE TITLE
writing big files to be BIDS compatible

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#17]
Right now files > 2GB are written as `filename-raw.fif` and `filename-raw-1.fif`. However, this needs to be made BIDS aware. That is write `filename_part-01_meg.fif` and `filename_part-02_meg.fif`

**Comment by agramfort** [comment]
for me it's virtually only 1 file. You should not read filename-raw-1.fif
directly. So maybe we can leave it as it is?

**Comment by jasmainak** [comment]
hmm ... but users will then try renaming the files because this new convention made it to the BIDS specification (see [page 16](https://docs.google.com/document/d/1FWex_kSPWVh_f4rKgd5rxJmxlboAPtQlmBc1gyZlRZM/edit?usp=sharing)). And as we know, renaming doesn't really work for such split files ... any opinion @teonbrooks ?

**Comment by jasmainak** [comment]
The thing is, many software such as `pybids` rely on the `<key>-<value>` structure of the filename to be able to query on BIDS datasets. The old Elekta convention breaks this rule making such operations harder.

**Comment by agramfort** [comment]
ok fair enough. We'll need to make the change in mne-python

**Comment by teonbrooks** [comment]
yeah, it's because of the way the pointers in other part(s) of the split files are definied and referred to within the fif file.

**Comment by teonbrooks** [comment]
so this is a bit complicated. I have been looking into the write function and the splitting of the files doesn't happen until the write file is written and it notices that it needs to go back for round 1+n. 

one solution: we could calculate the split at the beginning of the write for the file and have a switch case for naming if it is `bids` or not. it would require reworking the file naming logic within the `_write_raw` in `mne.io.base.py`

@larsoner, what are your thoughts? I see that you worked on file splitting

**Comment by larsoner** [comment]
We could add a `split_naming='elekta' | 'bids'` argument to `raw.save`, with a deprecation cycle to get to `'bids'` default. Or if it's possible to detect BIDS-standard naming, we could use `'auto'` to use Elekta-style when Elekta-like names are detected, BIDS when BIDS-style names are detected, and raise an error to be explicit if it's not clear.

It would be good to check that the bids-style naming works with MaxFilter, but in principle it should because the name of the next file gets stored. I can check once it's implemented.

**Comment by teonbrooks** [comment]
@jasmainak done :)

**Comment by jasmainak** [comment]
nice contribution @teonbrooks !

should we have a `whats_new.rst` to document these contributions and motivate future contributors/contributions?

**Comment by sappelhoff** [comment]
> should we have a whats_new.rst to document these contributions and motivate future contributors/contributions?

+1

**Comment by teonbrooks** [comment]
thanks!

however noticed a potential bug now with the split naming scheme addressed here: https://github.com/mne-tools/mne-python/issues/5519

stay tuned!

**Comment by jasmainak** [comment]
okay! looking forward @teonbrooks 

let me know if you need help in testing/trying out the PRs

**Comment by monkeyman192** [comment]
was this meant to have been fixed?
I am still having issues...
```
sub-01_ses-01_task-testing_acq-01_run-01_meg.fif
sub-01_ses-01_task-testing_acq-01_run-01_meg-1.fif
```
^ This is what my output looks like from MNE-BIDS with my data which is split (this is with the current master branch of MNE also, just in case...)
