### ISSUE TITLE
scans.tsv file writes paths with incorrect separator

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#175]
I run all my dev/testing on windows and I noticed which testing BIDSHandler that the data I generated using mne-bids wasn't being liked on Circle. The issue is because I am generating the data on a windows computer, so `os.path.join(~)` will use `\` as the separator, however, the BIDS specification requires `/` as the separator.
Should be an easy fix however so PR incoming...

**Comment by jasmainak** [comment]
sounds good. @monkeyman192 you should also review some PRs so I have less work ;-)
