### ISSUE TITLE
JOSS publication

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#188]
At the MNE-Sprint in Paris, @teonbrooks @jasmainak and I discussed about writing a short report on MNE-BIDS and publishing it in [JOSS](https://joss.theoj.org/about).

JOSS articles generally provide a very high level description of the software and its relevance:

> Your submission should probably be somewhere between 250-1000 words.

It would allow us to properly point to MNE-BIDS in citations and get some scholarly recognition for our work.

I suggest that we take `pybids` as an example and create a [`/paper`](https://github.com/bids-standard/pybids/tree/master/paper) directory in our repository where we prepare the submission.

Publishing at JOSS would mean that mne-bids stays separate from mne-python instead of being integrated eventually. In a short discussion with @agramfort, we all approved of this idea, because it will allow us to stay with our lightweight and "independent" repository, while users can still benefit from mne-bids by using it as a simple "module" to MNE-Python.

**Comment by sappelhoff** [comment]
One example of a JOSS publication is [Altair by Jake VanderPlas et al](https://www.theoj.org/joss-papers/joss.01057/10.21105.joss.01057.pdf)

It also seems to show up on [Google Scholar](https://scholar.google.de/citations?hl=de&user=0tDjsNUAAAAJ&view_op=list_works&sortby=pubdate)

**Comment by agramfort** [comment]
I am hoping the API will be rather stable by the summer so it can be
written during the summer. So yes +1. Let me know how to split
the work. A suggestion is to be as inclusive as possible with authors.

**Comment by jasmainak** [comment]
yes, we can add whoever made even one commit to the author list.

**Comment by teonbrooks** [comment]
> I am hoping the API will be rather stable by the summer

I am hoping it is stable by the end of week ;)

**Comment by teonbrooks** [comment]
re-visiting this issue, I think we are at a good point to draft a paper. we can create a md doc and add it to the repo. thoughts?

**Comment by jasmainak** [comment]
okay for me but maybe @sappelhoff should take the lead

**Comment by sappelhoff** [comment]
sure, I am happy to put up a draft soon where we can iterate towards a publication-ready document :)

**Comment by agramfort** [comment]
gr8
