### ISSUE TITLE
Acquisition time info in KIT data

### ISSUE THREAD

**Issue by grahamflick** [mne-tools/mne-bids#19]
Hi all, I've been testing raw_to_bids with KIT data and encountered a couple minor issues. Putting the first one here:

In _scans_tsv, the retrieval of the acquisition time selects the first element in a list returned by ```raw.info['meas_date']```

```acq_time = datetime.fromtimestamp(raw.info['meas_date'][0]).strftime('%Y-%m-%dT%H:%M:%S')```

But, unlike .fif files, in .con and .sqd files, ```raw.info['meas_date']``` returns only a single value, which causes an error. A quick fix could be selecting the acquisition time differently based on the file extension (below), but maybe this fails to address an issue in the format of the measurement info in KIT data?

```
fname, ext = os.path.splitext(raw_fname)
if ext in ['.con', '.sqd']:
    acq_time = datetime.fromtimestamp(raw.info['meas_date']).strftime('%Y-%m-%dT%H:%M:%S')
else:
    acq_time = datetime.fromtimestamp(raw.info['meas_date'][0]).strftime('%Y-%m-%dT%H:%M:%S')
```

**Comment by jasmainak** [comment]
@grahamflick thanks for giving it a try! Does this commit: https://github.com/mne-tools/mne-bids/commit/9f5c06711359e64e1ae95bda43f84d9132a37400 fix your problem?

**Comment by grahamflick** [comment]
@jasmainak sure does, thanks!
