### ISSUE TITLE
[ENH] Anonymize dates in dataset

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#193]
The BIDS specification that says anonymized date should have a year <= 1900 ([link](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file)). I quote:

> For anonymization purposes all dates within one subject should be shifted by a randomly chosen (but common across all runs etc.) number of days. This way relative timing would be preserved, but chances of identifying a person based on the date and time of their scan would be decreased. Dates that are shifted for anonymization purposes should be set to a year 1900 or earlier to clearly distinguish them from unmodified data.

There is an [anonymization](https://github.com/mne-tools/mne-python/blob/92f61faef72a335d6de63e816bd5bcfeaceffa09/mne/io/meas_info.py#L2008-L2038) procedure in MNE-Python. And it achieves that the measurement/recording date "`meas_date`" is assigned `None`. However, because we cannot have `None` as a date, this is actually a "magic date", see:

https://github.com/mne-tools/mne-python/blob/92f61faef72a335d6de63e816bd5bcfeaceffa09/mne/io/write.py#L20-L24

This "magic date" is some 35 minutes past midnight on the 1st of January 1970.

In MNE-BIDS, we could:
- parse all scans.tsv files
- parse all raw data that contains recording dates
- then calculate a (random) offset that needs to be deducted from the dates so that they are consistently shifted to earlier than 1990
- then write a function to:
    - adjust scans.tsv files in the BIDS directory
    - draw on MNE-Python's anonymization procedure to adjust the dates in the raw data files*

*this could mean also making a PR to MNE-Python and add a "constant_offset" argument to the anonymization procedure, see this [comment](https://github.com/mne-tools/mne-python/issues/4950#issuecomment-486287370)

**Comment by adam2392** [comment]
Any update on this? I totally need this cuz sometimes I forgot to anonymize correctly, and I get an angry bids validator. Is this the proposal you had in mind?

```
def anonymize_dataset(bids_root, ignore_sub=None, ignore_ses=None, ignore_task=None):
    # read scans.tsv

    for date, scan in scans.tsv:
        # anonymize the date to some magic date that doesn't make bids_validator complain
        
        # load in scan with mne
        
        # set_meas_date with mne 

        # re-save scan w/ same name
```

**Comment by jasmainak** [comment]
I believe this is already done thanks to @alexrockhill 

see [this function](https://mne.tools/mne-bids/stable/generated/mne_bids.get_anonymization_daysback.html#mne_bids.get_anonymization_daysback) and the related examples
