### ISSUE TITLE
Channel TSV

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-bids#2]
Since #1 is settled for now - I can close. 

Here I'm curious why `*_channel.tsv` for sample data is only displaying sample/condition info? According to [BEP008](https://docs.google.com/document/d/1FWex_kSPWVh_f4rKgd5rxJmxlboAPtQlmBc1gyZlRZM/edit#) 3.2

> *_channels.tsv: A channels .tsv file listing channel names, types, and other optional information.

I didn't see anything over at [#4128](https://github.com/mne-tools/mne-python/pull/4128), so it would be helpful to know how strictly we should adhere to BEP008 in this repo?

**Comment by kambysese** [comment]
@jasmainak I can start a PR to try and make `_channel_tsv` fall more in line with BEP008 3.2.2. LMK.

**Comment by jasmainak** [comment]
oops ... my bad indeed.

Fixed with https://github.com/mne-tools/mne-bids/commit/37bd5b73eddbe76af78b04ad8158379cc535e959

Thanks @kambysese !
