### ISSUE TITLE
Channel info for KIT reference channels

### ISSUE THREAD

**Issue by grahamflick** [mne-tools/mne-bids#20]
_channel_tsv calls channel_type from io.pick, which returns ```ref_meg``` for KIT reference channels. Since this isn't in the dictionary of channel names and descriptions, it yields an error. Could a solution be to just add the corresponding info to the existing dictionaries of channel types and descriptions?

The new dictionaries could be something like:
```map_chs = dict(grad='MEGGRAD', mag='MEGMAG', stim='TRIG', eeg='EEG',eog='EOG', ecg='ECG', misc='MISC',ref_meg = 'KITREF')```

```map_desc = dict(grad='Gradiometer', mag='Magnetometer',stim='Trigger', eeg='ElectroEncephaloGram', ecg='ElectroCardioGram', eog='ElectrOculoGram', misc='Miscellaneous', ref_meg='KITReference')```

**Comment by jasmainak** [comment]
Does this fix your problem https://github.com/mne-tools/mne-bids/commit/497d5120e26f412ef95706c7cbbe2314e6a3df48 @grahamflick ?

**Comment by grahamflick** [comment]
Yup, thanks! @jasmainak
