### ISSUE TITLE
our current (dev) version is wrong

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#204]
Our current version:

https://github.com/mne-tools/mne-bids/blob/9cb55591c328e0322b58e3dcc53e0b4897e500f4/mne_bids/__init__.py#L3

If we want to mirror the way it's done in MNE-Python, our current version should be `0.3.dev0`

see: https://github.com/mne-tools/mne-python/blob/3c9073f2c872af70db696e577420ab329495966f/mne/__init__.py#L19

probably would need to be updated in wiki as well: https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release

**Comment by jasmainak** [comment]
Sorry I am not sure I see the difference ... can you explain a bit?

**Comment by jasmainak** [comment]
oh indeed you are right. But I wouldn't change it midway. Let's skip a number for the next release. Otherwise, if someone reports a problem, we won't know where it came from ...

**Comment by sappelhoff** [comment]
I'll fix it today when I make the `0.3` release.

it'll be `0.4.dev0`
