### ISSUE TITLE
Homogenize use of `output_path` and `bids_root`

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#213]
We use both variable names in the code base ... but they mean the same thing.

This could perhaps be homogenized to ease interaction with the code.

see also: https://github.com/mne-tools/mne-bids/pull/211#discussion_r300075411

**Comment by adam2392** [comment]
I am down to take a look at this and refactor the codes to use "bids_root"?

Bids_root seems like a more intuitive name for the code base, because when I first used write_raw_bids, I thought output_path would be the path to the written file, not the output_path of the bids_root path.

**Comment by jasmainak** [comment]
go for it! Ok for using `bids_root`

**Comment by jasmainak** [comment]
closed by #303
