### ISSUE TITLE
Allow reading fiducials for write_anat also from a coordsystem.json (currently only mne.raw supported)

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#214]
see https://github.com/mne-tools/mne-bids/pull/211#issuecomment-508501309

Currently, we are taking the fiducials from MNE's `raw` object, and specifically `raw.info['dig'`. This is convenient, because MNE IO converts all different coordinate systems of the different raw data formats implicitly into FIFF formats --> so we have only the FIFF format to deal with.

When we are reading from `coordsystem.json`, we will have to interpret keys such as `CoordsystemDescription` and do the conversion to FIFF coordinates.

The benefit would be, that we can use the function also for `raw` data files, that do NOT have the required data to have a representation for `raw.info['dig']` ... what comes to mind are e.g., EEG data, iEEG data ... or complicated MEG systems, where one needs to have a large diversity of files (`headshape`, ...) and read them all into `raw` to get `raw.info['dig']`

**Comment by hoechenberger** [comment]
@sappelhoff Is this still relevant with the recent changes to `write_anat()`?

**Comment by sappelhoff** [comment]
Yes, I think we can close this. Pretty much everything has changed :-)

People can now read their BIDS data with `read_raw_bids`and have `raw` populated from the coordsystem.json files ... and then use `get_anat_landmarks` on that `raw`'s `info`
