### ISSUE TITLE
link to dev version of docs?

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#215]
We are currently only hosting the `stable` version of our docs.

CircleCI is building the dev docs on each PR.

Apparently, it is possible to [link to the most recent CircleCI artifacts](https://circleci.com/docs/api/#artifacts-of-the-latest-build)

--> this could be a way to have dev-docs available with no added effort.

I think it would involve making this link work:

`https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/latest/artifacts?circle-token=:token&branch=:branch&filter=:filter`

EDIT:
additional resources
- https://stackoverflow.com/a/52852011/5201771

**Comment by agramfort** [comment]
I've never done it. But yes it would be neat

>

**Comment by sappelhoff** [comment]
I think I made it work: https://circleci.com/api/v1.1/project/github/mne-tools/mne-bids/latest/artifacts/0/html/index.html?branch=master

This should always point to the latest CircleCI build of `master` and then point to the index of our docs. --> and if we only merge PRs that are green, we should never get into trouble.

Now we just need a good place to put it. ... E.g.,

- in the README
- as a "Tab" on the `stable` docs
- ...?

**Comment by agramfort** [comment]
both options are fine with me

>
