### ISSUE TITLE
CLI: Expose the "copyfile" functions as possible command line interfaces

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#220]
With MNE-BIDS we offer utility to rename files from several manufacturers, e.g. BrainVision: See the [example](https://851-89170358-gh.circle-artifacts.com/0/html/auto_examples/rename_brainvision_files.html#sphx-glr-auto-examples-rename-brainvision-files-py)

These utilities are important, because the specific files cannot simply be renamed with right-click and rename: They need to be fixed internally as well.

It would be cool if we could expose these utility functions as part of our [command line interface](https://851-89170358-gh.circle-artifacts.com/0/html/index.html#command-line-interface).

one could do
1. `pip install mne_bids`
1. `mne_bids copyfile_brainvision --input myfile.vhdr --output myNEWfile.vhdr`

perhaps one could rename `copyfile_brainvision` to `rename_brainvision` ... only for the sake of more prominently advertising the purpose of the function within the CLI (under the hood, we still call `copyfile_brainvision`)

**Comment by agramfort** [comment]
mne_bids copy --input myfile.vhdr --output myNEWfile.vhdr

should be enough to make it work

**Comment by jasmainak** [comment]
Agreed, this would be a nifty feature. I would actually go one step further to say:

mne_bids cp myfile.vhdr myNEWfile.vhdr

so you mirror the API of unix tools as closely as possible.

**Comment by sappelhoff** [comment]
I like `mne_bids cp myfile.vhdr myNEWfile.vhdr`

then we can run code internally that parses the extensions of the `--input` and `--output` arguments and redirects to 

- `copyfile_brainvision` if `.vhdr`
- `copyfile_eeglab` if `.set`
- etc.
- raises an error if `input-ext` and `output-ext` are different
- raises an error if an extension is not yet supported

If we want to take it even further, we could even allow conversions. For now, this would (currently) be possible
- from any format readable by MNE to BrainVision, via [`pybv`](https://github.com/bids-standard/pybv)
- we should generally support conversion only into BIDS compatible formats (not the other way around)

**Comment by jasmainak** [comment]
no conversions for now, let's do one step at a time and start with CLI for copy :-) You'd also need to document the command line API somewhere like MNE does -- https://martinos.org/mne/stable/generated/commands.html?highlight=command%20line
