### ISSUE TITLE
_read_events does not warn if STIM channel found, but always zero

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#221]
In our [`test_ctf`](https://github.com/mne-tools/mne-bids/blob/22812d9c60ddecc9ed22d526b61fff9ec2ab43e8/mne_bids/tests/test_write.py#L291) test, we are working with the testing CTF data. The file does have three `stim` channels, so `_read_events` is triggered:

```Python
    # code from _read_events
    elif 'stim' in raw:
        events = find_events(raw, min_duration=0.001, initial_event=True)
    # < some more elifs for other data formats cut out here >
    else:
        warnings.warn('No events found or provided. Please make sure to'
                      ' set channel type using raw.set_channel_types'
                      ' or provide events_data.')
        events = None
    return events, event_id
```

... and the warning is skipped. Then we proceed to `write.py`, where we have these lines:

```Python
    # code from write_raw_bids
    events, event_id = _read_events(events_data, event_id, raw, ext)
    if events is not None and len(events) > 0 and not emptyroom:
        _events_tsv(events, raw, events_fname, event_id, overwrite, verbose)
```

and we do not write events.

# Complaint

overall I think it's good that we warn whenever Events are not found / present 

... however, currently we do NOT warn IF `stim` channels are present (but they are always zero)

I think we should warn here.

**Comment by agramfort** [comment]
would it warn if you have rest data with no stimuli?

>

**Comment by sappelhoff** [comment]
> would it warn if you have rest data with no stimuli?

if the `raw` contains `stim` channels that are zero the whole time, no warning will be raised

**Comment by agramfort** [comment]
ok sounds good
