### ISSUE TITLE
Make dedicated example to reading raw bids files

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#222]
Our `read_raw_bids` functionality is improving one PR at a time, and I think we could have a dedicated example to show that off.

Currently, `read_raw_bids` is used in one example more as a "side note": [mne-sample-data-example](https://851-89170358-gh.circle-artifacts.com/0/html/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py)

Also, I would rename the "Gallery" tab to "Examples", because Gallery always makes me think of a photo exhibit:

![image](https://user-images.githubusercontent.com/9084751/61127877-c9e5f100-a4b0-11e9-848b-bb3f73a49710.png)

**Comment by agramfort** [comment]
works for me

>

**Comment by jasmainak** [comment]
+1 for Examples lol and +1 for dedicated example :-)

**Comment by sappelhoff** [comment]
When updating this example, we should also update the `quickstart` part of the README:

Quickstart
----------

Currently, we support writing of BIDS datasets for MEG and EEG. Support for
iEEG is experimental at the moment.

.. code:: python

    >>> from mne import io
    >>> from mne_bids import write_raw_bids
    >>> raw = io.read_raw_fif('my_old_file.fif')
    >>> write_raw_bids(raw, 'sub-01_ses-01_run-05', output_path='./bids_dataset')

**Comment by AdoNunes** [comment]
I could work on that if an example is still needed?l

**Comment by jasmainak** [comment]
Go for it! Let me know if you need any help

**Comment by adam2392** [comment]
@AdoNunes are you still working on this? If not, let me know and I can contribute something.

Else, #213 was addressed to generate a new keyword arguments for the `write/read raw_bids` and `make_bids_folders` functions.

**Comment by hoechenberger** [comment]
Can this issue be unpinned?

**Comment by jasmainak** [comment]
yes, I think so!
