### ISSUE TITLE
Make mne-bids less whiny?

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-bids#232]
Right now, mne-bids is extremely strict in what type of files it will read. For example, here:  
https://github.com/mne-tools/mne-bids/blob/master/mne_bids/utils.py#L135-L154  
the function checks against a white-list of BIDS approved parameters.

For a validator, this would be desirable, but for a reader? If I decide I want a custom parameter that is not in the BIDS standard (yet), the whole of mne-bids becomes unavailable to me.

Should mne-bids adopt a "be generous on input, strict on output" approach?

**Comment by agramfort** [comment]
can you be more specific? can you give an example of what you would like to
be able to do?

**Comment by wmvanvliet** [comment]
One use case woul dbe slightly non-comformant BIDS datasets. Say the raw files are named `sub-01-ses-01-run-01-task-naming_meg.fif`. MNE-bids will complain that `task` came after `run` (which is ok), but then flat out refuses to read the file (maybe not ok?)

**Comment by wmvanvliet** [comment]
Feel free to close this as "~mne-bids~Marijn is whining" :) I was just wondering what the reason for these strict tests is.

**Comment by agramfort** [comment]
> I was just wondering what the reason for these strict tests is.

make sure people follow the standard so we can simplify analysis code? :)

**Comment by sappelhoff** [comment]
> I was just wondering what the reason for these strict tests is.

I think our working assumption for all `read_bids` functionality was that for the datasets under question, the `bids-validator` has been run and all issues were solved.

And I agree with Alex for the reason: It allows us to focus on other (more exciting?) things.

I would find it okay however, to pass a flag `strict=False` (defaults to strict=True, our current behavior), where many of the errors are emitting warnings instead ... and files are being read/processed "on the users on risk".

Would that be what you thought of @wmvanvliet ?

**Comment by agramfort** [comment]
don't open the pandora's box. Why are these files misnamed? if they don't
pass the bids validator then
I don't think mne-bids should be held responsible

>

**Comment by wmvanvliet** [comment]
Makes sense. Thanks for the clarification guys!
