### ISSUE TITLE
write_anat deface MRI

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#239]
As written, MNE-BIDS doesn't look like it de-faces MRI. Freesurfer has an mri_deface command but that would require a dependency on Freesurfer and it's incompatibility with Windows... How should this be handled or should this not be supported?

**Comment by jasmainak** [comment]
It's a good question. A quick google search revealed many tools to do this:

https://github.com/poldracklab/pydeface
https://github.com/nipy/quickshear
https://github.com/AKhazane/DeepDeface
https://github.com/PeerHerholz/BIDSonym

Only quickshear seems to return a nibabel object but it's not the best defacing quality. Maybe you can motivate the DeepDeface folks to have an API to return a nibabel object. Once you have that, you can pass it to `write_anat`

**Comment by agramfort** [comment]
it requires tensorflow ... thought it's still better than FSL or
freesufer...

now I think that using marked fiducial points it's actually not that hard
to do
it in pure python...

challenge for @larsoner? :)

>

**Comment by agramfort** [comment]
yes :)

>

**Comment by jasmainak** [comment]
quickshear comes close, but maybe @larsoner can cook up something better ...

**Comment by alexrockhill** [comment]
Ok talking to RO about defacing his recommendation was use take the BIDS-specified landmarks (you will probably get LPA, RPA and NAS but you might get other less common landmarks that could be translated) and then make a bounding box relative to those that could be either zeroed out or smoothed based on user input. Other options pretty much all involve freesurfer/FSL/TensorFlow dependencies. I wanted to put this out there before working on this in case anyone had any thoughts about this.

**Comment by jasmainak** [comment]
sounds like a good idea to me!

**Comment by larsoner** [comment]
Alternatively, if we know that the BIDS MRI has a MNI transformation (?) we can in a standard way transform the fsaverage fiducial locations to each subject's MRI (see #6733). This is probably less accurate than the BIDS-provided ones, but we can use this for example if they're missing.

**Comment by jasmainak** [comment]
yeah, that's a good plan!
