### ISSUE TITLE
changing session within a participant

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-bids#24]
Hi, 
I have multiple session per participant and I did not see how to specify the session when using raw_to_bids function? (to output the bids file in a 'ses-02' folder in the same participant). Is it possible?
Thank you!
Romain

**Comment by jasmainak** [comment]
Indeed, it's hard coded at the moment. We'll need a fix :-)

**Comment by agramfort** [comment]
maybe @romquentin you can give it a try?

**Comment by romquentin** [comment]
I tried something here: #25
Sorry if it is messy :) This is my first pull request.
I did not test it because I needed the #23 merge...
Thank you
