### ISSUE TITLE
EEG Data: Chunking EDF based on task

### ISSUE THREAD

**Issue by smeisler** [mne-tools/mne-bids#240]
Hello,

Our teams collect a single EDF file per session that contains all tasks. EEG-BIDS requires that each task has it's own set of BIDS files (edf, json, channels etc.). We collect annotations that denote when tasks begin (and can calculate end times with the event durations) and have translated the annotation times to sample #. Do you know how we could chunk the EDF files so we have one EDF per task to be BIDS compliant? I would be happy to provide more information as needed.

Thank you,
Steven

**Comment by sappelhoff** [comment]
Hi @smeisler :-)

One quick idea that comes to my mind is reading the EDF with [MNE-Python](https://github.com/mne-tools/mne-python) to get a `raw` object, and then using [`raw.crop`](https://martinos.org/mne/dev/generated/mne.io.Raw.html#mne.io.Raw.crop) on your data using your computed indices.

From there you can proceed to write the cropped `raw` objects either to BrainVision format (e.g., using [`pybv`](https://github.com/bids-standard/pybv)), or back to EDF format (e.g., using [`pyedf`](https://github.com/bids-standard/pyedf)) ... but I would recommend BrainVision :+1:

**Comment by smeisler** [comment]
Thanks for the prompt response! I'll try that soon.

**Comment by smeisler** [comment]
I was able to use crop to separate the EDF file, but when I go to write the EDF to bids with write_raw_bids, I get the following error (the variable "raw" is the original EDF file that contained all tasks):

AssertionError:
Arrays are not equal
raw.times should not have changed since reading in from the file. It may have been cropped.

**Comment by sappelhoff** [comment]
Can you post the code you are using? You can use Markdown to format your code, see: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by jasmainak** [comment]
Yeah, cropping is not allowed. We have a check for that here: https://github.com/mne-tools/mne-bids/blob/master/mne_bids/write.py#L802

**Comment by jasmainak** [comment]
The reason is that MNE cannot write to any format other than fif. So internally the files are simply copied over. Even if you do `raw.crop` this is will not affect what is written.

If you want to support writing to Brainvision, we need to do this properly. There is an attempt [here](https://github.com/mne-tools/mne-bids/pull/237) by @alexrockhill. Perhaps you can join forces to make it happen?

**Comment by sappelhoff** [comment]
My idea for @smeisler was actually different.

1. load original EDFs in MNE-Python
1. crop the data
1. use pybv to write the cropped data to BrainVision format
1. load the new BrainVision format files with MNE-BIDS and write to BIDS

**Comment by smeisler** [comment]
Sorry for late update, but this seemed to have worked, so thanks! Closing now.
