### ISSUE TITLE
plot_anat should use BIDS subjects_dir

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#242]
I'm a bit confused by the example of convert_mri_and_trans.py. I think here:

https://github.com/mne-tools/mne-bids/blob/master/examples/convert_mri_and_trans.py#L139-L150

It should actually read in the nifti file that is written instead of the old mgz file. What do you think @sappelhoff ?

**Comment by sappelhoff** [comment]
You are right, fix is coming!
