### ISSUE TITLE
Update text before release

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#258]
The setup.py still states that this is experimental. I think it's grown up a fair bit :) this is the text that ends up on pypi. we should update it to reflect the package's aim

https://github.com/mne-tools/mne-bids/blob/f8f267b45ac36e1600ea9ceb5540299e1bf3ab21/setup.py#L17

**Comment by sappelhoff** [comment]
Thanks for the reminder @teonbrooks! Any suggestions to how we should describe it?

**Comment by teonbrooks** [comment]
here is the description for MNE-Python:
```
MNE python project for MEG and EEG data analysis.
```

For this project, we could say,
```
An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
```
