### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#265]
Hi, I've created a `conda-forge` package of `mne-bids`: https://anaconda.org/conda-forge/mne-bids

- [x] Would anybody like to co-maintain the [recipe](https://github.com/conda-forge/mne-bids-feedstock/blob/master/recipe/meta.yaml)?
- [ ] Could / should I update the installation instructions to include this package?

**Comment by jasmainak** [comment]
That's excellent, thanks for creating it!

- Feel free to make a pull request to add an optional way to install it through `conda`
- Happy to be added as a co-maintainer. But the disclaimer is that I have never worked with conda recipes :)

**Comment by agramfort** [comment]
I personally feel that conda for a pure python package is extra work
for little gain when pypi is there. But some folks like it :)

Make sure the notes on how to make a release are there so
you don't end up with a conda package that is old

i am not even sure of how maintains the mne-python recipe ...

**Comment by hoechenberger** [comment]
Hi @agramfort,

> Make sure the notes on how to make a release are there so you don't end up with a conda package that is old

no worries, it's super simple, as the `conda-forge` folks have a bot in place that registers new PyPI releases and automatically files a PR to update the feedfstock. Maintainers then simply have to merge that PR (and sometimes update the dependencies, if they changed upstream), it's no hassle at all.

I prefer to install everything via `conda`; this ensures consistency in the virtual environments, and makes it easy to have dedicated environments for each project / analysis: `conda create -n foo foo`, and you're set :)

> i am not even sure of how maintains the mne-python recipe ...

According to
https://github.com/conda-forge/mne-feedstock/blob/a63679acd327f003efd6f0ee84c7c2978f967c50/recipe/meta.yaml#L52-L54
this is currently @larsoner and @christianbrodbeck

**Comment by agramfort** [comment]
cool !

**Comment by sappelhoff** [comment]
nice! :sunglasses:
