### ISSUE TITLE
Update How to make a release guide to include conda-forge package

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#267]
https://github.com/mne-tools/mne-bids/pull/266#issuecomment-528043905

**Comment by sappelhoff** [comment]
@hoechenberger we will soonish have to make a new release to comply with JOSS rules (--> do a release upon publication).

Can you please write down the workflow for making the release on conda? A stepwise "cookbook" procedure would be great!

**Comment by hoechenberger** [comment]
Seems I’m behind schedule again 😇 Will look into this tonight!

**Comment by hoechenberger** [comment]
My computer broke, I will try to organize a replacement tomorrow. This just to say that I'll probably not work on this tonight unless you tell me it's super urgent? :)

**Comment by sappelhoff** [comment]
no, I think as long as we get it within the next two week it'd be great :-)

**Comment by jasmainak** [comment]
this issue should be closed as it's taken care of
