### ISSUE TITLE
write_raw_bids and write_anat? should have an anomymize parameter

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#269]
cc @jasmainak @LorenzE

**Comment by jasmainak** [comment]
+1 I think it might be an interesting issue for @alexrockhill

**Comment by alexrockhill** [comment]
Hey @larsoner, @drammock and I were talking and we had come up with using nibabel as a soft dependency, then finding the surface via either nibabel if they have that or marching cubes and then smoothing areas of high curvature and applying that back to the raw pixel values. Does that sound like a fruitful approach?

**Comment by agramfort** [comment]
here is a way to do MRI anon using freesurfer:

 mri_deface T1.mgz
/Applications/freesurfer/average/talairach_mixed_with_skull.gca
/Applications/freesurfer/average/face.gca T1_anon.nii

it just worked great for me.

>

**Comment by alexrockhill** [comment]
@agramfort I think that was the original idea and then we followed this thread https://github.com/mne-tools/mne-bids/issues/239. We can do mri_deface and that would be easy, do we still want a numpy/scipy-dependency only method?

**Comment by agramfort** [comment]
a pure numpy / scipy solution would be great. But maybe it's hard...
relying on an external tool is also a way to blame someone else
if it is not truly anonymized...

>

**Comment by larsoner** [comment]
Hadn't thought about blame / maintainability -- agreed, let's just use Freesurfer for this.

**Comment by alexrockhill** [comment]
@larsoner Sorry for changing the conversation between issues but does this https://github.com/mne-tools/mne-bids/issues/239 sound ok?

**Comment by jasmainak** [comment]
+1 on my end. Do you want to give it a shot with help from @robertoostenveld?

**Comment by sappelhoff** [comment]
Closing, because we do have `anonymize` for `write_raw_bids` and `deface` for `write_anat` now.
