### ISSUE TITLE
we need to specify minimum version requirements

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#276]
I am using mne-bids right now and I got an error that numpy got an unexpected keyword argument, `encoding`. I found out that the argument was introduced in 1.14, and then I realized, we don't specify a minimum version of any of our required packages. I think we need to enforce some minimum value. in mne-python, we have it in the readme. this error would have still occurred there because the minimum value is 1.12.

https://github.com/mne-tools/mne-bids/blob/78f40a19f353fb56017ea734877dba2b9fbdc8d4/mne_bids/tsv_handler.py#L121

**Comment by jasmainak** [comment]
Agreed absolutely!
