### ISSUE TITLE
write_raw_bids doesn't convert the .seq, .hsp, and .elp KIT related files

### ISSUE THREAD

**Issue by zuxfoucault** [mne-tools/mne-bids#283]
before bids conversion
![](https://files.gitter.im/mne-tools/mne-python/A33S/thumb/Screen-Shot-2019-11-03-at-12.56.11.png)

after bids conversion
![](https://files.gitter.im/mne-tools/mne-python/HxFs/thumb/Screen-Shot-2019-11-03-at-12.58.48.png)

**Comment by jasmainak** [comment]
@zuxfoucault I updated your description to include the screenshots

**Comment by zuxfoucault** [comment]
Also, raw read from `raw = read_raw_bids(bids_basename + '_meg.con', output_path)`, raw.info['dig'] information would loss after bids conversion.

**Comment by jasmainak** [comment]
I'm not sure if they are not supported @teonbrooks ? The BIDS specification does not forbid additional files that are not in the specification. And it seems we need these files to get the digitized head points in KIT system, no?

**Comment by teonbrooks** [comment]
i see what's going on. so we handle this properly for the marker files by storing the input strings into the raw constructor. we would need to capture the `hsp` and `elp` args and do the same there ([ref](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#head-shape-and-electrode-description-_headshapeltextgt)). 

i think the coordsystem.json also need to be updated with these files' locations

**Comment by jasmainak** [comment]
Right, @teonbrooks or @zuxfoucault does any of you have time to make a PR?

**Comment by zuxfoucault** [comment]
I added .elp, .hsp file copy in write.py, if it's enough i could make a PR
https://github.com/zuxfoucault/mne-bids/blob/master/mne_bids/write.py#L1269

But also I am thinking how to make it work in read.py

**Comment by jasmainak** [comment]
PR would be very welcome! If you start something, we can help you finish :-)
