### ISSUE TITLE
[ENH] Saving out fiducials to trans file for deface iEEG

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#288]
Maybe this already exists but could potentially be added to write_anat but I have iEEG data without a digitization montage and would like to deface a related aMRI but can't because as written deface requires a trans file. Deface only requires the nasion, LPA and RPA from the trans which could be set and saved to a trans file by clicking on the head model in the mne_analyze/mne coreg gui unless there's something wrong with doing that.

**Comment by agramfort** [comment]
mne coreg cannot save a trans without providing dig points?

>

**Comment by alexrockhill** [comment]
I didn't know any way to do that in mne_analyze but I guess mne coreg can, I don't know how though. You'd have to create new dig points right?

**Comment by agramfort** [comment]
mne coreg does not do this. I checked. Now one way to do this is to use
https://mne.tools/dev/generated/mne.channels.make_dig_montage.html
pass lpa, rpa and nasion specifying the coordinate system and you have
dig points that mne-bids should be able to write.

>

**Comment by jasmainak** [comment]
I am not sure I follow @agramfort . Do you propose to use "fake dig points" to generate a trans that is needed for `write_anat`?

**Comment by jasmainak** [comment]
I think this could be worthy of some documentation for sure.

**Comment by alexrockhill** [comment]
Thanks @agramfort! Since I opened the issue, could do a PR for how to make dig points and align them, it would probably only be used for defacing but maybe other people would want to do that too.

**Comment by agramfort** [comment]
Thinking out loud

Maybe mne Coreg can allow you to save fids as dig in mri coordinates 

Add a dig parameter to write_anat to save anatomical landmarks more transparently

**Comment by alexrockhill** [comment]
Ok so the one thing that I'm not sure about is scaling the distance between the three points. My best idea for a solution at the moment is to use the mne sample data fiducials under the assumption that head sizes of individuals are close enough. If anyone has a better idea, I'd love to hear it as one drawback to this approach is that it wouldn't work for children.

**Comment by alexrockhill** [comment]
In regards to setting the scale it doesn't matter the fiducials are able to be set independent of eachother. Also I was able to deface the MRI of our iEEG patient so the process works not just on example data!

**Comment by agramfort** [comment]
you should not store fiducials that are not valid location in MRI space. I
don't get why
you may wonder how to scale these points. They are from a template or
default values.
If we start to have datasets with fiducials that are not really fiducials
it's bad.

>
