### ISSUE TITLE
[docs,joss] binder examples do not have mne_bids installed

### ISSUE THREAD

**Issue by jdkent** [mne-tools/mne-bids#295]
`mne_bids` should be installed as a [dependency for generating the binder notebooks](https://github.com/mne-tools/mne-bids/blob/159797793ed80a169cd5c26641c8d91b84669b27/doc/conf.py#L130).

currently, `mne_bids` is not available for the binder examples ([example](https://mybinder.org/v2/gh/mne-tools/mne-bids/gh-pages?filepath=notebooks/auto_examples/create_bids_folder.ipynb))

**Comment by sappelhoff** [comment]
This should now be fixed: https://github.com/mne-tools/mne-bids/commit/acd5717a8c3d6c875693e53c8619d77e4f04906e

Please reopen if something is still wrong. :-)
