### ISSUE TITLE
[joss,refactor] similarity to pybids

### ISSUE THREAD

**Issue by jdkent** [mne-tools/mne-bids#297]
Definitely not an immediate issue, but I see some duplication of effort between `mne-bids` and `pybids`.

for example, [get_kinds](https://github.com/mne-tools/mne-bids/blob/159797793ed80a169cd5c26641c8d91b84669b27/mne_bids/utils.py#L32) in `mne-bids` appears similar to [get_entities](https://github.com/bids-standard/pybids/blob/24d2032020fd407e5bcbbbf20943726f48717574/bids/layout/layout.py#L602) in `pybids`.

[make_bids_basename](https://github.com/mne-tools/mne-bids/blob/159797793ed80a169cd5c26641c8d91b84669b27/mne_bids/write.py#L745) in `mne_bids` is also similar to [build_path](https://github.com/bids-standard/pybids/blob/24d2032020fd407e5bcbbbf20943726f48717574/bids/layout/writing.py#L62) in `pybids`.

I understand there is a balance between duplication of effort and bringing in extra dependencies, but I wanted to bring this up and see what your opinions are for synchronizing efforts (this may be for further down the line).

**Comment by sappelhoff** [comment]
Hi @jdkent, thanks for bringing up this discussion point. 

As you already hint at in your post, our decision for "duplicating" some pybids functionality was driven by the idea to rely on as few dependencies as possible. In fact, we *did* rely on pybids earlier this year, but then actively tried to reduce this dependency for user convenience (see e.g., https://github.com/mne-tools/mne-bids/issues/250#issue-476515380).

The pybids equivalents to `get_kinds` and `make_bids_basename` both rely on the pybids `layout` and are thus dealing with objects. For the mne-bids needs it has so far sufficed to have the short and simple functions like `get_kinds` and `make_bids_basename`.

However, if we in the future find that we require more and more of these basic bids-handling functions, I would see that as a good reason to go back to a pybids dependency.

Perhaps relevant in this context is also this issue: https://github.com/mne-tools/mne-bids/issues/255

cc @jasmainak @agramfort who were part of the discussion whether to use more pybids, or write the needed parts ourselves.

**Comment by agramfort** [comment]
Indeed I suggest to limit dependencies unless there start to have a lot of
code
duplication. Here it's just 2 short functions so I feel it's simpler in
terms of maintenance.
But yes we should not reinvent the wheel.

>

**Comment by jasmainak** [comment]
indeed, we were aware of the powerful querying functionality that pybids provides and we certainly don't want to reinvent the wheel. Here we want to do things that are specific to MEG/EEG/iEEG processing for BIDS which cannot be non-trivially achieved with other software.

**Comment by jdkent** [comment]
Thanks for the replies! Sounds like you all are well aware of `pybids` and are monitoring how much duplication is occurring between packages. I'll close this issue.
