### ISSUE TITLE
modernize digitization code

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#301]
Due to some refactoring in MNE (mne-tools/mne-python#6903), we now get:

```py
(mnebids) C:\Users\appelhoff\Desktop\bids\mne-bids>mne_bids
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\mnebids\Scripts\mne_bids-script.py", line 11, in <module>
    load_entry_point('mne-bids', 'console_scripts', 'mne_bids')()
  File "C:\tools\miniconda3\envs\mnebids\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\tools\miniconda3\envs\mnebids\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\tools\miniconda3\envs\mnebids\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\tools\miniconda3\envs\mnebids\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\appelhoff\desktop\bids\mne-bids\mne_bids\__init__.py", line 6, in <module>
    from mne_bids.write import (write_raw_bids, make_bids_folders, make_bids_basename,  # noqa: E501 F401
  File "c:\users\appelhoff\desktop\bids\mne-bids\mne_bids\write.py", line 26, in <module>
    from mne.io._digitization import _get_fid_coords
ModuleNotFoundError: No module named 'mne.io._digitization'
```

cc @sappelhoff

**Comment by agramfort** [comment]
I expected this to happen. Maybe copy this private function to mne-bids to
avoid the issue.
my bad...

>

**Comment by sappelhoff** [comment]
I am a bit confused ...

In the dev version of MNE-Python,  `_get_fid_coords` seems to be in [`mne.io._digitization`](https://github.com/mne-tools/mne-python/blob/76f38bdd351627504618516be29cf03947096a85/mne/io/_digitization.py#L215), which is exactly where we are importing it from in the dev version of mne-bids:

https://github.com/mne-tools/mne-bids/blob/8edbd97b64f42ca70d1e4110375cf769bce2297d/mne_bids/write.py#L26

So dev mne-bids should work when being used with dev mne-python.

---

The issue I showed above (linked by Mainak in the original post), was after doing a STABLE install ... so mne-bids 0.3 and mne-python 0.19.

Why is something breaking?

**Comment by agramfort** [comment]
private functions and especially these ones can move between versions

>

**Comment by jasmainak** [comment]
yeah I think we can copy this function into `mne-bids` as it seems fairly independent of other private functions in MNE

**Comment by agramfort** [comment]
yes go for it

**Comment by sappelhoff** [comment]
just to clarify what we want to do:

1. fix the CLI in our current stable version 0.3 ... and make a 0.3.1 release?

OR

2. make sure that the CLI will work in our next release 0.4?

---

If we want 1. ... then copying the private func will probably be easiest.

If we want 2. however, we should probably solve it without copying a private function.

**Comment by sappelhoff** [comment]
I cannot reproduce this error with a fresh installation of mne-bids dev version :man_shrugging: 

1. `conda create -n tryit Python=3.6`
1. `conda activate tryit`
1. `pip install -U mne`
1. `git clone https://github.com/mne-tools/mne-bids`
1. `cd mne-bids`
1. `pip install -e .`
1. `mne_bids` --> no issues

**Comment by jasmainak** [comment]
yeah it's now fixed thanks to a commit by Alex
