### ISSUE TITLE
[joss] add code of conduct

### ISSUE THREAD

**Issue by jdkent** [mne-tools/mne-bids#315]
Here are a couple examples for a code of conduct
- [fmriprep](https://github.com/poldracklab/fmriprep/blob/5d0c823921a2418f95ca5ff4ea499569971212b9/CODE_OF_CONDUCT.md)
- [nibetaseries](https://github.com/HBClab/NiBetaSeries/blob/a756e85cab21e5e94cb37ebb6ecea3c698330e0c/CODE_OF_CONDUCT.rst)
- [STEMMRoleModels](https://github.com/KirstieJane/STEMMRoleModels/blob/3510453ac71cfa79a6713ca78bdbe72482d8dc08/CODE_OF_CONDUCT.md)

**Comment by sappelhoff** [comment]
Thanks @jdkent 

I think we could use the CoC of MNE-Python (see [here](https://github.com/mne-tools/mne-python/blob/master/CODE_OF_CONDUCT.md)) ... WDYT @jasmainak @agramfort ?

Perhaps we can do it using the GitHub organization feature? That way, a single CoC file would be shared for all MNE repositories. cc @larsoner 

> You can add default community health files for your organization to the root of a public repository called .github that is owned by the organization. GitHub will use and display default files for any public repository in the organization that does not have its own file of that type in any of the following places ...

see here:

https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization

**Comment by agramfort** [comment]
Anything is ok for me

**Comment by larsoner** [comment]
I like the organization-wide one. I think we should check that the MNE-CPP folks are okay with ours. Can you open an issue on their GitHub repo to ask?

**Comment by sappelhoff** [comment]
@larsoner we got approval from the MNE-CPP folks in https://github.com/mne-tools/mne-cpp/issues/418#issuecomment-563035899.

Could you open the new `.github` repo and put the MNE-Python Code of Conduct there, please? I don't think I have the required rights for this.

**Comment by larsoner** [comment]
Done

https://github.com/mne-tools/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by sappelhoff** [comment]
awesome, thanks a lot @larsoner and @jdkent for bringing up this point.
