### ISSUE TITLE
ImportError: cannot import name 'get_anonymization_daysback' from 'mne_bids'

### ISSUE THREAD

**Issue by zuxfoucault** [mne-tools/mne-bids#325]
#### Describe the bug
ImportError: cannot import name 'get_anonymization_daysback' from 'mne_bids'

#### Steps to reproduce
`python tests/test_write.py`

Error message:
```
  File "test_write.py", line 32, in <module>
    from mne_bids import (write_raw_bids, read_raw_bids, make_bids_basename,
ImportError: cannot import name 'get_anonymization_daysback' from 'mne_bids' (/home/foucault/anaconda3/envs/mne_bids/lib/python3.7/site-packages/mne_bids/__init__.py)
```

**Comment by agramfort** [comment]
You need to work with mne master branch to develop here

**Comment by jasmainak** [comment]
@zuxfoucault how did you set up your development environment?

Did you use install `mne-bids` using the command "python setup.py develop" ?

**Comment by zuxfoucault** [comment]
I actually didn't install it. I am working directly based on `mne-bids` master branch. sym-link mne-bids/mne-bids/ to site-packages

**Comment by agramfort** [comment]
you should not symlink but use

pip install -e .

from your dev folders than contain a setup.py

it's much safer/simpler

**Comment by jasmainak** [comment]
closing this as the contributing guide has now been updated.

**Comment by zuxfoucault** [comment]
I followed the updated contributing guide and it worked without issues on my environment then
