### ISSUE TITLE
make_dataset_description shouldn't be written in write_raw_bids if it already exists

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#330]
#### Describe the bug
In `write.py`, in `write_raw_bids`, `make_dataset_description(output_path, name=" ", verbose=verbose)` is being called without checking that a dataset description might already exist. 

https://github.com/mne-tools/mne-bids/blob/6c6de051314ea955bb3104294a1ea1a454e2d2e8/mne_bids/write.py#L1218

If you produce the dataset description first, it just essentially always gets overwritten. So the only way this would work in practice with make_dataset_description is to ask users to call that afterwards. 
#### Expected results
It should not do that, but check that the file exists, since mne-bids provides a make_dataset_description function (imo). If you all agree, then I can make a quick PR, adding an existence check.

**Comment by jasmainak** [comment]
sounds fair, I would add an `overwrite` argument like in the other functions.
