### ISSUE TITLE
wrap up JOSS publication

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#334]
Hi everyone,

mne-bids is now accepted for publication and ready to be released :-)

We have a final list of to dos including a release, see here: https://github.com/openjournals/joss-reviews/issues/1896#issuecomment-564831574

Can we do a release in the next days @jasmainak @agramfort ?

**Comment by agramfort** [comment]
sure no objection.

>

**Comment by jasmainak** [comment]
Okay for me. Do you do a minor release or major?

**Comment by sappelhoff** [comment]
> Do you do a minor release or major?

I think any release would be fine, as long as it gets stored by zenodo. I have already enabled zenodo for this project ... so the next release (minor or major) will be stored.

I would be fine with either type of release.

**Comment by jasmainak** [comment]
fair enough!

**Comment by arokem** [comment]
Just to confirm: whatever suits you folks, as long as there is a Zenodo DOI associated with the version as accepted.

**Comment by sappelhoff** [comment]
I that case, I suggest to do a GitHub-only release (`0.3.1`), to trigger Zenodo. I think we're not ready for a big release (`0.4`) yet. And the GitHub-only `0.3.1` release will store our repo with no repercussions.

@jasmainak @agramfort - I'll do it once 

1. CIs are fixed
1. I have the OK from both of you.

**Comment by jasmainak** [comment]
yep I prefer a quick minor release. And okay for me to go ahead and make it!

**Comment by agramfort** [comment]
+1

>

**Comment by sappelhoff** [comment]
done :-) the DOI should work within the next minutes.

[![DOI](https://zenodo.org/badge/89170358.svg)](https://zenodo.org/badge/latestdoi/89170358)
