### ISSUE TITLE
No 0.3.1 packages on PyPI

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#339]
I realized version 0.3.1 hasn't been published to PyPI yet. Also, the version in the `maint/0.3` branch seems to be [stuck](https://github.com/mne-tools/mne-bids/blob/acd5717a8c3d6c875693e53c8619d77e4f04906e/mne_bids/__init__.py#L3) at 0.3.

**Comment by jasmainak** [comment]
I think we made the 0.3.1 tag just to make zenodo happy. Do you see a need to update it also in PyPi?

**Comment by hoechenberger** [comment]
> Do you see a need to update it also in PyPi?

I was only irritated by the inconsistency between Git tags and PyPI releases and thought you might have forgotten to upload the distributions to PyPI. Since that doesn't appear to be the case – never mind :)
