### ISSUE TITLE
read_raw_bids should read in sidecar json file to set line frequency

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#340]
#### Describe the problem
Currently, `read_raw_bids` does not read in the sidecar json of the BIDS dataset to set the line-frequency inside the mne.Raw object.

#### Describe your solution
Implement a `_handle_info_reading(sidecarjson_fname, raw)` function within `read.py` similar to 
- mne_bids/read.py:75

It could also do various checks on sampling frequency, and such for EEG/iEEG data.

**Comment by jasmainak** [comment]
Fair enough! You'd have to check that it's the same as in the file or that the file does not have this info.
