### ISSUE TITLE
`Status Description` should be added to `channels.tsv` sidecar

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#348]
#### Describe the problem
Although status is filled in w/ basically "good", or "bad", which allows mne-python to parse out bad chs to put in `raw.info['bads']`, in many cases, one will be interested in knowing why a channel was bad. 

Specifically in my case, if a channel is in white matter. 

#### Describe your solution
Append `status_description` with default "n/a" values into the channels.tsv sidecar file

#### Additional context
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#electrode-description-_electrodestsv

**Comment by jasmainak** [comment]
why should this be part of mne-bids if it's never actually used to fill any values?

**Comment by adam2392** [comment]
@jasmainak So I thought about this a little bit more and I thought this could be useful for two reasons:

1. Additional Layer of Distinction: you need more distinction in your channels besides just `bad` and `good`. For example, I have use of labeling SEEG channels `white-matter`, which is useful to know because in some analyses, these can possibly be included. Majority of the time you would by default denote these with `status = bad`. 
2. More transparency in how we label "Bad": you want to expose the reasoning behind what the reasoning for labeling a channel is `bad`. For example, if you label channels `bad` through MNE-Python's plotting GUI interface, then isn't it best-practice in BIDS to say why? (e.g. labeled `status-description = visual-mne-python`). 

I was then wondering could this be a utility public function for MNE-BIDS? Something like, 

`set_channels_status`, with inputs: `status`, `status-description` and `ch_names`

?

**Comment by jasmainak** [comment]
Do you think we could come up with something that's more generally useful than just for the channel status? Like a function to update a column/row of a tsv file for one subject/task? Because the usecases can quickly start to explode for different people. I don't exactly know what it could look like. Just thinking out loud ...

**Comment by jasmainak** [comment]
maybe @EtienneCmb has an opinion? :)

**Comment by EtienneCmb** [comment]
I'm not fully aware of sEEG Bids structure, however, usually what I've seen is an Excel file or csv that contains the anatomical description of each sEEG contact. And informations about white / gray matter are contained inside this table

**Comment by sappelhoff** [comment]
Maybe it'd be nice to support an annotation of WHY a channel is bad in MNE itself. 

Similar to how annotations of why a time segment is bad are supported: https://mne.tools/0.15/auto_tutorials/plot_artifacts_correction_rejection.html

that way we could easily write a `status_description` in addition to the `status` that we write. 

https://github.com/mne-tools/mne-bids/blob/master/mne_bids/write.py#L115-L117

**Comment by adam2392** [comment]
> Maybe it'd be nice to support an annotation of WHY a channel is bad in MNE itself.
> 
> Similar to how annotations of why a time segment is bad are supported: https://mne.tools/0.15/auto_tutorials/plot_artifacts_correction_rejection.html
> 
> that way we could easily write a `status_description` in MNE-BIDS in addition to the `status` that we write.
> 
> https://github.com/mne-tools/mne-bids/blob/master/mne_bids/write.py#L115-L117

I like this idea. However, in mne-python, how would this look? A new 'set_bad_chs' function that allows for  a dictionary with `ch: description`? 

Would we default to say... 'n/a' when ppl just append to bads via code like this: `raw.info['bads'].extend(ch_list)`?

**Comment by adam2392** [comment]
@agramfort any thoughts on how this would be feasible / if this is a desired addition to mne? 

Since many EEG analyses reject channels all the time as "bad", it does seem to make sense to have some way of describing why it is "bad".

**Comment by agramfort** [comment]
adding this in MNE is not impossible but it's quite hard as it means
changing the measurement info data
structure. So far bads is just a list. Now I see that bads could be a list
of tuple with ch_name and reason
or something like that. But if you do this then fif format needs to be
adjusted. Doing this in BIDS world
alone seem easier

**Comment by a-hurst** [comment]
At the least, adding a `status_description` column to the channels.tsv filled with "n/a" values would make it easier to manually add descriptions of bad channels later. Would be a quick improvement in the meantime while a more in-depth solution is developed.

**Comment by adam2392** [comment]
> At the least, adding a `status_description` column to the channels.tsv filled with "n/a" values would make it easier to manually add descriptions of bad channels later. Would be a quick improvement in the meantime while a more in-depth solution is developed.

@jasmainak what do you think? This seems valid to me, considering it helps "focus" dataset managers to make sure they have a "reason" for the status. Then it could potentially be overwritten with the discussion going on in https://github.com/mne-tools/mne-bids/issues/458.

**Comment by jasmainak** [comment]
okay for filling the column with "n/a" so it's easy to grep for it!
