### ISSUE TITLE
Scans.tsv being written shows ".edf" extension even if I wrote my data into BV format

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#351]
#### Describe the bug
Take EDF file and perform `write_raw_bids` and then the scans.tsv file will show ".edf" extension of the same file, even though it was converted into BV format.

#### Expected results
Should show the `bids_basename.vhdr` under 'filename' in scans.tsv.

**Comment by jasmainak** [comment]
Yeah that seems like a bug. PR is welcome :)
