### ISSUE TITLE
Participants JSON shouldn't overwrite existing components if added

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#356]
#### Describe the bug
If you add `participants.json` fields that are specific to your data, and theen add a new dataset, it should not overwrite the participants.json file, but not overwrite the participants.tsv file.

#### Steps to reproduce
1. Modify participants.json and participants.tsv to add elements outside MNE-BIDs
2. write a new dataset, and participants.json will not retain the old fields, while participants.tsv does.

#### Expected results
They should both retain fields. 

#### Additional information
In addition, `overwrite=True/False` I don't think is sufficient. If you set overwrite to True, then wouldn't you just overwrite the whole participants files and then have to start from scratch adding these new fields in?

**Comment by jasmainak** [comment]
the use case is not clear to me. If you add a new participant whose age and name doesn't match, then it's appended at the end. Otherwise, an error is thrown if overwrite = False. That would be the expected behavior

**Comment by adam2392** [comment]
So I was thinking something along the lines of this:

```
# check to make sure participant data is overwritten, but keeps the fields
    participants_tsv = op.join(bids_root, 'participants.tsv')
    data['subject_outcome'] = ['n/a'] * len(data['participant_id'])
    data['subject_outcome'][data['participant_id'].index('sub-01')] = 'S'
    _to_tsv(data, participants_tsv)
    participants_json_fpath = op.join(bids_root, 'participants.json')
    _update_sidecar(participants_json_fpath, 'subject_outcome',
                    {'Description': 'trial-outcome',
                     'Levels': {'S': 'success', 'F': 'failure'}})
    write_raw_bids(raw, bids_basename, overwrite=True)
    data = _from_tsv(participants_tsv)
    assert data['age'][data['participant_id'].index('sub-01')] == '9'
    assert data['subject_outcome'][data['participant_id'].index('sub-01')] == 'S'
```
When you overwrite, I would presume, it should retain new fields added into the participants.json file, besides age, hand, and sex, which are the only ones supported in MNE-BIDs rn.

**Comment by jasmainak** [comment]
sorry for the late response.

I see, it seems like an exotic use case. However, I'm okay with it if you can do it without adding too much code complexity.
