### ISSUE TITLE
MAINT: releasing mne-bids 0.4

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#359]
Once MNE-Python 0.20 is out ([soon](https://github.com/mne-tools/mne-python/issues/7385)), we plan to release MNE-BIDS 0.4

Please use this issue to point out any remaining work we should definitely get done before a release.

Also, this is a good chance to update milestones @mne-tools/mne-bids 

For reference, see [discussion](https://gitter.im/mne-tools/mne-bids?at=5e62257d63d3f3203462607d).

**Comment by jasmainak** [comment]
I would say none unless you want to kill a few easy issues :)

**Comment by jasmainak** [comment]
cc also @adam2392 @alexrockhill @hoechenberger

**Comment by adam2392** [comment]
I've handled a lot of the issues that arose in my  work :p. Most of my qualms are niceties at this point.

This looked like a cool and valuable PR to simplify Path making: https://github.com/mne-tools/mne-bids/pull/257

^ Is that going to be tabled for next release?

**Comment by jasmainak** [comment]
not on the top of my priority list at the moment ...

might be better to focus on getting our energies to get folks to convert large datasets and then see how smoothly the processing goes

**Comment by alexrockhill** [comment]
I have two big datasets that I want to try to convert next week. One in EEGLAB format 🤦🏼‍♂️ and another in edf so there might be some issues from those but hopefully not! 😊

**Comment by sappelhoff** [comment]
Mmh it seems like https://github.com/mne-tools/mne-bids/issues/301 could deserve some attention before a release.

But then again, it seems like not many users are using the CLI. At least judging from the fact that we do not get issue reports for it.

I migrated all remaining PRs/issues to a new  `0.5` milestone and scheduled it for September.

**Comment by sappelhoff** [comment]
Unless somebody disagrees, I will make the release tomorrow (Friday).

**Comment by hoechenberger** [comment]
@jasmainak 
> might be better to focus on getting our energies to get folks to convert large datasets and then see how smoothly the processing goes

That's what I've started doing :D But will take a while for me to compile feedback.

@sappelhoff +1 from my side on moving forward with a release

**Comment by jasmainak** [comment]
go for it!

**Comment by sappelhoff** [comment]
0.4 is released! :rocket: :-)

I still need to manage the projects: https://github.com/mne-tools/mne-bids/projects (close 0.4, prepare 0.5 and migrate open project cards)

but I'll do that tomorrow.

Can somebody of you tweet about this? I just recently tweeted about `pybv` and don't want to be too spammy.

@mne-tools/mne-bids-contributors
