### ISSUE TITLE
PowerLineFrequency is hard-coded to euro standards

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-bids#36]
I just noticed that powerline frequency is hard-coded to the euro value (https://github.com/mne-tools/mne-bids/blob/master/mne_bids/meg_bids.py#L193). How should we make this optional for the user to control?

One option would be to expose a `make_channels_json` function that'd give more control over the outputs in general (it could take an `info` object and give a bunch of kwargs to control the specifics). Thoughts?

**Comment by teonbrooks** [comment]
I think `42` is just a placeholder? `50Hz` is for euro and `60Hz`. I do think there should be an input arg somewhere for this because I don't know if this is explicit info in the data but not sure

**Comment by jasmainak** [comment]
closing since this was addressed in https://github.com/mne-tools/mne-bids/pull/37
