### ISSUE TITLE
read_raw_bids of electrodes.tsv doesn't work properly for iEEG coordinateframe and coordinateunit (scaling)

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#389]
#### Describe the bug
For both MEG and iEEG in https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson, the coordinates are allowed to be in pixels, cm, m, mm. When in cm, mm, or m, there should be a relevant conversion into meters, since that is the default acceptance of mne-python digMontage. The coordinates should scale correctly based on coordinate unit before passing to `make_dig_montage`.

In addition, the reading of the coordinate frames are not really robust wrt possible options for iEEG. E.g. if I have a T1 MRI in "LIA" coordinateframe, then ideally we could just pass in `coordinateframe = lia`. I did a bit of reading and it seems that mne-python doesn't have this capability yet, so I think we should just default to `coordinateframe = mri` in these cases for iEEG.

#### Steps to reproduce
Use this dataset https://www.dropbox.com/sh/lkz1q6do80w53sv/AAAoPAKQJi3xCgJ2y5GGeREsa?dl=0

and modify coordinate units to either `mm`, or `m` or `cm`. No changes occur on the digpoints.

```
    bids_root = "/Users/adam2392/Dropbox/test-mnebids-dataset/"

    subject = 'testla'
    session = 'seizure'
    acquisition = 'seeg'
    run = '01'
    task = 'monitor'

    bids_fname = make_bids_basename(subject, session, task, acquisition,  run,
                                    suffix='ieeg.vhdr')
    subjdir = os.path.join(bids_root, f'sub-{subject}', f'ses-{session}', 'ieeg')

    # raw = mne.io.read_raw_brainvision(os.path.join(subjdir, bids_fname))
    raw = read_raw_bids(bids_fname, bids_root)
    print(raw.info)
    print(raw.info['dig'])
    digpoint = raw.info['dig'][0]
    print(digpoint)
```

#### Additional information
See #381 for some discussion around electrodes.tsv development happening.

**Comment by agramfort** [comment]
maybe @sappelhoff or @jasmainak have some opinions here? they follow more closely than me the discussions on the standard

**Comment by jasmainak** [comment]
I was going to say PR is welcome but looks like you're thinking ahead of me :)
