### ISSUE TITLE
Allowing for raw files to be automatically relocated

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#39]
I assume the eventual scope of this library is to be able to allow for any raw files that are read to be relocated to an appropriate folder as per Section 5 (Appendix 1) of the BIDS MEG specification extension?
The raw_to_bids function as it stands doesn't produce the folder required to place the raw data in (but can be easily modified to do so).
As a follow on to this, I know it is a different library, but if the BaseRaw class in mne stored the paths to the various files that were used to generate it, then this information could be pulled out automatically by the raw_to_bids function instead of having to specify the files again.
Few other little notes:
- Some files names (eg. the sidecar file <name>_meg.json) aren't able to have the run etc info as part of their name.
- "SoftwareFilters" should default to "none", not "n/a" in the _channel_json function.
- 'MEGCoordinateSystem' should be the coordinate system, not manufacturer I believe (cf. 3.3.1 of BID MEG extension)
(sorry for having a few misc things tacked on...)

**Comment by jasmainak** [comment]
> The raw_to_bids function as it stands doesn't produce the folder required to place the raw data in (but can be easily modified to do so).

I am not sure I follow. Can you elaborate? `raw_to_bids` does produce the folder to put your BIDS compatible data.

Regarding the notes, you are correct. Do you have time to make a PR?

**Comment by monkeyman192** [comment]
When I ran the script it would produce the file structure like "sub-control01/ses-01/meg/" within which the .tsv and some .json files reside, however there should be a subsequent subfolder within this folder with the same title as the sidecar .json. so in the example given in the specification you would have a further subfolder within the above directory "~/sub-control01_ses-001_task-rest_run-01_meg/" where the raw data goes.

And yep, I can do a PR.

**Comment by jasmainak** [comment]
> however there should be a subsequent subfolder within this folder with the same title as the sidecar .json. so in the example given in the specification you would have a further subfolder within the above directory "~/sub-control01_ses-001_task-rest_run-01_meg/" where the raw data goes.

okay I did not understand this before, but I guess it is also something KIT specific? Feel free to make a PR

**Comment by monkeyman192** [comment]
I think there was some confusion on my end. The bids specification is a little bit un-unified on how the raw files should be located. The general example doesn't always match the examples for specific MEG systems. If you look at appendix VI (section 16) of the bids specification you can see that some systems are recommended to have a sub folder for the raw data, while others (eg Elekta) store the raw data in the main meg folder.
I will try consolidate the info in the specification into a PR to fix it.
I will probably include the raw file path in that PR too since the two will be linked.

**Comment by jasmainak** [comment]
> If you look at appendix VI (section 16) of the bids specification you can see that some systems are recommended to have a sub folder for the raw data, while others (eg Elekta) store the raw data in the main meg folder.

The reason for this is that for some MEG devices, the info for a single recording is spread out between different files. However, in the case of Elekta it is contained in a single *.fif file

**Comment by jasmainak** [comment]
That is correct. Although one of the visions/goals of mne-bids was to nudge users towards the `fif`file format. The MEG-BIDS discussions didn't lead to an accepted file format. However, the more file formats you have, the more you move away from standards :-) cc @teonbrooks

**Comment by monkeyman192** [comment]
Yep, I think this got included in a PR at some point :)
