### ISSUE TITLE
Function signatures in API doc sometimes too long for column

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#395]
I think a screenshot of the current API docs explains the issue best:

<img width="768" alt="Screenshot 2020-04-27 at 09 56 10" src="https://user-images.githubusercontent.com/2046265/80348637-60cc4000-886e-11ea-9f1c-ba977ee80f26.png">

This is in a full-screen browser window (Safari).

**Comment by sappelhoff** [comment]
Mhh, this does not happen on firefox :man_shrugging:

**Comment by hoechenberger** [comment]
Also cannot reproduce with Chrome. Will maybe look into this over the weekend when I'm bored.

**Comment by sappelhoff** [comment]
I think you solved this in #588 (thanks!) - if not, please re-open.
