### ISSUE TITLE
OpenNeuro Dataset ds000246 cannot be read

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#396]
#### Describe the bug

The OpenNeuro dataset [ds000246](https://github.com/OpenNeuroDatasets/ds000246) cannot be read because the `sex` key in `participants.csv` is not accepted by `mne-bids`. However, the `bids-validator` does _not_ complain, and the BIDS standard [seems to be more permissive](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) than `mne-bids` in this regard.

#### Steps to reproduce
Retrieve the dataset:
```
$ aws s3 sync --no-sign-request s3://openneuro.org/ds000246 ds000246
```

From the dataset directory, run in a Python REPL:
```python
import mne_bids
bids_basename = mne_bids.make_bids_basename(subject='0001', task='AEF', run='01')
fname_bids = bids_basename + '_meg.ds'
mne_bids.read_raw_bids(fname_bids, bids_root='.')
```

#### Expected results
Raw data should be loaded.

#### Actual results
An exception is raised:
```python
KeyError                                  Traceback (most recent call last)
<ipython-input-4-da065ba5a638> in <module>
----> 1 mne_bids.read_raw_bids(fname_bids, bids_root='.')

~/Development/mne-bids/mne_bids/read.py in read_raw_bids(bids_fname, bids_root, extra_params, verbose)
    439     participants_tsv_fpath = op.join(bids_root, 'participants.tsv')
    440     subject = "sub-" + params['sub']
--> 441     raw = _handle_participants_reading(participants_tsv_fpath, raw,
    442                                        subject, verbose=verbose)
    443

~/Development/mne-bids/mne_bids/read.py in _handle_participants_reading(participants_fname, raw, subject, verbose)
     87     for infokey, infovalue in participants_tsv.items():
     88         if infokey == 'sex':
---> 89             value = _convert_sex_options(infovalue[row_ind],
     90                                          fro='bids', to='mne')
     91         elif infokey == 'hand':

~/Development/mne-bids/mne_bids/config.py in _convert_sex_options(key, fro, to)
     77         raise RuntimeError("fro value {} and to value {} are not "
     78                            "accepted. Use 'mne', or 'bids'.".format(fro, to))
---> 79     return sex_options[key]

KeyError: 'Male'
```

#### Additional information
This behavior was introduced in #392.

My understanding is that the BIDS specification does not clarify which `sex` values are allowed.

The `bids-validator` also does not complain about the `sex` (but about some other, unrelated things in that dataset):
```
$ bids-validator .
bids-validator@1.4.4

	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./annex-uuid
			Evidence: annex-uuid

	Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

	2: [ERR] Entries in the "acq_time" column of _scans.tsv should be expressed in the following format YYYY-MM-DDTHH:mm:ss (year, month, day, hour (24h), minute, second; this is equivalent to the RFC3339 “date-time” format.  (code: 84 - ACQTIME_FMT)
		./sub-0001/sub-0001_scans.tsv
			@ line: 2
			Evidence: 18000101T094300
		./sub-0001/sub-0001_scans.tsv
			@ line: 3
			Evidence: 18000101T095100
		./sub-emptyroom/sub-emptyroom_scans.tsv
			@ line: 2
			Evidence: 18000101T080200

	Please visit https://neurostars.org/search?q=ACQTIME_FMT for existing conversations about this issue.

	1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
		./participants.tsv
			Evidence: Columns: dominant_hand not defined, please define in: /participants.json

	Please visit https://neurostars.org/search?q=CUSTOM_COLUMN_WITHOUT_DESCRIPTION for existing conversations about this issue.


        Summary:                Available Tasks:        Available Modalities:
        54 Files, 2.29GB        AEF                     T1w
        1 - Subject             noise                   photo
        1 - Session                                     coordsystem
                                                        headshape
                                                        channels
                                                        meg


	If you have any questions, please post on https://neurostars.org/tags/bids.
```
Ideally the dataset should probably also have a `participants.json` file specifying valid values for all keys, but reading the dataset should still work without it.

**Comment by jasmainak** [comment]
agreed, this issue should be raised in `mne-bids` ? cc @adam2392

**Comment by adam2392** [comment]
Ah yeah, okay that is definitely a bug then. 

I'm guessing what should happen is the following:

1. read in accompanying .json file and check if there is a "Levels" dictionary, and assign accordingly.
2. If there is not, then try to do a hard map, which is what is there currently
3. If that fails, then just fire a warning, but still read in the `raw` file.

@jasmainak  does that look right?

**Comment by agramfort** [comment]
@adam2392 @jasmainak can you agree on a fix asap as @hoechenberger is a bit stuck here. thanks

**Comment by hoechenberger** [comment]
@adam2392 
> 1. read in accompanying .json file and check if there is a "Levels" dictionary, and assign accordingly.
> 2. If there is not, then try to do a hard map, which is what is there currently

In either case, we'd have to map this to MNE's `0`, `1`, and `2` values. So there won't be a way around the "hard map" as the last step anyway, right?

> 3. If that fails, then just fire a warning, but still read in the `raw` file.

I would suggest: raise a warning, and set `subject_info['sex']` to unknown (`0`). Then again, not setting it at all might be better… I'm undecided.

**Comment by adam2392** [comment]
@hoechenberger okay taking another look, it seems the JSON file might not be sufficient. It has no restrictions and so trying to use that might be a lost cause.

Rather, we can just go w/ 2. and then -> 3. w/ a warning and setting `subject_info['x']` to unknown.

**Comment by jasmainak** [comment]
In my opinion, this is a case for the standard and validator to be fixed. The standard is too permissive in a case where it could easily have been more standardized. It's not something that should be fixed in software.

**Comment by agramfort** [comment]
I agree

**Comment by jasmainak** [comment]
cc @sappelhoff for thoughts. We should raise an issue in https://github.com/bids-standard/bids-specification/ if you agree

**Comment by adam2392** [comment]
> In my opinion, this is a case for the standard and validator to be fixed. The standard is too permissive in a case where it could easily have been more standardized. It's not something that should be fixed in software.

Agreed, but perhaps then at the minimum we should change these codes:

`_convert_sex_options` and the other to this return statement: `sex_options.get(key, None)` instead of just `sex_options[key]`, which raises the error @hoechenberger said. This way, we can still read in data, but nothing gets broken down?

**Comment by jasmainak** [comment]
yep I would make these fixes + start a discussion on BIDS standard github

**Comment by adam2392** [comment]
Cool! I can make these fixes later.

@sappelhoff is gonna start that discussion on BIDS?

**Comment by sappelhoff** [comment]
> In my opinion, this is a case for the standard and validator to be fixed. The standard is too permissive in a case where it could easily have been more standardized. It's not something that should be fixed in software.

I agree that we should do a better job with the spec or at least the validator, see: https://github.com/bids-standard/bids-specification/issues/458

Feel free to chime in :-)
