### ISSUE TITLE
A _write_dig_bids (read) function to write (read) electrodes and coordinate system sidecars

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#398]
#### Describe the problem
Writing and reading electrode coordinates (positions and coordinate frames) for iEEG data is currently not very robust with what the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html) allows. Also holds true for EEG and MEG data.

The main issue arises in the fact that there are A LOT of different coordinate systems for each recording modality. Hence many nuanced cases arise when currently writing and reading. A possible solution should be able to do the following:

```
bids_root = _write_dig_bids(raw, coord_frame_name) # or
bids_root = _write_dig_bids(ch_coords, ch_coord_frame)
```
and

```
raw = _read_dig_bids(raw) # or
montage = _read_dig_bids(bids_fname)
```

which handles missing values, error checks and data structures. 

#### Describe your solution
Imo I think the hardest part comes from the handling of coordinate systems. Upon reading the specifications though, we can conform by doing the following for writing/reading. Note writing is more limited since we're converting from coordinate systems in mne-python -> BIDS (mne-python is somewhat of a subset of what's allowed in BIDS):

**Writing**
- From data in the mne-python `Raw` data structure, map these correctly to the possible coordinate frames. 
- Each coordinate frame should have a coordinate description as well
- In addition the `coordsystem.json` and `electrodes.tsv` file should have the `space` BIDS entity written to be explicit.

**Reading**
- From data in the `coordsystem.json` and `electrodes.tsv`, we should try to map these if possible to mne-python definitions with the intention of improving these if mne-python expands its definitions down the road. If no mapping exists, probably warn the user and then read in the `Raw` data structure.

#### An example w/ IEEG

**Writing**

If `raw.info['dig']` has coordinates in `fs_tal` and coordinates in meters. `_write_dig_bids` should output the correct `space` BIDs entity and also the correct CoordinateSystemDescription. Note we can just copy descriptions from [specification](https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html).

Coordinate system json sidecar filename: `sub-01_ses-test_acq-seeg_space-fstal_coordsystem.json`
Coordinate system json sidecar contents:
```
{
    "IntendedFor": "T1.nii",
    "iEEGCoordinateSystem": "Other",
    "iEEGCoordinateUnits": "m",
    "iEEGCoordinateSystemDescription": "Freesurfer template in Talairach coordinates.",
}
```

**Reading**
Say we are reading an electrodes and coordsystem file written outside the scope of mne-bids. We might get something like this (acceptable by BIDS, but not writeable by `write_raw_bids`): 

Coordinate system json sidecar filename: `sub-01_ses-test_acq-seeg_space-lia_coordsystem.json`
Coordinate system json sidecar contents:
```
{
    "IntendedFor": "T1.nii",
    "iEEGCoordinateSystem": "Other",
    "iEEGCoordinateUnits": "mm",
    "iEEGCoordinateSystemDescription":  "first dimension (X) points towards the left hand side of the head, the second dimension (Y) points towards the bottom of the head, and the third dimension (Z) points towards the Anterior of the head.",
}
```
Here, `_read_dig_bids` should realize that the space is `LIA`, and probably in some MRI space(?). 

#### Additional context
See discussion: https://github.com/mne-tools/mne-bids/pull/390

**Comment by adam2392** [comment]
I think if this happens, then `write_raw_bids` and `read_raw_bids` can be refactored to use these two functions, and once it's been tested properly, as a user, it could perhaps become public-facing?

Regardless, I think having a nice clean way of merging the BIDS specification of writing electrodes/coordinate system w/ mne-bids would be nice-to-have.

**Comment by agramfort** [comment]
I would try:

_write_dig_bids(fname, info, coord_frame)

basically give it a try with private functions using info you make with make_dig_montage 

now to be able to write in any coord_frame you may need to provide some transforms

**Comment by jasmainak** [comment]
I think we might have to accept that we cannot read all the coordinate systems that BIDS allows. One could start with a small subset and then expand as the need arises

**Comment by agramfort** [comment]
+1

MRI vox and MRI are for me priorities

>

**Comment by sappelhoff** [comment]
> I think we might have to accept that we cannot read all the coordinate systems that BIDS allows. One could start with a small subset and then expand as the need arises

+1

for EEG it should for the beginning be sufficient to read and write `captrak`... which provides nice interoperability with MNE's `head`.

**Comment by hoechenberger** [comment]
Sounds excellent, y'all :)

**Comment by adam2392** [comment]
> +1 MRI vox and MRI are for me priorities
> […](#)

Do we have documentation regarding all the coordinate system definitions in MNE-Python? We can try to match as many as possible. Hopefully, the BIDS specifications are surjective to MNE-python definitions.

**Comment by agramfort** [comment]
see
https://mne.tools/dev/auto_tutorials/source-modeling/plot_source_alignment.html#understanding-coordinate-frames

>
