### ISSUE TITLE
Event onset shifts during mne-bids roundtrip

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#403]
#### Describe the bug
I'm converting a raw file to BIDS via `write_raw_bids()` and reading it again via `read_raw_bids()`. Extraction of the events via `mne.events_from_annotations()` reveals a **time shift of events in the read BIDS data** compared to the events in the **original (non-BIDS) raw data**; specifically, event onsets are shifted by `raw.first_samp` samples.

#### Steps to reproduce
I'm working with `SB01_Localizer_raw.fif` from this dataset: https://osf.io/k9bth/

```python
from tempfile import TemporaryDirectory
import mne
from mne_bids import make_bids_basename, read_raw_bids, write_raw_bids

mne.set_log_level(verbose=False)


subject = 'SB01'
raw_fname = 'SB01_Localizer_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, allow_maxshield=True)
events = mne.find_events(raw, min_duration=2/raw.info['sfreq'])
bids_basename = make_bids_basename(subject=subject)
bids_fname = bids_basename + '_meg.fif'

with TemporaryDirectory() as bids_root:
    write_raw_bids(raw=raw,
                   bids_basename=bids_basename,
                   bids_root=bids_root,
                   events_data=events,
                   overwrite=True,
                   verbose=False)

    raw_read = read_raw_bids(bids_fname=bids_fname,
                             bids_root=bids_root,
                             extra_params=dict(allow_maxshield=True),
                             verbose=False)
    events_read, _ = mne.events_from_annotations(raw_read)

print(f'First event sample before writing: {events[0, 0]}')
print(f'First event sample after reading:  {events_read[0, 0]}')
print(f'… after first_samp subtraction:    {events_read[0, 0] - raw_read.first_samp}')
```

#### Expected results
```
...
First event sample before writing: 24863
First event sample after reading:  24863
… after first_samp subtraction:    [0 <= x <= 24863]
```
#### Actual results
```
...
First event sample before writing: 24863
First event sample after reading:  47363
… after first_samp subtraction:    24863
```

#### Additional information
I tried to reproduce this with an MNE sample dataset and failed. I also thought maybe `raw.info['meas_date']` could be the cause (bc the data file used in the MWE doesn't have a measurement date set). No luck.

Am I missing somthing here?

Environment:
`mne-bids:master`
`mne-python:master`

**Comment by hoechenberger** [comment]
Seems to be an upstream bug in MNE. Will leave this issue open until resolved.

**Comment by sappelhoff** [comment]
is there an issue or PR upstream to reference here?

**Comment by hoechenberger** [comment]
@sappelhoff Yes, so this problem seems to be related to old (or incorrectly?) anonymized data, and @agramfort started working on a fix, which is only partially completed at the time of writing:
https://github.com/mne-tools/mne-python/pull/7711

**Comment by agramfort** [comment]
this has been fixed by https://github.com/mne-tools/mne-python/pull/8209
