### ISSUE TITLE
Excluding empty-room measurements from dataset entity retrieval

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#407]
#### Describe the problem
I'm working with an MEG BIDS dataset that includes empty-room recordings. Because it is required that these data have the recording date stored as their `session` attribute, a call to `mne_bids.utils.get_entity_vals(..., entity_key='ses')` returns all sessions including those from the empty-room recordings. So in my case – where experiments only lasted one session, hence the experimental data doesn't have any `session` specified – I get the following:

```
['20020101', '20020102', '20020103', '20020104', '20020105', '20020106', '20020107', '20020108', '20020109', '20020110', '20020111']
```
I would have wanted to receive an empty list instead. Now in my specific case, I can just ignore those return values; but assume I had one or more experimental sessions, it would be impossible to easily figure out which values are experimental session names, and which are empty-room recordings.

Similarly, `get_entity_vals(..., entity_key='sub')` also returns the `emptyroom` subject; however this one is very easy to filter out – which is not the case with the empty-room sessions, as demonstrated above. Another example that can potentially lead to confusion is `get_entity_vals(..., entity_key='task')`, which would return the `noise` task for empty-room recordings – now imagine you had an _experimental task_ "noise" as well, …

#### Describe your solution
`get_entity_vals()` is a very low-level function and should probably not be part of the public API. Instead, we should add small convenience functions that allow retrieval of the requested entities, optionally after applying a filter:

```python
def get_subjects(*, bids_root, include_emptyroom=False):
    vals = _get_entity_vals(...)
    return filter_func(vals, include_emptyroom=include_emptyroom)


def get_sessions(*, bids_root, include_experiments=True, include_emptyroom=False):
    vals = _get_entity_vals(...)
    return filter_func(vals, include_experiments=include_experiments,
                       include_emptyroom=include_emptyroom)


def get_tasks(*, bids_root, include_emptyroom=False):
    vals = _get_entity_vals(...)
    return filter_func(vals, include_emptyroom=include_emptyroom)
```

**Comment by jasmainak** [comment]
I agree that the function is not great and needs care.

In your new proposal how do you take care of the fact that there are different number of runs or sessions per subjects? This is actually pretty common.

**Comment by hoechenberger** [comment]
@jasmainak 
> In your new proposal how do you take care of the fact that there are different number of runs or sessions per subjects? This is actually pretty common.

So these proposed functions would return the union of the requested entity in the dataset, across all "hierarchies"; i.e., for `ses`, we would return the union of all sessions that we can find across participants, regardless of whether _each_ participant has _all_ of them. Similarly for _run_.

But of course, one could add more fine-grained filters, or add a function that returns a table of the _intersection_ of all entity values across all measurements.

Or did I misunderstand your question?

**Comment by jasmainak** [comment]
I think we need more fine-grained filters. E.g., if I want to iterate over runs, how would this work in my script? There is an open PR for this on [`mne-study-template`](https://github.com/mne-tools/mne-study-template/pull/41) which shows the problem.

Are you aware of what [`BIDSHandler`](https://github.com/Macquarie-MEG-Research/BIDSHandler) and `pybids` are doing? Those tools are driven by user need, so it might be a good idea to look at what they are doing for querying.

**Comment by hoechenberger** [comment]
> I think we need more fine-grained filters. E.g., if I want to iterate over runs, how would this work in my script?

I'm not sure I exactly understand what you're referring to in this PR, but do you mean that it could be nice to be able to query the dataset like:

> Give me all sessions of participant X

> Give me all tasks of participant X

> Give me all sessions of participant X where task is 'foo'

Haven't looked into `BIDSHandler` and `pybids` so far, will do.

**Comment by jasmainak** [comment]
> I'm not sure I exactly understand what you're referring to in this PR

it introduces a test with a dataset with different runs for different participants. Isn't `get_entity_vals` used in `mne_study_template`? The CircleCI is failing with the message:

```py
OSError: The file /home/circleci/mne_data/ds001971/sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-02_eeg.set does not exist.
```

because subject 2 has two runs but subject 1 has only one.

**Comment by jasmainak** [comment]
> but do you mean that it could be nice to be able to query the dataset like

yes, exactly!

**Comment by hoechenberger** [comment]
> > but do you mean that it could be nice to be able to query the dataset like
> 
> yes, exactly!

Ok.

A database-like query operation like this would be piece of cake e.g. with Pandas. We could simply aggregate all data into a `DataFrame` and then filter.

Which again raises a big question for me:
Why do we have to infer so many things from _filenames_? We already use JSON files, couldn't we have, like, an `index.json` that describes the content of the dataset, so one wouldn't have to `glob` over it? It would make it trivially easy to query dataset contents. I imagine something like an a truly RESTful web service, where you get _complete_ information about all endpoints (here: participants, tasks, sessions, runs, data filenames etc.), so you could navigate the service without any prior knowledge. It would allow us to do stuff like

```
give me the path of the raw data files of session A 
    from participants 1–15
    if the task was button-press and
    participant-handedness was left
```

**Comment by jasmainak** [comment]
> A database-like query operation like this would be piece of cake e.g. with Pandas.

right, so maybe we just need to make stuff available in `mne-bids` that in pandas friendly format and then allow pandas to do the rest. This could be demoed with an example.

> We already use JSON files, couldn't we have, like, an index.json that describes the content of the dataset, so one wouldn't have to glob over it? 

hmm... are you proposing this as a modification to BIDS? Or do you mean that `mne-bids` should write out something like this. 

Note that there have been long discussions in the BIDS forums why things are the way they are. One of the core principles driving BIDS is that the data should be easy to curate -> that's why there are tsv files and jsons that are easily editable.

**Comment by hoechenberger** [comment]
> hmm... are you proposing this as a modification to BIDS? Or do you mean that `mne-bids` should write out something like this.

I'm just saying there should be something like this ;) Considering how complex it seems to be to amend the standard, it's probably much more feasible to implement this functionality in `mne-bids`. Nothing would necessarily need to be written out, either – we could create a JSON or `DataFrame` object on-the-fly and return it / work with it.

> Note that there have been long discussions in the BIDS forums why things are the way they are. One of the core principles driving BIDS is that the data should be easy to curate -> that's why there are tsv files and jsons that are easily editable.

Yes I understand that. In my opinion, the lack of a centralized index file makes the datasets much harder to explore. If BIDS were a web service, I would hate it 😉 because I would not only have to parse JSON and TSV files, but also the file and directory name structure.

**Comment by hoechenberger** [comment]
Ok trying to be a little more constructive again ;) I think we could easily offer a functionality like this. Simply glob through the directory structure and potentially merge the collected metadata with `participants.tsv`. Thoughts?

**Comment by jasmainak** [comment]
That sounds like a good idea to me!

**Comment by hoechenberger** [comment]
Can `mne-bids` depend on `pyBIDS`? Or is this not desirable? Because they already have functionality we could build upon, like:
https://bids-standard.github.io/pybids/generated/bids.layout.parse_file_entities.html

**Comment by jasmainak** [comment]
BIDSHandler is not actively maintained any more but you could take over if needed, I'm sure @monkeyman192 would be happy :)

PyBIDS has the functionality yes, but remember they (used to?) have other dependencies like Grabbids. Most of it is not well-documented with just one example file. Again, these are not arguments against using it. I'm just saying you can perhaps help these packages or maybe decide we don't need all the functionality, so we can just copy the good bits into `mne-bids`. Whatever works.

**Comment by hoechenberger** [comment]
> I'm just saying you can perhaps help these packages or maybe decide we don't need all the functionality, so we can just copy the good bits into `mne-bids`. Whatever works.

I guess what we need for now can be implemented with `pandas`, `pathlib`, and a little regexp-and-string-manipulation-foo.

**Comment by hoechenberger** [comment]
There is already a function in `mne-bids` that does the entity-from-filename extraction:
https://github.com/mne-tools/mne-bids/blob/1ce1717f923843fc5eea970c6aa44e95c018bef0/mne_bids/utils.py#L304-L307
