### ISSUE TITLE
Add support for split files to reader

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#418]
`read._get_bids_fname_from_filesystem()` currently [does not support](https://github.com/mne-tools/mne-bids/blob/102de3eec6f1fb3c3724ed837fda036edd55bc0f/mne_bids/read.py#L393-L400) split files. Now that we have officially agreed upon a naming scheme (see https://github.com/mne-tools/mne-python/pull/7794), we should implement support for splitting.

**Comment by sappelhoff** [comment]
can probably be closed? cc @hoechenberger

**Comment by hoechenberger** [comment]
Yes I believe this is working now!
