### ISSUE TITLE
Make get_matched_empty_room() more robust

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#419]
### Describe the problem
Initially reported at https://github.com/mne-tools/mne-study-template/issues/121

So I'm working on emptyroom processing, and I wanted to test my code with `ds000246` and `ds000248`. Turns out that mne-bids' `get_matched_empty_room()` cannot discover the empty-room recordings because they're stored without the `ses` entity in their path:

https://github.com/OpenNeuroDatasets/ds000246/tree/master/sub-emptyroom/meg
https://github.com/OpenNeuroDatasets/ds000248/tree/master/sub-emptyroom/meg

#### Describe your solution
If the empty-room data doesn't have a `ses` entity, walk through `sub-emptyroom/meg/`, read all data files one by one and extract `info['meas_date']`. Find the file corresponding to the date closest to the experimental measurement.

Edit:
We can use `mne.io.read_info()`.

**Comment by jasmainak** [comment]
I thought that BIDS datasets should always have `ses-<session_date>`. I don't how well your solution will work for non-fif files. Quoting the specification:

> This data is stored inside a subject folder named sub-emptyroom. The session label SHOULD be that of the date of the empty-room recording (e.g. ses-YYYYMMDD).

the SHOULD means it's not optional. This should be a validator issue rather than an `mne-bids` issue.

**Comment by jasmainak** [comment]
good lord, it's a SHOULD and not a MUST :( I don't even know why SHOULD exists. It might as well be called OPTIONAL

**Comment by hoechenberger** [comment]
> I thought that BIDS datasets should always have `ses-<session_date>`.

As you figured: yes, they SHOULD. That's exactly the problem LOL



> I don't how well your solution will work for non-fif files.

What do you mean?

**Comment by hoechenberger** [comment]
> I don't even know why SHOULD exists. It might as well be called OPTIONAL

It's easier to use in a sentence :)

**Comment by jasmainak** [comment]
> What do you mean?

I mean I don't know if the measurement date is stored in the files for all the 5 or 6 MEG manufacturers. Might be worth looking into the MNE readers to check that.

**Comment by sappelhoff** [comment]
> It's easier to use in a sentence :)

I always see SHOULD as a synonym to "PLEASE FUCKING DO IT", whereas OPTIONAL is truly optional to me :smile:

**Comment by hoechenberger** [comment]
> I mean I don't know if the measurement date is stored in the files for all the 5 or 6 MEG manufacturers. Might be worth looking into the MNE readers to check that.

I would say we should check in the following order:

- `scans.tsv`
- filename parsing
- file content parsing

If none of those succeeds, there's nothing we can do, and the user will have to manually provide the emptyroom data.
