### ISSUE TITLE
Can kind be inferred from acq for read_raw_bids in mne-bids?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#422]
@hoechenberger in https://github.com/mne-tools/mne-bids/pull/410 added the `kind` kwarg for `read_raw_bids`, and I like this addition. 

My question is that shouldn't it be possible to infer kind from acq? E.g.

```
params = _parse_bids_filename(bids_basename)
acq = params['acq']
if acq == 'meg':
    kind = 'meg'
elif acq in ['ecog', 'seeg']:
   kind = 'ieeg'
elif acq in ['eeg']:
   kind = 'eeg'
else:
   raise Error("This isn't implemented yet")
```
?

**Comment by jasmainak** [comment]
I think it's already inferred automatically by default.

acq is different, it need not necessarily be the modality

**Comment by hoechenberger** [comment]
> acq is different, it need not necessarily be the modality

That's what @adam2392's example shows :)

> ```python
> elif acq in ['ecog', 'seeg']:
>    kind = 'ieeg'
> ```

**Comment by adam2392** [comment]
> I think it's already inferred automatically by default.
> 
> acq is different, it need not necessarily be the modality

Okay, I guess my understanding of acq was too "specific", but it seems to be more "general" then what I presumed.
