### ISSUE TITLE
[BUG] `read_raw_bids` doesn't find split files

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#426]
#### Describe the bug
when using `read_raw_bids`, it does not gracefully find raw files with split parts.

With matching the pattern, we should include an optional match for the entity `split`.

**Comment by jasmainak** [comment]
cc @hoechenberger @sappelhoff

**Comment by hoechenberger** [comment]
Yes this is a known problem:
https://github.com/mne-tools/mne-bids/blob/d0374455dcd8e953ce728a888b0c3bbcd310c3c2/mne_bids/read.py#L394-L401

But good idea to keep this issue here as a reminder

Is this an urgent problem for you, @teonbrooks?

**Comment by teonbrooks** [comment]
for me, instead of finding multiple files, it finds none. i suspect that it is because the pattern matching assumes the basename is complete. it wouldn't be if it is known if a file has the `split` entity. 
https://github.com/mne-tools/mne-bids/blob/d0374455dcd8e953ce728a888b0c3bbcd310c3c2/mne_bids/read.py#L383
I will bypass this in just use the `mne.io.read_raw_fif` and specify the full path for now

**Comment by teonbrooks** [comment]
just a quick note on this topic:
mne raises a `FileNotFound` err vs mne_bids' `RuntimeError`

**Comment by hoechenberger** [comment]
Thanks for these details! Would you mind sharing a split dataset with me so I have something to work with when debugging this issue? My email address is richard.hoechenberger@gmail.com

**Comment by hoechenberger** [comment]
@sappelhoff “split” should NOT be treated as a BIDS entity or should it?

**Comment by teonbrooks** [comment]
actually, i take it back, I do need it. there isn't a public function for reading `events.tsv` so i can't load events using mne directly. :/

**Comment by teonbrooks** [comment]
> @sappelhoff “split” should NOT be treated as a BIDS entity or should it?

It's been added to the entity table. It has been an entity but poorly specified in the spec. however that was clarified here: https://github.com/bids-standard/bids-specification/pull/460
https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html

**Comment by hoechenberger** [comment]
> actually, i take it back, I do need it. there isn't a public function for reading `events.tsv` so i can't load events using mne directly. :/

If it's urgent, just used this function:
https://github.com/mne-tools/mne-bids/blob/d0374455dcd8e953ce728a888b0c3bbcd310c3c2/mne_bids/read.py#L156

Otherwise I will look into this tomorrow. Could you provide me with some sample files?

**Comment by hoechenberger** [comment]
> It's been added to the entity table. It has been an entity but poorly specified in the spec. however that was clarified here: [bids-standard/bids-specification#460](https://github.com/bids-standard/bids-specification/pull/460)
> https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html

Thanks, I did follow that discussion but never realized it's considered an actual _entity_.

**Comment by sappelhoff** [comment]
yes, `split` is a proper entity now. You can also use it for other files that need to be split for size reasons ... but if you do, please also make a PR to the spec so that we can improve docs coverage there.

**Comment by hoechenberger** [comment]
Actually super annoying we still have to deal with stuff like that in 2020. Reminds me of the days where I hat to split RAR archives so they would fit on a bunch of floppy disks...

**Comment by teonbrooks** [comment]
@hoechenberger thanks for the suggestion.

yeah...the whole FIF split is a bit of a nostalgia bummer. i remember this discussion years ago, and if we wanted to support a new FIF, it would break backwards compatibility.

**Comment by hoechenberger** [comment]
> and if we wanted to support a new FIF, it would break backwards compatibility.

I suppose there could be a `.fif.tar` or something…

**Comment by hoechenberger** [comment]
x-ref #418

**Comment by hoechenberger** [comment]
Is this still an issue, now with `BIDSPath` and all?
