### ISSUE TITLE
An updated function in the API for updating scans.tsv and participants files

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#439]
#### Describe the problem
When you're writing datasets using the `write_raw_bids` functions, sometimes you might manually delete a participant, or some scans. However, this needs to get reflected in the corresponding files. The only way to do that is manually right now.

#### Describe your solution
A `update_scans_tsv()` and `update_participants_files` function perhaps to do that book-keeping for you. I'm not sure what the best looking API would look like, but if people agree, then I can put together something and a short "example?

The U in CRUD:

```Python

def update_scans_sidecar(bids_root, subject=None, session=None):
     # if a specific subject/session, then only do that specific scans.tsv
     # else loop through all files
 
     # load scans tsv file
     # delete row if that file doesn't exist anymore
```

```Python

def update_participants_sidecar(bids_root):
     # get all subject ids inside bids_root
 
     # load participants tsv file
     # delete row if that subject doesn't exist anymore
```

#### Describe possible alternatives
Possibly the function could be combined into one? Allowing one to update sidecar files in general? Idk how that would look though because we definitely can't account for all sidecars.

#### Additional context
Minimally keeping the scans and participants file up to date would be nice.

**Comment by jasmainak** [comment]
it sounds like a reasonable request to me

@hoechenberger @sappelhoff wdyt?

**Comment by hoechenberger** [comment]
This is something that has been on our "want-to-have" list for a while now, so: yes, I want to have this ;) I will need to think about which solution / API would make most sense, though. I believe we should try to sketch this out a little before you start with an implementation, @adam2392.

@agramfort may also have some ideas on this.

**Comment by agramfort** [comment]
what we need is a basic CRUD (in DB sense) for certain files. Participants,
bad channels, coregistration info

>

**Comment by sappelhoff** [comment]
yes, I agree it's important to replace this "manual fiddling around" with code as far as possible :+1:

**Comment by adam2392** [comment]
> This is something that has been on our "want-to-have" list for a while now, so: yes, I want to have this ;) I will need to think about which solution / API would make most sense, though. I believe we should try to sketch this out a little before you start with an implementation, @adam2392.

What do you think of the proposed two functions, I put into the issue just now?

**Comment by agramfort** [comment]
would be the signature of these two functions? Can you share a snippet
to illustrate the use case?

>

**Comment by hoechenberger** [comment]
Hey @adam2392, sorry I haven't gotten back to you yet, I was busy with other stuff. Like @agramfort said, an API proposal could be very helpful to get a discussion started! :)
