### ISSUE TITLE
[API Request]: An update function for bids_basename

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#445]
## Describe the problem
When one is passing around the 'bids_basename' variable in analyses, one will probably be saving say derivatives of that file, but appending, or updating various entities in the bids_basename.

Then I get really long and verbose code like:

```Python
# <all the BIDS entities>
bids_basename = make_bids_basename(subject=subject, task=task, ...)
raw = read_raw_bids(bids_basename, bids_root, kind='ieeg')

result = do_some_analysis_with_raw(raw)

# type out all the inputs again
deriv_basename = make_bids_basename(subject=subject, ...)

# save the output
np.save(deriv_basename, result)
```

#### Describe your solution
Alternatively, if we had an `update_bids_basename` function, which operates the same way as `make_bids_basename`, but allows arbitrary entity modification in place.

Then code would look like:
```Python
# <all the BIDS entities>
bids_basename = make_bids_basename(subject=subject, task=task, ...)
raw = read_raw_bids(bids_basename, bids_root, kind='ieeg')

result = do_some_analysis_with_raw(raw)

# simplified bids_basename
deriv_basename = update_bids_basename(bids_basename, suffix=new_suffix)

# save the output
np.save(deriv_basename, result)
```

#### Additional context
In addition,  having this `update_bids_basename` makes users not require to pass around all the bids entities from functions  to functions and just the 'bids_basename' variable is enough, as one can then alter any part of the bids_basename with an update call.

**Comment by agramfort** [comment]
I don't get it. What do you want to do with the result variable.

**Comment by adam2392** [comment]
> I don't get it. What do you want to do with the result variable.

Just save it to disc in this example, but still following the BIDs formatting. In general it would just be a way to modify the bids_basename in place w/o re-calling `make_bids_basename` with all the entities typed out.

**Comment by jasmainak** [comment]
This sounds a bit similar to something I never finished: https://github.com/mne-tools/mne-bids/pull/257

**Comment by hoechenberger** [comment]
What is the actual use case of this? Do you have a real-world example? I do see what it does, but I haven't come across a case where I would have needed this functionality… Could you maybe give an example?
