### ISSUE TITLE
Fixing channels tsv

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#45]
So as it stands the channels.tsv file doesn't quite produce the expected results.
As a comment in function that produces it indicates, the `MEGGRAD` value isn't even in the bids specification, with `MEGGRADAXIAL` and `MEGGRADPLANAR` being required to specify the actual gradiometer type.
Further, as I mentioned in the issue I raised for mne-python (https://github.com/mne-tools/mne-python/issues/5311), the units of the KIT gradiometer channels are set to be T, which mne then uses to decide that it is a magnetometer channel, even though it isn't.
My initial thought of how to fix this would be to change the `map_chs` dictionary to be one that maps the `coil_type` value in the channel (eg. `'coil_type': 6001` in the KIT data I have) to the channel type.
Ie. something like
`map_chs.update(meggradaxial=(FIFF.FIFFV_COIL_KIT_GRAD), ... etc)`
The issue with this may be that it may be a bit cumbersome, and also we will need to know exactly what type of gradiometer etc all the various manufacturers use.
Again, I may well be overlooking some other value that is more suitable for correctly identifying the channel type.

**Comment by jasmainak** [comment]
perhaps we could start with the ones that are present in the [mne constants.py file](https://github.com/mne-tools/mne-python/blob/master/mne/io/constants.py#L786-L844)? you could make a list of these. And if it's not a recognized type, then we may have to default to something that BIDS does not complain about.

want to give it a shot @monkeyman192 ?

**Comment by monkeyman192** [comment]
Yeah, there are quite a few, and I realised that there are some missing (eg [the KIT channel types](https://github.com/mne-tools/mne-python/blob/master/mne/io/constants.py#L820-L823) have only two values here, where there are far more in the [KIT constants file](https://github.com/mne-tools/mne-python/blob/master/mne/io/kit/constants.py#L52-L59))
While these may be the more commonly used ones, one of the MEG systems we have recently had the axial gradiometer reference channels modified so that they are realised as such in the con file, and as it stands, these will not be picked up correctly by mne I don't think (modification was only last week, so I haven't had a chance to test it yet...)
I will give it a go when I get to work on Monday.

**Comment by jasmainak** [comment]
okay sounds great, thanks!
