### ISSUE TITLE
should BIDSPath include bids_root

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#454]
Continuing the [discussion](https://github.com/mne-tools/mne-bids/pull/446#discussion_r442978954) off #446 , it's a bit weird that 

1. BIDSPath()._get_bids_fname returns an instance of `BIDSPath` and not `str`, and
2. It looks like `BIDSPath` should take bids_root as an argument so that bids_fname can be constructed easily. This should be `None` if you want to make bids_basename. 

We need to hash this out properly before touching any code. What would be the implications if we did this @adam2392 ? Would `read_raw_bids` and `write_raw_bids` still need `bids_root` as an argument? What would be affected? Can we make this not very invasive a change and can it make things more consistent?

cc @agramfort

**Comment by adam2392** [comment]
Here's some thoughts:

The `BIDSPath()._get_bids_fname` is very nice cuz you can "infer" the full path to the data file using mne-bids, which reduces users need to `Path` a bunch of strings together.

BIDSPath taking bids_root doesn't seem like a big issue to me actually. The idea of a BIDSPath is that it should always be "within" a bids_root, or derivatives directory. So optionally passing it in seems to make sense to me. 

From an API and usage perspective, I think some of the following changes could occur:

1. Return 'str', or a `pathlib.Path` object in `BIDSPath()._get_bids_fname`, since this is a full path now if one has `bids_root` parameter set. I think regardless of what we decide, this func should minimally not return a `BIDSPath` object.

2. Allow bids_root to be an optional parameter in BIDSPath. The BIDSPath would then be fully represented by the "bids_root" and the "bids_basename". If this is done, then `get_bids_fname` only needs `kind` as a parameter to infer the full filepath. However, do we want to add this parameter to `make_bids_basename`? 

I think the pros are really reducing code clutter and allowing automatic filepath inferences. The cons are that the possibilities really become endless; which sidecar files to infer and how to do it? 

3. Re `read_raw_bids` and `write_raw_bids`.. I'm indifferent. I think keeping current API is fine, but also getting rid of `bids_root` parameter would make sense if we incorporate above changes. There just needs to be an informative error message that forces them to use `BIDSPath` with `bids_root` set if we do this change. 

**Misc thoughts:**

By including bids_root as a parameter inside BIDSPath, then... one can automatically infer `scans.tsv`, `participants.tsv` filepaths pretty easily?

This would also allow "public" functions to automatically get the sidecar json/tsv filepaths. E.g.

```Python
sidecarjson_fpath = get_sidecar_filepath(bids_path, suffix=f'{kind}.json')
electrodes_fpath = get_sidecar_filepath(bids_path, suffix=f'electrodes.tsv')
...
```

compared to right now:

```Python
kind = 'ieeg'
bids_basename = make_bids_basename(..., suffix=f'{kind}.json')

sidecarjson_fpath = list(Path(bids_root).rglob(bids_basename))[0]

# or

sidecarjson_fpath = Path(bids_root) / f'ses-{session}' / kind / bids_basename
```

**Comment by jasmainak** [comment]
so according to you `str(bids_path)` always returns the path relative to `bids_root` but `bids_path.get_bids_fname(...)` returns the full path?

**Comment by adam2392** [comment]
> so according to you `str(bids_path)` always returns the path relative to `bids_root` but `bids_path.get_bids_fname(...)` returns the full path?

That seems right to me.

**Comment by agramfort** [comment]
in BIDSPath what is the meaning of suffix and prefix? what are the use
cases?

>

**Comment by jasmainak** [comment]
excellent question!

**Comment by adam2392** [comment]
> in BIDSPath what is the meaning of suffix and prefix? what are the use cases?
> […](#)

To me as a use case, they are the general additions that can get added to a `bids_basename`, where prefix is generally the full path to the `bids_basename`, or the relative path from bids_root.

Suffix is more or less adding arbitrary things after the last bids entity, which can mean: `f'{kind}.{ext}`, or other keywords that aren't in mne-bids yet, but are in the BIDs specification, like `desc`.

**Comment by jasmainak** [comment]
I think `prefix` and `suffix` are somewhat vague from an API perspective. They were meant to be a catch all for different use cases. Prefix was mostly used to create full paths at different levels of the bids folders. I like the idea of using `bids_root` instead of `prefix` and standardizing things a bit. 

Not sure `suffix` can be replaced so easily though. It is used to deal with different kinds of sidecars/modalities.

**Comment by adam2392** [comment]
Sounds like:

1. we should substitute prefix for `bids_root` in BIDSPath and keep suffix for now.
2. refactor `get_bids_fname`

Should we change `make_bids_basename`?

**Comment by jasmainak** [comment]
yes, agreed with 1. Not sure what exactly you mean by 2. Not sure about `make_bids_basename`. We don't use it internally right? Maybe there should be a deprecation cycle if there are no concrete usecases of `prefix` in `make_bids_basename`. So everything is consistent. Not sure, you'll know once you look at the code :)

**Comment by agramfort** [comment]
sounds good

**Comment by adam2392** [comment]
> yes, agreed with 1. Not sure what exactly you mean by 2. Not sure about `make_bids_basename`. We don't use it internally right? Maybe there should be a deprecation cycle if there are no concrete usecases of `prefix` in `make_bids_basename`. So everything is consistent. Not sure, you'll know once you look at the code :)

Well the thing w/ `bids_root` instead of `prefix` is that just with bids_root and a bids_basename, should we expect to be able to infer the full filepath?

E.g. for participants.tsv
```Python
bids_fpath = make_bids_basename(bids_root=bids_root, suffix='participants.tsv')
print(bids_fpath)
>>> <bids_root>/participants.tsv
```

for scans, seems to make sense:
```Python
bids_fpath = make_bids_basename(bids_root=bids_root, subject='01', session='01', suffix='scans.tsv')
print(bids_fpath)
>>> <bids_root>/sub-01/ses-01/sub-01_ses-01_scans.tsv
```

But if say the user neglects to include session, what happens?
```Python
bids_basename = make_bids_basename(bids_root=bids_root, subject='01', task='01')
print(bids_basename)
>>> ?
```

**Comment by agramfort** [comment]
>
> But if say the user neglects to include session, what happens?
>
>
it should crash with a meaningful error. What I did last week with
emptyroom
is basically along those lines.  make_bids_basename does a BIDSPath
and requires some extra checks that the file is valid.

**Comment by adam2392** [comment]
Is it safe to say that:

if `prefix=participants.tsv` then only bids_root is necessary. Otherwise, `subject` and `session` should be mandatory variables since everything else is in a subdirectory of subject and session?

Then possible errors are:
1. didn't include `subject` or `session` 
2. didn't include enough entities to correctly identify the full file path. (e.g. maybe you need `run` to correctly identify the data file)

**Comment by jasmainak** [comment]
@adam2392 

> if prefix=participants.tsv then only bids_root is necessary

if this is used internally to generate a filename, you should pass the right thing. Don't put too much logic in the `BIDSPath`. Fail for the most reasonable use cases. We do expect the user to have some working knowledge of operating systems and the ability to browse through files and see where `participants.tsv` resides. A meaningful error that the file does not exist is good enough for me.

**Comment by hoechenberger** [comment]
Hello, sorry I'm so late to the party, I was on vacation and I'm now just trying to catch up on the discussion.

I'm having a little bit of a difficulty here, which may or may not be related to the present discussion – I clearly must be missing something, but maybe you can help me:

Why do we even keep on using `make_bids_basename()`? It seems to me that currently there's two ways to create BIDS paths: either by calling `make_bids_basename`, which instantiates `BIDSPath`; or by instantiating `BIDSPath` directly. Both are part of the public API and it's not super clear to me which one I should use, and when.

I'm very much in favor of BIDSPath accepting a `bids_root` kwarg (which should be `./` by default), so one can always easily resolve the exact (absolute or relative) path of BIDS files.



> Well the thing w/ `bids_root` instead of `prefix` is that just with bids_root and a bids_basename, should we expect to be able to infer the full filepath?
> 
> E.g. for participants.tsv
> 
> ```python
> bids_fpath = make_bids_basename(bids_root=bids_root, suffix='participants.tsv')
> print(bids_fpath)
> >>> <bids_root>/participants.tsv
> ```

This feels "very wrong" to me – `participants.tsv`, here, is not a suffix, but the actual filename inside the BIDS folder structure. I'd favor an API like, `BIDSArbitraryPath(bids_root=bids_root, path='participants.tsv')`

**Comment by agramfort** [comment]
currently make_bids_basename does some checks that BIDSPath does not do.
It was necessary to deal with empty room specificities. I see now BIDSPath
as a clever namedtuple

**Comment by hoechenberger** [comment]
> currently make_bids_basename does some checks that BIDSPath does not do.

So… let's add `bids_root` to `BIDSPath` and rename `make_bids_basename` to `make_bidspath`? :)

**Comment by hoechenberger** [comment]
While working on https://github.com/mne-tools/mne-study-template/pull/146 I realized a limitation in `BIDSPath`'s `prefix`, if it's (ab?)used to inject a BIDS root into the path:

```python
from mne_bids import make_bids_basename
import os.path as op


bids_root = '.'
prefix = 'average'

# Manual path concatenation
bids_basename = make_bids_basename(task='task')
fname_1 = op.join(bids_root, 
                  '_'.join(['average',
                            str(bids_basename)]))

# Abuse `prefix` to supply bids_root
fname_2 = make_bids_basename(task='task', prefix=op.join(bids_root, prefix))

print(fname_1)
print(fname_2)
```
Output:
```
./average_task-task
./average/task-task
```
The first output is what I want (and what I would expect based on the name of the `make_bids_basename()` argument, `prefix`)

I would therefore propose to allow passing `bids_root` in addition to `prefix`, so one could do:
```
python
bids_root = '.'
prefix = 'average'

fname = make_bids_basename(task='task', prefix=prefix, bids_root=bids_root)
```
which would produce
```
./average_task-task
```

**Comment by adam2392** [comment]
> I'm very much in favor of BIDSPath accepting a `bids_root` kwarg (which should be `.` by default), so one can always easily resolve the exact (absolute or relative) path of BIDS files.

The behavior of bids_root = `.` by default would just be if you wanted to "get the filepath" right? Whereas, when you do `str(bids_path)`, it only returns  the bids_basename?

I guess it seems that BIDSPath needs to have the ability to be used  as a basename, but also as a full filepath.

**Comment by jasmainak** [comment]
it seems to me that `prefix` is kind of vague and it could be abused easily. Why do you want to keep it? what are the usecases?

**Comment by hoechenberger** [comment]
@adam2392 
> The behavior of bids_root = `.` by default would just be if you wanted to "get the filepath" right? Whereas, when you do `str(bids_path)`, it only returns the bids_basename?
> 
> I guess it seems that BIDSPath needs to have the ability to be used as a basename, but also as a full filepath? Which function calls would/should then correspond to each?

Ok I was just re-thinking this, and my idea would be to have something like the following:

```python
>>> subject = '01'
>>> session = 'test'
>>> bids_root = '/foo/bar'
>>> bids_path = BIDSPath(subject=subject, session=session, bids_root=bids_root)
>>> print(bids_path)
BIDSPath(basename: sub-01_ses-test, BIDS root: '/foo/bar')
>>> print(bids_path.basename)
'sub-01_ses-test'
>>> print(bids_path.root)
'/foo/bar'
>>> print(bids_path.full_path  # ugh… probably needs better name :)
'/foo/bar/sub-01_ses-test'
```

@jasmainak 
> it seems to me that `prefix` is kind of vague and it could be abused easily. Why do you want to keep it? what are the usecases?

Like I wrote above, currently there is no easy way to create a basename like
```
arbitrarystring_task-task
```
which we use in the `mne-study-template` (i.e., `average_...`); however I'm now thinking that maybe we just should store `average` (grand mean) data as if it came from an actual participant, i.e., `sub-average`. This would serve consistency, and we wouldn't need a `prefix`, which -- as you correctly say -- can easily be abused.

**Comment by jasmainak** [comment]
like your API suggestion @hoechenberger 

regarding `arbitrarystring_task-task`, indeed it's not a valid BIDS path (unless it is somehow not allowed in the derivative specification? @sappelhoff ?)

**Comment by hoechenberger** [comment]
> regarding `arbitrarystring_task-task`, indeed it's not a valid BIDS path (unless it is somehow not allowed in the derivative specification? @sappelhoff ?)

I never liked it, so getting rid of it would be a good idea anyway :)
@agramfort is there any convincing reason **not** to treat grand average data like data from an "ordinary" participant with the name "average"?

**Comment by hoechenberger** [comment]
@adam2392 regarding what I said about `BIDSPath` above:

> Regarding `bids_root='.'`, I just thought to always have it by default for reasons of consistency. A `.` would refer to the current working directory.

I think a default of `None` could serve the same purpose.

**Comment by sappelhoff** [comment]
`sub-average` sounds reasonable to me :+1: certainly more so than `arbitrarystring_task-task`

**Comment by agramfort** [comment]
I like also the sub-average idea !

**Comment by agramfort** [comment]
I would do:

```
>>> subject = '01'
>>> session = 'test'
>>> bids_root = '/foo/bar'
>>> bids_path = BIDSPath(subject=subject, session=session, bids_root=bids_root)
>>> bids_path  # use REPR
BIDSPath(basename: sub-01_ses-test, root: '/foo/bar')
>>> print(bids_path.basename)
'sub-01_ses-test'
>>> print(bids_path.root)
'/foo/bar'
>>> print(bids_path)   # use __str__
'/foo/bar/sub-01_ses-test'
```

**Comment by adam2392** [comment]
I'll get on this sometime either later this week, or next. 

Just a short summary based on what I'm reading:

Seems like some mods to `__repr__` and also a function `infer_dataset_fpath()` to get the full filepath for that BIDS dataset. All `__str__` and `root` and `basename` attributes should then be pretty straightforward based on what @agramfort and @hoechenberger typed out.

**Comment by adam2392** [comment]
> >>> print(bids_path)   # use __str__
> '/foo/bar/sub-01_ses-test'
> ```

Okay before getting started, my only issue with this one is that `'/foo/bar/sub-01_ses-test'` is not really a valid bids path. In order to infer the full file path for datasets, one needs to pass in the actual `kind` most likely in the suffix, or as a different kwarg. The `kind` can be things like `ieeg, eeg, meg, electrodes, coordystem, scans` that represent the last suffix. 

Is it safe to say that calling `__str__` method performs `infer_full_fpath` function and errors out otherwise? 

So something like:

> >>> print(bids_path)   # use __str__
> '/foo/bar/sub-01_ses-test'

would probably error out?

**Comment by hoechenberger** [comment]
> In order to infer the full file path for datasets, one needs to pass in the actual `kind` most likely in the suffix, or as a different kwarg.

Yes this should be a separate kwarg. I had simply forgotten about `kind` in my previous example, and I believe the same happened to @agramfort, who used my comment as a template.

**Comment by adam2392** [comment]
> > In order to infer the full file path for datasets, one needs to pass in the actual `kind` most likely in the suffix, or as a different kwarg.
> 
> Yes this should be a separate kwarg. I had simply forgotten about `kind` in my previous example, and I believe the same happened to @agramfort, who used my comment as a template.

Should we add `kind` to `make_bids_basename` then?

**Comment by hoechenberger** [comment]
> Should we add `kind` to `make_bids_basename` then?

No, it's not part of the basename in my understanding.

What I meant to propose is this:
```python
>>> bids_path = BIDSPath(subject=subject, session=session, kind='meg', bids_root=bids_root)
>>> bids_path  # use REPR
BIDSPath(basename: sub-01_ses-test, kind: meg, root: '/foo/bar')
```
WDYT?

**Comment by hoechenberger** [comment]
But I do see the difficulty…

**Comment by adam2392** [comment]
> > Should we add `kind` to `make_bids_basename` then?
> 
> No, it's not part of the basename in my understanding.
> 
> What I meant to propose is this:
> 
> ```python
> >>> bids_path = BIDSPath(subject=subject, session=session, kind='meg', bids_root=bids_root)
> >>> bids_path  # use REPR
> BIDSPath(basename: sub-01_ses-test, kind: meg, root: '/foo/bar')
> ```
> 
> WDYT?

I do like the semantics of what BIDSPath can look like. However, yeah I think there's a lot of weird edge cases and details that is hard to work through. (e.g. emptyroom)

Hmm... then what's the diff between `make_bids_basename` and `BIDSPath` besides the error checking that occurs in make_bids_basename? Should we just get rid of that altogether? or should we change the semantics, so that way `make_bids_basename` has no `prefix` since that implies "it is not a basename"?

**Comment by agramfort** [comment]
>
> Hmm... then what's the diff between make_bids_basename and BIDSPath
> besides the error checking that occurs in make_bids_basename?
>

presently yes. And if you don't do this it will make some code complex in
certain places. It's quite convenient that BIDSPath does no testing for
example.


> Should we just get rid of that altogether? or should we change the
> semantics, so that way make_bids_basename has no prefix since that
> implies "it is not a basename"?
>

what do you mean  "get rid of that altogether" ?

**Comment by adam2392** [comment]
Sorry, I guess what I meant was: what's the use case / usage for `make_bids_basename` and `BIDSPath` in conjunction?

**Comment by hoechenberger** [comment]
@agramfort 
>> Hmm... then what's the diff between make_bids_basename and BIDSPath besides the error checking that occurs in make_bids_basename?
> presently yes. And if you don't do this it will make some code complex in certain places. It's quite convenient that BIDSPath does no testing for example.

Do you have a concrete example for when it would "make some code complex"? I'm still failing to see that … and I asked myself the same question as @adam2392: whether we still need `make_bids_basename` at all

**Comment by jasmainak** [comment]
in my mind, `BIDSPath` is a thin object with no logic that behaves like a `Path` object but with the added advantage that you can get the entities from it easily. It shouldn't have too many methods.

Then you can have different functions, `make_bids_basename`, `make_bids_folders` etc that encode extra logic on top of it, for example to account for empty room, to deal with the "kind" and suffix etc. This will keep the code modular and flexible as opposed to making a big object that does everything. Also, as far as I recall, there is a slight discrepancy in the way the paths are constructed/deconstructed when reading vs writing. This could also go into functions.

But before we dive into this, I think it would be helpful to move all these "path" related functions/objects into a file called `path.py` as @hoechenberger hinted before. It will help us understand the problem better.

**Comment by agramfort** [comment]
I fear you need to try to update the code and test to understand where
the difficulty is coming from.

I ended with the solution we have now in terms of design but you use
it more than me in practice
so you could see possible improvements I don't see. Try, look at diff,
comment and see how it goes.
But I agree that a complex object is not ideal

**Comment by adam2392** [comment]
Starting this conversation again: is there any reason that `prefix` kwarg in `make_bids_basename` and `BIDSPath` should not be named `bids_root`, or `root`? If not, then I propose the following refactoring to get rid of prefix and suffix because that imo is the source of confusion and arbitrary usages:

1. (I think easy?) Refactor all BIDSPath and make_bids_basename tests to change `prefix` kwarg to `root` and make sure all the tests work. One thing we can add to `make_bids_basename` is that if the bids_root doesn't exist, or isn't valid, we suggest they use `make_bids_folder` first and fire off a warning(?)

2. (harder) Refactor BIDSPath to be represented by a `root` and a `basename`, where `root` is the directory that houses that specific `basename`. 

In addition, the following changes to the object parameters are added:
- `subject` is required. If not passed in, then errors out. I think all files have the subject entity in (M/I/E)EG data.
- `kind` and `ext` is added to `make_bids_basename` and `BIDSPath` (to replace `suffix`) and allowed to be `('eeg', 'ieeg', 'meg', 'channels', 'coordsystem', 'electrodes', 'scans')`. `ext` is allowed to be acceptable BIDS extensions
- has an internal function `_infer_bids_fname()`, where if `kind` is None, then it tries to infer the full filepath for the raw M(I)EEG dataset, but if `kind` is set, then it explicitly gets that filepath. Here, sidecar JSONs will only be able to be full pathed if one sets `ext='.json'`.

**Comment by jasmainak** [comment]
I think this sounds like a good idea. Let me look at the associated PR
