### ISSUE TITLE
raw_to_bids: reading non-FIF files is broken

### ISSUE THREAD

**Issue by a-hurst** [mne-tools/mne-bids#455]
### Problem
In both the development version (latest Git commit) and release version (0.4) of mne-bids, running the `raw_to_bids` CLI tool on an EEG data file in the EDF format raises an exception:

```
mne_bids raw_to_bids --subject_id sub001 --task tracelab --raw edfs/demi_01\ Data.edf --bids_root bids

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py", line 81, in <module>
    run()
  File "/usr/local/lib/python3.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py", line 74, in run
    allow_maxshield=opt.allow_maxshield)
  File "/usr/local/lib/python3.7/site-packages/mne_bids/read.py", line 63, in _read_raw
    raw = reader[ext](raw_fpath, preload=True, **kwargs)
TypeError: read_raw_edf() got an unexpected keyword argument 'allow_maxshield'

```

### Cause
Looking at the current mne-python and mne-bids source code, the source of the bug becomes clear:

Basically, this line in the CLI tool calls the mne-bids `_read_raw` function with `allow_maxshield` as a keyword argument: https://github.com/mne-tools/mne-bids/blob/11464cdc85940175e4752c99ff40fd8bff38668d/mne_bids/commands/mne_bids_raw_to_bids.py#L74

Then, for files with the .edf extension, that keyword argument gets passed to the .edf reader function in mne's `io` module:
https://github.com/mne-tools/mne-bids/blob/11464cdc85940175e4752c99ff40fd8bff38668d/mne_bids/read.py#L60

However, the mne `read_raw_edf` function [has no `allow_maxshield` argument](https://github.com/mne-tools/mne-python/blob/171917801f6d197d31af82fda7350d3553d8300f/mne/io/edf/edf.py#L1114), so it throws an exception:
```python
def read_raw_edf(input_fname, eog=None, misc=None,
                 stim_channel='auto', exclude=(), preload=False, verbose=None):
```

Looking through the MNE source, it looks like the *only* reader function for which `allow_maxshield` is a valid argument is the `.fif` reader, meaning that unless I'm misunderstanding something, the `raw_to_bids` CLI tool should be broken for all formats except `.fif`.

### Solution?
It seems like the simplest fix would be to assign the `allow_maxshield` value from the kwargs dict to some variable early in the `_read_raw` function, remove that key/value pair from the kwargs, and then use the assigned value only in the call to `read_raw_fif`.

Also, thanks for all the efforts creating and maintaining this package! Eager to start adopting BIDS for all my EEG work.

**Comment by agramfort** [comment]
@hoechenberger maybe you can have a look?

**Comment by sappelhoff** [comment]
... or maybe @a-hurst wants to give this a try in a PR on their own? :-)

the reasoning about whats causing the error and the potential solution sound good to me so far.

**Comment by a-hurst** [comment]
@sappelhoff sure thing! This is just my first instance of contributing to explicitly scientific software, so I wasn't sure to what extent you preferred community contributions vs careful control of your own code. PR will be made shortly.

**Comment by sappelhoff** [comment]
>  community contributions vs careful control of your own code

we try to embrace both here at MNE :wink: 

Thanks for your PR.
