### ISSUE TITLE
MEG coordinates --> We are probably writing the wrong string into `HeadCoilCoordinateSystem`

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#464]
We are writing things like `RAS`, see the `orient` variable in these lines: https://github.com/mne-tools/mne-bids/blob/237b3badab5fe8c28b64bf68b398780d1b53fa7d/mne_bids/dig.py#L243-L249

But `RAS` is not a valid value for this field, see [the part in the spec](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson).

It should be a value from this [list of restricted keywords](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html#meg-specific-coordinate-systems).

Found together with @jasmainak while checking out some datasets on OpenNeuro that were probably processed using MNE-BIDS (but didn't cite 😞 cc #460 )

see here: https://openneuro.org/datasets/ds002598/versions/1.0.0/file-display/sub-08:ses-day2:meg:sub-08_ses-day2_coordsystem.json

**Comment by agramfort** [comment]
yes another thing that should be fixed with a better validator

to me if we write not valid files and our CIs are green the tool to blame
is first the validator

>

**Comment by sappelhoff** [comment]
I agree, see: https://github.com/bids-standard/bids-validator/issues/945
