### ISSUE TITLE
Reorganize mne_bids modules (remove mne_bids.utils module)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#466]
I don't see a good reason to have the `utils.py` module; it seems to be becoming a catch-all place to just dump anything we are not feeling is worth putting more effort into thinking about more useful namespaces (whoo… what a sentence!)

I was always a little irritated by the fact that we have `utils. get_entity_vals()` and `utils.get_kinds()` while e.g. `get_matched_empty_room()` is in the `mne_bids` "root namespace". Doesn't make any sense to me, but I could ignore it.

But now with the introduction of `BIDSPatch` I feel very strongly this is something that should _not_ be in `utils`. I claim it just ended up there because, well, we _have_ a `utils.py`, and what do you do with a super generic module name like that? Right, you just keep adding stuff. This is not helpful in terms of project and namespace structure. I therefore suggest to get rid of `utils.py` entirely.

I'd also like to explicitly point out that this is _not_ a criticism of `BIDSPath` itself, or the development & design decisions that went into its creation. I'm just ranting about an IMHO sub-optimal namespace choice that extends beyond `BIDSPath`, but only became really apparent to me now.

What's your opinion on this?

**Comment by agramfort** [comment]
yes utils is a terrible naming and should not be exposed to users for doing
standard stuff.

so you want to be able to do:

from mne_bids import BIDSPath, get_matched_empty_room,
get_entity_vals, get_kinds
?

>

**Comment by sappelhoff** [comment]
>  it seems to be becoming a catch-all place to just dump anything we are not feeling is worth putting more effort into thinking about more useful namespaces

I don't have a strong opinion, but yes, I think you are right with that point ...

**Comment by jasmainak** [comment]
+1 do you want to move `BIDSPath` to a new file too? or just want to change the namesapce?

**Comment by hoechenberger** [comment]
I'll try to answer both of you at once:

@agramfort 
> so you want to be able to do: from mne_bids import BIDSPath, get_matched_empty_room, get_entity_vals, get_kinds

@jasmainak 
> +1 do you want to move `BIDSPath` to a new file too? or just want to change the namesapce?


I would propose that we move the following classes & functions from `utils.py`:
- … to `path.py` (new module):
  - `BIDSPath`
  - `print_dir_tree`
  - `make_bids_folders`
  - `make_bids_basename`
  - `get_entity_vals`
  - `get_kinds`
  - `_mkdir_p`
  - `_path_to_str`
  -  `_parse_ext`
  - `_parse_bids_filename`
  - `_find_matching_sidecar`
- … to `write.py`:
  - `_write_json`
  - `_write_tsv`
  - `_write_text`
- … to `read.py`:
  - `_read_events`
- … to `_date.py` (new module):
  - `_age_on_date`
- … to `_mne.py` (new module):
  - `_get_ch_type_mapping`
- … to `_eeg.py` (preferred) or to `write.py` (new module):
  - `_infer_eeg_placement_scheme`


`BIDSPath`, `get_entity_vals`, and `get_kinds` should be importable from `mne_bids`.

I'm not sure yet about the best places for the following functions:

- `_estimate_line_freq`
- `_extract_landmarks`
- `_infer_kind`

I'm not super happy about putting  `get_entity_vals` and `get_kinds` in `path.py` and would appreciate ideas for a better place :)

WDYT?

**Comment by jasmainak** [comment]
I would be wary of having files with just one function in them. It makes the code less readable in my experience and makes it harder for newcomers. I'm fine keeping things in a `misc` or `utils` file until it becomes clear that 2 or 3 functions should go to a new file.

**Comment by hoechenberger** [comment]
> I would be wary of having files with just one function in them. It makes the code less readable in my experience and makes it harder for newcomers.

I don't really see why, though? Good naming schemes should make it _easier_ for newcomers (both users and developers) than meaningless generic names :)

**Comment by jasmainak** [comment]
Because it starts to become a labyrinth. Same reason I wouldn't make a 3 line function. Also no 2000 line files please :-)

**Comment by hoechenberger** [comment]
In either case, I think we should at least to the following:

> * … to `path.py` (new module):
>   
>   * `BIDSPath`
>   * `print_dir_tree`
>   * `make_bids_folders`
>   * `make_bids_basename`
>   * `get_entity_vals` (but see below)
>   * `get_kinds` (but see below)
>   * `_mkdir_p`
>   * `_path_to_str`
>   * `_parse_ext`
>   * `_parse_bids_filename`
>   * `_find_matching_sidecar`
> * … to `write.py`:
>   
>   * `_write_json`
>   * `_write_tsv`
>   * `_write_text`
> * … to `read.py`:
>   
>   * `_read_events`

**Comment by sappelhoff** [comment]
I agree with:

>  I wouldn't make a 3 line function. Also no 2000 line files please

and 

> I would be wary of having files with just one function in them. 

... but what you propose @hoechenberger with moving to `write.py`, `read.py` and a new `path.py` sounds like a good compromise to me.

**Comment by sappelhoff** [comment]
talking about re-organizing modules ... we have also been looking for ways to remove `mne_bids.datasets`. 

At least, we can remove `fetch_brainvision_testing_data` ... it's not being used anymore and it was more of a short-term-convenience function anyhow.

**Comment by agramfort** [comment]
+1 for path.py and to remove datasets module. We should have a fetch_openneuro and maybe the nilearn code is enough here.

https://nistats.github.io/modules/generated/nistats.datasets.fetch_openneuro_dataset_index.html#nistats.datasets.fetch_openneuro_dataset_index

the more we centralize datasets with openneuro the better.

**Comment by hoechenberger** [comment]
> We should have a fetch_openneuro and maybe the nilearn code is enough here.
> 
> https://nistats.github.io/modules/generated/nistats.datasets.fetch_openneuro_dataset_index.html#nistats.datasets.fetch_openneuro_dataset_index

This looks good. A full usage example can be found at https://nistats.github.io/auto_examples/02_first_level_models/plot_bids_features.html#fetch-openneuro-bids-dataset 
Quoting it here:

```python
from nistats.datasets import (fetch_openneuro_dataset_index,
                              fetch_openneuro_dataset, select_from_index)

_, urls = fetch_openneuro_dataset_index()

exclusion_patterns = ['*group*', '*phenotype*', '*mriqc*',
                      '*parameter_plots*', '*physio_plots*',
                      '*space-fsaverage*', '*space-T1w*',
                      '*dwi*', '*beh*', '*task-bart*',
                      '*task-rest*', '*task-scap*', '*task-task*']
urls = select_from_index(
    urls, exclusion_filters=exclusion_patterns, n_subjects=1)

data_dir, _ = fetch_openneuro_dataset(urls=urls)
```

I like it, it even allows us to only fetch exactly those files we need for testing.

**Comment by hoechenberger** [comment]
I believe we've addressed most (all?) of the things mentioned here, closing.
