### ISSUE TITLE
Add `anonymize` parameter to copyfile_edf function

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#469]
Currently, all EEG files are converted to BrainVision format if `anonymize` is set in `write_raw_bids`, because we have anonymization utilities only fir FIF (for MEG) and BrainVision (EEG and iEEG).

We can add anonymization functionality for the EDF data format quite easily, and then we won't have to "force-convert" the data to BrainVision anymore.

The function `anonymize_edf` in the pretty popular `pyedflib`, could be used to extend our own `copyfile_edf` with an `anonymize` parameter.

- https://github.com/holgern/pyedflib
- https://pyedflib.readthedocs.io/en/latest/ref/highlevel.html#pyedflib.highlevel.anonymize_edf

Usage from pyedflib would look like this:

```Python
from pyedflib import highlevel

# anonymize edf
highlevel.anonymize_edf('edf_file.edf', new_file='anonymized.edf'
                             to_remove=['patientname', 'birthdate'],
                             new_values=['anonymized', ''])

# check if the two files have the same content
highlevel.compare_edf('edf_file.edf', 'anonymized.edf')
```

alternatives:

- this command line tool? : https://www.physionet.org/content/edf-anonymize/1.0.0/

**Comment by jasmainak** [comment]
I would argue that there is nothing wrong in converting to Brainvision since for MEG we convert to fif. Standardization is the price you pay for anonymization ;-)

**Comment by sappelhoff** [comment]
mhhh okay, fair point. What do you say about #473 though? I think I can achieve #473 in one small private function and 3 lines in `write_raw_bids`.

I certainly would sleep more easily if MNE-BIDS does not read my BV files and rewrites them using pybv (although I am a maintainer of pybv :rofl: )

**Comment by agramfort** [comment]
> I certainly would sleep more easily if MNE-BIDS does not read my BV files
and rewrites them using pybv (although I am a maintainer of pybv 🤣 )

I see it as a good challenge to keep pybv the reference python
implementation to read/write BV files in Python :)

**Comment by jasmainak** [comment]
I agree with @agramfort :)

**Comment by a-hurst** [comment]
@sappelhoff Just FYI, I've written a [pure-python EDF writer](https://github.com/LBRF/DEMI_EEG_Pipeline/tree/main/utils) (based on a heavily-modified pyEDF) which would support this type of functionality, for my own analysis pipeline (passing EEG data from Python to R). Was wondering if it might be useful to a project like this!

Actually, I don't think you'd even need an external library at all to do this: the patient ID data in the EDF+ format always starts and ends at the same location in the header (bytes 88 to 168), so all you'd need to do would be read that in and parse it (MNE already has the code for this in the io module), update the relevant parts of the string, and then overwrite those bytes in the EDF header using the new string. Here are the bits I wrote for creating and validating the participant ID string:

```python
def verify_ascii(x):
    err = "'{0}' contains unsupported characters (only printable ASCII allowed)"
    vals = [ord(c) for c in x]
    if min(vals) == 32:
        raise ValueError("Header fields cannot contain spaces")
    elif min(vals) < 32 or max(vals) > 126:
        raise ValueError(err.format(x))

def date_to_str(dt, fmt="%d-%b-%Y"):
    try:
        datestr = dt.strftime(fmt)
    except AttributeError:
        raise ValueError("All dates must be passed as Python datetime objects")
    return datestr.upper()

def create_patient_id(pid="X", sex="X", birthdate="X", name="X"):
    # First, check if inputs are valid
    verify_ascii(pid)
    if sex.upper()[0] not in ["M", "F", "X"]:
        raise ValueError("EDF+ only supports 'M', 'F', and 'X' as valid sex values")
    sex = sex.upper()[0]
    if birthdate != "X":
        birthdate = date_to_str(birthdate)
    verify_ascii(name)
    # Once validated, create and return string
    outstr = " ".join([pid, sex, birthdate, name])
    if len(outstr) > 80:
        raise ValueError("Combined ID string cannot exceed 80 characters")
    return outstr
```

**Comment by sappelhoff** [comment]
> the patient ID data in the EDF+ format always starts and ends at the same location in the header (bytes 9 to 88), so all you'd need to do would be read that in and parse it (MNE already has the code for this in the io module), update the relevant parts of the string, and then overwrite those bytes in the EDF header using the new string. 

Interesting, is that true for both edf, and edf+? 

I still think it'd be cool to allow for edf anonymizing without forcing a conversion to brain vision.

If it can be accomplished with a small and robust function, that'd be cool for mne-bids imho

**Comment by a-hurst** [comment]
> Interesting, is that true for both edf, and edf+?

[According to the official specs](https://www.edfplus.info/specs/edf.html) the header region for patient info is identical for both EDF and EDF+ (bytes 9 to 88), the only difference is that  EDF+ explicitly defines the format that the participant info data must take ({id}-{sex}-{birthdate}-{name}) whereas regular EDF seems to let users define it however they want.

I think the easiest solution is to try and parse all patient data fields as EDF+, and if there's a parsing error of any kind, just write out "X-X-X-X" as the string since that's the correct way of specifying "no patient info" according to the EDF+ spec.

Based on what I've done already I can probably put together a PR for this pretty quickly!

**Comment by sappelhoff** [comment]
What do @agramfort @jasmainak @hoechenberger say about it?

**Comment by hoechenberger** [comment]
Sounds good to me!

**Comment by agramfort** [comment]
sounds good to me too

>

**Comment by jasmainak** [comment]
+1 for me but @sappelhoff don't give up on `pybv` ;-)
