### ISSUE TITLE
If anonymize=True in "write..." and Brainvision --> DO NOT convert to BrainVision

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#473]
Currently, all EEG files are converted to BrainVision format if `anonymize` is set in `write_raw_bids`.

for data that is already in BrainVision format, this means that it's unnecessarily re-written using `pybv`.

A cleaner (IMO more sensible and less error prone) alternative would be to write a short snippet of code in MNE-BIDS that ...

- copies the BrainVision files to BIDS and then ...
- goes through the `.vmrk` file
- identifies the lines in `.vmrk` that contain the recording date
- replace this recording date with the anonymized date

**Comment by agramfort** [comment]
this makes then BV a special case. For me it's more to be used as a
unit-test.

my 2c

>

**Comment by sappelhoff** [comment]
together with #469 we'd have "two special cases" --> I just say that if we can achieve anonymization with a few lines of code WITHOUT having to change the original data format ... then that's better than data format conversion.

**Comment by agramfort** [comment]
fair enough

>
