### ISSUE TITLE
Cannot import name 'find_ch_adjacency' from 'mne.channels'

### ISSUE THREAD

**Issue by gharshini** [mne-tools/mne-bids#480]
I tried to import find_ch_adjacency from mne.channels. I cannot do that. I have the updated version of mne. can you help me on this?

**Comment by sappelhoff** [comment]
Hi @gharshini. This is the wrong channel for MNE-Python usage questions.

Please ask on the MNE-Python gitter channel: https://gitter.im/mne-tools/mne-python

one hint: check your MNE-Python version and whether the docs you were reading match this MNE version.
