### ISSUE TITLE
Should _get_ch_type_mapping() ignore case of input data?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#481]
I was working with the [OpenNeuro ds001810 dataset](https://openneuro.org/datasets/ds001810). When reading the data via `read_raw_bids()`, all channels are set to type `eeg` although there are also EOG, misc and trigger channels included. I checked the `channels.tsv` file and the channels are clearly marked with the correct type:

```
name    type    units   sampling_frequency      description     status  status_description
...
PO4     eeg     uV      512     EEG channel     good    n/a
O2      eeg     uV      512     EEG channel     good    n/a
EXG1    eog     uV      512     above left eyebrow (VEOG1)      good    n/a
EXG2    eog     uV      512     below left eye (VEOG2)  good    n/a
EXG3    misc    uV      512     left earlobe (for re-referencing)       good    n/a
EXG4    misc    uV      512     right earlobe (for re-referencing)      good    n/a
...
Status  trig    unknown 512     triggers        good    n/a
```

I dug a bit into the code and found that the mapping between BIDS and MNE channel types is done using a dictionary, which is created by `utils._get_ch_type_mapping()`:
https://github.com/mne-tools/mne-bids/blob/e2798b3a202124b843ff6209f3d54db2fe8b6ae0/mne_bids/utils.py#L446-L453

Obviously, this assumes that the correct way to specify channel types in the BIDS dataset is in uppercase letters, [as specified in the standard](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html). The ds001810 dataset, however, uses **lowercase** channel types, and hence `read_raw_bids()` assigns the type `misc` to all of them (and, later, somehow, they all beome `eeg`, but I'm not sure yet where this occurs).

Now – ds001810 passes the BIDS validator. The question is whether we should file a bug report upstream and ask the validator be fixed, and also ask for the ds001810 dataset to be fixed; or whether we can make MNE-BIDS a little more robust by ignoring the channel type case in the input data? We wouldn't run into any ambiguities if we ignored case, and it seems easier to work around this issue on our end than to wait for the BIDS validator and the dataset to get updated … Thoughts?

**Comment by hoechenberger** [comment]
Forgot to add:
I'm not sure using a `defaultdict()` is the best idea here:
https://github.com/mne-tools/mne-bids/blob/e2798b3a202124b843ff6209f3d54db2fe8b6ae0/mne_bids/utils.py#L460-L464

I only noticed something must be wrong with my channels when trying to plot topomaps, and MNE complained about missing location info for some of the channels. I would have preferred to get an error message early on if a channel type cannot be mapped correctly from BIDS to MNE.

**Comment by agramfort** [comment]
Mne bids should follow what the validator accepts. So if the standard says upper case it should be upper case. Now if we accept lower case too we could do it with a warning

**Comment by sappelhoff** [comment]
I think we should raise an issue on bids-validator that upper/lower case should be checked ... and only upper case should be valid.

**Comment by hoechenberger** [comment]
> I think we should raise an issue on bids-validator 

Will do.

**Comment by jasmainak** [comment]
cross-posting my comment from the validator repo because I don't monitor that one closely

> humm ... the specification doesn't say anywhere that uppercase is required. Or did I miss something?

**Comment by sappelhoff** [comment]
>     humm ... the specification doesn't say anywhere that uppercase is required. Or did I miss something?

The specification provides a list of "restricted keywords" The way I read it, these are the values that can be used, and that includes casing. Are you saying it's ambiguous?

**Comment by jasmainak** [comment]
yes I think this is ambiguous.

**Comment by hoechenberger** [comment]
> yes I think this is ambiguous.

Interesting! Is that only because those are TSV files, or would you also consider this ambiguous if it were JSON files? Asking because JSON, "by default", **is** case sensitive.

**Comment by jasmainak** [comment]
okay then there is definitely an inconsistency in the validator but also the specification is ambiguous for both cases.

**Comment by agramfort** [comment]
agreed. The spec needs to be clarified, then the validator eventually adjusted than mne-bids

**Comment by sappelhoff** [comment]
okay, sounds very reasonable to me.

- PR to bids-specification, adding a note that casing IS IMPORTANT
- PR to bids-validator, enforcing the casing
- Follow up PR to MNE-BIDS to adjust the temporary changes from #482

**Comment by sappelhoff** [comment]
update: everything is done from BIDS and BIDS-validator side now, we can do step 3:

" Follow up PR to MNE-BIDS to adjust the temporary changes from #482 "

whenever somebody has time and energy

**Comment by eort** [comment]
I just stumbled over this: 

https://github.com/mne-tools/mne-bids/blob/74ac41a3f2035e4469f9930e725fe36f53f07146/mne_bids/read.py#L373-L383

I suppose this can go, now that [this](https://github.com/bids-standard/bids-validator/issues/1018) is closed?

**Comment by hoechenberger** [comment]
No let's leave it in, as there are still old datasets out there that don't follow this pattern.

Unless our idea is to only support the latest BIDS specs..?

@sappelhoff WDYT?

**Comment by sappelhoff** [comment]
I'd be fine leaving it in for a bit longer, but to remove it eventually.
