### ISSUE TITLE
Move away from OrderedDict?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#490]
MNE is dropping support for Python <3.6 with the next release, which means that using an OrderedDict won't be necessary anymore to preserve element insertion order (order is automatically preserved in Py3.6+ dicts). I was wondering if it would be ok to move away from the OrderedDict, at least for new code, in MNE-BIDS? I always found OrderedDicts extremely cumbersome to work with:

```python
    ch_data = OrderedDict([
        ('name', raw.info['ch_names']),
        ('type', ch_type),
        ('units', units),
        ('low_cutoff', np.full((n_channels), low_cutoff)),
        ('high_cutoff', np.full((n_channels), high_cutoff)),
        ('description', description),
        ('sampling_frequency', np.full((n_channels), sfreq)),
        ('status', status)])
```
This looks like Lisp to me :)

Thoughts?

**Comment by jasmainak** [comment]
sounds good to me, you might have to explicitly mention in the readme what version of Python we support.

**Comment by agramfort** [comment]
no objection although low priority for me

>

**Comment by sappelhoff** [comment]
We can say that Python 3.6 is minimum and just use normal dicts instead of ordered dicts in new code.

when sombody had time they can go over the existing code and replace ordered dicts with normal ones.

**Comment by hoechenberger** [comment]
In https://github.com/mne-tools/mne-python/pull/8107 @larsoner pointed out that "dict preserves insertion order" is a CPython implementation detail in 3.6, and only became a language standard in 3.7 :( So for now we should probably keep using OrderedDicts.

**Comment by sappelhoff** [comment]
I see, let's stop once MNE-Python stops :-)
