### ISSUE TITLE
MEG fine-calibration and crosstalk files

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#495]
So it seems the BIDS MEG specification does not cover MEG fine-calibration and crosstalk files.

> Note that we do not provide specifications for cross-talk and fine-calibration matrix files in the current version of BIDS.

https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#neuromagelektamegin

This is … let's just say **unfortunate**, as typically we require these files to run Maxwell filters or Elekta's MaxFilter on the data to even make them **usable**. Without these files, the recordings are basically trash. It is therefore **of uttermost importance** to distribute these files along with the recorded experimental data.

Now it has been [suggested](https://github.com/bids-standard/bids-examples/issues/56#issuecomment-372744313) to place these files in the `derivatives/` folder, [as done for the ds000248 OpenNeuro dataset](https://github.com/OpenNeuroDatasets/ds000248/tree/master/derivatives). 

However, these files can **not** be created from the raw recordings. Therefore, they are actually **not** derivatives in the BIDS sense.

Further, since derivatives are not yet fully specified, there is no agreed-upon naming scheme, making fully automated processing of the data impossible.

So to me it's clear: this needs to become part of the standard ASAP.

But "ASAP" in BIDS Time can mean "quite long" in Human Time.

Therefore I would like to propose to

1. start pushing forward a proposal to amend the BIDS standard (which will take ~long to complete);and while this is cooking, we already
1. urge ourselves to decide upon a storage / naming scheme for fine-calibration and crosstalk files **within MNE-BIDS** – producing something usable even **before the standard is finally amended**.

Users could leave it to MNE-BIDS to store those files for them properly, even if that would be "outside the official standard" in the beginning.

My idea is that `write_raw_bids()` would gain two keyword arguments, `fine_calib_fname` and `crosstalk_fname`, which allow specification of those files; and they would be placed in the appropriate (decided by us) places in the BIDS hierarchy.

Once 1. is finally finished, we adopt the then-standardized storage method. We could even offer a convenience function to convert from "our" storage (2.) to the standard storage (1.) automatically.

Thoughts?

**Comment by jasmainak** [comment]
I am hesitant to overload `write_raw_bids` too much. We should not try to make `mne-bids` like pandas unless that's the vision somehow :)

Now regarding fine calibration and cross talk files -- note that this applies only for Elekta systems. It's another reason why you should not add these arguments to `write_raw_bids`. Is SSS considered a derivative in BIDS world? I thought even that was not clear ... 

> It is therefore of uttermost importance to distribute these files along with the recorded experimental data.

not completely true. You know the location of recording from the `dataset_description` file? And from that you can get the cross-talk and fine calibration file because they are stored in standard locations in the acquisition computer. What is true though that completely automatic processing might be tricky ...

**Comment by hoechenberger** [comment]
> Now regarding fine calibration and cross talk files -- note that this applies only for Elekta systems. It's another reason why you should not add these arguments to `write_raw_bids`

Why though? Elekta Neuromag files are part of the standard. And as such, the auxiliary files required to make actual use of the data -- fine-calibration and crosstalk files -- need to have their designated spots somewhere too.


> Is SSS considered a derivative in BIDS world? I thought even that was not clear ...

Not sure what others think but to me yes, this is definitely derivative, as it doesn't fall out of the machine like that and requires manual or automated intervention: problematic channels need to be marked as bad before running SSS.

**Comment by agramfort** [comment]
could fine cal and cross talk matrices be written in some json sidecar
files? just trying to be creative here.

>

**Comment by sappelhoff** [comment]
> start pushing forward a proposal to amend the BIDS standard (which will take ~long to complete);and while this is cooking, we already .....

+1 to start integrating this in BIDS. We have all that it takes:

1. a use case
2. knowledge and expertise
3. good connections to the community
4. very good connections to a BIDS maintainer :-)

**Comment by agramfort** [comment]
you have my blessing :)

**Comment by jasmainak** [comment]
> Not sure what others think but to me yes, this is definitely derivative, as it doesn't fall out of the machine like that and requires manual or automated intervention: problematic channels need to be marked as bad before running SSS.

The argument is that Elekta files are not usable without applying MaxFilter. Note that you can also mark bad channels during acquisition, and you can also software/hardware filters during acquisition. Thus the lines between what is raw and what is derived is less clear than we would like to think. See also: https://github.com/bids-standard/bids-specification/issues/23

**Comment by jasmainak** [comment]
> Why though? Elekta Neuromag files are part of the standard. And as such, the auxiliary files required to make actual use of the data -- fine-calibration and crosstalk files -- need to have their designated spots somewhere too.

I am just questioning if it should be part of `write_raw_bids`, not questioning if it should be a functionality in `MNE-BIDS`. If you just need to copy two files, shouldn't this be done manually? Note you just need to share one fine-calibration and crosstalk file for your entire study, not one per file. I see `write_raw_bids` as a function that writes stuff specific to a single recording.

**Comment by hoechenberger** [comment]
> Note you just need to share one fine-calibration and crosstalk file for your entire study, not one per file. I see `write_raw_bids` as a function that writes stuff specific to a single recording.

Not if you have a long-running study, either longitudinal or with looots of participants over time. Then the files might change bc the MEG system is maintained & recalibrated before the study is completed. This just to say that even within a subject these files **might** change between sessions.

**Comment by jasmainak** [comment]
humm I see, fair enough. So the first step is to change the standard, right?

**Comment by hoechenberger** [comment]
> So the first step is to change the standard, right?

My idea was go **start** the "standard amendment procedure", but since this will take ~long to finalize, we should already implement a temporary solution in MNE-BIDS in a way that will hopefully allow us later to seamlessly migrate the data to the standard once it has been amended.

**Comment by jasmainak** [comment]
I would be really wary of implementing something before it's part of the standard. The reason is that it could lead to a fragmented standard with folks starting to implement ad hoc modifications of the standard that works for their software.

also thinking more about it, what exactly do you want to amend? These files are already in the `derivatives` folder in most of the datasets (ds00248, ds000117, ds002598) etc. I think the path of least resistance would be to 

1) formalize that they exist in the `derivatives` folder with a certain name, the argument being it's already used this way in many datasets, then
2) in mne_study_template or mne-bids, search for the filename and use it.

Wdyt?

**Comment by sappelhoff** [comment]
are crosstalk and fine-calibration files needed for all MEG data? Or only for Elekta/Megin/Neuromag (=.fif) data?

Furthermore, I looked at ds000248

![image](https://user-images.githubusercontent.com/9084751/89869976-72cfb580-dbb5-11ea-9f56-aee2b7386e3c.png)

at least the `.dat` file (=fine-calibration?) is just a relatively small 2D matrix. I didn't look at the `.fif` (=crosstalk?) file --> is that also just a small 2D matrix?

--- 

if:

- these two files are needed for all MEG data and
- they boil down to two small 2D matrices each

then why weren't they included in BIDS MEG? @jasmainak do you have some context perhaps?

in any case, to me it looks very simple to include this in the standard.

Depending on how big these things can maximally get, it could even be encoded in the MEG sidecar file `*_meg.json`

something like:

```Python
{
"crosstalk" : {
    "values": [1,2,3,4,5],  # must be shape (n,)
    "dimensions": [40, 50],  # rows x columns
    "column_ordering": "C"  # C or Fortran style ... could also be fixed by the standard to be REQUIRED "C" or "F"
}
}
```

and then similarly for fine-calibration.

WDYT?

**Comment by hoechenberger** [comment]
> are crosstalk and fine-calibration files needed for all MEG data? Or only for Elekta/Megin/Neuromag (=.fif) data?

It's an Elekta NeuroMag-only thig, I believe.

> Furthermore, I looked at ds000248
> 
> ![image](https://user-images.githubusercontent.com/9084751/89869976-72cfb580-dbb5-11ea-9f56-aee2b7386e3c.png)
> 
> at least the `.dat` file (=fine-calibration?) is just a relatively small 2D matrix.

Yes that's the fine-calibration file. Fun fact: it seems that @larsoner found a way to generate this file from empty-room recordings, https://github.com/mne-tools/mne-python/pull/8113

But according to the MaxFilter manual, this file and the crosstalk file are usually to be deployed by Elekta service personnel.

The fine-calibration file I have here from the NeuroSpin research center has 306 rows (one per sensor) and ~15 columns or so.

> I didn't look at the `.fif` (=crosstalk?) file --> is that also just a small 2D matrix?

You can read it via `mne.io.proc_history._read_ctc()`. I again only tried it with a file I have from NeuroSpin, and I get a 306x306 matrix and a list of all channel names (and some more meta info):

```python
In [5]: mne.io.proc_history._read_ctc('NeuroSpin_2008_ct_sparse.fif')['decoupler']
Out[5]:
<306x306 sparse matrix of type '<class 'numpy.float32'>'
	with 5360 stored elements in Compressed Sparse Column format>
```

> 
> if:
> 
> * these two files are needed for all MEG data and

Only for Elekta systems, it seems.

> in any case, to me it looks very simple to include this in the standard.

🥂

> 
> Depending on how big these things can maximally get, it could even be encoded in the MEG sidecar file `*_meg.json`
> 
> something like:
> 
> ```python
> {
> "crosstalk" : {
>     "values": [1,2,3,4,5],  # must be shape (n,)
>     "dimensions": [40, 50],  # rows x columns
>     "column_ordering": "C"  # C or Fortran style ... could also be fixed by the standard to be REQUIRED "C" or "F"
> }
> }
> ```
> 
> and then similarly for fine-calibration.
> 
> Upon reading one would get `value` and reshape them using `dimensions` and `column_ordering`.
> 
> WDYT?

I feel that the matrices I have here would be a little too big for inclusion in the `_meg.json` sidecar file (remember that 306x306 is 93,636)

**Comment by sappelhoff** [comment]
> I feel that the matrices I have here would be a little too big for inclusion in the _meg.json sidecar file

is your concern that the JSON would not be easily "human readable" anymore (i.e., opening the file and reading with your eyes)?

benefit of JSON would be that also the other metadata fields could be encoded.

Let me loop in @robertoostenveld: Robert, we are discussing fine-calibration and crosstalk files for Elekta/Neuromag/Megin MEG data and we are trying to find a way how to include these officially in BIDS. Sorry to burden you with all this text in the thread, but reading the original post by @hoechenberger as well as the two posts above this one may be enough to give you sufficient context (and enough to capture your interest :wink: )

**Comment by hoechenberger** [comment]
> is your concern that the JSON would not be easily "human readable" anymore (i.e., opening the file and reading with your eyes)?

Yes. So personally, I couldn't care less, but I assumed this was one of the reasons why these text-only files were picked in the first place in BIDS :) But if long colons of numbers are no problem, then I'm in support for inclusion in the JSON files.

**Comment by robertoostenveld** [comment]
_Disclaimer: I did not read the whole thread._ 

The reduced numerical precision in the text-based JSON files could be a problem, especially since it is about _improving_ calibration accuracy.

Just stepping back: had I designed it, I probably would have made the calibrations part of the recordings (i.e. in each fif header). Right now they are stored only on the respective lab computer.  These are two extremes: share them with each fif file, or share them only in the lab. But there are levels in between: 

- the calibration can be shared once with the BIDS dataset as a whole
- the calibration can be shared per session (since it can differ for different subjects)
- the calibration can be shared per run (although it won't be different for multiple runs/fif files of one subject)

BIDS inheritance actually comes in handy here, since it allows the calibrations to be shared at either level.

An alternative is that the calibration files are stored elsewhere (in a central repository) and that the JSON file points (with a URL) to the corresponding calibration file. That is more similar to how the (spatial) reference/template images are used in BIDS derivatives.  See https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html#spatial-references

**Comment by sappelhoff** [comment]
fair point with JSON and reduced numerical precision. I am just trying to find a way how we can accommodate the two files in the existing standard without having to make up 

1. new entities
1. new extensions
1. new file types

For that I need to know more about the files ... 

>  306 rows (one per sensor) and ~15 columns or so

>  get a 306x306 matrix and a list of all channel names (and some more meta info):

sounds to me like another way to include it in BIDS would be via the channels.tsv and using the *_meg.json to add new fields that:

1. carry metadata that cannot be included in channels
1. point to the specific channels.tsv that includes the calibration and crosstalk data

---

I am aware that that sounds very hacky, but let's try to brainstorm about solutions and be pragmatic.

**Comment by robertoostenveld** [comment]
at first glance, I was positive about channels.tsv. However, its format is not really suited for a large matrix, furthermore, it contains quite some channels for which the calibration/crosstalk does not apply (EEG, TRIG, etc). 

How about adding a `FineCalibrationFile: './sss_cal.dat` to the `meg.json` (where the name of the file, and relative path can be anything), idem for `CrossTalkFile: './ct_sparse.fif'`, and adding the files to the `.bidsignore`. In that case, the format of the files can stay as it is (which is already supported by existing software), people can manually copy the files into their BIDS datasets and text-edit the JSON to add it (no new tooling required immediately).

See also https://ohba-analysis.github.io/osl-docs/downloads/maxfilter_user_guide.pdf around page 37. Important to consider is that the fine calibration can also be applied to the fif file, so for some fif files it would not apply. Search for "calibration" in the PDF.

**Comment by hoechenberger** [comment]
> fair point with JSON and reduced numerical precision.

No. I mean yes, in principle you're right, but this is a common problem that has long been solved :) The trick is trivial: floats are simply stores as strings to guarantee no loss in precision :)

**Comment by hoechenberger** [comment]
> How about adding a `FineCalibrationFile: './sss_cal.dat` to the `meg.json` (where the name of the file, and relative path can be anything), idem for `CrossTalkFile: './ct_sparse.fif'`, and adding the files to the `.bidsignore`.

Would be a possibility, but it **does** seem kind of hacky to me – something that's, like, "officially BIDS" shouldn't have to go ito `.bidsignore`. I'd therefore be in favor of adding it to the MEG JSON sidecar if we can agree upon a format and procedure that guarantees we won't lose numerical precision.

**Comment by sappelhoff** [comment]
fyi, I advertised this post in the bids meg channel on [brainhack mattermost](https://mattermost.brainhack.org/brainhack/pl/sqdstjh8z7yo5ciaty17f4f3ph)

**Comment by robertoostenveld** [comment]
Having them in `.bidsignore` is indeed kind of hacky. But using existing file formats rather than inventing new ones (to ensure compatibility with existing software) follows the general BIDS philosophy. And linking to other files is already used in BIDS elsewhere (e.g. linking MEG to anatomical MRIs, and in derivatives for spatial transformations).

Please consider the consequence that the existing Neuromag/Elekta/Megin MAXFILTER(R) software cannot be used if the fine calib and crosstalk were stored in a new (e.g. json/tsv) format.

**Comment by hoechenberger** [comment]
> Please consider the consequence that the existing Neuromag/Elekta/Megin MAXFILTER(R) software cannot be used if the fine calib and crosstalk were stored in a new (e.g. json/tsv) format.

Good point: I was only thinking this from the perspective of MNE-BIDS users so far, I'm afraid.

But I still have to disagree with you to some extent: if you wish to process BIDS data, you should use a software that **supports** BIDS data. Assume a user simply loads the rawdata FIF files with some non-BIDS-aware software. All information regarding channel status from `*_channels.tsv` will be ignored, and it's **not** guaranteed that the FIF file holds the same metadata.

Or take the `*_T1w.json` file, encoding the fiducials. This file needs to be read somehow by a processing software.

Therefore I don't think we should adjust the specification to match existing, non-BIDS-compatible software. The software should be updated – or we could produce some conversion scripts that automatically extract the required information from BIDS and compile the input for that software.

**Comment by larsoner** [comment]
> The software should be updated – or we could produce some conversion scripts that automatically extract the required information from BIDS and compile the input for that software. Otherwise we limit ourselves too much and will require an endless number of hacky compromises over time.

Just a drive-by comment that mne-tools/mne-python#8113 adds the ability to read/write fine cal in MaxFilter's format (to/from standard Python types), and writing cross-talk should be pretty easy as well -- so there is no difficult bottleneck for getting MNE-Python at least to write out formats that MaxFilter wants. But I doubt it matters too much since going with a non-MaxFilter compatible BIDS format means that all BIDS software that wants to have a MaxFilter step needs to support these conversions from BIDS-to-MF, which requires being able to write FIF files somehow.

**Comment by sappelhoff** [comment]
I was thinking that with the JSON s olution, it'd be relatively straight forward to do this cycle:

1. read original crosstalk / fine-calib
1. write data+metadata to JSON
1. BIDS STORAGE
1. read the JSON
1. some tiny reshaping + other operations to get a data object in any language (matlab, python, julia, whatever)
1. write the data object to crosstalk / finecalib original format

- step 1+2 are for data curators
- step 3 is just storage
- strap 4+5+6 is for data users ... aided by software --> but not strictly necessary (except writing to FIF maybe)

**Comment by hoechenberger** [comment]
> 1. read original crosstalk / fine-calib
> 2. write data+metadata to JSON
> 3. BIDS STORAGE
> 4. read the JSON
> 5. some tiny reshaping + other operations to get a data object in any language (matlab, python, julia, whatever)
> 6. write the data object to crosstalk / finecalib original format

+1, yes, I like that.

**Comment by jasmainak** [comment]
I am with @robertoostenveld on this one. Let's keep it simple please and not change habits. We want people to adopt BIDS. Zen of Python (even if BIDS may not be in Python ;-) says:

> Although practicality beats purity

and now let me respond to this specifically:

> if you wish to process BIDS data, you should use a software that supports BIDS data.

unfortunately, asking folks to do extra work for no gain is not going to hold is in good stead long term. We have these `.dat` matrices that are understood by MNE-C and Maxfilter for decades and BIDS is relatively new.

Also I agree with this:

> But using existing file formats rather than inventing new ones (to ensure compatibility with existing software) follows the general BIDS philosophy.

that's exactly it. If you look at other file formats, BIDS does not touch them.

I think a simple solution is to add a field that points to the file. That's compatible with 3. or 4 in the [comment above](https://github.com/mne-tools/mne-bids/issues/495#issuecomment-671945457)

**Comment by hoechenberger** [comment]
I still don't see the value in allowing users to access the data "directly" through non-BIDS-aware software. It will blow up, they won't end up with the right channels marked as bad, they won't get the correct fiducials, etc. I'm very, very skeptical.

**Comment by hoechenberger** [comment]
This just to bring up my reconciliation attempt again: we could offer conversion scripts, e.g. "from BIDS to MaxFilter" etc.

**Comment by jasmainak** [comment]
> I still don't see the value in allowing users to access the data "directly" through non-BIDS-aware software.

yeah, but this is also an argument for not using `tsv` and `json` files. I could simply have stored things in regular files and then let the software do the job. For me the argument was that tsv and json files can be edited in any text editor ...

**Comment by hoechenberger** [comment]
But that is exactly my point: We (BIDS) offers some human-readable files for easy inspection and modification of datasets. 

But of course to make this useful, software **using** the data must also be aware of those human-readable files and handle things according to their content. 

You're arguing that software should be able to simply ignore those files. Which reduces BIDS to merely a definition of file naming schemes. Which is ok, but I wonder why we're even going through the pain to create MNE-BIDS then. Could've simply written a simple tool that ensures correct file naming and be done with it...

**Comment by jasmainak** [comment]
> You're arguing that software should be able to simply ignore those files.

not really, that's not what I'm saying.

The way I see it, BIDS should not change what we do with single-subject analysis too much. Someone may want to pick one file from the dataset and still inspect it or analyze it in traditional software. That's why we don't want to create new formats.

Where it really shines (or should shine) is group-level analysis and studies involving multiple subjects and runs. You can query/grep easily, have information about empty-room files, know all the information needed to actually write a paper (gender of different participants, age etc).

**Comment by jasmainak** [comment]
> You're arguing that software should be able to simply ignore those files.

Thinking a bit more about this, I wonder if there is a fundamental misunderstanding. In the BIDS MR world, the validator checks if the sidecars agree with information in the file. If not, it throws an error. 

For some reason, in MNE-BIDS, we have invented this hierarchy where BIDS information is given more weight than what's stored in the file format. I think this is a mistake. This is probably a result of not having a good validator which checks these aspects.

**Comment by sappelhoff** [comment]
> Basically, BIDS should encode extra information that's not in the file format but information already there should agree.

:100: absolutely agree

> This is probably a result of not having a good validator which checks these aspects.

we don't have JS io software for all the MEG EEG and iEEG file formats ... and just writing any JS code to do the job is also not sufficient, which I learned the hard way when I started to write JS io software for BrainVision: https://github.com/sappelhoff/brainvision-validator/

the main issue is that the bids-validator works in the browser AND on the command line --> but in the browser, the file access API is vastly different (and seems complicated to me) --> so developing these JS readers is complex and challenging.

But big challenge blah blah --> we NEED that kind of software to assure mainak's point that I agreed with in the beginning of this post.

Wish I could switch to a parallel universe for a year to do the job and then come back. --> but until that's possible we need to find volunteers with more time or less responsibilities than we have ...  and/or money :)

**Comment by robertoostenveld** [comment]
From https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#meg-recording-data : 

> Unprocessed MEG data MUST be stored in the native file format of the MEG instrument with which the data was collected. 

Which for me includes the fine calibration and crosstalk files: these result from the Neuromag software and the work of the MEGIN engineers during maintenance, not from MNE-Python, or FieldTrip, or BrainStorm. 

Furthermore from the MEG specification:

> With the MEG specification of BIDS, we wish to promote the adoption of good practices in the management of scientific data. Hence, the emphasis is not to impose a new, generic data format for the modality, but rather to standardize the way data is stored in repositories. 

Which for me means that if there is an existing format for data in BIDS that - although perhaps it is not perfect, like NIFTI - does not have big disadvantages, that format should be preferred over a newly defined format. The benefit of being able to use existing tooling outweighs the cost of implementing and supporting new tooling.

PS note that the MEG specification writes "good" practices, not "best" practices, which is on purpose and relates to https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good. The MNE-Python specific perspective on how data should be organized in BIDS might be best but is not per see good. The applicability of the Pareto principle has been discussed for BIDS elsewhere. Note also that other raw data formats can (and should) be discussed, but then in relation to BIDS 2.x. That would also allow us to step away from fif for raw data (and CTF, BTi, etc), for example to a format like that of https://github.com/tierneytim/OPM

**Comment by hoechenberger** [comment]
> > Basically, BIDS should encode extra information that's not in the file format but information already there should agree.
> 
> 💯 absolutely agree

So why have e.g. `status` in `channels.tsv` for FIFF files, then? Duplicating the `info['bads']` metadata in the sidecar just adds more complexity and a source of inconsistencies and errors. If, for example, a users want to mark a certain channel as bad, you'd expect them to 
- edit the `channels.tsv` sidecar
- but also being able to read & write the FIFF file(s) in question to update `info['bads']`

But it was already argued that users should be able to process the data files with the tools they have, without having to worry about BIDS. So they will open the FIFF, update the bads in there, and -- forget about the sidecar. And, of course, **not** run the validator again, because they're not using BIDS-aware software anyway, so they won't have the validator installed either. And even if they **did** run the validator: how are they ever going to fix those inconsistencies without using BIDS-aware software? Bad channel specifications may still be kind of simple to match up between raw and metadata by hand; but there's also other structures where I would imagine this being super cumbersome.

I don't know, right now I'm beginning to stop seeing the point of BIDS entirely, beyond providing some file naming directions.

**Comment by sappelhoff** [comment]
> So why have e.g. status in channels.tsv for FIFF files, then?

to improve human and machine readability: everyone and everything can parse a TSV, this is not the case with FIF

>but also being able to read & write the FIFF file(s) in question to update info['bads']

we are talking about different "states" of the data now. When I ship my raw data in BIDS, it should serve as a *source* ... once you start doing work on it (e.g., update BADS), then you either

- make a new "derivative" dataset
- or make a new version of the "raw" dataset --> here you would need to update the FIF file indeed, as you mention

**Comment by sappelhoff** [comment]
Another option would be to allow fine calibration files as long as their `acq` is specified

- `sub-01_task-nback_acq-finecalibration_meg.fif`

And the same for crosstalk, ... but additionally add another valid extension: `.dat` to be valid in MEG BIDS
- `sub-01_task-nback_acq-crosstalk_meg.dat`

**Comment by hoechenberger** [comment]
> Another option would be to allow fine calibration files as long as their `acq` is specified
> 
> * `sub-01_task-nback_acq-finecalibration_meg.fif`
> 
> And the same for crosstalk, ... but additionally add another valid extension: `.dat` to be valid in MEG BIDS
> 
> * `sub-01_task-nback_acq-crosstalk_meg.dat`

Oh, this seems quite clean, I think I like that! 👍

**Comment by hoechenberger** [comment]
> we are talking about different "states" of the data now. When I ship my raw data in BIDS, it should serve as a _source_ ... once you start doing work on it (e.g., update BADS), then you either
> 
> * make a new "derivative" dataset
> * or make a new version of the "raw" dataset --> here you would need to update the FIF file indeed, as you mention
> 
> edit: I am not addressing the rest of your points because they seem based on the assumption that I get a BIDS dataset and keep working _in_ that dataset, chaotically changing its state without keeping track or being able to keep track.

So you would consider BIDS only for one-off distribution of a dataset that shouldn't be changed anymore?

**Comment by robertoostenveld** [comment]
> So why have e.g. status in channels.tsv for FIFF files, then?

We don't have `status` in `channels.tsv` just for fif files, we have it for all EEG, MEG and iEEG data formats, also the ones where some `info['bads']` syntax (which I don't recognize anyway, since I happen not to be an MNE-Python user) does not apply. Note that one could say that `status` is in principle not a feature of raw data, but only a feature that can be added for derived data, since it requires some analysis and interpretation of the data. But at the time of writing the raw MEG, EEG and iEEG specifications, we did want to be able to share status information. 

I typically do not change my raw data MEG or EEG files when I interpret them (i.e. I would never update the content of the original file), but rather write the interpretation to separate files with metadata (e.g. mat files, or in this case a `channels.tsv` so that other people can reuse my interpretation). The reading from and writing back to fif files is a strategy that I suspect is specific to the MNE software tools (and perhaps EEGLAB does it as well with the `*.set` files). Other MEG software and also (f)MRI analysis software does not read and then write to the same (raw) data file. BIDS aims to be software agnostic.

**Comment by sappelhoff** [comment]
> Oh, this seems quite clean, I think I like that! +1

The next step would be to propose the solutions we brainstormed about in an issue at the bids-specification repo. 

Then let's reasonably quickly converge on a solution (preferably through consensus)

Finally, we implement the changes to spec and validator

Do you want to make the issue @hoechenberger ?

**Comment by agramfort** [comment]
my 2c on this. I would also not alter raw files to mark channels as bad.
You can mark
channels as bad during the acquisition or using megin software but it's
kind of an exception.
The true authority for what to treat as bad should be the channels.tsv
file. Our MNE way here
is to take both list of bads if for some reason the bads were marked in the
file using a megin/mne-C tool.
However note that when writing the files using mne-bids the bads from the
orig file are written
in channels.tsv so I think we are good here.

>

**Comment by hoechenberger** [comment]
@sappelhoff 
> The next step would be to propose the solutions we brainstormed about in an issue at the bids-specification repo.
> 
> Then let's reasonably quickly converge on a solution (preferably through consensus)
> 
> Finally, we implement the changes to spec and validator
> 
> Do you want to make the issue @hoechenberger ?

I can give it a shot!

**Comment by sappelhoff** [comment]
> I can give it a shot!

I had some spare minutes and simply went ahead and simply proposed my solution. :-)

**Comment by sappelhoff** [comment]
this should be resolved now, I am fairly certain the new solution from https://github.com/bids-standard/bids-specification/pull/581 will survive criticisms by Guio and Mainak and will be part of the next BIDS release.

**Comment by jasmainak** [comment]
no critiques from my end :)

**Comment by hoechenberger** [comment]
I'm re-opening because now that we've adjusted the validator in https://github.com/bids-standard/bids-validator/pull/1053, the following storage patterns are now "official" with the [latest specification](https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#example-with-single-session-omitted-session-folder), and we should add support for them to MNE-BIDS:

**Example with single session (omitted session folder)**

```
sub-01/
    meg/
        sub-01_acq-crosstalk_meg.dat
        sub-01_acq-calibration_meg.fif
sub-02/
    meg/
        sub-02_acq-crosstalk_meg.dat
        sub-02_acq-calibration_meg.fif
```

**Example with multiple sessions**

```
sub-01/
    ses-01/
        meg/
            sub-01_ses-01_acq-crosstalk_meg.dat
            sub-01_ses-01_acq-calibration_meg.fif
    ses-02/
        meg/
            sub-01_ses-02_acq-crosstalk_meg.dat
            sub-01_ses-02_acq-calibration_meg.fif
```

So, the files **must** be stored on the deepest nesting level.

Now, how do we add this do MNE-BIDS? In the past I had proposed amending the signature of `write_raw_bids` to simply accept two new arguments, namely `crosstalk_path` and `calibration_path`; but now looking at that function again, after we've switched to using `BIDSPath`, I don't think this would be a great idea.

So then I thought, well, let's just amend `BIDSPath`, and it could gain a `calibration` and a `crosstalk` attribute. But this also comes with problems, I believe.

So… for now, why not simply add two super simple functions, `write_calibration` and `write_crosstalk`, and add two methods to `BIDSPath` that would retrieve these files, similar to how we currently retrieve the matching empty-room recordings?

**Comment by agramfort** [comment]
> So… for now, why not simply add two super simple functions,
write_calibration and write_crosstalk, and add two methods to BIDSPath that
would retrieve these files, similar to how we currently retrieve the
matching empty-room recordings?

sounds good to me

>
