### ISSUE TITLE
parse_bids_fname should extract kind

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#497]
#### Describe the bug
After working on the PR #496 , I noticed that `kind` and `ext` are not extracted from the bids_fname, whereas it should be I think. 

#### Expected results
This is the current example in the docstring:

```
    >>> fname = 'sub-01_ses-exp_run-02_meg.fif'
    >>> parse_bids_filename(fname)
    {'subject': '01',
    'session': 'exp',
    'task': None,
    'acquisition': None,
    'run': '02',
    'processing': None,
    'space': None,
    'recording': None,
    'split': None,
    'kind': None}
```

It should one, have `kind='meg'` and also `ext='.fif'`.

#### Additional information
I'm not sure how to implement this because I am absolutely 100% noob at regex besides what I find on SO. Is there a way to include this into the param_regex for `kind` and `ext`, or just hack it after the regex search for the other BIDS entities?

**Comment by hoechenberger** [comment]
I agree that `kind` should be there, but not sure about `ext`, as it's no BIDS entity. `parse_bids_fname` should actually be renamed to `get_bids_entities_from_fname` :) Extensions are currently extracted via the private function `_parse_ext()`:
https://github.com/mne-tools/mne-bids/blob/8eec738aa521344e5c772d8a744f4838059f28d8/mne_bids/path.py#L359
