### ISSUE TITLE
What is the correct order of BIDS entities?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#500]
There are different orders for the BIDS entities in both `BIDSPath` and `parse_bids_fname` (or soon to be `get_bids_entities_from_fname`).

I actually don't know the corrrect order outside of subject, session, task and kind... How do we resolve this?

**Comment by hoechenberger** [comment]
The specification [says](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html), for the MEG data files:

```
        sub-<label>[_ses-<label>]_task-<label>[_run-<index>][_proc-<label>]_meg.<manufacturer_specific_extension>
```

**Comment by hoechenberger** [comment]
For the coordsystem file, it says:

```
        [sub-<label>[_ses-<label>][_acq-<label>]_coordsystem.json]
```

Personally I would put `acq` behind the other params in the function signature :)

**Comment by hoechenberger** [comment]
So to summarize: I think the following order would make most sense:

1. sub
1. ses
1. task
1. run
1. proc
1. acq

**Comment by adam2392** [comment]
What about split and space to be complete?

**Comment by hoechenberger** [comment]
```
         sub-<label>[_ses-<label>][_space-<label>]_electrodes.tsv
```

```
It is RECOMMENDED that .fif files with multiple parts use the split-<index> entity to indicate each part.

Example:


sub-control01_ses-001_task-rest_run-01_split-01_meg.fif
sub-control01_ses-001_task-rest_run-01_split-02_meg.fif
```


So I would say let's definitely put split last, before kind; and re space and acq, it probably doesn't matter… My updated proposal:

1. sub
1. ses
1. task
1. run
1. proc
1. space
1. acq
1. split
1. kind

**Comment by adam2392** [comment]
Closing. Thanks for elaborating!
