### ISSUE TITLE
kind vs file kind vs suffix in establishing BIDS Paths

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#509]
**Problem**
I was always under the impression that `kind` was the characters after the last `_`, but I suppose in BIDS, it's called the `suffix` (https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#file-name-structure). I think some discussion and clarification around what everything should be named and meaning of each word would help in not only the code-base and making improvements, but also in people's usage.

However, the `suffix` does not include the extension, so at least adding `extension` in #496 was good. In addition `suffix` should only be a single word, and shouldn't contain `_` or `-` characters.

**Questions**
How should we separate `suffix` vs the "file kind" i.e. (meg, eeg, ieeg, anat) in the code? Should BIDSPath take both a `suffix` and a `kind`? Should it be `kind` or `filekind`?

**How to address**
Based on answers here, there's some clean up I feel like I can do that can address some issues I'm facing in #492 .

**Comment by agramfort** [comment]
hum...

well I miss some background here but what the doc you point to suggests is
that suffix is
what we now call kind in master.

I would than conclude that the suffix if one of the modality kind it
implies something
on the category of the file. For example it will have one sidecar file?

@sappelhoff can you enlighten us here?

**Comment by jasmainak** [comment]
so you could have the same filename (ending with _channels.tsv) that are stored in two different folders (meg and ieeg), right? That's why you need `kind` to disambiguate them.

**Comment by adam2392** [comment]
> so you could have the same filename (ending with _channels.tsv) that are stored in two different folders (meg and ieeg), right? That's why you need `kind` to disambiguate them.

Yep. They can have the exact same filename and be specification compliant, but it's the parent directory name that differentiates them.

**Comment by hoechenberger** [comment]
To make things even more unambiguous, couldn't we rename `kind` to `modality`? Even though `anat` doesn't really sound like a modality _per se_, I think this change would make things a little more intuitive…
```python
BIDSPath(subject='01', session='test', task='AV', modality='eeg', suffix='channels', extension='.tsv')
```

**Comment by agramfort** [comment]
>
> To make things even more unambiguous, couldn't we rename kind to modality?
> Even though anat doesn't really sound like a modality *per se*, I think
> this change would make things a little more intuitive…
>
> BIDSPath(subject='01', session='test', task='AV', modality='eeg', suffix='channels', extension='.tsv')
>
>
+1 I was thinking the same. If kind is not a BIDS concept let's use
modality which is what BIDS uses in its documentation. See
https://bids-specification.readthedocs.io/en/stable/01-introduction.html the
ToC

**Comment by hoechenberger** [comment]
Should we try to squeeze this into #492 or is the universe going to explode then?

**Comment by agramfort** [comment]
https://github.com/mne-tools/mne-bids/pull/492 is the next one after this PR

**Comment by adam2392** [comment]
> Should we try to squeeze this into #492 or is the universe going to explode then?

definitely will explode... ;) into a 1000+line PR heh.

**Comment by agramfort** [comment]
are you ok with my changes here @adam2392 ?

**Comment by adam2392** [comment]
> are you ok with my changes here @adam2392 ?

I'm assuming you mean in https://github.com/mne-tools/mne-bids/pull/511 ? Yep I am. Once that PR is merged, I'm going to add the `modality` entity. Then when that is merged in, I'll finally add in the `BIDSPath.fpath()` changes.
