### ISSUE TITLE
Make get_matched_basenames a method of BIDSPath

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#524]
As per discussion at https://github.com/mne-tools/mne-bids/pull/517#issuecomment-682042937

**Comment by hoechenberger** [comment]
Same for `get_matched_emptyroom()`, right?

**Comment by adam2392** [comment]
> Same for `get_matched_emptyroom()`, right?

Want me to just stick it into #532? Same process: i) privatize ii) call in BIDSPath and iii) do some minor update of tests.

**Comment by hoechenberger** [comment]
yes, I'm currently working on it. Will file a PR shortly
