### ISSUE TITLE
Drop make_bids_folders()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#527]
`make_bids_folders()` can safely be dropped if we make it convenient to access the folder structure(s) via `BIDSPath`. I imagine we have an attribute `BIDSPath.folder` that essentially returns `BIDSPath.fpath.parent`

```python
bids_path = BIDSPath(subject='foo', session='bar', task='baz', modality='meg')
subject_folder = bids_path.folder  # returns a Path
if not subject_folder.exists():
    subject_folder.mkdir(parents=True)
```
(one could also omit the `if` line and call `subject_folder.mkdir()` without a prior check)

**Comment by jasmainak** [comment]
how would this work for "incomplete" `BIDSPath` ?

**Comment by hoechenberger** [comment]
We would need at least subject and modality. I believe this is the only restriction?

--

**Comment by jasmainak** [comment]
hummm right, I think so!

**Comment by adam2392** [comment]
> We would need at least subject and modality. I believe this is the only restriction?

I would say at least subject because if you want to go to the scans file, you might not need modality.

**Comment by hoechenberger** [comment]
> I would say at least subject because if you want to go to the scans file, you might not need modality. 
￼￼
And if you only want to go to the root dir, and the root shall be a relative path -- you don't need anything at all 😅

**Comment by agramfort** [comment]
we can try to see if this works but this is going the right direction I think
