### ISSUE TITLE
"Commit history does not contain any merge commits"

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#530]
The PR checklist contains the point "Commit history does not contain any merge commits". I believe now that we're always squashing the PRs via GitHub before merging, this point can be dropped?

**Comment by sappelhoff** [comment]
Are we *always* squashing?

If that's our new policy, we should untick the rebase setting:

![image](https://user-images.githubusercontent.com/9084751/91550843-7723fe80-e929-11ea-8922-9c0a54ef32ce.png)


and then yes, that point could be dropped.

Else, there could be a case where we rebase a merge commit on master and have an ugly merge commit in our master history :)

**Comment by agramfort** [comment]
+1 to always squash

>
