### ISSUE TITLE
make_bids_folders() should become a method of BIDSPath

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#536]
Current signature:
https://github.com/mne-tools/mne-bids/blob/1a52b18d87e09b18b821287180da4e235acb939e/mne_bids/path.py#L726-L727

The function could easily changed to accept a `BIDSPath` instead of `subject`, `session`, `datatype`, and `bids_root`. In the next step, it should become a method of `BIDSPath`. I was thinking something like `BIDSPath.mkdir()`.

Thoughts?

**Comment by adam2392** [comment]
+1 for this. esp since a loto f the functionality comes from `Path.mkdir(overwrite=True, exist_ok=True, etc.)`.

**Comment by hoechenberger** [comment]
The `make_dir=False` functionality should be removed, and instead we should expose sth like `BIDSPath.fpath.parent` as `BIDSPath.directory` or something like that

**Comment by adam2392** [comment]
> The `make_dir=False` functionality should be removed, and instead we should expose sth like `BIDSPath.fpath.parent` as `BIDSPath.directory`

down for this, since `pathlib` is more general
