### ISSUE TITLE
Rename read_raw_bids, write_raw_bids to read_raw, write_raw

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#537]
The current names of these functions seem redundant to me, as they're shipping with mne-**bids**, and we don't have any other read/write functions for (non-BIDS) Raw data.

This would also be more consistent with the existing `write_anat`

Thoughts?

**Comment by sappelhoff** [comment]
I think that's a fair point, and given that the 0.5 release will have many breaking changes anyhow, it might be a good time to do this transition as well (and include it in the migration guide).

**Comment by hoechenberger** [comment]
Allow me to go totally wild here and propose we make both functions **methods** of `BIDSPath`:

```python
raw = mne.io.read_raw_fif(...)

p = BIDSPath(subject='foo', session='bar', task='baz', modality='meg')
p.write_raw(raw, overwrite=True)

raw = p.read_raw(allow_maxshield=True)
```

**Comment by agramfort** [comment]
I expect that most users will do:

from mne_bids import read_raw_bids, BIDSPath

I am not convinced about read_raw as I fear it will conflict with read_raw
in mnelab (I suppose)
and I don't forsee people writing `mne_bids.read_raw` in their code.

my 2c

>

**Comment by adam2392** [comment]
I personally like the `read_raw_bids` and `write_raw_bids` because it makes it explicit in the code and there's no confusion as to is this a `write_raw/read_raw` from BIDs or from mne-python?

I wonder if we should perhaps rename `write_anat` to `write_anat_bids` instead to be consistent?

**Comment by agramfort** [comment]
I am fine with current API :)

**Comment by jasmainak** [comment]
Let's not change everything just for cosmetic benefit. It should be usecase driven.

**Comment by hoechenberger** [comment]
Ok, let's leav it the way it is for now. Closing.
