### ISSUE TITLE
Read BIDS folders

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#54]
Next step: support reading BIDS directory. We will need to walk over the directory and compile all the metadata. We might want a structured dictionary or a custom object that holds all of this and help coordinate reading a specific subject, task, session, etc.

cc: @jasmainak

**Comment by jasmainak** [comment]
well, I think this is something `pybids` already does. So, I'm not sure if we want to reinvent the wheel or do a PR there ...

**Comment by jasmainak** [comment]
although @teonbrooks take a look at this: https://github.com/mne-tools/mne-bids-app. Maybe this could help here ...

**Comment by teonbrooks** [comment]
oh, if pybids is doing it, then we should def use that. I just looked through their codebase but didn't see support for MEG yet. I guess we should file PR against it to extend it

**Comment by jasmainak** [comment]
yes agreed :)

**Comment by jasmainak** [comment]
Let's keep this for next release

**Comment by sappelhoff** [comment]
Mainak's related comment copied from #38 

> Something like:
> `from mne-bids import read_raw_bids`
> `raw = read_raw_bids(raw_fname, tsv_fnames=None, json_fnames=None)`
> `# None would mean you just use the raw_fname to construct tsv_fname and json_fname`

**Comment by jasmainak** [comment]
Any takers for this now that `0.1` is released? ;-)

**Comment by jasmainak** [comment]
okay I'm going to stab at this tomorrow. Just to be sure we are on the same plane, this is the API I was thinking of:

```py
from mne-bids import read_raw_bids
raw, events = read_raw_bids(fname, return_events=True)
```

we could also imagine doing:

```py
epochs = make_bids_epochs(fname, tmin, tmax)
```

and this would read in the events file and construct the epochs based on `tmin` and `tmax`.

Or one could think of doing:

```py
evokeds = make_bids_evoked(fname, tmin, tmax)
```

or even:

```py
evoked_ave = bids_grand_average(bids_folder_root, tmin, tmax)
```

I think we should do try to leverage the BIDS organization structure as much as possible. For example, different runs can be concatenated when reading and averaging. The list of data files to read can be read from `study.tsv`. Maybe something can be gleaned also from `participants.tsv`. Any other ideas?

In a sense, what I'm proposing isn't a true "BIDS app" but I think docker etc. come later.

Thoughts @agramfort @teonbrooks @sappelhoff @monkeyman192 ?

**Comment by monkeyman192** [comment]
why not make a PR on pybids?
They already have a reasonable code base to read the folder structure and extract a fair bit of information. It falls down with MEG/EEG data, but that would probably be less work to implement there than re-write some of it here?
Although having had a little bit of a play with pybids I didn't particularly like how it worked. I think it would be nice if you could do things like:
```python
bids = BIDS(folder_path)
for proj in bids.projects:
 # this would be a Project object which you can do things with, eg:
  for subj in proj:
    # this would be a Subject object
    print(subj.ID, subj.age)
    # etc
```

**Comment by jasmainak** [comment]
my impression is that `pybids` is simply `glob` on drugs ... maybe @teonbrooks has some other opinions here. What we want to do here is a bit more than that -- streamline the processing of MEEG data, not just getting filenames etc.

We don't want to reinvent the wheel but at the same time we can't have a dependency on `pybids` (which in turn has dependencies although these are never explicitly mentioned in their website).

**Comment by agramfort** [comment]
+1 for this:

from mne-bids import read_raw_bids
raw, events, event_id = read_raw_bids(fname, return_events=True)

I think people can then make the epochs.

for the full study grand average we can then do this later and it's
probably beyond mne_bids scope.

**Comment by sappelhoff** [comment]
> from mne_bids import read_raw_bids
raw, events = read_raw_bids(fname, return_events=True)

+1 ... and if people want, they can still get their filename via pybids (we don't enforce it)

**Comment by teonbrooks** [comment]
> from mne_bids import read_raw_bids raw, events = read_raw_bids(fname, return_events=True)

wrt the api, I find it would be very useful if the input was a bids directory and you can specify subject, run, task. it could still have the same output of the raw and the event. otherwise, the api would be just another reader function

**Comment by teonbrooks** [comment]
so you are intending to make a public version of the generic `read_raw` function?

I guess we are planning to leave that for pybids, then this should then end up in an example we have. the user story I can think of is: I receive a M/EEG bids dataset, i want to get a sample subject for a given task to do my analysis with MNE, what do I do?

**Comment by jasmainak** [comment]
> so you are intending to make a public version of the generic read_raw function?

not really. I'm hoping that with the BIDS structure, we can infer all the arguments we need for `_read_raw`. But maybe I'm too optimistic. Let's see ...

> I guess we are planning to leave that for pybids, then this should then end up in an example we have

yeah, maybe ...

> the user story I can think of is: I receive a M/EEG bids dataset, i want to get a sample subject for a given task to do my analysis with MNE, what do I do?

hmm ... I would go step-by-step. As a first stab, I would suggest just reading in the raw data and populating the the `raw.info`, the `raw.chs['info']` etc. based on the sidecar files. 

We don't want to reinvent what `pybids` already does ... unless we can think of arguably better ways to do things (maybe ...?). For now, I'm quite happy to let users do a `glob` or `pybids` to select the filenames. If there is a compelling use case, we can write a function for getting a list of files matching a certain task etc. But I'm not much in favor of mishmashing all functionality into a single function.
