### ISSUE TITLE
Make README function to never overwrite

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#551]
I am iterating a dataset multiple times and using the README to keep track of possible issues and notes for users, it unfortunately gets rewritten everytime. I think since it's a user-defined file, it could just be written to only IF it doesn't already exist. This would have minimal impact since the only thing that gets written is the citation #460 , which can be written if they don't already have a README.

So this line would be:

```
    # save all participants meta data and readme file
    _readme(bids_path.datatype, readme_fname, overwrite, verbose)
```

to

```
    # save all participants meta data and readme file
    _readme(bids_path.datatype, readme_fname, False, verbose)
```

**Comment by jasmainak** [comment]
It sounds fair to me
