### ISSUE TITLE
Use MNE's Sphinx GitHub Substitution

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#557]
See https://github.com/mne-tools/mne-python/pull/8283#discussion_r492649817

**Comment by sappelhoff** [comment]
Yes, that's be cool, I agree :-)

**Comment by hoechenberger** [comment]
I don't see this happening anytime soon… so closing

**Comment by sappelhoff** [comment]
wouldn't it simply be copying over this file: https://github.com/mne-tools/mne-python/blob/master/doc/sphinxext/gh_substitutions.py

and adding a line to conf.py?

**Comment by sappelhoff** [comment]
yup, that works, PR incoming.

It's dumb of me to do this now after this issue has been open so long. Also, there is actually other work I wanted to do. Finally, it's Sunday morning ... but meh ¯\_(ツ)_/¯
