### ISSUE TITLE
Appending Additional Channel/Electrodes Information Into raw.info

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#558]
#### Describe the problem
**Situation**
The BIDS specification allows for some arbitrary flexibility in `electrodes.tsv` and `channels.tsv` files that "append" information to the channel space. 

This can be for white matter contacts in SEEG. See https://neurostars.org/t/how-to-annotate-white-matter-channels-for-seeg-data/5857/2.

Or it can be for say anatomical regions marked by an atlas assigned to each channel. For example, see this `electrodes.tsv` file:

```
name	x	y	z	destriuex	desikan-killiany
L'1	-1.095576	66.539884	35.287211	Unknown	Unknown
L'2	-3.804778	67.947332	35.308774	ctx_lh_G_front_sup	ctx-lh-superiorfrontal
L'3	-7.318944	67.799889	35.474825	ctx_lh_G_front_sup	ctx-lh-superiorfrontal
```

with the corresponding `electrodes.json` specified to describe these extra columns.

**The problem**
If I want to use `read_raw_bids` to return a raw object, I have to go through some extra loading steps to make sure that I can get each of these "dictionaries" of other metadata. I also store it in some arbitrary way. Ideally this is able to be say "appended" to the `raw.info` dictionary.

#### Describe your solution
If there are extra columns in the `electrodes.tsv`/`channels.tsv` files that are described with a JSON file, then we read the data in as a dictionary mapping channels -> said metadata. This dictionary is then appended to the `raw.info` data structure with some checks to ensure that it does not overwrite anything in `raw.info`.

#### Additional context
This also could also possibly be enabled for `write_raw_bids` if say.... the user passes in a list of additional column names to look for in `raw.info`?

This seems like it might be a "misuse" of mne `Info`, but at the same time, `Info` is essentially a dictionary with some set components, and as long as we don't overwrite those components, this should be okay?

Theoretically something similar for `participants.tsv` could also happen where we "append" to `raw.info['subject_info']`?

**Comment by agramfort** [comment]
I would say yes it's a misuse of Info. It will violate check  info function
and you will loose the data on write if you write to fif.
I would rather suggest to explain how to get this info with pandas.read_csv

>

**Comment by hoechenberger** [comment]
Wouldn't it be as simple as 
```python
data = pd.read_csv(bids_path
                   .copy()
                   .update(suffix='electrodes', extension='.tsv'),
                   sep='\t')
```
?

Alternatively we could add `BIDSPath.sidecar_as_dataframe(which='electrodes.tsv')` but this somehow doesn't match our current API not so great…
