### ISSUE TITLE
make_dataset_description uses only string but should accept array (list)

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#56]
[`mne_bids.utils.make_dataset_description`]() accepts only strings for the input fields, however in the BIDS `dataset_description.json`, a few fields should be arrays, such as the authors, see this (correct) example:

```json
{
  "Name": "Matching Pennies",
  "BIDSVersion": "1.1.1, BEP006(EEG) as of 20th of June, 2018",
  "License": "ODbL (https://opendatacommons.org/licenses/odbl/summary/)",
  "Authors": [
    "Stefan Appelhoff",
    "Daryl Sauer",
    "Suleman Gill"
  ],
  "Acknowledgements": "We thank Daniel Myklody for general guidance and help in setting up the recording site.",
  "HowToAcknowledge": "We hope that all users of this dataset will cite the citation listed under the ReferencesAndLinks field.",
  "ReferencesAndLinks": [
    "Appelhoff, S., Sauer, D., & Gill, S. S. (2018, May 25). Matching Pennies: A Brain Computer Interface Implementation. Retrieved from osf.io/cj2dr"
  ]
}

```

Violation of this will yield the following error by the BIDS-validator:

``` bash
	1: Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./dataset_description.json
			Evidence: .Authors should be array

```

See the requirements of the BIDS-validator concerning `dataset_description.json` [here](https://github.com/INCF/bids-validator/blob/ef705d0300b9867e45aed1efc324e10184ae4f37/validators/schemas/dataset_description.json).

**Comment by jasmainak** [comment]
cool, PR welcome :-)

also, I would say if it's a string then a list should be created.
