### ISSUE TITLE
Add on_fail to get_entities_from_fname to allow entities outside the currently allowed list

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#565]
#### Describe the problem
I have filenames that are derivatives in the BIDS sense like: `sub-jh103_ses-presurgery_task-interictal_acq-ecog_run-01_desc-statematrix_ieeg.npy`, which I would like to still use utility functions in mne-bids. 

I understand that we can't fully support derivatives yet, but if I use `get_entities_from_fname` on the above name, it would be ideal to be able to turn off the error check.

#### Describe your solution
Add `on_fail` kwarg that has ignore, warn and raise options with default as `raise`.

**Comment by agramfort** [comment]
ok to me

>
