### ISSUE TITLE
Roundtrip error from EDF -> BV for write_raw_bids and then read_raw_bids? Possibly linked to mark_bad_channels?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#571]
#### Describe the bug
There is a potential bug that might even extend to mne-python, but I am having a hard time understanding what is going on. I basically have this EDF file that I want to convert to BIDS and in so doing, would prefer doing BV write since that seems less error prone compared to an EDF write.

However, when I load back the data, I get a bunch of nans in places. I suspect this is due to actually the `units` of the channels being messed up somehow. So I noticed that my `raw._orig_units` changes from uV to nV after reading/writing.

#### Steps to reproduce
```Python
   entities = {'subject': '001', 'session': '001', 'task': 'interictal', 'run': '01', 'suffix': 'ieeg', 'datatype': 'ieeg', 'extension': '.vhdr'}

    # load in EDF file
    raw = read_raw_edf(edf_fpath)

    nan_indx = np.argwhere(np.isnan(raw.get_data()))
    if nan_indx.any():
        print(nan_indx)
        print(len(nan_indx))

    # set channel types
    raw.set_channel_types({ch: 'ecog' for ch in raw.ch_names})

    # set line freq
    raw.info['line_freq'] = 60

    # construct the BIDS path that the file will get written to
    bids_path = BIDSPath(**entities, root=bids_root)

    # Get acceptable range of days back and pick random one
    daysback_min, daysback_max = get_anonymization_daysback(raw)
    daysback = random.randrange(daysback_min, daysback_max)
    anonymize = dict(daysback=0, keep_his=False)

    # write to BIDS based on path
    print(F'HERE ARE THE RAW UNITS: {raw._orig_units}')
    raise Exception('hi')
    output_bids_path = write_raw_bids(raw, bids_path=bids_path,
                                      anonymize=anonymize,
                                      overwrite=True, verbose=False)
    
    # mark one bad channel
    mark_bad_channels(raw.ch_names[0], bids_path=bids_path,
                          descriptions=['Excel-labeled'],
                          overwrite=False)

    raw = read_raw_bids(bids_path)
    raw.load_data()
      print(raw._orig_units)
      nan_indx = np.argwhere(np.isnan(raw.get_data()))
      if nan_indx.any():
                print(nan_indx)
                print(len(nan_indx))
                raise Exception('WTF?')
```

#### Expected results
I'm not sure what happens here but I think the `mark_bad_channels` basically re-normalizes the data a second time?

#### Actual results
If I do the mark_bad_channels, I get this because all of a sudden there are nans:

```
Traceback (most recent call last):
  File "/Users/adam2392/Documents/interictal_study/analysis/bids/run_bids_conversion.py", line 480, in <module>
    raise Exception('WTF?')
Exception: WTF?
[[     0    320]
 [     0    329]
 [     0    938]
 ...
 [   132 501652]
 [   132 501751]
 [   132 501867]]
219193
```

#### Additional information
Link to EDF file: https://www.dropbox.com/s/c5fa2ex1864vxms/DA001001_1-1_.edf?dl=0

**Comment by adam2392** [comment]
Basically all my data becomes nan after the `mark_bad_channels`... I suspect it's due to this line in `mark_bad_channels()`?

```Python
    # XXX (How) will this handle split files?
    raw.save(raw.filenames[0], overwrite=True, verbose=False)
```
??

**Comment by hoechenberger** [comment]
What's the content of `raw.filenames` at this stage?

**Comment by hoechenberger** [comment]
Also, can you verify that simply loading the data via `read_raw_bids()` doesn't show this problem already?

**Comment by adam2392** [comment]
Yes `read_raw_bids` works fine if I comment out the line `mark_bad_channels` :(

**Comment by adam2392** [comment]
> What's the content of `raw.filenames` at this stage?

During `mark_bad_channels` it is now `<source_entities>_run-01_ieeg.eeg`, so it was converted to BrainVision during `write_raw_bids`. 

The actual source original file is in the Dropbox link and is an EDF file.

**Comment by hoechenberger** [comment]
Almost seems like a bug in the writer, but haven't tested yet. Could you change the raw.save() line of mark_bad_channels() such that it wouldn't overwrite the existing file, but produce a new one? And then try to read this?

**Comment by hoechenberger** [comment]
Btw I didn't know MNE could write BV files… interesting. Wouldn't you be expected to pass a `.vhdr` filename to the write function, then?

**Comment by hoechenberger** [comment]
Oh ok. So it it's BV data, I suppose we cannot write it via `raw.save`, but would have to use `pybv` instead?!

**Comment by adam2392** [comment]
> Almost seems like a bug in the writer, but haven't tested yet. Could you change the raw.save() line of mark_bad_channels() such that it wouldn't overwrite the existing file, but produce a new one? And then try to read this?

Yes commented that part out and it works fine!


> Oh ok. Since it's BV data, I suppose we cannot write it via `raw.save`, but would have to use `pybv` instead?!

Oh unfortunate, but perhaps then this would be a good place to refactor the portion in `write_raw_bids` that writes the final data file to a private function, which then can also be called in this final line of `mark_bad_channels`?

**Comment by agramfort** [comment]
I put this one for v0.5 milestone

**Comment by sappelhoff** [comment]
> However, when I load back the data, I get a bunch of nans in places. I suspect this is due to actually the units of the channels being messed up somehow. So I noticed that my raw._orig_units changes from uV to nV after reading/writing.

not sure if it's a lead, but you may wanna look into the `units` param of `pybv.write_brainvision` ... in mne-bids, we don't set this param and leave it at default:

- https://pybv.readthedocs.io/en/latest/generated/pybv.write_brainvision.html#pybv.write_brainvision

... that'd need `pybv` 0.3 though

**Comment by adam2392** [comment]
We kind of solved the issue, but related to what you said:

`pybv.write_brainvision` though only takes one units. It cannot handle different channels having different units possibly (e.g. bio, ref, etc.) as described here: https://github.com/mne-tools/mne-bids/pull/574#issuecomment-703278260
