### ISSUE TITLE
write_anat() should be changed to accept a BIDSPath

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#572]

**Comment by hoechenberger** [comment]
@adam2392 Want to give this one a shot?

**Comment by adam2392** [comment]
Might not have time to get to this before release...

**Comment by adam2392** [comment]
but if I do i will :)

**Comment by hoechenberger** [comment]
I think we should postpone the release until we have this implemented… otherwise we'll release with an inconsistent API
