### ISSUE TITLE
Allow get_entity_vals to return full entity string

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#577]
#### Describe the problem
Currently `get_entity_vals` will return only the "values" in the key/value pair of entities. For example:

```
subjects = get_entity_vals(root, 'subject')
print(subjects)
>>> ['001', '002', ...]
```

However, if you want the full key-value pair as `sub-001, sub-002, ...`, then you have to manually add it back in, which gets hard to keep track of and leads to incorrectly formatted paths or code downstream.

#### Describe your solution
Adding a kwarg entry to `get_entity_vals` called `return_full_entity`, which allows us to get the full entity key-value string.

**Comment by sappelhoff** [comment]
wouldn't this simply be solved using

`subjects = [f"sub-{label}" for label in get_entity_vals(root, "subject")]`

?

**Comment by adam2392** [comment]
> wouldn't this simply be solved using
> 
> `subjects = [f"sub-{label}" for label in get_entity_vals(root, "subject")]`
> 
> ?

Yes that's what I have ended up doing, but then it ends up getting super cluttered w/ a list comprehension for each entity? WDYT?

**Comment by hoechenberger** [comment]
We could return a dict, but then the function should be renamed to `get_entities()`, I believe…

**Comment by adam2392** [comment]
Hmm okay no problem I suppose. Not high on my priority list.

**Comment by agramfort** [comment]
Adding a parameter to return full strings would be fine with me. 

Is there à bids naming convention for such full names ?

**Comment by sappelhoff** [comment]
> Is there à bids naming convention for such full names ?

- entity: sub-<label>
- entity key: sub
- entity value: <label>

**Comment by agramfort** [comment]
ok so maybe

get_entity_vals(..., with_key=True | False)


?

**Comment by hoechenberger** [comment]
> get_entity_vals(..., with_key=True | False)

+1 for adding a parameter. My proposal would be `return_dict: bool`

**Comment by agramfort** [comment]
-1 on return dict param. Either we return a list of a dict. We should have
one way of doing things.
We just need to choose and ideally before the release

>

**Comment by hoechenberger** [comment]
> -1 on return dict param. Either we return a list of a dict. We should have one way of doing things.

Oh I thought that was what your proposal was supposed to mean. I don't understand what you were proposing, then, when you brought up the `with_key` kwarg…

**Comment by sappelhoff** [comment]
Probably if `with_key=True`, the output would be `[sub-01, sub-02]` instead of `[01, 02]`

**Comment by hoechenberger** [comment]
Did you mean returning strings that have the entity name as a prefix? `['sub-foo', 'sub-bar']`?

**Comment by hoechenberger** [comment]
Ah yes ok, I get it

**Comment by agramfort** [comment]
sorry I meant:

get_entity_vals(root, 'subject', with_key=True)
>>> ['sub-001', 'sub-002', ...]


wdyt?

**Comment by sappelhoff** [comment]
That'd solve @adam2392's problem in a clean and easy way and the API looks good to me (also in terms of naming of params and function).

I don't know if a `get_entities` function that returns all entities with keys AND value as a dict is needed, but that could be a separate function.

**Comment by hoechenberger** [comment]
@agramfort 
> get_entity_vals(root, 'subject', with_key=True)
> >> ['sub-001', 'sub-002', ...]
> wdyt?

Sounds good, 👍 from my side
