### ISSUE TITLE
Allow get_entity_vals to ignore_datatypes

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#579]
#### Describe the problem
Currently, `get_entity_vals` will get you say different tasks, acquisitions, and runs. It has the ability to ignore different subjects, or sessions, but not datatypes (e.g. anat, ieeg, eeg).

#### Describe your solution
Add `ignore_datatypes` kwarg to `get_entity_vals`

#### Additional context
I'm not sure what is the best way to add this in to make sure to fit in w/ the regex in this method. @hoechenberger any thoughts?

**Comment by hoechenberger** [comment]
I wouldn't complicate the regexp, but instead check inside the `for` loop whether the current `filename` is placed inside of an `ignore_datatype` sub directory; and if yes, `continue`.
