### ISSUE TITLE
consider adding generic _events.json

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#58]
`_events.json` accompanies the `events.tsv` and describes its columns.

We can consider offering to write a minimal `events.json`:

```json
{
  "onset": {
    "LongName": "onset",
    "Description": "Onset of the event",
    "Units": "seconds"
  },
  "duration": {
    "LongName": "duration",
    "Description": "Duration of the event",
    "Units": "seconds"
  }
}
```

Users can then add the other columns manually or with custom code --> but at least there would be a starting point.

This `events.json` could be a parameter in the main function `raw_to_bids` which defaults to `False` ... and if `True`, the default minimal file above is written.

What do you think?

**Comment by jasmainak** [comment]
I would just write what can be written. Don't give the users too many options until they start shouting for it :-) PR welcome.

**Comment by sappelhoff** [comment]
We should wait a bit with this, I have just submitted a related [issue](https://github.com/INCF/bids-validator/issues/521) to the BIDS-validator:

**Comment by sappelhoff** [comment]
I revert my previous opinion: I think we shouldn't write an `events.json`. All we could write without user input are the default keys. And the meaning of those are already described in the documentations. So overall there is no added value.

See also this issue for reference: https://github.com/INCF/bids-validator/issues/530
