### ISSUE TITLE
Should write_raw_bids create an events data structure even if no events/eventid passed in?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#581]
#### Describe the bug
If you have a dataset (say in EDF format), that you pass to write_raw_bids that has events in the Annotations of the Raw data structure, it is not written to `events.tsv` unless you explicitly pass in the events/eventid kwarg to `write_raw_bids`.

#### Expected results
I would expect it to tell me it is not doing it unless the events are encoded into a Stim channel, and if you want to parse those events explicitly, then you need to use `mne.events_from_annotations(raw)` to pass in the events explicitly.

#### Additional information
This line in `write_raw_bids` only looks for stim channel and only sets events if they are `.vhdr`, or `.set` extension. 

```
    events, event_id = _read_events(events_data, event_id, raw, ext,
                                    verbose=verbose)
```

My question is: Is this intended behavior? If so, I can make a quick PR updating the documentation on `write_raw_bids` to remind myself and other users to use `mne.events_from_annotations` explicitly if they don't have stim, vhdr, or set data.

**Comment by agramfort** [comment]
a discussion was started about this in the past. My opinion is that we
should write whatever is passed. So if you have annotations write them and
if you have events passed explicitly you write them too.

>

**Comment by hoechenberger** [comment]
Yes we should merge things. So far Annotations are simply discarded.

**Comment by sappelhoff** [comment]
+1 to write events as extensively as we can without guessing. If users don't want that, they can do `raw.annotations = None` before mne-bids
