### ISSUE TITLE
Write MNE Reference information

### ISSUE THREAD

**Issue by timonmerk** [mne-tools/mne-bids#589]
MNE offers a functionality to reference data: https://mne.tools/dev/auto_examples/preprocessing/plot_rereference_eeg.html. 
For data acquisition workflows the used reference is commonly already done by the acquisition system (e.g. by the used amplifier). For writing the channels.tsv file for a specific run, it would therefore be useful to specify the kind of reference being used. 
This could just be a keyword e.g. CAR/earlobe/certain channel (for bipolar referencing) for the `write_raw_bids` function. 

I have two questions regarding that.
First, Is there a way to only set the used reference for the info of the RawArray in MNE without actually performing the referencing as described in https://mne.tools/dev/auto_examples/preprocessing? 
And second, mne-bids currently does not write out this reference parameter of the RawArray info instance. Here it get's explained that it needs to be added afterwards: https://mne.tools/mne-bids/stable/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py How can that parameter be written out automatically? Is the current intended workflow to add it afterwards by hand?

**Comment by jasmainak** [comment]
> First, Is there a way to only set the used reference for the info of the RawArray in MNE without actually performing the referencing as described in https://mne.tools/dev/auto_examples/preprocessing

Look at the `projection` argument [here](https://mne.tools/stable/generated/mne.set_eeg_reference.html#mne.set_eeg_reference)

> Here it get's explained that it needs to be added afterwards

you said this in the gitter too but I couldn't find the word "reference" in the example.

It would be nice if we don't add more arguments to `write_raw_bids` but let's see what API folks come up with.

**Comment by timonmerk** [comment]
@jasmainak The projection keyword states that it's only used for the "average" ref_channels. I am looking for an automatic way to supply to mne_bids any kind of reference e.g. earlobe that is not even stored in the data. 

For the second example I am sorry, I was referring to example 8:  https://mne.tools/mne-bids/stable/auto_examples/convert_ieeg_to_bids.html#sphx-glr-auto-examples-convert-ieeg-to-bids-py

But I understand that adding the reference column to the channels.tsv is also not such a big deal and can be easily added via a script reading the file and adding it afterwards.

**Comment by sappelhoff** [comment]
> But I understand that adding the reference column to the channels.tsv is also not such a big deal and can be easily added via a script reading the file and adding it afterwards.

this sounds like it's another thing that could be simplified via https://github.com/mne-tools/mne-bids/issues/458

**Comment by hoechenberger** [comment]
> @jasmainak The projection keyword states that it's only used for the "average" ref_channels.

Yes, this is correct. The projector can only be added for the average reference.

I believe the correct way (or: first step) to address your specific problem is by adding a column `reference` to `*_channels.tsv`, as decribed in the BIDS specification:

![Screenshot 2020-10-20 at 10 13 09](https://user-images.githubusercontent.com/2046265/96559287-2099c780-12bd-11eb-83b3-a714721441ec.png)

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv

**Comment by agramfort** [comment]
what's the action point here?

>

**Comment by timonmerk** [comment]
@agramfort It was mainly a theoretical question from me. I think it got sorted out, and can be closed. Thanks again!
