### ISSUE TITLE
minor enh: allow print_dir_tree to return a str 

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#590]
if print_dir_tree could return a string, then we could "plot" that string, which could then be used as a thumbnail for the examples gallery.

I think that'd be easy to do, would make the gallery more beautiful, and perhaps even come in handy when one wants to print the dir tree to a file.

Example:

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

# imagine this:
# s = print_dir_tree(".", max_depth=4, return_str=True)

s="""
|eegmmidb_bids_group_conversion/
|--- README
|--- dataset_description.json
|--- participants.json
|--- participants.tsv
|--- sub-001/
|------ ses-01/
|--------- sub-001_ses-01_scans.tsv
|--------- eeg/
|------------ sub-001_ses-01_task-MotorImagery_run-01_channels.tsv
|------------ sub-001_ses-01_task-MotorImagery_run-01_eeg.eeg
|------------ sub-001_ses-01_task-MotorImagery_run-01_eeg.json
|------------ sub-001_ses-01_task-MotorImagery_run-01_eeg.vhdr
|------------ sub-001_ses-01_task-MotorImagery_run-01_eeg.vmrk
|------------ sub-001_ses-01_task-MotorImagery_run-01_events.tsv
|------------ sub-001_ses-01_task-MotorImagery_run-02_channels.tsv
|------------ sub-001_ses-01_task-MotorImagery_run-02_eeg.eeg
|------------ sub-001_ses-01_task-MotorImagery_run-02_eeg.json
"""

ax.text(x=0, y=1, s=s)
ax.axis("off")
fig
```

![image](https://user-images.githubusercontent.com/9084751/96716400-45696a00-13a5-11eb-9e89-d305d1aa4e4a.png)

**Comment by hoechenberger** [comment]
Generally I think we should have some figure / nice icon for each item in our gallery.

But how would we generate a plot like you propose without adding additional code to the examples?

**Comment by sappelhoff** [comment]
> But how would we generate a plot like you propose without adding additional code to the examples?

without additional code, we'd have to generate images "behind the scenes" during the doc build process, and then link them in the sphinx-gallery config ... or add lots of assets (which I wouldn't like)

however, I think that my proposal with it's 4 added lines would work quite well already. WDYT?

**Comment by hoechenberger** [comment]
I like it, it’s just that I’m a bit concerned it might confuse users to see this code. Maybe we can somehow mark it clearly as “housekeeping, nothing to see here, move along”?

--

**Comment by hoechenberger** [comment]
@sappelhoff It seems we might not need this after all. I believe this will do what we want:
https://sphinx-gallery.github.io/stable/configuration.html#providing-a-figure-for-the-thumbnail-image

**Comment by sappelhoff** [comment]
Yes, this is also what I had in mind with this part of what I said:

> without additional code, we'd have to generate images "behind the scenes" during the doc build process, and then link them in the sphinx-gallery config ... or add lots of assets (which I wouldn't like)

I'd be fine with generating a few plots during the build process, and linking them as thumbnails. Including them as static files (assets) would be too much baggage IMHO.

Still, for *producing* some of these thumbnails, I think a thumbnail like this one would be nice: 

![image](https://user-images.githubusercontent.com/9084751/96767874-6a79cf00-13dd-11eb-9d25-c8a7ea17cee6.png)


it just looks BIDSy
