### ISSUE TITLE
minor bug?: electrodes.tsv and coordsystem.json writing per eeg/ieeg should only have certain entities

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#592]
#### Describe the problem
According to the spec: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#electrode-description-_electrodestsv

ieeg can have subject/session/space for `electrodes.tsv`.

while eeg can have subject/session/acquisition/run for `electrodes.tsv` (and maybe space?)

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv

Is this correct?

#### Describe your solution
If the above is correct, then I can modify `_write_dig_bids()` accordingly.

#### Additional context
The more I read the spec sometimes, the more I'm not sure if I have the correct understanding :p so lmk if that is how it should be interpreted.

**Comment by sappelhoff** [comment]
That sounds like an issue for bids-standard/bids-specification. We'd have to look in the entity table and potentially fix the "templates". Also looking at the validator regexps would be helpful ... and finally common sense and then fix spec/validator/mne-bids --> :slightly_smiling_face:  :slightly_smiling_face:  :slightly_smiling_face:  :slightly_smiling_face:  :slightly_smiling_face:

**Comment by adam2392** [comment]
Okay then the issue based on https://github.com/bids-standard/bids-specification/issues/649

is that a PR should refactor so that way subject/session/acquisitoin/space are the only things written in electrodes/coordsystem for eeg/ieeg.
