### ISSUE TITLE
Remove .gz extension for fif: It's no longer part of the validator

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#60]
Throughout the current state of MNE BIDS, the file ending `.gz` is used as an identifier for FIF files:

https://github.com/mne-tools/mne-bids/blob/c73ce744d30be87645e1648754b488f7572307f3/mne_bids/meg_bids.py#L33-L34

Can we change this to `fif.gz`? I am just concerned, because other files can be `.gz` and have nothing to do with FIF.

**Comment by jasmainak** [comment]
okay agreed ! PR welcome

**Comment by sappelhoff** [comment]
given this [issue](https://github.com/INCF/bids-validator/issues/491) on the bids-validator, we should wait until there is some resolution before starting to work on this.

**Comment by sappelhoff** [comment]
Since `fif.gz` is no longer supported with the validator, we should remove it. See https://github.com/INCF/bids-validator/pull/496

**Comment by jasmainak** [comment]
yeah, let's follow that PR and remove it once it is removed
