### ISSUE TITLE
write_raw_bids_: annotations are extracted despite event_data passed

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-bids#602]
Not sure whether this is one bug, two bugs, or just an unclear bit in the documentation...

#### Describe the bug

In the documentation of `write_raw_bids` it says as description of the `event_data` argument that:
>If None, events will be inferred from the the raw object’s mne.Annotations using mne.events_from_annotations.

Maybe I am misunderstanding, but I read this as mne.Annotations are *only* extracted if None is passed to event_data. However, despite me setting event_data with an MNE events array, `write_raw_bids` is still trying to extract events from annotations. Because of that, `write_raw_bids` fails with this error: 

```
Traceback (most recent call last):
  File "makeBids.py", line 76, in <module>
    mb.write_raw_bids(raw, bids_basename,event_id = event_id[task], events_data = events,overwrite=True)
  File "/home/ede/tools/miniconda3/envs/coconut/lib/python3.6/site-packages/mne_bids/write.py", line 1108, in write_raw_bids
    verbose=False)
  File "/home/ede/tools/miniconda3/envs/coconut/lib/python3.6/site-packages/mne_bids/utils.py", line 234, in _read_events
    verbose=verbose)
  File "<decorator-gen-44>", line 20, in events_from_annotations
  File "/home/ede/tools/miniconda3/envs/coconut/lib/python3.6/site-packages/mne/annotations.py", line 1008, in events_from_annotations
    annotations.description, event_id=event_id, regexp=regexp)
  File "/home/ede/tools/miniconda3/envs/coconut/lib/python3.6/site-packages/mne/annotations.py", line 865, in _select_annotations_based_on_description
    raise ValueError('Could not find any of the events you specified.')
ValueError: Could not find any of the events you specified.
```

The annotations I have in my raw file are `BAD_` and `EDGE_` markers of where I concatenated two raw files (and therefore nothing I would want to be extracted as files). According to this [closed issue](https://github.com/mne-tools/mne-python/pull/6333) in MNE-python, these event should be ignored anyway. To avoid this error, I had to add the `regexp=None` argument to the call of [mne.events_from_annotations](https://github.com/mne-tools/mne-bids/blob/2a035c77a8a2d2708efa17144bd341acb96af121/mne_bids/utils.py#L233) in `utils._read_events()`. Even though mne still tried to extract annotations, `BAD_` and `EDGE_` are being ignored.

#### Steps to reproduce
a call like this: 
`write_raw_bids(raw, bids_basename,event_id = event_id, events_data = events)`
on a raw file that has annotations in it (which are not listed in the `event_id` dict.)

#### Expected results
write_raw_bids should extract events and make an event.tsv

#### Actual results
crash with the error message from above.

**Comment by hoechenberger** [comment]
Thank you for reporting this issue!

The problem is that we currently pass `event_id` to `events_from_annotations()`, which we really shouldn't:
https://github.com/mne-tools/mne-bids/blob/2a035c77a8a2d2708efa17144bd341acb96af121/mne_bids/utils.py#L233-L234

But if we don't we'd have to ensure we don't get overlapping event IDs in case users pass `event_data` and `event_id` too, while Annotations are present.

@agramfort Would the clean way to go here to move from our current approach – read events from an events file or an event dict and merge those with the events produced by `events_from_annotations` – to instead do the following:

- use events from events file or event dict
- convert these events to Annotations
- THEN extract **all** events via `events_from_annotations`?

We'd have to be super careful about `raw.first_time` when creating the Annotations, I'm afraid?

**Comment by agramfort** [comment]
yes I agree we need a different strategy.

what you suggest would work yes.

@eort to fix your pb for now you can do

raw.set_annotations(None)

before calling write_raw_bids

>

**Comment by hoechenberger** [comment]
@agramfort 
> what you suggest would work yes.


Ok I will file a PR sometime today. I'll need help dealing with the `orig_time` param of `Annotations` / it's interaction (?) with `Raw.first_time`, I never really understood this part I'm afraid. – We can discuss during the PR review ;)

**Comment by hoechenberger** [comment]
@eort This should be fixed in `master` now, and we'll make a new stable release of MNE-BIDS soon, including this fix.

**Comment by sappelhoff** [comment]
> we'll make a new stable release of MNE-BIDS soon, including this fix.

you mean `0.5.1`? :-) what's your plan @hoechenberger?

**Comment by hoechenberger** [comment]
> you mean `0.5.1`? :-) what's your plan @hoechenberger?

I'm afraid we'll have to make a `0.6` as #603 breaks backward-compatibility again 😅

**Comment by sappelhoff** [comment]
I see, okay - fair enough :+1:
