### ISSUE TITLE
mne-bids writes durations as zero and it does not make use of the original date?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#606]
#### Describe the bug
There are two issues I found:

1. event durations: I usually don't have events / annotations with duration > 0, but today working on getting a new project off the ground with iEEG data and created an `Annotations` object from metadata with `duration>0` for events, and they were all being output as in the `events.tsv` file.

2. orig_time usage: If I have events that say span over multiple files (e.g. in `fif` files we use the `split` entity to split up contiguous recordings), then using the `meas_date` of the `Raw` data structure I would presume allows one to then set annotations properly. 

## Reproducing Results
For example, if I have:

```
raw1.meas_date = 10/27/2020:12:00:00
raw2.meas_date = 10/27/2020:12:00:10

# length of raw1 recording = 10 seconds

```
with events:

```
onset = [5, 11]
durations = [1, 2]
description = ['test1', 'test2']
annotations = Annotations(onset, durations, description)
raw1.set_annotations(annotations)

events, events_id = events_from_annotations(raw1)
write_raw_bids(raw1, bids_path, events=events, events_id=events_id)

write_raw_bids(raw2, bids_path, events=events, events_id=events_id)
```

Then I would make an `Annotations` data structure, do `raw.set_annotations` and then use `events_from_annotations` to get the events and ID to pass into `write_raw_bids`.

Then I would presume "event_2" is not written to the `*events.tsv` file for raw2?

#### Expected results
1. The durations are kept?

2. `*events.tsv` written should only contain event_1 for raw1 and event_2 for raw2.

#### Actual results
1. Durations are written as 0

2. The same copy of events is written for `raw1` and `raw2`. 

#### Additional information
This brings me to another question. How come we have users pass in `events/event_id` instead of an `Annotations` data structure?

**Comment by hoechenberger** [comment]
> #### Expected results
> 
> 1. The durations are kept?

This was just introduced with #603.

> 2. `*events.tsv` written should only contain event_1 for raw1 and event_2 for raw2.

I'm not sure what you mean here? We always write Annotations; users can pass **additional** events via `events_data` and `event_id`.

> #### Actual results
> 
> 1. Durations are written as 0

If that happens on `master`, it's clearly a bug.


> This brings me to another question. How come we have users pass in `events/event_id` instead of an `Annotations` data structure?

We make use of `Raw.annotations`, which should be set before invoking `write_raw_bids()` via `Raw.set_annotations()`.

**Comment by adam2392** [comment]
Yes you're right. I opened issue too soon. I could've swore I was on the most recent mne-bids version :p. 

Re annotations, I found out that they have a `crop` function to get rid of any events before the current `raw.info['meas_date']`.
