### ISSUE TITLE
A simple function for obtaining the BIDS root of a file path?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#608]
## Describe the problem
I've recently needed to dynamically obtain the root of the BIDS dataset for a valid filepath. I found it was slightly more involved then ideal. So given a filepath like: `/blah/test/mne/here/sub-01/ses-01/ieeg/<fname>`, I would want to return `/blah/test/mne/here/`.

#### Describe your solution
The soln I came up with isn't pretty, but it seems to work consistently, and it made me wonder if it would be good to just expose an API function for it in mne-bids?

```Python
fpath = Path(fpath)
        fname = fpath.name
        entities = get_entities_from_fname(fname)
        bids_rel_path = BIDSPath(**entities).fpath

        file_parts = fpath.parts
        rel_parts = bids_rel_path.parts
        bids_root_parts = []
        for part in file_parts:
            if part not in rel_parts:
                bids_root_parts.append(part)
        bids_root = Path(*bids_root_parts)
```

+ some error checks if this becomes a supported function.

#### Additional context
I'm not an expert in pathing, so maybe this is convoluted and a better soln exists, but wanted to open a discussion on if this was valuable or not?

**Comment by agramfort** [comment]
what's the use case? if you work with BIDSPath you have the root attribute

>

**Comment by hoechenberger** [comment]
I feel this is not how users should work with BIDS data. They shouldn't have to worry about "filepaths" like these as far as MNE-BIDS is concerned…
