### ISSUE TITLE
write_raw_bids changes the data dtype on write for fif files

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#609]
if you convert a fif files the data get systematically written to disk in float32 (default format of raw.save).

this is bad. The data buffers should not be changed.

@jasmainak thoughts?

**Comment by agramfort** [comment]
I saw the pb when using old fils stored in short and the written files were twice bigger...

**Comment by jasmainak** [comment]
agree that the dtype should not change

**Comment by hoechenberger** [comment]
Wow, good catch
