### ISSUE TITLE
ADD: Configure CircleCI

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#61]
So that we can check the artifacts tab for builds of the docs

**Comment by sappelhoff** [comment]
@jasmainak I guess somebody with write-access needs to do this? Potential milestone for 0.1.0? I remember in my PR, there were occasional issues with `make html` in the `/doc` directory that you caught but I didn't notice. Circle CI would have alerted me to that earlier, wouldn't it?

**Comment by jasmainak** [comment]
Yeah sure I can give you write access. Do you want to make a PR?

**Comment by sappelhoff** [comment]
Yes, but I am running into issues:
1. It seems that you can only set up circle CI for repos that you actually own - I couldn't find information on how to deal with it if you have write access as a contributor

2. As an alternative, I wanted to set up circle CI on a branch of my fork ... but apparently it's a bit troublesome to have circleCI only on one branch. And I don't want to pollute my master branch with something that might not get merged.

3. Running through the procedure and reading up on it I was asking myself to questions:

a) What does CircleCI offer to us, that we cannot do with Travis? --> couldn't we add a `cd /doc; make html` call to the travis script?

b) What exactly is the `make` call doing here? https://github.com/mne-tools/mne-bids/blob/cf47d16acf3432957448546eb650f47af3ddd4bb/.travis.yml#L27-L28

I don't see any make file. Is that some implicit python default configuration that I don't know of?

**Comment by jasmainak** [comment]
1. Just make a PR. I will enable it so when you push Circle will get activated and you can iterate till you make it pass

2. See 1.

3. a) You could but you have an artifacts tab in CircleCI which lets you browse the html that is built. I'm not sure if Travis allows you to do that

b) You do have a makefile [here](https://github.com/mne-tools/mne-bids/blob/master/Makefile). When you call it without any arguments, I _think_ it calls "make all"
