### ISSUE TITLE
Key error in mne_bids.write_raw_bids for Elekta Triux file (ias)

### ISSUE THREAD

**Issue by RuKrei** [mne-tools/mne-bids#615]
Dear mne_bids developers,

thanks for the great work you are putting into this tool.

#### Describe the bug
Unfortunately I ran into an error that might most likely be a bug:
When including raw fif-files to a BIDS-Dataset a key error occurs. This happens to unprocessed (and undamaged) files using mne0.21 and also mne0.22.dev0. I am using the latest stable mne_bids version as obtained via pip.

#### Steps to reproduce
The code I am executing is the following:

```
bids_root = "/home/idrael/DATA/MEG/BIDS_clinic"
data_root = "/home/idrael/DATA/MEG_playground"


def convert_dcm_folder(subj):
    try:
        anafolder = os.path.join(data_root, subj, "data", "anat", subj)
        folder = str(glob.glob((anafolder + '/1*/100*/100*'), recursive=True)[0])
        convert_directory(folder, anafolder, compression=True, reorient=True)
    except OSError as e:
        print(e)

for subj in subjects:
    data_dir = os.path.join(data_root, subj, "data")
    raws = glob.glob(data_dir + "/*.fif")
    bids_path = BIDSPath(subject=subj, session=session, task="resting", root=bids_root)
    for run, rawfile in enumerate(raws):
        run += 1
        raw = mne.io.read_raw(rawfile)
        bids_path.update(run=run)
        write_raw_bids(raw, bids_path, overwrite=True)    # this breaks with fif-files due to an IAS-Key Error
    convert_dcm_folder(subj)
    anafolder = os.path.join(data_root, subj, "data", "anat", subj)
    niis = glob.glob(anafolder + "/*.nii*")
    try:
        for n in niis:
            write_anat(n, bids_path=bids_path, overwrite=True)
    except Exception as e:
        print(e)
```

#### This results in the following error message:
Writing '/home/idrael/DATA/MEG/BIDS_clinic/dataset_description.json'...

{
    "Name": " ",
    "BIDSVersion": "1.4.0",
    "DatasetType": "raw",
    "Authors": [
        "Please cite MNE-BIDS in your publication before removing this (citations in README)"
    ]
}
Reading 0 ... 1201999  =      0.000 ...  1201.999 secs...

Writing '/home/idrael/DATA/MEG/BIDS_clinic/sub-PP05071984/ses-resting/meg/sub-PP05071984_ses-resting_task-resting_run-01_meg.json'...

{
    "TaskName": "resting",
    "Manufacturer": "Elekta",
    "PowerLineFrequency": 50.0,
    "SamplingFrequency": 1000.0,
    "SoftwareFilters": "n/a",
    "RecordingDuration": 1201.999,
    "RecordingType": "continuous",
    "DewarPosition": "n/a",
    "DigitizedLandmarks": false,
    "DigitizedHeadPoints": false,
    "MEGChannelCount": 306,
    "MEGREFChannelCount": 0,
    "EEGChannelCount": 64,
    "EOGChannelCount": 2,
    "ECGChannelCount": 1,
    "EMGChannelCount": 0,
    "MiscChannelCount": 2,
    "TriggerChannelCount": 18
}
Traceback (most recent call last):
  File "/home/idrael/DATA/git/SourceLoc/src/01_create_DS_and_Folders.py", line 38, in <module>
    write_raw_bids(raw, bids_path, overwrite=True)    # this breaks with fif-files due to an IAS-Key Error
  File "/home/idrael/anaconda3/envs/MEG_dev/lib/python3.8/site-packages/mne_bids/write.py", line 1118, in write_raw_bids
    _channels_tsv(raw, channels_path.fpath, overwrite, verbose)
  File "/home/idrael/anaconda3/envs/MEG_dev/lib/python3.8/site-packages/mne_bids/write.py", line 109, in _channels_tsv
    ch_type.append(map_chs[_channel_type])
KeyError: 'ias'

#### Thank you for looking into it, please let me know if you need a minimal working example.
Best, 
R. Kreidenhuber

**Comment by agramfort** [comment]
I am looking into it

**Comment by hoechenberger** [comment]
Thanks for reporting! 
@agramfort Seems there's an IAS channel type we're currently not handling?

**Comment by RuKrei** [comment]
Thanks,

I guess it's something concerning "internal active shielding".

**Comment by agramfort** [comment]
yes I am on it

>

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-bids/pull/616/files
