### ISSUE TITLE
Next release – Bump pybv requirement to 0.4

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#621]
We've fixed some serious issues here, which demand a new release; and I think once pybv 0.4 has been released, we should bump our requirement to that version, because otherwise we might end up writing … problematic BV files. WDYT? 

cc @sappelhoff

**Comment by hoechenberger** [comment]
See https://github.com/bids-standard/pybv/issues/60

**Comment by sappelhoff** [comment]
yes, definitely agreed :+1:

**Comment by hoechenberger** [comment]
Will 0.4 also fix the roundtrip issue we encountered recently?

**Comment by sappelhoff** [comment]
yes, see https://github.com/sappelhoff/pybv/pull/1 which is based off https://github.com/bids-standard/pybv/pull/58

I'll open that PR properly once https://github.com/bids-standard/pybv/pull/58 is merged, to avoid conflicts

**Comment by sappelhoff** [comment]
done: https://github.com/bids-standard/pybv/releases/tag/v0.4.0
