### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 147

### ISSUE THREAD

**Issue by levchenkoegor** [mne-tools/mne-bids#622]
Hello, everyone!

I was moving from 0.4 to 0.5 version of mne-bids and faced with a problem while writing files in BIDS format.

The code is next:

```
import mne_bids
import mne
from pathlib import Path

proj_root = Path() / '..'
data_raw_dir = proj_root / 'data_raw'
data_bids_dir = proj_root / 'data_bids'

raw_file = mne.io.read_raw_fif(str(raw_file_path)) # raw_file_path is just a direct path to MEG fif file

subj_id = '1001'
date_record = '20201111'
task_name = 'vid1'

bids_filename = mne_bids.BIDSPath(subject=subj_id, session=date_record, task=task_name, root=data_bids_dir)
mne_bids.write_raw_bids(raw=raw_file, bids_path=bids_filename, verbose=True,  anonymize={'daysback': 40000}, overwrite=True)

```

Output error:

```
Traceback (most recent call last):
  File "<input>", line 8, in <module>
  File "E:\Egor_Levchenko\Software\Miniconda\envs\MCCA-MEG\lib\site-packages\mne_bids\write.py", line 1082, in write_raw_bids
    _readme(bids_path.datatype, readme_fname, False, verbose)
  File "E:\Egor_Levchenko\Software\Miniconda\envs\MCCA-MEG\lib\site-packages\mne_bids\write.py", line 236, in _readme
    _write_text(fname, text, overwrite=True, verbose=verbose)
  File "E:\Egor_Levchenko\Software\Miniconda\envs\MCCA-MEG\lib\site-packages\mne_bids\utils.py", line 176, in _write_text
    fid.write(text)
  File "E:\Egor_Levchenko\Software\Miniconda\envs\MCCA-MEG\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 147: character maps to <undefined>
C:\Programs\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py:322: RuntimeWarning: Could not locate a data file of a supported format. This is likely a problem with your BIDS dataset. Please run the BIDS validator on your data. (root=..\data_bids, basename=sub-1001_ses-20201111_task-vid1). []
  value = format % v
```

I am building my environment using conda with this `.yml` file:
```
name: MCCA-MEG
dependencies:
  - python=3.7.7
  - pip=20.2.4
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.3.2
  - pandas=1.1.1
  - conda-forge::mne=0.21.0
  - conda-forge::mne-bids=0.5
  - conda-forge::dicom2nifti=2.2.10 #should be deleted if dcm2niix is successful enough
  - conda-forge::dcm2niix=1.0.20190902
  - pip:
      - pybids==0.12.3
```

Can you tell me please what am I missing in the new version of mne-bids?

Thanks for any suggestions!

**Comment by hoechenberger** [comment]
Hello @levchenkoegor, sorry to hear you're experiencing difficulties!

Have you tried starting again with a fresh (empty) `data_bids_dir`?

**Comment by levchenkoegor** [comment]
Hello @hoechenberger, thank you for the reply!

Yes, I tried and checked the result with another file (empty-room recording):

```
mne_bids.print_dir_tree(data_bids_dir)

|data_bids_test\
|--- README
|--- sub-emptyroom\
|------ ses-20190314\
|--------- meg\
```

Looks like that the problem not in the paths, but in writing files.

**Comment by hoechenberger** [comment]
Yes the problem occurs when processing the `README`. I'm not sure why, though. Is there any content in the `README`?

Otherwise, do you think you could share one of the problematic files with me so I could have a look? My email address is richard.hoechenberger@gmail.com

**Comment by levchenkoegor** [comment]
`README` file is empty and has 0 KB size.

Sure! I've sent an archive with the file to your email.

**Comment by hoechenberger** [comment]
The problem is related to processing cyrillic characters. I will see what I can do.

**Comment by levchenkoegor** [comment]
@hoechenberger, do you mean that somewhere in the record file cyrillic characters are?
Just not sure that they should be there - the recording and the analysis both are on English based machines.
Can you spot me to the lines where they appear? I can try to think about the solution

**Comment by hoechenberger** [comment]
@levchenkoegor Sorry, my computer is unfortunately currently malfunctioning, so I cannot really look into this before tomorrow. But I believe what needs to be changed is this (dirty hack, but let's see if it helps):

- open `E:\Egor_Levchenko\Software\Miniconda\envs\MCCA-MEG\lib\site-packages\mne_bids\utils.py`
- Go to line 175:
https://github.com/mne-tools/mne-bids/blob/9d809c88001d7b01b1aa79bcac10e26bc89c3c56/mne_bids/utils.py#L175
- Replace this with:
   ```python
       with open(fname, 'w', encoding='utf-8') as fid:
   ```
- Save
- Restart Python / Re-run your script

**Comment by hoechenberger** [comment]
> `raw_file = mne.io.read_raw_fif(str(raw_file_path)) # raw_file_path is just a direct path to MEG fif file`

But you shouldn't have to convert the Path to a string. And if you do, it's a bug in MNE-Python we should fix :)

**Comment by levchenkoegor** [comment]
@hoechenberger, Thank you!
You're right - it helped and now the file is written to the folder. I will check it on the whole dataset to be sure that everything is okay.

Yes, `str()` command is redundant - `read_raw_fif` works perfectly with Path type.

**Comment by hoechenberger** [comment]
Great! We’ll add this fix to the next release. 

Just out of curiosity, can you see any cyrillic characters in the README now?

**Comment by levchenkoegor** [comment]
I run the code for 4 different empty rooms recording. It looks strange in some places:

```
... Tavabi, K., **HР В Р’В Р Р†Р вЂљРЎС™Р В РІР‚в„ўР вЂ™Р’В¶chenberger**, R., Welke, D., Brunner, C., Rockhill, A., ...
```

You can find `README` attached.

[README.zip](https://github.com/mne-tools/mne-bids/files/5526427/README.zip)

**Comment by hoechenberger** [comment]
In `write.py` in the function `_readme()` there is a line:

`with open(fname, 'r') as fid:`

Replace it with:

`with open(fname, 'r', encoding='utf-8') as fid:`

(I'm on the phone now so typing is difficult)

**Comment by levchenkoegor** [comment]
Thank you!

You have helped me a lot!

**Comment by hoechenberger** [comment]
Thanks for reporting the issue, it’s great when users reach out to us so we can fix things 😅👌
