### ISSUE TITLE
issue when adding participants to an evolving dataset where the columns in participants.tsv changed

### ISSUE THREAD

**Issue by dnacombo** [mne-tools/mne-bids#623]
I add participants to an old dataset. 
In that dataset, the participants.tsv looked like this:
```participant_id	age	sex
sub-001	n/a	n/a
sub-002	n/a	n/a
sub-003	n/a	n/a
sub-004	n/a	n/a
sub-005	n/a	n/a
sub-008	n/a	n/a
sub-011	n/a	n/a
sub-013	n/a	n/a
sub-014	n/a	n/a
sub-015	n/a	n/a
...
```
In the new datasets, I just add more data to sub-001 and others.
Now in mne_bids/write.py, line 305, it expects a fourth column with handedness, and crashes because it can't find it.

**Comment by hoechenberger** [comment]
Thanks for reporting! We should add columns that are not existing, and fill them with n/a

**Comment by hoechenberger** [comment]
@adam2392 if you feel like it, you can work on this 😅 my computer is broken and I won't be able to take a shot until tomorrow evening or so I'm afraid!

**Comment by adam2392** [comment]
I unfortunately have a bunch of things to get done for my PI these next few weeks before Thanksgiving :(. If things free up this weekend, can take a look.

**Comment by sappelhoff** [comment]
or maybe @dnacombo wants to give it a shot himself? :wink:
