### ISSUE TITLE
BUG: Not saving MEG data if format is not .fif AND path does not exist

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#63]
https://github.com/mne-tools/mne-bids/blob/c73ce744d30be87645e1648754b488f7572307f3/mne_bids/meg_bids.py#L434-L447

This is an error that somehow passed through the tests: Checking the if-clauses, you save if:
- it's .fif or .gz
- if its any other MEG format AND the path exists AND overwrite=True

--> however, what if the format is NOT .fif/.gz and the path does not exist?

**Comment by monkeyman192** [comment]
Yeah, I do have a fix for this... I'll have to have a look at what I did and see whether I can just do it as another easy PR...

**Comment by sappelhoff** [comment]
fixed in #69
