### ISSUE TITLE
write_anat creates filenames with task entity, violating BIDS spec

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#637]
The spec only allows a limited set of entities for anatomical scans, we must follow this:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data

**Comment by sappelhoff** [comment]
perhaps a good overview: https://github.com/bids-standard/bids-specification/blob/f2545fecd646c92d4377e0620b17a07d3cd97b69/src/schema/datatypes/anat.yaml#L37-L43

**Comment by hoechenberger** [comment]
This has been closed by #641
