### ISSUE TITLE
[MAINT] remove try-except in copyfile edf

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#639]
These lines should be removed when

- [x] https://github.com/mne-tools/mne-python/pull/8558 is merged
- [ ] MNE 0.22 is released

right, @a-hurst ?

see: 

https://github.com/mne-tools/mne-bids/blob/18cc4f912495e8de8ab30d9c3077b19c923bebf4/mne_bids/copyfiles.py#L456-L478

**Comment by a-hurst** [comment]
Yep, this is correct!
