### ISSUE TITLE
write_raw_bids raises FileExistsError for coordsystem.json when processing a second task/run

### ISSUE THREAD

**Issue by kalenkovich** [mne-tools/mne-bids#656]
I am moving my data to a BIDS dataset. When I use `write_raw_bids` on a second run of any given subject, I get the following error: 

```python
FileExistsError: "E:\Evgenii_Kalenkovich\syntax_tagging\data_BIDS\auditory\sub-um0bvhu4\meg\sub-um0bvhu4_coordsystem.json" already exists. Please set overwrite to True.
```

because `coordsystem.json` had already been created when processing the first run.

I could, of course, just set overwrite to True but that does not seem like a really good idea to do this for all files. What would you do instead?

I am also confused about the reasons why `*_electrodes.json` and  `*_coordsystem.json` are not specified with the same granularity. Is `coordsystem.json` supposed to be shared between runs and tasks? If it is, shouldn't `write_raw_bids` either assume that the coordinate system is the same for all the runs after the first one or actually check if `coordsystem.json` would change if overwritten and then skip it if nothing has changed? And what if it did change? On a couple of occasions, I had to redigitize the coils between the runs leading to a change of the coordinate system.

Here is a subject's directory tree after setting overwrite to True:

```
|sub-um0bvhu4\
|--- sub-um0bvhu4_scans.tsv
|--- meg\
|------ sub-um0bvhu4_coordsystem.json
|------ sub-um0bvhu4_task-listeningToSpeech_run-01_channels.tsv
|------ sub-um0bvhu4_task-listeningToSpeech_run-01_meg.fif
|------ sub-um0bvhu4_task-listeningToSpeech_run-01_meg.json
|------ sub-um0bvhu4_task-listeningToSpeech_run-02_channels.tsv
|------ sub-um0bvhu4_task-listeningToSpeech_run-02_meg.fif
|------ sub-um0bvhu4_task-listeningToSpeech_run-02_meg.json
```

**Comment by hoechenberger** [comment]
Hi @kalenkovich,

> Is `coordsystem.json` supposed to be shared between runs and tasks?

according to [the spec](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson), yes, it's supposed to be shared, as the coordinate systems typically shouldn't change between runs within the same session.

As for [_electrodes.tsv](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv), this can be specified for each run individually.

> If it is, shouldn't `write_raw_bids` either assume that the coordinate system is the same for all the runs after the first one or actually check if `coordsystem.json` would change if overwritten and then skip it if nothing has changed?

I think a check would be good, and fail hard if there's a difference between the files, because …

> And what if it did change? On a couple of occasions, I had to redigitize the coils between the runs leading to a change of the coordinate system.

… I don't think BIDS currently specifies this. @sappelhoff might know more?

**Comment by kalenkovich** [comment]
Thanks for the explanation, @hoechenberger!

I noticed that the spec allows for different acquisitions to be specified for `coordsystem.json`. Maybe this could be hijacked to allow for multiple coordinate system files? Not sure how to keep the correspondence between the raw files and the coordinate system files in this case though.

**Comment by sappelhoff** [comment]
> … I don't think BIDS currently specifies this. @sappelhoff might know more?

yes, it was assumed that the coordinate system would not change during an experimental run. If you have arguments for why this should be allowed, opening an issue on https://github.com/bids-standard/bids-specification may be a way to trigger a discussion and a potential amendment of the spec.

> Maybe this could be hijacked to allow for multiple coordinate system files?

yes, the `acq` entity for coordsystems is intended to capture something like digitizing before and after an experiment (or similar).

**Comment by kalenkovich** [comment]
Thank you, @sappelhoff!

> > … I don't think BIDS currently specifies this. @sappelhoff might know more?
> 
> yes, it was assumed that the coordinate system would not change during an experimental run. If you have arguments for why this should be allowed, opening an issue on https://github.com/bids-standard/bids-specification may be a way to trigger a discussion and a potential amendment of the spec.

The problem is a bit different, I think: in my case, at least, the coordinate system does not indeed change during an experimental run but might change from run to run. It does not happen often but sometimes the head position coils move during the experiment and have to be re-digitized: the participant has to come out of the MEG room, some coils are re-applied and the coordinates of the fiducial points, of all the coils, and possibly of head points have to be digitized from scratch. For these cases, one coordinate system file per run would be enough but the current way of having one coordinate system file per session - would not.

> > Maybe this could be hijacked to allow for multiple coordinate system files?
> 
> yes, the `acq` entity for coordsystems is intended to capture something like digitizing before and after an experiment (or similar).

Do you think using the `acq` entity to specify the run the coordinate system corresponds to is a reasonable solution? If so, do you have any advice on how to properly store the run-acqusition correspondence?

**Comment by sappelhoff** [comment]
> Do you think using the acq entity to specify the run the coordinate system corresponds to is a reasonable solution? If so, do you have any advice on how to properly store the run-acqusition correspondence?

I guess you could "hack" the specification by doing something like `acq-Run1`, `acq-Run2`, and so forth.

I would still recommend that you open an issue with the details of your case at the bids-specification repository. Then we can discuss the implications with a broader audience and potentially improve the situation so that hacks like the one mentioned above would not be necessary.

Note that the specification is aimed to cover those data collection scenarios that occur 80% of the time well --> it seems like your scenario may be one that is a bit rare :thinking: but I may be wrong, so let's discuss it in that new issue you may open.

In any case, let me know if that `acq` hack works for you for now.

**Comment by kalenkovich** [comment]
> > Do you think using the acq entity to specify the run the coordinate system corresponds to is a reasonable solution? If so, do you have any advice on how to properly store the run-acqusition correspondence?
> 
> I guess you could "hack" the specification by doing something like `acq-Run1`, `acq-Run2`, and so forth.
> 

In my case, it would actually become `acq-TaskListeningToSpeechRun1` because I have multiple tasks. This is not a problem, of course.

> I would still recommend that you open an issue with the details of your case at the bids-specification repository. Then we can discuss the implications with a broader audience and potentially improve the situation so that hacks like the one mentioned above would not be necessary.

Will do!

> Note that the specification is aimed to cover those data collection scenarios that occur 80% of the time well --> it seems like your scenario may be one that is a bit rare  but I may be wrong, so let's discuss it in that new issue you may open.

Sure! I did not mean to sound like I was criticizing BIDS because it did not cover my quite possibly very rare case. Now that I think of it, however, it *would* be useful if there was a principled way to deviate from BIDS (maybe there is and just couldn't google it right). It is simple enough to document any deviations but ideally, any BIDS-compliant software would throw an error when it meets any kind of deviation. So, for example, when processing `run-2`, `coordsystem_acq-Run1.json` would not be loaded simply because it is the first one the software finds. I guess that for that to work there would need to be something like `deviations.json` or `schema_deviation.json` which, in principle, BIDS could specify. Just thinking out loud.
 
> In any case, let me know if that `acq` hack works for you for now.

To be honest, it might not come to that: I am not certain that the data I am working on right now contain the cases with the coordinate system changing between the runs. The current issue was originally about `mne_bids` complaining about `coordsystem.json` already existing when I am trying to process multiple runs. Right now, the warning suggests to set overwrite to True which - if followed - could theoretically lead to errors in the cases I am describing. This is why I brought the potential problems with the shared `coordsystem.json` up.

Once I figure how to work around the mne_bids hickup I will see if I need to use `acq` at all. I will make sure to let you know then.

**Comment by kalenkovich** [comment]
> > shouldn't `write_raw_bids` either assume that the coordinate system is the same for all the runs after the first one or actually check if `coordsystem.json` would change if overwritten and then skip it if nothing has changed?
> 
> I think a check would be good, and fail hard if there's a difference between the files, because …

@hoechenberger, should I try implementing such a check?

**Comment by kalenkovich** [comment]
BTW, [docs](https://mne.tools/mne-bids/stable/generated/mne_bids.write_raw_bids.html) for `write_raw_bids` incorrectly state that `coordsystem.json` is *not* shared between tasks/runs:

```
This will write the following files in the correct subfolder root:

sub-01_ses-01_task-testing_acq-01_run-01_meg.fif
sub-01_ses-01_task-testing_acq-01_run-01_meg.json
sub-01_ses-01_task-testing_acq-01_run-01_channels.tsv
sub-01_ses-01_task-testing_acq-01_run-01_coordsystem.json

```
