### ISSUE TITLE
Unable to convert EDF -> BV anymore?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#659]
#### Describe the bug
I was doing another conversion again for EDF source iEEG files, and I noticed that I can't convert to BV anymore, even if I pass back anonymization daysback. 

In the BIDs spec, it is said that ~~BV~~ BV and EDF are the RECOMMENDED format for iEEG data.

Is this intended behavior? I built a lot of func that required me to assume that data was stored in BV. Wiil it be possible to add a `convert` kwarg to `write_raw_bids` that converts the said dataset into the `RECOMMENDED` format?

**Comment by hoechenberger** [comment]
Is this because of #636?

**Comment by adam2392** [comment]
> Is this because of #636?

Just took a look, and yes I believe so due to these lines: 

https://github.com/a-hurst/mne-bids/blob/4b65b40911b092026ebb39dc1f9d0cd5b4f8fd76/mne_bids/write.py#L1116-L1122

**Comment by adam2392** [comment]
WDYT, is it okay to support "converting to RECOMMENDED" formats?

**Comment by hoechenberger** [comment]
Yes I think there should be a switch / parameter to toggle this…

@sappelhoff @agramfort @jasmainak WDYT?

**Comment by sappelhoff** [comment]
yes, a switch to toggle conversion if it's wanted could be nice for some users.

**Comment by jasmainak** [comment]
fine by me!

**Comment by adam2392** [comment]
> WDYT, is it okay to support "converting to RECOMMENDED" formats?

Sorry, just re-read the specification, and I suppose EDF and BV are both "RECOMMENDED" formats for iEEG. However, it still brings up an issue because I was pretty used to working w/ BV files, and ideally would like to stick w/ that.

If we wanted to "convert" files from EDF -> BV like this, would it be best to add a kwarg to `write_raw_bids`, or add another function for converting data files? For example:

```Python
def convert_datafile(bids_path, to_format='.vhdr'):
   # convert say EDF to .vhdr and then delete the EDF file
```

**Comment by hoechenberger** [comment]
> If we wanted to "convert" files from EDF -> BV like this, would it be best to add a kwarg to `write_raw_bids`, or add another function for converting data files?

Depends on what you want to do… convert an existing file, no matter whether it's in a BIDS folder structure, and write it anywhere? Store it as BIDS? Or take an existing BIDS dataset and convert it to another BIDS dataset with a different format?

**Comment by sappelhoff** [comment]
> If we wanted to "convert" files from EDF -> BV like this, would it be best to add a kwarg to write_raw_bids

I think a `convert_to={'BrainVision}` parameter would be best ... and the value could also be `fif` for MEG data 🤷 


>  I suppose EDF and BV are both "RECOMMENDED" formats for iEEG. However, it still brings up an issue because I was pretty used to working w/ BV files, and ideally would like to stick w/ that.


Personally I think that BrainVision is superior to EDF because we can have data as float32, because the header and marker files are human readable, because dates can be properly anonymized, etc. etc. --> so I totally get why you'd want to ditch EDF

**Comment by adam2392** [comment]
> I think a `convert_to={'BrainVision}` parameter would be best ... and the value could also be `fif` for MEG data 🤷

Okay PR coming in... Dam I wish I caught this before 0.6 :p  

> Personally I think that BrainVision is superior to EDF because we can have data as float32, because the header and marker files are human readable, because dates can be properly anonymized, etc. etc. --> so I totally get why you'd want to ditch EDF
 :)

**Comment by sappelhoff** [comment]
> Okay PR coming in... Dam I wish I caught this before 0.6 :p

wait a second with the PR until we have heard more people's opinions :-)

**Comment by adam2392** [comment]
Any other thoughts before implementation of a kwarg `convert_to`?

@hoechenberger @jasmainak @agramfort

**Comment by jasmainak** [comment]
> I built a lot of func that required me to assume that data was stored in BV

I'm wondering what kind functionality requires this kind of knowledge? Once you read a file in MNE, it's the same whether you start from BV or from EDF

**Comment by adam2392** [comment]
> I'm wondering what kind functionality requires this kind of knowledge? Once you read a file in MNE, it's the same whether you start from BV or from EDF

I do some custom mods of the header info on the vhdr file that isn't encompassed into mne. 

In addition, For me things are just generally easier having everything in BrainVision because of the benefits @sappelhoff pointed out.

**Comment by jasmainak** [comment]
no strong opinions. I let @sappelhoff and @hoechenberger decide

**Comment by adam2392** [comment]
The proposal for this would be:

```Python
def write_raw_bids(raw, bids_path, events_data=None,
                   event_id=None, anonymize=None, convert_to=None,
                   overwrite=False, verbose=True):
"""
...
    convert_to : str | None
        If `None` (default), there is no explicit change in how the file is
        converted to BIDS. If a str, then will accept RECOMMENDED
        BIDS file formats. For example, EEG and iEEG RECOMMENDED formats
        are ``BrainVision`` and ``European Data Format``. If ``'BrainVision'``
        is passed in, then file will be forced to be converted to the 
        ``BrainVision`` file format. For MEG, this could be ``FIF``.
"""
...
# check that convert_to is acceptable given datatype
...
# rewrite convert logic to force convert data to BrainVision
```

**Comment by sappelhoff** [comment]
LGTM, but I would be explicit in what arguments are allowed. Sentences like "For MEG, this could be FIF" are difficult to interpret. It's better to say (with some more words than I use now):

This is allowed:
- for EEG/iEEG --> BrainVision
- for MEG --> FIF

**Comment by agramfort** [comment]
I would actually propose to do:

```Python
def write_raw_bids(raw, bids_path, events_data=None,
                   event_id=None, anonymize=None, format='auto',
                   overwrite=False, verbose=True):
"""
...
    format : 'auto' | 'BrainVision' | 'EDF' | 'FIF'
        If `'auto'` (default), there is no explicit change in how the file is
        converted to BIDS. The native format is used. If a str, then will accept RECOMMENDED
        BIDS file formats. For example, EEG and iEEG RECOMMENDED formats
        are ``BrainVision`` and ``EDF``. If ``'BrainVision'``
        is passed in, then file will be forced to be converted to the 
        ``BrainVision`` file format. For MEG, this could be ``FIF``.
"""
...
# check that convert_to is acceptable given datatype
...
# rewrite convert logic to force convert data to BrainVision
```

**Comment by adam2392** [comment]
> I would actually propose to do:
> 
> ```python
> def write_raw_bids(raw, bids_path, events_data=None,
>                    event_id=None, anonymize=None, format='auto',
>                    overwrite=False, verbose=True):
> """
> ...
>     format : 'auto' | 'BrainVision' | 'EDF' | 'FIF'
>         If `'auto'` (default), there is no explicit change in how the file is
>         converted to BIDS. The native format is used. If a str, then will accept RECOMMENDED
>         BIDS file formats. For example, EEG and iEEG RECOMMENDED formats
>         are ``BrainVision`` and ``EDF``. If ``'BrainVision'``
>         is passed in, then file will be forced to be converted to the 
>         ``BrainVision`` file format. For MEG, this could be ``FIF``.
> """
> ...
> # check that convert_to is acceptable given datatype
> ...
> # rewrite convert logic to force convert data to BrainVision
> ```

Like this soln. seems most explicit. 

Only thing is, I might exclude EDF since we don't have a robust edf writer to my knowledge.
