### ISSUE TITLE
Import error in make_bids_basename

### ISSUE THREAD

**Issue by pchholak** [mne-tools/mne-bids#661]
Command: from mne_bids import read_raw_bids, make_bids_basename
Error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-0c9d52c6dabf> in <module>
----> 1 from mne_bids import read_raw_bids, make_bids_basename

ImportError: cannot import name 'make_bids_basename' from 'mne_bids' (/Users/rob/anaconda3/envs/mne/lib/python3.8/site-packages/mne_bids/__init__.py)

========================================================
Please note that the same command is not stopping from importing 'read_raw_bids'
Also, the command 'import mne_bids' works without any error.

**Comment by hoechenberger** [comment]
Hello @pchholak, this is expected behavior, as `make_bids_basename` was removed in MNE-BIDS 0.5.

Please see the [Quick-Start Guide ](https://mne.tools/mne-bids/stable/use.html#quickstart) for info on how to use the name `BIDSPath`.

**Comment by pchholak** [comment]
Thanks, Richard!

**Comment by hoechenberger** [comment]
@pchholak Actually there's a mistake in the example in the quickstart guide: `BIDSPath` doesn't accept a `bids_root` parameter – this should be `root`.
