### ISSUE TITLE
Documentation bug in quickstart guide

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#663]
@pchholak Actually there's a mistake in the example in the quickstart guide: `BIDSPath` doesn't accept a `bids_root` parameter – this should be `root`.

_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-bids/issues/661#issuecomment-747440629_

**Comment by adam2392** [comment]
@hoechenberger 

I can fix this really quick. Any chance at releasing 0.7 as a quick fix after that regarding anonymization of EDF files / `format='BrainVision'` feature?

**Comment by hoechenberger** [comment]
We can make another release soon, alright. But we should fix #656 and #662 first

**Comment by sappelhoff** [comment]
> We can make another release soon, alright. But we should fix #656 and #662 first

there'll also be a BIDS release soon, and there are two issues that may impact MNE-BIDS as well (in terms of features)

- potentially EEGLAB as a keyword for coordsystems https://github.com/bids-standard/bids-specification/issues/701
- potentially all MEG coordsystems also valid for EEG if recorded simultaneouslyhttps://github.com/bids-standard/bids-specification/pull/700
- some other stuff with coordsystems https://github.com/bids-standard/bids-specification/pull/700

but of course that could also be included in mne-bids 0.8 ...

**Comment by hoechenberger** [comment]
> there'll also be a BIDS release soon, and there are two issues that may impact MNE-BIDS as well (in terms of features)

Thanks @sappelhoff! I was aware of the EEGLAB change but not of the others changes.

Any gut feeling when the new BIDS release will be due?

**Comment by sappelhoff** [comment]
> Any gut feeling when the new BIDS release will be due?

yes, we'll try to release 1.5.0 within the next two weeks to integrate the ASL (arterial spin labelling) and qMRI extensions ... but these won't impact mne-bids as far as I can tell.

Then we'll be working hard on integrating PET as a 1.6 release ... hopefully a maximum of 1 to 2 months later.

But the coordsystem PR and other "smaller" things that may impact mne-bids more will be integrated in these larger releases.

**Comment by hoechenberger** [comment]
I would say, then, we just proceed with MNE-BIDS at normal speed and fix the issues that were mentioned, and we'll decide ad-hoc whether it's worth supporting new BIDS features (if they've been released at that time) or whether we should simply schedule their support for the release after that. I don't think it's super important to support all BIDS changes within a few days or even weeks…

**Comment by sappelhoff** [comment]
agreed :-)

**Comment by adam2392** [comment]
> > We can make another release soon, alright. But we should fix #656 and #662 first
> 
> there'll also be a BIDS release soon, and there are two issues that may impact MNE-BIDS as well (in terms of features)
> 
> * potentially EEGLAB as a keyword for coordsystems [bids-standard/bids-specification#701](https://github.com/bids-standard/bids-specification/issues/701)
> * potentially all MEG coordsystems also valid for EEG if recorded simultaneouslyhttps://github.com/[bids-standard/bids-specification/pull/700](https://github.com/bids-standard/bids-specification/pull/700)
> * some other stuff with coordsystems [bids-standard/bids-specification#700](https://github.com/bids-standard/bids-specification/pull/700)
> 
> but of course that could also be included in mne-bids 0.8 ...

Yeah I think overall there is a bit of "cleanup" work to do to support multiple coordsystems/electrodes json/tsv files. Even those can theoretically exist, I'm in favor of pushing that off for 0.8, since that's a very corner-case. 

I've had one subject where i wanted to store multiple copies of the electrode coordinates, but didn't need to use mne-bids in that one.

For these 3 main issues @hoechenberger pointed out, looks like a quick and easy fix, so I submitted a PR #675.
