### ISSUE TITLE
Error on BrainVision(?) Writing For Channels That Are not in Volts

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#664]
#### Describe the bug
I'm using mne-bids 0.5 and I got this error:

```
RuntimeError: Conversion to BrainVision format needed to be stopped, because your raw data contains channel types that are not represented in Volts: "{'DC16', 'DC08', 'DC05', 'DC09', 'E', 'DC10', 'DC15', 'DC12', 'DC02', 'DC11', 'DC04', '$TP10', 'DC06', 'DC14', '$TP9', 'DC07', 'DC13', 'DC03', 'DC01'}"
E           
E           Until BrainVision format conversion is improved, you must drop these channels from your raw data before using mne-bids. Please contact the mne-bids team about this.
```

I just wanted to clarify: Can I just simply convert these channels to `misc` and the problem go away, or I must drop channels? What is the intended fix here?

Sorry I haven't been following all issues well, so this might've been discussed, but I have no idea what's going on here since it used to work 1 week ago.

#### Additional information
〈Replace this text with information about your system. For example through
using MNE-Python and running `mne.sys_info()` and pasting the output here.〉

**Comment by hoechenberger** [comment]
Is this still the case with 0.6?

**Comment by sappelhoff** [comment]
the big underlying issue that needs to be solved is https://github.com/bids-standard/pybv/issues/50

however if your channel types **are** in fact in Volts but MNE somehow doesn't encode this, then you may be able to work around that.

**Comment by adam2392** [comment]
Yes it still comes up w/ 0.6. For those `DC01,...` channels, i've been setting them to `misc` channel type. I couldn't find that much information on channel types and don't see any way of labeling these as "reference" channels :(.

**Comment by adam2392** [comment]
Now that pybv PR is merged, I can work on this.

I have a few questions was hoping you mne-pros can help out with. How do we map the `unit` in `info['chs']` to an actual string?

In https://mne.tools/dev/generated/mne.Info.html, I see that each channel has a unit specified that is an int. This int is specified in the `FIFF` constants. Rather then creating a long if/else statement manually mapping each unit to its corresponding mne string, is there already a function for doing so? 

Once I know how to do the above, I think a short modification to `_write_raw_brainvision` will suffice.

**Comment by sappelhoff** [comment]
here we go: https://pypi.org/project/pybv/0.5.0/
