### ISSUE TITLE
Triux SYS or mne syst channel chrashes 

### ISSUE THREAD

**Issue by ancpJR** [mne-tools/mne-bids#668]
Dear developer team,

First of all let me thank you for your great tool.

#### Bug description
When I tried to convert a Triux *.fif-file with mne-bids 0.6 to the BIDS format the function chrashes with "KeyError: 'syst'". A call stack is provided below.

The problem seems to be that the SYS channel of the Triux systems is not handled. Reading the file with mne.io.read_raw_fif recognizes the SYS-channel and adds a channel with attribute 'syst' to the raw.info['chs'] object. However, this channel type is not defined in the mne to BIDS mapping dictionary in function _get_ch_type_mapping in utils.py. Therefore, function _channels_tsv chrashes in line 110 of write.py

I suggest to either 1) add a mapping 'syst='OTHER' to  the mapping dictionary from mne to bids in _get_ch_type_mapping in utils.py or 2) make the mapping _channels_tsv in write.py more resilient against missing channels. 

I briefly tested the option 1). It seems to prevent the crash and the data written in BIDS can be read back using read_raw_bids. 

Regards, 
     Jochem

#### Steps to reproduce
Writing 'noisetests-bids/participants.tsv'...

participant_id	age	sex	hand
sub-emptyroom	2	M	R

Writing 'noisetests-bids/participants.json'...

{
    "participant_id": {
        "Description": "Unique participant identifier"
    },
    "age": {
        "Description": "Age of the participant at time of testing",
        "Units": "years"
    },
    "sex": {
        "Description": "Biological sex of the participant",
        "Levels": {
            "F": "female",
            "M": "male"
        }
    },
    "hand": {
        "Description": "Handedness of the participant",
        "Levels": {
            "R": "right",
            "L": "left",
            "A": "ambidextrous"
        }
    }
}
Writing of electrodes.tsv is not supported for data type "meg". Skipping ...
<ipython-input-11-4167cf9e7ed0>:16: RuntimeWarning: This filename (noisetests/20180519/empty_IASoff_68.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz or _meg.fif
  er_raw = mne.io.read_raw_fif(er_raw_fname)
<ipython-input-11-4167cf9e7ed0>:27: RuntimeWarning: This filename (noisetests/20180519/empty_IASoff_68.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz or _meg.fif
  write_raw_bids(er_raw, er_bids_path, overwrite=True)

Writing 'noisetests-bids/dataset_description.json'...

{
    "Name": " ",
    "BIDSVersion": "1.4.0",
    "DatasetType": "raw",
    "Authors": [
        "Please cite MNE-BIDS in your publication before removing this (citations in README)"
    ]
}

Writing 'noisetests-bids/sub-emptyroom/ses-20180605/meg/sub-emptyroom_ses-20180605_task-noise_meg.json'...

{
    "TaskName": "noise",
    "Manufacturer": "Elekta",
    "PowerLineFrequency": 50,
    "SamplingFrequency": 1000.0,
    "SoftwareFilters": "n/a",
    "RecordingDuration": 301.999,
    "RecordingType": "continuous",
    "DewarPosition": "n/a",
    "DigitizedLandmarks": false,
    "DigitizedHeadPoints": false,
    "MEGChannelCount": 306,
    "MEGREFChannelCount": 0,
    "EEGChannelCount": 0,
    "EOGChannelCount": 0,
    "ECGChannelCount": 0,
    "EMGChannelCount": 0,
    "MiscChannelCount": 0,
    "TriggerChannelCount": 1
}
Traceback (most recent call last):

  File "<ipython-input-11-4167cf9e7ed0>", line 27, in <module>
    write_raw_bids(er_raw, er_bids_path, overwrite=True)

  File "mne2/lib/python3.9/site-packages/mne_bids/write.py", line 1241, in write_raw_bids
    _channels_tsv(raw, channels_path.fpath, overwrite, verbose)

  File "mne2/lib/python3.9/site-packages/mne_bids/write.py", line 110, in _channels_tsv
    ch_type.append(map_chs[_channel_type])

KeyError: 'syst'

#### Additional information
mne.sys_info()
Platform:      Linux
Python:        3.9.1 | packaged by conda-forge | (default, Dec 21 2020, 22:08:58)  [GCC 9.3.0]
Executable:   mne2/bin/python
CPU:           x86_64: 8 cores
Memory:        15.4 GB

mne:           0.22.0
numpy:         1.19.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:         1.5.3
matplotlib:    3.3.3 {backend=Qt5Agg}

sklearn:       0.24.0
numba:         Not found
nibabel:       3.2.1
nilearn:       0.7.0
dipy:          1.3.0
cupy:          Not found
pandas:        1.1.5
mayavi:        4.7.2
pyvista:       0.27.4 {pyvistaqt=0.2.0, OpenGL 4.5.0 NVIDIA }
vtk:           9.0.1
PyQt5:         5.12.3

**Comment by hoechenberger** [comment]
Hello @ancpJR, thanks for the report! This issue is already being tracked at #666. We were having a little difficulty understanding what **exactly** the `syst` channel encodes… maybe you could comment on #666 to help us?

Closing, as we should discuss this in #666
