### ISSUE TITLE
MNE Forum

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#671]
Hello all,

we're (MNE-Python folks) starting to switch all our user support & discussions over to our shiny new Discourse forum, https://mne.discourse.group/

It would make **total** sense to also direct MNE-BIDS usage questions there. Also I'd like to encourage all interested parties, esp. developers, to join us in the forum to help create a friendly, welcoming, but also knowledgeable space 👍 

We should also consider adding a link to the forum to our docs.

cc @adam2392 @sappelhoff @alexrockhill

**Comment by sappelhoff** [comment]
cool :-) 

:+1: on that. And we can replace our gitter badge with a discourse badge.

**Comment by agramfort** [comment]
yes let's remove our refs to gittter

>
