### ISSUE TITLE
How to deal with datasets that don't come with events.tsv, but have events saved as part of the raw data?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#683]
[ds000246](https://openneuro.org/datasets/ds000246/versions/00001) doesn't ship with `*_events.tsv`. Yet, we've managed to successfully process it for months using the `mne-study-template`. Turns out the dataset has events stored in the raw data (as annotations, I believe), so when reading the data using MNE-BIDS, we do get access to those events, even though the BIDS sidecars do not expose any.

I believe this should not happen: annotations & events should be constructed based on the sidecar information alone. When reading a file, we should call `raw.set_annotations(None)` early on, so that if no `*_events.tsv` is present, we'd end up without any Annotations. Otherwise we risk leading our users to believe they're dealing with BIDS-compliant data when in fact the only reason they're getting access to events is due to implementation details in MNE and MNE-BIDS.

Thoughts?

cc @agramfort @sappelhoff @adam2392 @jasmainak

**Comment by sappelhoff** [comment]
I agree, if data is read via read_raw_bids, the bids-sidecar files should determine the events, not what's in the raw files. Everything else feels like a user is conveniently "hacking" BIDS by storing their events in the FIFF file, not bothering about BIDS recommendations.

**Comment by agramfort** [comment]
Robert already pointed the problem on openneuro a year ago. Guio need to fix it

**Comment by jasmainak** [comment]
I think this is a validation issue. MNE-BIDS should throw an error if a dataset is not BIDS compatible?

We could vendor the Python version of bids-validator: https://github.com/bids-standard/bids-validator/blob/master/bids-validator/bids_validator/bids_validator.py. It's just one file

**Comment by sappelhoff** [comment]
> We could vendor the Python version of bids-validator

Unfortunately that's not a fully featured validator, it can only tell you if a filename is bids compliant or not :(

Apart from that, it also needs the full "rules" directory with the regexps, so it's more than a file

**Comment by hoechenberger** [comment]
> MNE-BIDS should throw an error if a dataset is not BIDS compatible?

I'd been thinking about that in the past, but the problem is that the validator is written in JS and requires Node to run. While it would be entirely possible to integrate MNE-BIDS with the validator, it would complicate installation for our users. No issues as long as they're on `conda-forge`, but complicated it they want to install via `pip` from PyPI…

**Comment by jasmainak** [comment]
> it can only tell you if a filename is bids compliant or not 

is there any reason it has not been developed further? Could we copy the code and use it for our purposes? I think Python validation is wayyyyyyy easier than JS

**Comment by sappelhoff** [comment]
> is there any reason it has not been developed further? Could we copy the code and use it for our purposes? I think Python validation is wayyyyyyy easier than JS

perhaps @effigies can help me here, but I think the python version of the validator was initially developed as part of pybids ... and for some reason (?) no additional features beyond the `"tell me if this out-of-context file name is BIDS compatible"` are needed.

having that said, there is one issue about extending the python bids validator:

- https://github.com/bids-standard/bids-validator/issues/911

and there is one on bringing the complete validator to conda. But that one is stale. @rwblair tried to make it happen but ran into some problems that I don't know the details of.

- https://github.com/bids-standard/bids-validator/issues/780

Finally, about

> Could we copy the code and use it for our purposes?

yes we could, it's MIT licensed :-)

**Comment by hoechenberger** [comment]
> and there is one on bringing the complete validator to conda. But that one is stale.

This should actually be easy to do.



> I think Python validation is wayyyyyyy easier than JS

In the end it's just an application that users need to run… the only critical point is distribution. And the advantage of the JS validator, of course, is that you can run it in the browser too. I don't think having to maintain **two** validators -- one in Python, one in JS -- is going to help the BIDS cause, as development resources are already scarce :(

**Comment by sappelhoff** [comment]
> This should actually be easy to do.

do you want to give it a try @hoechenberger ? --> https://github.com/conda-forge/staged-recipes/pull/9771

**Comment by hoechenberger** [comment]
Yeah well I'd rather start from scratch.. and not before this weekend, quite busy currently!

**Comment by jasmainak** [comment]
> I don't think having to maintain two validators -- one in Python, one in JS -- is going to help the BIDS cause, as development resources are already scarce :(

I agree about this. But JS validator will always have gaps because there is no IO for MEG/EEG files although some crazy person did write a nifti library :) Alternative is to copy the code only for mne-bids purposes and not advertise it as a validator of any sort but use it only for input validation. I'm imagining a `_validator.py` file that's not accessible by the user or public API.

**Comment by hoechenberger** [comment]
> Alternative is to copy the code only for mne-bids purposes and not advertise it as a validator of any sort but use it only for input validation. I'm imagining a `_validator.py` file that's not accessible by the user or public API.

Could you elaborate? I don't really understand what you're proposing here :) Are you saying we should stick with the JS validator, and add some kind of interface code to MNE-BIDS so it can call the validator? But what would we do if the validator is not installed?

**Comment by jasmainak** [comment]
No, I'm saying ... copy the Python validator code and repurpose it for input validation in MNE-BIDS. I don't think we should support data that are clearly not BIDS compliant, right?

**Comment by hoechenberger** [comment]
> I don't think we should support data that are clearly not BIDS compliant, right?

Question is what BIDS version we're talking about 😅 There's lots of data out there which apparently used to be compliant sometime back and is not really following the latest specs anymore.



> copy the Python validator code and repurpose it for input validation in MNE-BIDS.

Ok, got it. Yes we could do that, we'd just need to ensure to update the schemas regularly.

**Comment by jasmainak** [comment]
> There's lots of data out there which apparently used to be compliant sometime back and is not really following the latest specs anymore.

Was it? I think part of the problem 

is that folks have been hacking the specification by using "bidsignore". See my complaints on the BIDS-specification github :)

> we'd just need to ensure to update the schemas regularly.

agreed!

**Comment by hoechenberger** [comment]
> > There's lots of data out there which apparently used to be compliant sometime back and is not really following the latest specs anymore.
> 
> Was it? I think part of the problem is that folks have been hacking the specification by using "bidsignore". See my complaints on the BIDS-specification github :)
> 
> >

Hm yeah or maybe this, and insufficient validation :)

**Comment by adam2392** [comment]
Sorry late to the party.

> I believe this should not happen: annotations & events should be constructed based on the sidecar information alone. When reading a file, we should call `raw.set_annotations(None)` early on, so that if no `*_events.tsv` is present, we'd end up without any Annotations. Otherwise we risk leading our users to believe they're dealing with BIDS-compliant data when in fact the only reason they're getting access to events is due to implementation details in MNE and MNE-BIDS.

Agreed. +1.

> I think this is a validation issue. MNE-BIDS should throw an error if a dataset is not BIDS compatible?

From my exp with the validator, it's still quite a bit behind the spec (regardless of js vs python), so downstream, I could see functional tests say.. using a validator, but for now it would have to be discussions like these that decide "let's not read in events from the raw file", which leads to errors.

**Comment by hoechenberger** [comment]
I also wonder what and when exactly we intend to validate. As in, should we validate the entire BIDS root upon each MNE-BIDS action? This would be crazy… Esp since access time for NAS are horribly slow, so parsing an entire directory tree for a large dataset may take seconds or even tens of seconds, no?

**Comment by adam2392** [comment]
> I also wonder what and when exactly we intend to validate. As in, should we validate the entire BIDS root upon each MNE-BIDS action? This would be crazy… Esp since access time for NAS is horribly slow, so parsing an entire directory tree for a large dataset may take seconds or even tens of seconds, no?

I wonder if there's a way we can include a time-stamp into the `dataset_description.json` of the last validation run (version of validator, timestamp,e tc.)? This can potentially alleviate that issue. 

E.g. don't run validator, if it's been run?

**Comment by hoechenberger** [comment]
But how do you decide when to run the validation again? If the time stamp is more than 2 minutes old? 1 day? 5 weeks? I don't think this is going to help is much… we'd need some kind of checksum and this will not be feasible, I'm afraid.

**Comment by sappelhoff** [comment]
>  insufficient validation :)

yes, in two ways:
1. having too many optional or recommended fields that could have been mandatory
2. lagging behind with validating everything that could be meaningfully validated (this is an issue of having too few contributors to bids-validator)

**Comment by sappelhoff** [comment]
the discussion is currently swaying away from bids-validating in python, but I wanted to make one more point

>  Ok, got it. Yes we could do that, we'd just need to ensure to update the schemas regularly.

the [JSON schemas](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/validators/json/schemas) and the [reg-exps](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/bids_validator/rules) are more or less the "core" of the BIDS validator (IMHO), and these could easily be turned into their own repos, and included in all validators as git submodules, thus being easily updated.

**Comment by hoechenberger** [comment]
> the [JSON schemas](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/validators/json/schemas) and the [reg-exps](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/bids_validator/rules) are more or less the "core" of the BIDS validator (IMHO), and these could easily be turned into their own repos, and included in all validators as git submodules, thus being easily updated.

I think they should go to https://github.com/bids-standard/bids-schema and this should be released to regularly so one can easily depend on it…

**Comment by effigies** [comment]
Beefing up the python validator would definitely be great, but if you're looking for the simplest intervention that might prompt users to check their data before posting a bug, you can patch the exception hook so that you can print a message after any exception. Example:

```Python
import sys
_sys_excepthook = sys.excepthook

def _checkbids_excepthook(type, value, tb):
    import traceback

    traceback.print_exception(type, value, tb)
    print("\nPlease verify that your data is formatted according to BIDS.")

def patch_excepthook():
    sys.excepthook = _checkbids_excepthook

def unpatch_excepthook():
    sys.excepthook = _sys.excepthook
```

You could even make it a context manager so that only places where BIDS-related issues could plausibly arise get the message.

```Python
import contextlib

@contextlib.contextmanager
def warn_about_bids():
    import sys
    old_excepthook = sys.excepthook
    sys.excepthook = _checkbids_excepthook
    yield  # contents of "with" block happen here
    sys.excepthook = old_excepthook

with warn_about_bids():
    # Read from dataset
```

Since this seems to be more of a toolbox than an end-user app, you could use these within your functions and also provide them to users so they can choose when to set them.

**Comment by hoechenberger** [comment]
Hello @effigies, thanks for your suggestion! However, I don't think this is what we want – we're doing **lots** of stuff in MNE-BIDS, and only **some** of the exception we'll encounter will be due to a dataset not conforming to BIDS, which we try to handle gracefully. In fact, I believe most exceptions will simply be caused by plain bugs ;) Asking them to verify your data puts us (and them) back to square one: needing to run some sort of validator. This is the part that needs to be so easy that it becomes a no-brainer…

**Comment by jasmainak** [comment]
again -- I don't suggest a full validation but mostly to leverage the regular expressions and schemas to use them for checks in certain functions for subsets of files. E.g., if the user wants to read in a raw file, we should check that the events file is present and in BIDS naming format. And the rest is just a matter of organization. Having such checks in one file `_validator.py` will help keeping things consolidated and might develop into something more concrete down the line. But that's not what I'm suggesting right now :)

**Comment by hoechenberger** [comment]
I'm closing this for now, as it's unclear how to proceed here. It seems we will want to think about ways to add a bit of validation in the future, but this should probably be addressed in a separate, more specifically phrased issue. (Please feel free to reopen, though, if you believe this shouldn't be closed)
