### ISSUE TITLE
0.7 release sometime?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#686]
Hi,

Wanted to ask if there were any other low-hanging issues to tackle before 0.7 release? Just wanted to integrate the latest changes in some CI of mine that depends on the EDF -> BV being done correctly.

Linked discussion: https://github.com/mne-tools/mne-bids/issues/663

**Comment by sappelhoff** [comment]
apart from #676  and #677 I don't see low hanging issues, and these are your own even :)

just out of curiosity: why do you need a release? do you want to publish code and pin all versions before?

You can also pip install mne-bids from GitHub, pinning at an exact commit:

`pip install git+git://github.com/mne-tools/mne-bids.git@19efb4f2324319c665b17197fc5a0757b37fa029`

**Comment by hoechenberger** [comment]
@adam2392 I can cut a release this weekend. Whichever changes we manage to squeeze in until then will be part of the release :)

@sappelhoff I think we have some important bug fixes in `master` already that are worth shipping to our users :)

**Comment by hoechenberger** [comment]
I'd like to make a release tomorrow or Sunday, do you believe there are any blockers?

@sappelhoff @agramfort @adam2392

**Comment by adam2392** [comment]
Sounds good to me! Some low-hanging fruit: https://github.com/mne-tools/mne-bids/pull/717 that I'll try to finish asap.

I do need to fix this finnicky RST file :(

**Comment by sappelhoff** [comment]
good from my side :+1:

**Comment by adam2392** [comment]
Once #729 is merged, all good to go from me.

Can probably figure out the `BIDSPath.fpath` stuff in 0.8?

**Comment by hoechenberger** [comment]
Release is on PyPI.
