### ISSUE TITLE
events.tsv with same trial_type, but different value

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#687]
I have some `events.tsv` files that look like this:

```
onset    	duration 	sample 	trial_type 	stim_file 	value
9.6211   	0.0      	9853   	response   	n/a       	202
15.1250  	0.0      	15489  	response   	n/a       	202
19.4121  	0.2      	19879  	stimulus   	n/a       	11
19.8926  	0.0      	20371  	response   	n/a       	201
20.8623  	0.2      	21364  	stimulus   	n/a       	12
21.3164  	0.0      	21829  	response   	n/a       	201
22.3779  	0.2      	22916  	stimulus   	n/a       	14
22.7969  	0.0      	23345  	response   	n/a       	201
```
As you can see, the `response` `trial_type` can either be associated with a `201` (correct) or `202` (incorrect) value.

When this file is read by MNE-BIDS, the distinction between the two types of response disappears, as we ignore the `value` column if we find a `trial_type` column.

There's a similar pattern for the `stimulus` trial type.

I would propose that in the case where we find that the `trial_type` <> `value` mapping is not unique, we create hierarchical event names composed of both fields, i.e. in this specific case, `response/201` and `response/202`.
Also we should make it easy for users to rename the events on the BIDS level.

Thoughts?

cc @sappelhoff @adam2392 @jasmainak @agramfort

**Comment by hoechenberger** [comment]
The BIDS specification, by the way, is IMHO **very** lenient regarding the `trial_type` column and encourages the behavior we see above:

> `trial_type` Primary categorisation of each trial to identify them as instances of the experimental conditions. For example: for a response inhibition task, it could take on values "go" and "no-go" to refer to response initiation and response inhibition experimental conditions.

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html

**Comment by agramfort** [comment]
great idea !

>

**Comment by sappelhoff** [comment]
I like the idea - and please go ahead and make a PR to bids-specification if you have a clarification to make there. Smaller PRs usually go through easily.
