### ISSUE TITLE
scans.tsv for split files

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-bids#692]
Hi, 
I was running the bids-validator on my data and stumbled upon a BIDS-incompatibility. The information in the `scans.tsv` does not match with the actual scans present in the directory, when the  scans consist of split files. To illustrate, Ihere is the `scans.tsv` file:
~~~
filename	                                        acq_time
meg/sub-01_ses-02_task-ml_meg.fif	                2020-10-23T12:20:27
meg/sub-01_ses-02_task-rdm_meg.fif	                2020-10-23T11:25:01
meg/sub-01_ses-02_task-restingstate_meg.fif	        2020-10-23T10:30:32
meg/sub-01_ses-02_task-vbm_meg.fif	                2020-10-23T10:49:34
~~~

 and a screenshot of the corresponding directory:
![image](https://user-images.githubusercontent.com/8819465/106287432-10dc3880-6247-11eb-9b55-255eb5e358e6.png)

For all the split files, the bids-validator had following issue: 
~~~
Error 2: [Code 129] SCANS_FILENAME_NOT_MATCH_DATASET
The filename in scans.tsv file does not match what is present in the BIDS dataset.
~~~

Not sure whether this is or the bids-validator-repo would be the place to report this. If more appropriate there, I could move the issue. 

Thanks

**Comment by hoechenberger** [comment]
Thanks for the report! This is an interesting edge case indeed. @sappelhoff do you know whether the spec defines what to do in a situation like this? Otherwise I can have a look myself later

**Comment by sappelhoff** [comment]
Thanks for raising this issue @eort I think this is a good place to discuss it.

I guess we never discussed whether split parts of a scan are to be considered "one scan", or "multiple scans" --> I cannot find anything about this in the specification ... but the validator apparently expects each "split" that is in the data to also be listed in scans.tsv --> wheres in MNE-BIDS we go the other way (split parts are still one scan, so only one scan is listed)

Overall I think it would be *easier* to consider each split part a separate scan file ... i.e., adjust MNE-BIDS ... it may also be a better overview for someone inspecting the scans.tsv.

However, I can also see it the other way around ... it's sensible to think of the split parts as *one single scan*.

Either way, there are these options:
1. fix mne-bids to comply with the validator and move on with our lives
2. start a discussion on the bids-specification repo which road we wanna go (A or B), and then:
    3. update the specification
    4. update EITHER validator or mne-bids


links to the parts in the spec:

- https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#split-files
- https://bids-specification.readthedocs.io/en/latest/99-appendices/09-entities.html#split

**Comment by hoechenberger** [comment]
> * fix mne-bids to comply with the validator and move on with our lives

I think that's the best approach for now. Looking at `scants.tsv` will always easily reveal whether a file listed there is actually a "complete" scan or simply a partial scan (split file), as the split file naming is standardized.

**Comment by eort** [comment]
I agree. Also, the split scans will have the same `acq-time`, right?

**Comment by sappelhoff** [comment]
> I agree. Also, the split scans will have the same acq-time, right?

I would make that a requirement, *all* metadata should be the same, except that in the name, they have `split-<index>`

**Comment by sappelhoff** [comment]
@eort do you want to raise an issue about this in the BIDS specification repo? https://github.com/bids-standard/bids-specification/

We should clarify the spec with what we agreed on here. (And get feedback from others, who may or may not think differently)

**Comment by eort** [comment]
> @eort do you want to raise an issue about this in the BIDS specification repo? 
Will do.

But to be clear, the plan is to change the way `_scans.tsv` is being written (so separately listing split files), and to suggest at the BIDS repo, that this procedure is made explicit?

**Comment by sappelhoff** [comment]
Exactly:

1. Make a pull request (PR) to mne-bids, so that all `_split-*` files are also listed in `scans.tsv`
1. Make a PR to https://github.com/bids-standard/bids-specification/ adding a note in an appropriate place, that different `_split-*` files should (MUST) still be listed as individual scans in scans.tsv

Let me know if you need help with this - especially if you have never made a PR --> I don't know what your background is.

The sections to look at in the BIDS specification are these ones (search for "split"):
- https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#meg-recording-data
- https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#split-files
- https://bids-specification.readthedocs.io/en/latest/99-appendices/09-entities.html#split

**Comment by eort** [comment]
Ok, I'll have a look over the weekend.
