### ISSUE TITLE
More flexible treatment of unexpected events

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-bids#694]
Hi, 

This is just a minor thing, but would it make sense to not necessarily throw an error every time events that don't have an event_id entry are present in a file?  

In my MEG files, I have a number of events that have unexpected values. This usually happens when button presses coincide with changes in the experimental phase. I tried to minimize the chances of this happening, but it can't be prevented entirely. 

Since I updated to version `0.6`, this events cause a `ValueError` (`ValueError: No description was specified for the following event(s): 528. Please add them to the event_id dictionary, or drop them from the events_data array.`), and are not silently lumped as `n/a` anymore, as was done in `0.5`. 

Both suggested solutions are not ideal. To add them to the dict, I would first need to explore the events and label them accordingly. Just dropping them, would be a waste, as from the number of them it is often quite obvious to which of the legit event_IDs they would belong. Ideally, I would not change the event values at that stage yet (for sakes of storing the data as raw as possible). 

Right now I am still using version `0.5` for this reason (and not having to change my procedure mid-study). I guess it was a deliberate choice to make that change in `0.6`, but wondered whether it could be loosened up somewhat?

**Comment by agramfort** [comment]
well it's a conscious decision. Your events in the BIDS format should be
"clean" and be considered
the truth for further analysis. So you should clean things up before
writing to save you time later.

**Comment by eort** [comment]
Yeah, that makes sense. Still, I'm not sure whether the requirement for the BIDS-formatted dataset to be clean is more important than it to be as little processed as possible. 
Well anyway, I'll see how much cleaning can be done safely. 
Thanks

**Comment by hoechenberger** [comment]
> Still, I'm not sure whether the requirement for the BIDS-formatted dataset to be clean is more important than it to be as little processed as possible.

I wouldn't consider naming your events "processing", but "annotating" :)

**Comment by jasmainak** [comment]
catching up with my emails now. Is "description" (or is it "trial_type") a required column in BIDS? If not, I would say MNE-BIDS is deviating from the standard ...

**Comment by eort** [comment]
> I wouldn't consider naming your events "processing", but "annotating" :)

The issue is not naming itself, but deciding on *how* to name a deviant event. Oftentimes it is obvious, sometimes not. I can't make up my mind whether I want to play the inference game or not. So, I hoped I could postpone the decision to some unspecified time in the future ;) But yeah, it does make sense to clean up events before proceeding.

> Is "description" (or is it "trial_type") a required column in BIDS?

It's [optional](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html)
