### ISSUE TITLE
write_raw_bids() shouldn't require info['line_freq']

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#696]
According to the [BIDS specs](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#sidecar-json-_eegjson), `PowerLineFrequency` may also be `'n/a'`. This should be our default if `raw.info['line_freq']` has not been set. Currently, we'd raise an exception:

```python
ValueError: PowerLineFrequency parameter is required in the sidecar files. 
Please specify it in info['line_freq'] before saving to BIDS (e.g.
raw.info['line_freq'] = 60 or with --line_freq option in the command line.).
```

We should only raise a warning in this case.

Thoughts?

**Comment by sappelhoff** [comment]
Can users do `raw.info['line_freq'] = "n/a"`? If yes, we could add that to the warning string.

I think prodding the user to set some values in their raw files is good, because it results in better BIDS datasets.

**Comment by agramfort** [comment]
raw.info['line_freq'] = None

maybe as it should be a float (it cannot be a string for sure)

>

**Comment by hoechenberger** [comment]
> I think prodding the user to set some values in their raw files is good, because it results in better BIDS datasets.

Yeah but … then we should also enforce `EEGReference` and a couple others we currently simply set to `'n/a'` by default…

**Comment by sappelhoff** [comment]
If we **could** do something like `raw.info["EEGReference"] = "electrode placed 1cm above FCz location foo bar"`, then I would vote to use that feature and force users to set it prior to passing `raw` to mne-bids.

But we don't have that for EEGReference.

We **do** have it for LineFrequency --> So I suggest to use it. Ask users to add one line to their loop in their script:

`raw.info['line_freq'] = None`

that's not too much to ask IMHO. And if it's `None`, or `np.nan` (whatever is possible), then we set it to `n/a` in BIDS
