### ISSUE TITLE
write_raw_bids() creates BIDS datasets that read_raw_bids() refuses to read if channels were renamed before writing

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#697]
### Problem description
@MaelysSolal ran into this.

Yesterday, we converted a dataset to BIDS after renaming some channels.. Today, the same data cannot be read.

### Reproduction
MWE:

```python
import mne
from mne.datasets import eegbci

from mne_bids import read_raw_bids, write_raw_bids, BIDSPath


subject = '001'
task = 'RestEyesClosed'
bids_root = '/tmp/bci-bids'
bids_path = BIDSPath(subject=subject, task=task, root=bids_root)

raw_fname = eegbci.load_data(subject=1, runs=2, update_path=True)[0]
raw = mne.io.read_raw_edf(raw_fname)
raw.info['line_freq'] = 50

raw.rename_channels({'Fc5.': 'FC5'})  # <--- !!!

write_raw_bids(raw=raw, bids_path=bids_path, overwrite=True)
read_raw_bids(bids_path=bids_path)
```
Output:

> RuntimeError                              Traceback (most recent call last)
> /private/tmp/mwe-rename-chs.py in 
>      18 
>      19 write_raw_bids(raw=raw, bids_path=bids_path, overwrite=True)
> ---> 20 read_raw_bids(bids_path=bids_path)
> 
> ~/Development/mne-bids/mne_bids/read.py in read_raw_bids(bids_path, extra_params, verbose)
>     515                                             on_error='warn')
>     516     if channels_fname is not None:
> --> 517         raw = _handle_channels_reading(channels_fname, bids_fname, raw)
>     518 
>     519     # Try to find an associated electrodes.tsv and coordsystem.json
> 
> ~/Development/mne-bids/mne_bids/read.py in _handle_channels_reading(channels_fname, bids_fname, raw)
>     377         if not (ch_names_raw[-1] == 'STI 014' and
>     378                 ch_names_raw[:-1] == ch_names_tsv):
> --> 379             raise RuntimeError(msg)
>     380 
>     381     # Now we can do some work.
> 
> RuntimeError: Channels do not correspond between raw data and the channels.tsv file. For MNE-BIDS, the channel names in the tsv MUST be equal and in the same order as the channels in the raw data.
> 
> 64 channels in tsv file: "/tmp/bci-bids/sub-001/eeg/sub-001_task-RestEyesClosed_channels.tsv"
> 
>  --> ['FC5', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']
> 
> 64 channels in raw file: "sub-001_task-RestEyesClosed_eeg.edf"
> 
>  --> ['Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']

### Workaround
In this specific case, enforcing a format conversion to BrainVision works:
```python
write_raw_bids(raw=raw, bids_path=bids_path, overwrite=True,
               format='BrainVision')
read_raw_bids(bids_path=bids_path)
```
Output:
```
<RawBrainVision | sub-001_task-RestEyesClosed_eeg.eeg, 64 x 9760 (61.0 s), ~68 kB, data not loaded>
```

### Expected behavior
Either we should fail early (during writing) or not at all. (I'm all for the latter: it should just work)

I think renaming (sanitizing, in our case) channels before writing the BIDS data is a totally sane use case and should be properly supported.

Since we've started moving away from the "sidecar metadata must match raw header metadata" paradigm, we probably can simply remove the check for matching channel names between the two, which is causing the exception here?

cc @sappelhoff @agramfort @jasmainak @adam2392

**Comment by agramfort** [comment]
as discussed in the past the sidecar files are the truth for BIDS. We should overwrite the channel names on read if they are different so we can keep sharing the raw data really as raw without having to convert them

my 2c

**Comment by hoechenberger** [comment]
We need to update the [BIDS spec](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv). Currently, it says:

>  To avoid confusion, the channels SHOULD be listed in the order they appear in the EEG data file.

This should be changed to a MUST, otherwise we're at risk of processing channels incorrectly with the new change in #698, as we're simply iterating over `zip(channel_names_from_tsv, channel_names_from_raw)` and renaming all raw channels if they don't match the name from the TSV.

**Comment by sappelhoff** [comment]
> This should be changed to a MUST, otherwise we're at risk of processing channels incorrectly with the new change in #698, as we're simply iterating over zip(channel_names_from_tsv, channel_names_from_raw) and renaming all raw channels if they don't match the name from the TSV.

agreed, I think the "SHOULD" at that point in the spec is in contrast to BIDS's usual principle of "put the most burden on the dataset curator" (=one-time-burden), although some people may disagree. a "MUST" would be better.

A problem I see is: How do we validate that? ... and back we go to a discussion about a python validator ^^

somewhat parallel issue: https://github.com/bids-standard/bids-specification/issues/667

**Comment by hoechenberger** [comment]
> How do we validate that?

I don't think you can, but I don't really see a problem with this. It's up to the dataset creation tools to enforce this rule.
