### ISSUE TITLE
Incorrect mapping: RESP <> resp

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#700]
### Problem Description

- Currently, MNE-BIDS maps the BIDS `RESP` channel type to MNE's `resp`
- However:
    - BIDS `RESP` -> respiration
    - MNE `resp` -> some kind of response trigger channel

### Fix

Probably we should convert BIDS `RESP` to MNE `misc`

@agramfort, do you know if `misc` MNE channels keep their unit? The BIDS `RESP` channels we have here have unit Volts, would be good to keep it that way.

Problem was discovered by @MaelysSolal

**Comment by agramfort** [comment]
good catch....

>

**Comment by sappelhoff** [comment]
argh, nice catch. I thought misc channels are unit less, because you could have anything in there.

**Comment by hoechenberger** [comment]
Following the discussion at https://github.com/mne-tools/mne-python/issues/8853, this is actually only a bug in MNE-Python's BTi reader, and nothing we need to address in MNE-BIDS.
