### ISSUE TITLE
Improve MEG sidecar writing: Dig Landmarks and Headpoints

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#705]
raised by @eort in https://mne.discourse.group/t/mne-bids-digitizedlandmarks-with-neuromag-systems/2694/2

It looks like we are setting two fields in the MEG sidecar JSON to `false`, no matter what the data says:

https://github.com/mne-tools/mne-bids/blob/d65b8ca3edf38a4be5a1db8d24592cf2a1a3d5ef/mne_bids/write.py#L632-L633

Can we improve this behavior?

These fields are referred to in BIDS here: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson

**Comment by sappelhoff** [comment]
@eort could you perhaps share an output of what your `info["dig"]` contains? And perhaps post what the `coordsystem.json` file contains after mne-bids conversion.

I find these two BIDS fields a little confusing, because I don't know what they refer to:

- Does `DigitizedLandmarks` need to be set to `true` when you have something like this in your `coordsystem.json` file?

```
    "HeadCoilCoordinates": {
        "NAS": [
            3.725290298461914e-09,
            0.10260561108589172,
            4.190951585769653e-09
        ],
```

As for `DigitizedHeadPoints` --> can these be shared WITHIN the FIF file? As far as I know, some MEG formats share these in a separate file (for example `*_headshape.pos`) which one should then point to in BIDS via the `DigitizedHeadPoints` field.

So `DigitizedHeadPoints` should definitely be `true` if some `*_headshape.pos` file or similar is present. But I don't know what a FIF file and corresponding mne-bids output would look like when "headpoints" are embedded in the FIF.

**Comment by sappelhoff** [comment]
Maybe @jasmainak can remember from when he was working on the MEG spec

**Comment by eort** [comment]
Here is `raw.info['dig']`:

```
[<DigPoint |        LPA : (-74.3, -0.0, -0.0) mm    : head frame>,
 <DigPoint |     Nasion : (-0.0, 95.0, -0.0) mm     : head frame>,
 <DigPoint |        RPA : (72.6, 0.0, -0.0) mm      : head frame>,
 <DigPoint |     HPI #1 : (58.5, 61.2, 75.0) mm     : head frame>,
 <DigPoint |     HPI #2 : (68.4, -40.7, -5.0) mm    : head frame>,
 <DigPoint |     HPI #3 : (-67.4, -41.5, -10.5) mm  : head frame>,
 <DigPoint |     HPI #4 : (-58.9, 65.0, 70.1) mm    : head frame>,
 <DigPoint |   Extra #1 : (-5.4, -85.6, -25.2) mm   : head frame>,
 <DigPoint |   Extra #2 : (-7.7, -85.0, 4.5) mm     : head frame>,
...
# this continues for as many extrapoints as were recorded (representing the headshape)
```

and here is the `coordsystem.json`:
```
{
    "MEGCoordinateSystem": "ElektaNeuromag",
    "MEGCoordinateUnits": "m",
    "MEGCoordinateSystemDescription": "RAS orientation and the origin between the ears",
    "HeadCoilCoordinates": {
        "NAS": [
            -5.587935447692871e-09,
            0.09501296281814575,
            -7.450580596923828e-09
        ],
        "LPA": [
            -0.07426634430885315,
            -1.4901161193847656e-08,
            -1.4901161193847656e-08
        ],
        "RPA": [
            0.07260997593402863,
            0.0,
            -1.4901161193847656e-08
        ],
        "coil1": [
            0.058461662381887436,
            0.0612209290266037,
            0.07497470825910568
        ],
        "coil2": [
            0.06841837614774704,
            -0.04068693891167641,
            -0.00504457950592041
        ],
        "coil3": [
            -0.06736689805984497,
            -0.04152616485953331,
            -0.010496650822460651
        ],
        "coil4": [
            -0.058862555772066116,
            0.0649959072470665,
            0.07011465728282928
        ]
    },
    "HeadCoilCoordinateSystem": "ElektaNeuromag",
    "HeadCoilCoordinateUnits": "m"
}
```

I don't know how other MEG system handle this, but if these fields are not present in all common systems, it might be simpler to write some default values, and then later selectively update those values for system that are known to include them. 

ps. not sure whether related, but the `dewarPosition` seams to also be hardcoded. However, I can't find it in `raw.info` either, so maybe that information is not included in the file?

**Comment by sappelhoff** [comment]
Cool, thanks for the info.

So these `HeadCoilCoordinates` look to me like they are digitized positions on the head --> so maybe we should set `DigitizedHeadPoints = True`?

Furthermore, given that NAS, LPA, and RPA are present we should probably set `DigitizedLandmarks = True`

WDYT @hoechenberger?

---

> ps. not sure whether related, but the dewarPosition seams to also be hardcoded. However, I can't find it in raw.info either, so maybe that information is not included in the file?

Yes, `DewarPosition` is hardcoded as a missing value: https://github.com/mne-tools/mne-bids/blob/d65b8ca3edf38a4be5a1db8d24592cf2a1a3d5ef/mne_bids/write.py#L631

I don't even know what that is (any hint?).

**Comment by eort** [comment]
> I don't even know what that is (any hint?).

It is basically the position of the MEG device, [this](https://startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.researchgate.net%2Fprofile%2FCezary_Sieluzycki%2Fpublication%2F225139749%2Ffigure%2Ffig3%2FAS%3A669343947960323%401536595441174%2Fleft-Sketch-of-an-MEG-dewar-indicating-positions-of-SQUIDs-reference-coils-and.ppm&sp=1613144009T5d5a9066b531778fff36897a379eea15609e5e60270834bbe2222b3f31a7d726) entire thing is the dewar

**Comment by sappelhoff** [comment]
> It is basically the position of the MEG device, this entire thing is the dewar

I see, thanks. That looks like something that differs between manufacturers .. and even MEG system models. So it's probably the best we can do to `n/a` --> the mne-python raw files do not contain the information about the MEG system *model* (only the manufacturer), so trying to "guess" the dewar position would be error prone, WDYT?

I suggest that you have a look at this function: https://mne.tools/mne-bids/dev/generated/mne_bids.update_sidecar_json.html#mne_bids.update_sidecar_json

and this example: https://mne.tools/mne-bids/dev/auto_examples/update_bids_datasets.html#sphx-glr-auto-examples-update-bids-datasets-py

**Comment by eort** [comment]
. I suggest that you have a look at this function: https://mne.tools/mne-bids/dev/generated/mne_bids.update_sidecar_json.html#mne_bids.update_sidecar_json

Yes, that's what I am currently doing. Also for the landmarks and headpoints, by the way. I just asked because I was wondering why they were set to false (and not n\a), even though the raw.info suggested otherwise. 

> so trying to "guess" the dewar position would be error prone, WDYT?
Agreed. It should be easier to produce sidecars with basic information, and only later update them, or let users do it themselves. In that case it might make sense to note somewhere that the sidecars mne-bids produced are not as "complete" as they could be, so that users are aware that there are things to change (at least I just happen to stumble over the discrepancies).

**Comment by sappelhoff** [comment]
For some fields, setting an `n/a` value is impossible, see this [JSON-schema](https://json-schema.org/) for the bids-validator:

https://github.com/bids-standard/bids-validator/blob/c1ad2821b4eb3676ed7e87c51e89613c9089f563/bids-validator/validators/json/schemas/meg.json#L62-L63

as you can see, the values in the JSON MUST be boolean in this case.

---

one markdown hint for you: You need to leave a blank line after a quote, otherwise what you write below is rendered as part of the quote, see:

```
> this is a quote
this is supposed to be another thing
```

renders as:

> this is a quote
this is supposed to be another thing

```
> this is a quote

this is supposed to be another thing
```

renders as:

> this is a quote

this is supposed to be another thing

**Comment by sappelhoff** [comment]
> Cool, thanks for the info.
> So these HeadCoilCoordinates look to me like they are digitized positions on the head --> so maybe we should set DigitizedHeadPoints = True?
> Furthermore, given that NAS, LPA, and RPA are present we should probably set DigitizedLandmarks = True

@eort, I looked into this a bit more: `DigitizedHeadPoints` and `DigitizedLandmarks` are coded as `"False"`, because we do not write this information to the `coordsystem.json file`:

https://github.com/mne-tools/mne-bids/blob/a45695ed43394f067a776f0f51441723915bcbf5/mne_bids/dig.py#L260-L273

I think we definitely **could** easily write `DigitizedLandmarks`, because they are well defined in `raw` objects, and we are already writing this for EEG data:

https://github.com/mne-tools/mne-bids/blob/a45695ed43394f067a776f0f51441723915bcbf5/mne_bids/dig.py#L274-L281

Then a PR would be extending (and testing) this EEG behavior to MEG, and if this is done, go back to the `_sidecar_json` function and edit the lines:

https://github.com/mne-tools/mne-bids/blob/a45695ed43394f067a776f0f51441723915bcbf5/mne_bids/write.py#L650-L655

... to account for the fact that `DigitizedLandmarks=True`.

---

Regarding `DigitizedHeadPoints`, I think my previous point was false. HPI coils are not the same as "headpoints". In the [section in the bids spec](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson), there are two separate entries for:

- `HeadCoilCoordinates` and
- `DigitizedHeadPoints`

so given your example from https://github.com/mne-tools/mne-bids/issues/705#issuecomment-778210768, I now understand you correctly (I think) that the coords labeled "Extra" are the digitized head points.

So here the solution is probably as simple as checking `raw.info["dig"]` for any "Extra" entries, and then set `DigitizedHeadPoints=True` in the `_sidecar_json` function for MEG.

todo:

- [ ] Make sure that the "Extra" entries in `raw.info["dig"]` do indeed refer to digitized head points.
- [ ] Test that after writing to BIDS (via mne-bids), and then reading the data back, these "Extra points" are indeed there


Do you want to make a PR for this?

**Comment by eort** [comment]
> So here the solution is probably as simple as checking raw.info["dig"] for any "Extra" entries, and then set DigitizedHeadPoints=True in the _sidecar_json function for MEG.

We should also make sure that non-Neuromag systems don't code other thinsg with extra points. Or run this test only for neuromag systems. 

> I think we definitely could easily write DigitizedLandmarks, because they are well defined in raw objects, and we are already writing this for EEG data:

Ah, so `DigitizedLandmarks` refer to `AnatomicalLandmarks`? I was already wondering what the differences between them might be. I thought they would refer to the same points in two different coordinate systems. 

> Do you want to make a PR for this?

I don't have a lot of time on hands these weeks, but if it is not urgent, I can try!

**Comment by sappelhoff** [comment]
just realized that this came up years ago in #48 and an initial attempt was made in #77.

> We should also make sure that non-Neuromag systems don't code other thinsg with extra points. Or run this test only for neuromag systems.

if we can get it to run for FIF, that'd already be an improvement. Everything else we can get to work would be a bonus - but probably requires someone who is familiar with those file formats (KIT, BTI, 4D, whatever the others are called)

**Comment by eort** [comment]
I might underestimate the amount of my confused-ness, but I think I start to understand stuff somewhat. 

> DigitizedLandmarks

What I thought this field in the `_meg.json` would refer to is whether LPA, RPA, NAS (and maybe the head coils) are present in the recording (afaik, the must be present in every recording). However, this is about are extra fiducial points (e.g. as measured with this procedure at the [Donders](https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/). If no such procedure is used, `raw.info['dig']` usually does not store the `DigitizedLandmarks` (no clue whether they would be stored in `raw.info['dig']` if present).
Therefore, I am not sure whether `DigitizedLandmarks` are as well-defined as you say @sappelhoff. What would happen if there are none? Silently assuming that the coils are fiducials doesn't make sense, no?

> DigitizedHeadPoints

Writing those still makes sense. I'm only a little concerned that other MEEG systems might write `Extra points` that don't refer to head points. I might submit something later today.

**Comment by sappelhoff** [comment]
I thought/think that `DigitizedLandmarks` should be `true` as soon as any coordinate data for any landmark is contained/shipped with the recording. That's not limited to LPA, RPA, and NAS --> but as these are most commonly recorded, it's most robust to try to detect them and then set the field to `true` ... and do `false` otherwise (although this might theoretically lead to a false negative if somebody recorded e.g., the "vertex" of the skull, but not LPA, RPA, NAS)

screenshot:

![image](https://user-images.githubusercontent.com/9084751/111809084-e61c7100-88d4-11eb-811d-f4dcde3c22a2.png)

source of screenshot:

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#sidecar-json-_megjson



> I'm only a little concerned that other MEEG systems might write Extra points that don't refer to head points.

I am concerned about non-FIF formats as well here, so I would try to only support *native* FIF data at this point ... so **not** e.g., BTI data that's been read into FIF and is handled as FIF during mne-bids, but then gets "copied over" at BTI into the bids dataset. (e.g., https://mne.tools/mne-bids/stable/generated/mne_bids.copyfiles.copyfile_bti.html#mne_bids.copyfiles.copyfile_bti)

**Comment by eort** [comment]
What are landmarks then? I thought they are any points in the anatomical image that work as reliable reference (fiducial point) to align head coordsystem with anatomical coordsystem. As far as I understand NAS could be such a point, but RAS and LAS are not reliably enough detectable in an anatomical scan to serve as such. But suppose those three points could indeed serve as anatomical landmarks, would the values for `HeadCoilCoordinates`,`HeadCoilCoordinateSystem`, and `HeadCoilCoordinateUnits` be the same as those for `AnatomicalCoilCoordinates`,`AnatomicalCoilCoordinateSystem`, and `AnatomicalCoilCoordinateUnits` ?

> so I would try to only support native FIF data at this point

Is there a way to get from the raw instance whether a file is `native` FIF or converted?

**Comment by sappelhoff** [comment]
> What are landmarks then? I thought they are any points in the anatomical image that work as reliable reference (fiducial point) to align head coordsystem with anatomical coordsystem.

In my book these are any points *on* a human that can be reliably identified ... but not necessarily in an MRI: Other identification methods are fine as well.

> But suppose those three points could indeed serve as anatomical landmarks, would the values for HeadCoilCoordinates,HeadCoilCoordinateSystem, and HeadCoilCoordinateUnits be the same as those for AnatomicalCoilCoordinates,AnatomicalCoilCoordinateSystem, and AnatomicalCoilCoordinateUnits

if the headcoils are placed exactly on those points (LPA, RPA, NAS), then I'd say yes. See also this thread (specifically Robert's post from March 16): https://groups.google.com/g/bids-discussion/c/BeyUeuNGl7I

> Is there a way to get from the raw instance whether a file is native FIF or converted?

I think `raw.filename` should work, see also: https://github.com/mne-tools/mne-bids/issues/404

**Comment by eort** [comment]
> In my book these are any points on a human that can be reliably identified ... but not necessarily in an MRI: Other identification methods are fine as well.

Okay, makes sense. Then this should indeed be straightforward to implement. I'll push some time this week.
