### ISSUE TITLE
Change tests from _TempDir to tmpdir

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#711]
Our CI often fails on issues like this one:

> E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp_mne_tempdir_json6b4j3\\participants.json'

see e.g., https://github.com/mne-tools/mne-bids/runs/1924242938?check_suite_focus=true

Should we change from MNE-Python's `_TempDir()` to pytest's `tmpdir`? I think we are doing that in the MNE-Python codebase as well, right? It seems to me like pytest's `tmpdir` is more stable.

Changes would look like this:

```diff
-def test_convert_dataset_format(dir_name, fname, reader):
+def test_convert_dataset_format(tmpdir, dir_name, fname, reader):
    """Test force-converting files to RECOMMENDED formats."""
-   bids_root = _TempDir()
+   bids_root = tmpdir
```

**Comment by sappelhoff** [comment]
also, we could start [caching](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows) the MNE testing data in the GH actions workflow ... I have also seen the CIs error out on download http timeouts etc. often recently. WDYT?

**Comment by hoechenberger** [comment]
> Our CI often fails on issues like this one:
> 
> > E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp_mne_tempdir_json6b4j3\participants.json'
> 
> see e.g., https://github.com/mne-tools/mne-bids/runs/1924242938?check_suite_focus=true
> 
> Should we change from MNE-Python's `_TempDir()` to pytest's `tmpdir`? I think we are doing that in the MNE-Python codebase as well, right? It seems to me like pytest's `tmpdir` is more stable.

Where does the error come from anyway? Why should switching to `tmpdir` fix things?

**Comment by sappelhoff** [comment]
> Where does the error come from anyway?

no idea, just a hunch that our temporary dir handling is at fault.

> Why should switching to tmpdir fix things?

Maybe it doesn't, but it's the better practice anyhow, so it'd be worth trying.

**Comment by hoechenberger** [comment]
Let's give it shot then and see what happens 🤷‍♂️

**Comment by sappelhoff** [comment]
@larsoner do you perhaps have an opinion about pytest `tmpdir` vs MNE-Python `_TempDir`? I remember you telling me in some PR to switch to `tmpdir`, but cannot remember the reasoning.

**Comment by larsoner** [comment]
`_TempDir` is mostly a relic of the past from when `pytest` didn't exist. Nowadays any test should be written using `tmpdir` as it's more flexible and standard than `_TempDir` (anyone with a big enough pytest background will immediately recognize `tmpdir` and know how to make use of it).

However, we need to keep `_TempDir` in MNE-Python because there are times we want to create a temporary directory for running some command-line utilities with intermediate output files, and we don't want to require people to have `pytest` installed to do it.
