### ISSUE TITLE
Better documentation for iEEG coordinate system/frames in examples

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#715]
With some rehauling in the [BIDS spec](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/04-intracranial-electroencephalography.html#electrode-description-_electrodestsv) and [validator](https://github.com/bids-standard/bids-validator/pull/1190), the writing/reading of iEEG-BIDS (and MEG/EEG also) is constrained. This is good for making sure there's only a few ways to do "coordinate" related stuff, but a bit troublesome because mne-python doesn't have all the "coordinate frames". 

A proposed PR would be to document the various things that ARE possible, and perhaps a short discussion on what is not possible yet. 

Once https://github.com/mne-tools/mne-bids/pull/704, is merged then I can make a quick PR updating the example in https://mne.tools/mne-bids/stable/auto_examples/convert_ieeg_to_bids.html#sphx-glr-auto-examples-convert-ieeg-to-bids-py to talk more about how you might write coordinates in different systems.

**Comment by sappelhoff** [comment]
Cool, this is a good first step, but we must not forget to also warn users early when they want to pass a `label` to the `_space-<label>` entity that is invalid, see https://github.com/bids-standard/bids-specification/pull/735

**Comment by hoechenberger** [comment]
> we must not forget to also warn users early when they want to pass a `label` to the `_space-<label>` entity that is invalid

Shouldn't we `raise` in that case?

**Comment by adam2392** [comment]
Before, we constrain this here, I was hoping to get this sorted out: https://github.com/bids-standard/bids-specification/issues/747

@sappelhoff @hoechenberger if you have any thoughts, please post there?

**Comment by sappelhoff** [comment]
I am completely out of my comfort zone with that topic, but I'll keep reading and hope that people like dora and Chris, and maybe robert will be able to help. Of course I'll chime in when something comes to my mind.
