### ISSUE TITLE
GBK encode error on windows 10

### ISSUE THREAD

**Issue by const7** [mne-tools/mne-bids#716]
#### Describe the bug
Get a gbk error when using `write_raw_bids` to get BIDS files.

#### Steps to reproduce
I'm using the example code and data on MNE-BIDS official website: [04. Convert EEG data to BIDS format](https://mne.tools/mne-bids/dev/auto_examples/convert_eeg_to_bids.html#sphx-glr-auto-examples-convert-eeg-to-bids-py).

#### Expected results
Generate BIDS files successfully.

#### Actual results
Got a gbk encode error.
```
Extracting EDF parameters from C:\Users\const\mne_data\MNE-eegbci-data\files\eegmmidb\1.0.0\S001\S001R02.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...   
Extracting EDF parameters from C:\Users\const\mne_data\MNE-eegbci-data\files\eegmmidb\1.0.0\S001\S001R02.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Traceback (most recent call last):
  File "mnebids.py", line 41, in <module>
    write_raw_bids(raw, bids_path, overwrite=True)
  File "C:\Users\const\miniconda3\lib\site-packages\mne_bids\write.py", line 1081, in write_raw_bids
    _readme(bids_path.datatype, readme_fname, False, verbose)
  File "C:\Users\const\miniconda3\lib\site-packages\mne_bids\write.py", line 235, in _readme        
    _write_text(fname, text, overwrite=True, verbose=verbose)
  File "C:\Users\const\miniconda3\lib\site-packages\mne_bids\utils.py", line 176, in _write_text    
    fid.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 143: illegal multibyte sequence
```

#### Additional information
```
Platform:      Windows-10-10.0.19041-SP0
Python:        3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
Executable:    C:\Users\const\Miniconda3\python.exe
CPU:           AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD: 16 cores
Memory:        31.9 GB

mne:           0.22.0
numpy:         1.19.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.4.1
matplotlib:    3.3.2 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.23.1
numba:         0.52.0
nibabel:       Not found
nilearn:       Not found
dipy:          Not found
cupy:          Not found
pandas:        1.1.0
mayavi:        Not found
pyvista:       Not found
vtk:           Not found
```

#### Other information
I got this error on my own data, and then I tested it using the official example. 
When I changed code in `_write_text` function in `mne_bids/utils.py` from
```python
with open(fname, 'w') as fid:
    fid.write(text)
    fid.write('\n')
```
to
```python
with open(fname, 'w', encoding='utf-8') as fid:
    fid.write(text)
    fid.write('\n')
```
everything worked well.

I know this probably not a bug caused by mne and I would be very grateful if someone could give some advice. Also, is there any way to work well without changing the official code in `utils.py`?
Thanks!

**Comment by hoechenberger** [comment]
Hello @const7, thanks for reporting this! Yes this is clearly a bug. May I ask which language your OS is using? Simplified Chinese?

Best wishes,

Richard

**Comment by hoechenberger** [comment]
@const7 In fact, this should already be fixed in the development version of MNE-BIDS, which you can install via:

```shell
pip install -U https://github.com/mne-tools/mne-bids/archive/master.zip
```

Can you check and see if this solves your problem?

**Comment by const7** [comment]
> Hello @const7, thanks for reporting this! Yes this is clearly a bug. May I ask which language your OS is using? Simplified Chinese?
> 
> Best wishes,
> 
> Richard

I'm using English as my default OS language, but the region setting is China. I'm not sure if this will be the problem.
![image](https://user-images.githubusercontent.com/19154386/109417581-3bb0dc80-79ff-11eb-89e0-835025f2ce5e.png)

**Comment by const7** [comment]
> @const7 In fact, this should already be fixed in the development version of MNE-BIDS, which you can install via:
> 
> ```shell
> pip install -U https://github.com/mne-tools/mne-bids/archive/master.zip
> ```
> 
> Can you check and see if this solves your problem?

Thank you! This version works well.
