### ISSUE TITLE
Move all "checks" in BIDSPath to `_check()` to allow dataset_description.json to be represented as a BIDSPath

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#727]
#### Describe the problem
I am trying to apply `update_sidecar_json` to `dataset_description.json` and I realized that it is impossible to represent `dataset_description.json` right now as a BIDSPath.

```Python
        deriv_dataset_template = {
            'GeneratedBy': [
                {
                    'Name': 'pydmd',
                    'Version': pydmd.__version__,
                    'Description': 'Dynamic Mode Decomposition',
                    'CodeURL': 'https://github.com/adam2392/seizure_genesis',
                }
            ]
        }
        update_sidecar_json(dataset_descrip_fpath, deriv_dataset_template)
```

does not work for a `pathlib.Path`, or `str` object.

#### Describe your solution
I propose adding an `if check is True` wrapper to this line in `BIDSPath.update`:

```
# check if there are any characters not allowed
            if val is not None and key != 'root':
                _check_key_val(key, val)
```

so we could represent `dataset_description.json` as a `BIDSPath(suffix='dataset_description'`, extension='.json')`.

#### Describe possible alternatives
Alternatively, we want to allow str/pathlib.Path objects in more functions.

**Comment by sappelhoff** [comment]
I agree that it'd be good to be able to represent all valid "standard" BIDS files as BIDSPath.

**Comment by agramfort** [comment]
+1

>
