### ISSUE TITLE
`split` suffix is forced to be added to BIDSPath?

### ISSUE THREAD

**Issue by levchenkoegor** [mne-tools/mne-bids#731]
I convert my raw meg files to BIDS standard using mne_bids (version 0.6)
I constructed BIDSPath:
```
meg_bids_path = mne_bids.BIDSPath(subject=subj_id, session=date_record, task=task_name, root=data_bids_dir)
```

And then use it to save the raw file:
```
mne_bids.write_raw_bids(raw=raw_meg, bids_path=meg_bids_path, anonymize={'daysback': 40000}, overwrite=True, verbose=True)
```

As a result, I have `scans.tsv` file with a value `meg/sub-1001_ses-20190416_task-vid2_meg.fif` (which is correct for my file and for `meg_bids_path` after I define it), but the real filename in `meg` folder is `sub-1001_ses-20190416_task-vid2_split-01_meg.fif`. It leads to an error during validation of my dataset with BIDS-Validator.

Is it possible somehow to suppress the `split` suffix in my final filename? Or maybe take control of it to include it in `scans.tsv`?

For me, it looks strange that the suffix appears unexpectedly in the resulting filename and I can't control it anyhow.
Any comments/ideas are appreciated :)

**Comment by sappelhoff** [comment]
@levchenkoegor thanks for your report. Can you replicate this using the MNE sample data?

I tried with the script below, but I cannot reproduce your error:

```Python
# %%
import mne_bids
import mne
import os

# %%
dpath = mne.datasets.sample.data_path()
data = os.path.join(dpath, "MEG", "sample", "sample_audvis_raw.fif")

raw_meg = mne.io.read_raw_fif(data)

# %%

subj_id = "1"
date_record = "20210316"
task_name = "Test"
data_bids_dir = os.path.join(os.path.expanduser("~"), "mne-bids-issue-731")

meg_bids_path = mne_bids.BIDSPath(
    subject=subj_id, session=date_record, task=task_name, root=data_bids_dir
)


mne_bids.write_raw_bids(
    raw=raw_meg,
    bids_path=meg_bids_path,
    anonymize={"daysback": 36879},
    overwrite=True,
    verbose=True,
)
```

This is the output:

```
.
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
└── sub-1
    └── ses-20210316
        ├── meg
        │   ├── sub-1_ses-20210316_coordsystem.json
        │   ├── sub-1_ses-20210316_task-Test_channels.tsv
        │   ├── sub-1_ses-20210316_task-Test_meg.fif
        │   └── sub-1_ses-20210316_task-Test_meg.json
        └── sub-1_ses-20210316_scans.tsv

3 directories, 9 files

```

And the contents of `scans.tsv`

```
filename	acq_time
meg/sub-1_ses-20210316_task-Test_meg.fif	1901-12-14T19:01:10.720100Z
```

**Comment by agramfort** [comment]
are you using the latest validator? the split appears as the file is
larger than 2GB?
are you using mne_bids development version?

**Comment by hoechenberger** [comment]
> are you using mne_bids development version?

@levchenkoegor stated to be using 0.6

**Comment by sappelhoff** [comment]
I have slightly adjusted my "reproduction script" to make sure that the MEG file is large enough to be "split" by MNE-Python.

However I still cannot reproduce the error:

```python
# %%
import mne_bids
import mne
import os
from tempfile import NamedTemporaryFile


dpath = mne.datasets.sample.data_path()
data = os.path.join(dpath, "MEG", "sample", "sample_audvis_raw.fif")

raw_meg = mne.io.read_raw_fif(data)
raw_concat = mne.concatenate_raws([raw_meg] * 5)

# %%
subj_id = "1"
date_record = "20210316"
task_name = "Test"
data_bids_dir = os.path.join(os.path.expanduser("~"), "mne-bids-issue-731")

meg_bids_path = mne_bids.BIDSPath(
    subject=subj_id, session=date_record, task=task_name, root=data_bids_dir
)


with NamedTemporaryFile(suffix="_raw.fif") as f:
    fname = f.name
    raw_concat.save(fname, overwrite=True)
    raw_concat = mne.io.read_raw_fif(fname, preload=False)
    mne_bids.write_raw_bids(
        raw=raw_concat,
        bids_path=meg_bids_path,
        anonymize={"daysback": 55},
        overwrite=True,
        verbose=True,
    )
```

yields this:

```
.
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
└── sub-1
    └── ses-20210316
        ├── meg
        │   ├── sub-1_ses-20210316_coordsystem.json
        │   ├── sub-1_ses-20210316_task-Test_channels.tsv
        │   ├── sub-1_ses-20210316_task-Test_events.tsv
        │   ├── sub-1_ses-20210316_task-Test_meg.json
        │   ├── sub-1_ses-20210316_task-Test_split-01_meg.fif
        │   └── sub-1_ses-20210316_task-Test_split-02_meg.fif
        └── sub-1_ses-20210316_scans.tsv

3 directories, 11 files

```

scans.tsv:

```
filename	acq_time
meg/sub-1_ses-20210316_task-Test_split-01_meg.fif	2002-10-09T19:01:10.720100Z
meg/sub-1_ses-20210316_task-Test_split-02_meg.fif	2002-10-09T19:01:10.720100Z
```

**Comment by levchenkoegor** [comment]
Thank you for your replies, everybody!

To be more clear with the data and the problem:

My input data is organized like these:
```
.
subj_name1
і   190416
і           subj_name1_vid1.fif
і           subj_name1_vid2.fif
і           subj_name1_vid3.fif
і           subj_name1_vid4.fif
subj_name2
...
```

I read and save file by file:
```
data_bids_dir = proj_root / 'data_bids_test2'

for raw_file_path in raw_files_paths:
    raw_meg = mne.io.read_raw_fif(raw_file_path)

    subj_id = '1001'
    task_name = raw_file_path.parts[-1].split('.')[0][-4:]  # vid*
    date_record = str(raw_meg.info['meas_date']).split(' ')[0].replace('-', '')

    meg_bids_path = mne_bids.BIDSPath(subject=subj_id, session=date_record, task=task_name,
                                                                 root=data_bids_dir)

    # at this point print(meg_bids_path) returns this:
    # `data_bids_test2\sub-1001\ses-20190416\meg\sub-1001_ses-20190416_task-vid2_split-01_meg.fif`
    # I don't understand why suffix `split-01` appears

    mne_bids.write_raw_bids(raw=raw_meg, bids_path=meg_bids_path, anonymize={'daysback': 40000}, 
                                             overwrite=True, verbose=True)
```

Final output of BIDS folder:
```
і   dataset_description.json
і   participants.json
і   participants.tsv
і   README
і   
sub-1001
і    ses-20190416
і       і   sub-1001_ses-20190416_scans.tsv
і       і   
і       meg
і               sub-1001_ses-20190416_coordsystem.json
і               sub-1001_ses-20190416_task-vid1_channels.tsv
і               sub-1001_ses-20190416_task-vid1_meg.json
і               sub-1001_ses-20190416_task-vid1_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid2_channels.tsv
і               sub-1001_ses-20190416_task-vid2_meg.json
і               sub-1001_ses-20190416_task-vid2_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid3_channels.tsv
і               sub-1001_ses-20190416_task-vid3_meg.json
і               sub-1001_ses-20190416_task-vid3_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid4_channels.tsv
і               sub-1001_ses-20190416_task-vid4_meg.json
і               sub-1001_ses-20190416_task-vid4_split-01_meg.fif
```

The content of `sub-1001_ses-20190416_scans.tsv` file:
```
filename	acq_time
--
meg/sub-1001_ses-20190416_task-vid1_meg.fif	1909-10-10T08:38:12.310251Z
meg/sub-1001_ses-20190416_task-vid2_meg.fif	1909-10-10T08:01:19.595069Z
meg/sub-1001_ses-20190416_task-vid3_meg.fif	1909-10-10T08:15:25.874010Z
meg/sub-1001_ses-20190416_task-vid4_meg.fif	1909-10-10T08:26:33.396239Z
```

As a result, when I use [BIDS validator v1.6.0](https://bids-standard.github.io/bids-validator/) it returns an error:
```
[Code 129] SCANS_FILENAME_NOT_MATCH_DATASET
```

@agramfort, raw files are lower than 2Gb size (around 900 MB each) and I use the mne-bids 0.6 version. To be more detailed I install it through the `conda-environment.yml` file:
```
name: MCCA-MEG
dependencies:
  - python=3.7.7
  - pip=20.2.4
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.3.2
  - pandas=1.1.1
  - scikit-learn=0.24.0
  - conda-forge::mne=0.21.0
  - conda-forge::mne-bids=0.6
  - conda-forge::dcm2niix=1.0.20201224
```

@sappelhoff, yes, with the MNE sample can't reproduce it too. I don't know why, but maybe problem is that I have 4 records per subject. I will try to do more experiments to figure it out!

Please let me know if something more is needed to clarify the issue!

**Comment by hoechenberger** [comment]
@levchenkoegor Do you still see this issue with the development version of MNE-BIDS?

**Comment by levchenkoegor** [comment]
@hoechenberger with the development version everything works fine!

BIDS folder:
```
і   dataset_description.json
і   participants.json
і   participants.tsv
і   README
і   
sub-1001
і   ses-20190416
і       і   sub-1001_ses-20190416_scans.tsv
і       і   
і       meg
і               sub-1001_ses-20190416_coordsystem.json
і               sub-1001_ses-20190416_task-vid1_channels.tsv
і               sub-1001_ses-20190416_task-vid1_meg.json
і               sub-1001_ses-20190416_task-vid1_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid2_channels.tsv
і               sub-1001_ses-20190416_task-vid2_meg.json
і               sub-1001_ses-20190416_task-vid2_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid3_channels.tsv
і               sub-1001_ses-20190416_task-vid3_meg.json
і               sub-1001_ses-20190416_task-vid3_split-01_meg.fif
і               sub-1001_ses-20190416_task-vid4_channels.tsv
і               sub-1001_ses-20190416_task-vid4_meg.json
і               sub-1001_ses-20190416_task-vid4_split-01_meg.fif
```

And `sub-1001_ses-20190416_scans.tsv` contains:
```
filename	acq_time
--
meg/sub-1001_ses-20190416_task-vid1_split-01_meg.fif	1909-10-10T08:38:12.310251Z
meg/sub-1001_ses-20190416_task-vid2_split-01_meg.fif	1909-10-10T08:01:19.595069Z
meg/sub-1001_ses-20190416_task-vid3_split-01_meg.fif	1909-10-10T08:15:25.874010Z
meg/sub-1001_ses-20190416_task-vid4_split-01_meg.fif	1909-10-10T08:26:33.396239Z
```

But how do you think why it adds `split-01` suffix to each file if it is not a split actually? These are 4 different records on the same day for the one subject with a size lower than 2GB definitely. The parameters from record to record are the same, but is it right to treat it with `split` suffix?
Just trying to understand the behaviour of the code :)

**Comment by sappelhoff** [comment]
there is definitely something wrong here ... if the file is small and not split, there shouldnt be a `_split-01` :thinking:

**Comment by hoechenberger** [comment]
So you're still seeing the split issue with the development version? I cannot reproduce this unfortunately. Would it be possible for you to share one of your datasets with us so we can try to get to the bottom of this?

**Comment by levchenkoegor** [comment]
@hoechenberger, sure!

I uploaded one subject to google drive [here](https://drive.google.com/drive/folders/1WSHqke2ZoiDmm0y70zBpwKV4kDxCtCIO?usp=sharing).

**Comment by sappelhoff** [comment]
Thanks for the data @levchenkoegor I tried to replicate your issue, but again I couldn't (using `master` of mne-bids):

```
# %%
import mne_bids
import mne
import os

# %%

home = os.path.expanduser("~")

# %%
use = "david"  # can be sample, or david

additional_files_to_write = []
if use == "sample":
    dpath = mne.datasets.sample.data_path()
    data = os.path.join(dpath, "MEG", "sample", "sample_audvis_raw.fif")
elif use == "david":
    dpath = os.path.join(home, "Downloads")
    data = os.path.join(dpath, "akjolbaev_david", "190416", "akjolbaev_david_vid1.fif")
    additional_files_to_write = ["vid2", "vid3", "vid4"]
else:
    raise ValueError("use must be one of ['sample', 'david']")

raw_meg = mne.io.read_raw_fif(data)

# %%

subj_id = "1001"
date_record = "20190416"
daysback = 40000
task_name = "vid1"
data_bids_dir = os.path.join(home, "mne-bids-issue-731")

meg_bids_path = mne_bids.BIDSPath(
    subject=subj_id, session=date_record, task=task_name, root=data_bids_dir
)

# write initial file
mne_bids.write_raw_bids(
    raw=raw_meg,
    bids_path=meg_bids_path,
    anonymize={"daysback": daysback},
    overwrite=True,
    verbose=True,
)

# potentially write additional files
for fname_replace in additional_files_to_write:

    raw_meg = mne.io.read_raw_fif(data.replace("vid1", fname_replace))
    meg_bids_path.update(task=fname_replace)

    mne_bids.write_raw_bids(
        raw=raw_meg,
        bids_path=meg_bids_path,
        anonymize={"daysback": daysback},
        overwrite=True,
        verbose=True,
    )
```

The files are as expected:

```
.
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
└── sub-1001
    └── ses-20190416
        ├── meg
        │   ├── sub-1001_ses-20190416_coordsystem.json
        │   ├── sub-1001_ses-20190416_task-vid1_channels.tsv
        │   ├── sub-1001_ses-20190416_task-vid1_meg.fif
        │   ├── sub-1001_ses-20190416_task-vid1_meg.json
        │   ├── sub-1001_ses-20190416_task-vid2_channels.tsv
        │   ├── sub-1001_ses-20190416_task-vid2_meg.fif
        │   ├── sub-1001_ses-20190416_task-vid2_meg.json
        │   ├── sub-1001_ses-20190416_task-vid3_channels.tsv
        │   ├── sub-1001_ses-20190416_task-vid3_meg.fif
        │   ├── sub-1001_ses-20190416_task-vid3_meg.json
        │   ├── sub-1001_ses-20190416_task-vid4_channels.tsv
        │   ├── sub-1001_ses-20190416_task-vid4_meg.fif
        │   └── sub-1001_ses-20190416_task-vid4_meg.json
        └── sub-1001_ses-20190416_scans.tsv

3 directories, 18 files

```

and scans.tsv is fine as well (screenshot)

![image](https://user-images.githubusercontent.com/9084751/111470083-c09e3480-8727-11eb-8763-42ef2708598f.png)


I did a very brief video recording of my working directory as my code was running and the files were being written (see the attachment).

Interestingly, when the file gets written, it's initially with a `_split-` ... but this is then removed as soon as the actual file-writing is finished. I hope you can see that in the video. Not sure if this is related to your problem or not. Can you try to reproduce your issue using my code, please?

https://user-images.githubusercontent.com/9084751/111470144-d0b61400-8727-11eb-8fee-8a6262f1b2e4.mp4

](url)

**Comment by agramfort** [comment]
if it helps to understand in the old stable release we were writing in
float64 even if the initial data was float32
so it used to create unnecessary split files

>

**Comment by levchenkoegor** [comment]
@sappelhoff thank you for the test and code! With your code and packages with versions
```
dependencies:
...
  - conda-forge::mne=0.22.0
  - pip:
    - git+https://github.com/mne-tools/mne-bids.git 
```
everything works exactly as in your video!

But if I use `mne=0.21.0` and `mne-bids=0.7.dev0` (or `=0.6`), so I will have this issue with `split-01` suffix.

The behaviour of the script is exactly the same as yours, when I update `mne` to `0.22.0` and use any of versions of `mne-bids` (0.6 or 0.7.dev0).

As I understood from the [website](https://mne.tools/mne-bids/stable/install.html) dependence is: `mne(>=0.21)`. My guess that it is needed `mne>=0.22.0` for `mne-bids 0.6` to avoid this issue.

Please correct if I misunderstood something or my problem is still not reproducible for you.

**Comment by sappelhoff** [comment]
> But if I use mne=0.21.0 and mne-bids=0.7.dev0 (or =0.6), so I will have this issue with split-01 suffix.

indeed, I could replicate that :-)

When using `mne>=0.21.2` (not the `2` at the end!)  your bug also disappears.

This is already part of the development documentation: https://mne.tools/mne-bids/dev/install.html

In your case I suggest you just update to mne 0.21.2 :+1:

**Comment by sappelhoff** [comment]
This is another good hint that we should release v0.7 better sooner than later.

**Comment by sappelhoff** [comment]
So thanks for the report @levchenkoegor - I hope your issue is solved now!

If not, please reopen this.
