### ISSUE TITLE
write_raw_bids causing mne events error

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids#733]
Howdy folks
I am hitting an _AttributeError_ with `write_raw_bids` complaining about `mne.event.py`, so I'm not sure where this should go. `read_events` can read the binary events file but `event_list.shape = (-1, 3)` is causing a ruckus.

 Here's the trace...

>   File ".../raw_to_bids.py", line 30, in <module>
>     write_raw_bids(
>   File ".../mne_bids/write.py", line 1274, in write_raw_bids
>     events_array, event_dur, event_desc_id_map = _read_events(
>   File "...mne_bids/read.py", line 101, in _read_events
>     events = read_events(events_data, verbose=verbose).astype(int)
>   File "<decorator-gen-158>", line 20, in read_events
>   File ".../mne-python/mne/event.py", line 259, in read_events
>     event_list, event_id = _read_events_fif(f, tree)
>   File "..../mne/event.py", line 167, in _read_events_fif
>     event_list.shape = (-1, 3)

**Comment by hoechenberger** [comment]
Hello, could you please share the full traceback and the commands that lead to this behavior? Also, which versions of MNE and MNE-BIDS are you using?

**Comment by ktavabi** [comment]
This is the whole trace friend, I just deleted my home path...

> File ".../raw_to_bids.py", line 30, in 
> write_raw_bids(
> File ".../mne_bids/write.py", line 1274, in write_raw_bids
> events_array, event_dur, event_desc_id_map = _read_events(
> File "...mne_bids/read.py", line 101, in _read_events
> events = read_events(events_data, verbose=verbose).astype(int)
> File "", line 20, in read_events
> File ".../mne-python/mne/event.py", line 259, in read_events
> event_list, event_id = _read_events_fif(f, tree)
> File "..../mne/event.py", line 167, in _read_events_fif
> event_list.shape = (-1, 3)

I am on master dev branches ad43de7ce and 5a259f9f for mne and mne-bids.

**Comment by hoechenberger** [comment]
Again, please share the entire trace including the error message / part where the exception is raised, and the code you executed leading to this problem. Thanks.

**Comment by ktavabi** [comment]
> And I'm not your friend. Stop calling me that please.

It's a figure of speech, get over yourself, Dick.

**Comment by hoechenberger** [comment]
Don't you ever approach me again. Your behavior is unacceptable.
