### ISSUE TITLE
CIs are failing

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#741]
Anyone got time to look into this? :S

**Comment by sappelhoff** [comment]
I noticed that in https://github.com/mne-tools/mne-bids/pull/738#issuecomment-802887805 as well. No idea where these failures come from.

**Comment by hoechenberger** [comment]
I believe it's caused by this upstream change https://github.com/mne-tools/mne-python/pull/9103, looking into this now

**Comment by hoechenberger** [comment]
Ok I've tracked it down, also discovered another bug along the way … will file a PR tonight or sometime tomorrow.

**Comment by hoechenberger** [comment]
I've opened a PR upstream:
https://github.com/mne-tools/mne-python/pull/9175

Once merged, I will address an issue in MNE-BIDS that is somewhat related.

**Comment by rob-luke** [comment]
CI is now passing in PRs. Thanks @hoechenberger
