### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#748]
For sake of consistency with other MNE projects (e.g. MNE-Python, MNE-Realtime), we should rename the `master` branch to `main`.

Any oppositions?

**Comment by agramfort** [comment]
no objection

>

**Comment by larsoner** [comment]
+1

**Comment by larsoner** [comment]
No objection raised so I'll go ahead and do it!

**Comment by sappelhoff** [comment]
thanks @larsoner 

for all devs who need to change their git setup now, these are helpful instructions by @cbrnr: https://mne.discourse.group/t/we-have-renamed-the-main-development-branch-on-github-to-main/2526

**Comment by sappelhoff** [comment]
PS: I did some cleanup of renaming master to main in https://github.com/mne-tools/mne-bids/commit/3866db49f6887f53ef1b1ac147a13a44b7137811 and pushed that directly to master ... eeeer main ;-)
