### ISSUE TITLE
STY: Move to pydata-sphinx-theme

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids#749]
Now that NumPy, SciPy (in progress), pandas, and (most importantly I think) MNE-Python have moved to pydata-sphinx-theme, it might be nice to move `mne-bids` over, too, for cohesiveness. Any thoughts or objections?

**Comment by sappelhoff** [comment]
no objections, the motivation to move to pydata-sphinx-theme is very clear to me (discussed here: https://github.com/mne-tools/mne-python/issues/8184#issuecomment-685047720).

**Comment by larsoner** [comment]
@sappelhoff do you want to give it a shot? Hopefully it's less onerous than it was for MNE since the config and custom CSS used here is much simpler...

If not, I can take a look.

**Comment by sappelhoff** [comment]
> If not, I can take a look.

That'd be very nice! We have some docs on our documentation setup here: https://github.com/mne-tools/mne-bids/wiki/Explanation-of-Documentation-Setup

should be very similar to MNE, which is where most of it was copied from :thinking:
