### ISSUE TITLE
new EEGLAB files may contain fields in root of file, instead of nested in "EEG" struct

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#761]
see: https://github.com/mne-tools/mne-python/pull/8874

We need to apply @cbrnr's fix also here:

https://github.com/mne-tools/mne-bids/blob/415988e88f6253527d38d60dd521d0b94d5baa98/mne_bids/copyfiles.py#L516-L518

**Comment by hoechenberger** [comment]
And we should make use of the new test file he provided

**Comment by sappelhoff** [comment]
@cbrnr do you maybe have some time to take this over? :-) before users start running into this as a problem?

**Comment by cbrnr** [comment]
Sure!

**Comment by sappelhoff** [comment]
crosslink to potentially related issue: #654
