### ISSUE TITLE
Allow file extensions to be capitalized

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#763]
#### Describe the bug
Reading in EDF files with extension `.edf` or `.EDF` is the same in mne-python. It's just a casing issue. However, if we have files with `.EDF`, it throws an error right now because of a check.

#### Expected results
~~Apply lower-case to all extensions found in filenames that aren't case-sensitive (e.g. Nihon-Kohden)?~~ Add `.EDF` to acceptable keywords in config.py.

**Comment by sappelhoff** [comment]
+1, it seems that both `.edf` and `.EDF` are valid:

https://www.edfplus.info/specs/edfplus.html

> All EDF+ files must have .edf or .EDF as filename extension

**Comment by agramfort** [comment]
+1
