### ISSUE TITLE
Anatomical landmarks – defined set of keys?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#768]
According to the spec, [`AnatomicalLandmarkCoordinates `](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomical-landmarks) doesn't seem to enforce any sort of naming convention for the keys (landmark names); however, MNE-BIDS claims that there "MUST" be ``LPA``, ``RPA``, ``NAS``.

I have a dataset where the nasion is labeled `Nasion` instead of ``NAS``; I haven't run the bids-validator but according to the spec, this should be alright.

I suppose we should add a keyword argument to MNE-BIDS functions that work with landmarks, allowing users to supply a custom mapping of sidecar landmark names to LPA, RPA, and nasion. Or we simply make our functions more lenient, e.g. case-agnostic;  and we could accept  both `NAS` and `Nasion` for the nasion

**Comment by hoechenberger** [comment]
Just to provide a concrete example from the code:

https://github.com/mne-tools/mne-bids/blob/29f867bb824c84b03a18cd8583d7b711660f772e/mne_bids/read.py#L644-L649

**Comment by sappelhoff** [comment]
>  I haven't run the bids-validator but according to the spec, this should be alright.

you are absolutely right, and this is another spot where more standardization would have been beneficial. (NAS LPA and RPA are so common that it's really fair enough to tell everybody to also really name it like that)

**Comment by hoechenberger** [comment]
> you are absolutely right, and this is another spot where more standardization would have been beneficial. (NAS LPA and RPA are so common that it's really fair enough to tell everybody to also really name it like that)

Would it make sense to propose a "MUST name LPA, RPA, nasion: ..." for the next spec revision?

**Comment by sappelhoff** [comment]
I think we can only make that an explicit recommendation to not break backwards compatibility. but that would be worth it I think.

**Comment by hoechenberger** [comment]
> explicit recommendation

As in, SHOULD? 😅

**Comment by sappelhoff** [comment]
yeah :roll_eyes: I don't like it either, but we need to work with what we have.

**Comment by sappelhoff** [comment]
and obviously next to having a "SHOULD" it would involve adding a brief paragraph like:

> if you have nasion lpa, rpa, you SHOULD name them NAS LPA RPA ....

**Comment by hoechenberger** [comment]
Yep, all good.
