### ISSUE TITLE
Website out of date

### ISSUE THREAD

**Issue by wouterpotters** [mne-tools/mne-bids#775]
This website contains an excellent example to convert EEG to BIDS, but with errors:
https://mne.tools/mne-bids/v0.1/auto_examples/convert_eeg_to_bids.html#sphx-glr-auto-examples-convert-eeg-to-bids-py
e.g.:
 `from mne_bids import write_raw_bids, make_bids_basename`

`from mne_bids.utils import print_dir_tree`

However, the code on this website is out-of-date. I found this out when trying to make a pull request; the github repository does contain the correct example code. 

**Solution**: 

fix the website on https://mne.tools/mne-bids/v0.1/auto_examples/convert_eeg_to_bids.html#sphx-glr-auto-examples-convert-eeg-to-bids-py to contain the same code as here: https://github.com/mne-tools/mne-bids/blob/main/examples/convert_eeg_to_bids.py

**Comment by adam2392** [comment]
You're currently looking at a v0.1 website, so that code will work, but only for v0.1 release unfortunately.

For stable/development version, adjust the url. Here is the stable one:

https://mne.tools/mne-bids/stable/index.html

**Comment by wouterpotters** [comment]
Woops. missed that. Thank you for the quick response :)
