### ISSUE TITLE
copyfile_ctf additional files

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids#776]
Hi!

When using the copyfile.py `copyfile_ctf` function, these files: 
BadChannels, ChannelGroupSet.ctg, ClassFile.cls, and MarkerFile.mrk
which are not usually renamed, are not copied? are they useful for something? or can they just be omitted?

**Comment by agramfort** [comment]
yes they should be copie to keep the data as intact as possible but also I
think it should be used
to write bids files. For example

BadChannels should be used to mark channels as bad in _channels.tsv
MarkerFile.mrk should be used to make the _events.tsv file

for the other files I am not sure.

**Comment by sappelhoff** [comment]
I think mne-bids should copy these files over :thinking: 

But if I remember correctly, one issue was that these files can be empty, and the BIDS validator does not accept empty files. 

I opened an issue on that a long time ago: https://github.com/bids-standard/bids-validator/issues/651

> BadChannels should be used to mark channels as bad in _channels.tsv
MarkerFile.mrk should be used to make the _events.tsv file

I agree with that.

**Comment by hoechenberger** [comment]
> > BadChannels should be used to mark channels as bad in _channels.tsv
> > MarkerFile.mrk should be used to make the _events.tsv file
> 
> I agree with that.

+1

**Comment by sappelhoff** [comment]
> BadChannels, ChannelGroupSet.ctg, ClassFile.cls, and MarkerFile.mrk
which are not usually renamed, are not copied? are they useful for something? or can they just be omitted?

according to our code, all files in the CTF `.ds` directory should be copied, see the `_copytree(src, dest) ` function.

And then a subset of  files is getting renamed, while all other files retain their names:

https://github.com/mne-tools/mne-bids/blob/bc488fc0d77c9c7ac022e80489b39bafcbb9ca9c/mne_bids/copyfiles.py#L137-L166

So @guiomar can you perhaps share an example where the issue occurs that not all files are copied over with `mne_bids.copyfile_ctf`?

**Comment by guiomar** [comment]
Thanks a lot!! 

@giulia-berto would you mind providing some details? Could it be that because these are not renamed you were skipping them?

**Comment by guiomar** [comment]
Yes, that was the case! Thanks a lot!
