### ISSUE TITLE
doc build fails

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#781]
this is the error:

> /home/circleci/project/doc/whats_new_previous_releases.rst:268: WARNING: py:attr reference target not found: mne.io.Raw.annotations

I don't really see whats wrong with that: https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new_previous_releases.rst

**Comment by hoechenberger** [comment]
Let's just turn it into a verbatim string if we cannot figure it out within 2 minutes ;)
