### ISSUE TITLE
Problem with make_report() as reported on the forum

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#783]
This was with MNE-BIDS 0.7, so might be fixed in `main` already..?

https://mne.discourse.group/t/did-not-find-any-eeg-json-associated-with-in-mne-bids-make-report

**Comment by agramfort** [comment]
can you replicate?

>

**Comment by hoechenberger** [comment]
Haven't tried yet, will do later

**Comment by hoechenberger** [comment]
I believe the user's data was not conforming to BIDS, closing.
