### ISSUE TITLE
[BUG] Events stuttered with events_data and raw.annotations

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#784]
When `events_data` is passed to `write_raw_bids` as well as annotations in the `raw` argument, the events get stuttered (i.e. are applied twice). Probably `events_data` should overrule the annotation events.

Posting minimally reproducible example as soon as I get a chance.

**Comment by hoechenberger** [comment]
I personally would say we shouldn't try to be clever here. If the users provides raw data with annotations AND `events_data`, we should write both. If the users doesn't want to have duplicated events, well, they can simply **not** pass `events_data` then?

**Comment by alexrockhill** [comment]
Sounds good, I think a warning might be nice though because why would you have both?

**Comment by hoechenberger** [comment]
But how would you really test for this? There could be rounding errors (Annotations in seconds, events in samples), and how would we know that certain Annotations are actually a duplicate of events? Would could only be certain if we also had an events dictionary that maps event IDs to event names, and then we could compare those to the Annotations ...

**Comment by alexrockhill** [comment]
I think it would just be odd to pass both even if they are exactly the same...

**Comment by alexrockhill** [comment]
Just to warn if you pass the events_data and then you forgot your raw had the events in it basically, that would be nice I think

**Comment by agramfort** [comment]
it was design decision to write whatever is passed ie both if present. Use
raw.set_annotations() before to discard
annotations or don't pass events

>

**Comment by alexrockhill** [comment]
Just ran into the issue myself and thought a warning would be nice but if not that's fine

**Comment by hoechenberger** [comment]
@alexrockhill I think I'd be open for a very unsophisticated check: if there are any annotations in the raw and the user passes events, emit a warning

Would that work for you?

**Comment by hoechenberger** [comment]
Or actually, it should only be an Info and not a warning
