### ISSUE TITLE
tests for iEEG

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#79]
Currently the iEEG conversion is not at all tested.

cc @choldgraf

**Comment by jasmainak** [comment]
@choldgraf do you have any suggestion what data we should use for the testing here?

**Comment by choldgraf** [comment]
Whenever the iEEG spec gets merged there should be some sample datasets released as well, we could just use those (they're lightweight because they don't have the actual data). Or we could just define our own dataset

**Comment by jasmainak** [comment]
we do need actual data because `mne-bids` needs header information to write the `json` files. But on further thought, for the tests, we could probably make do with doing `raw.set_channel_types` and changing it to `ecog`. @monkeyman192 or @sappelhoff does any of you have time to take a stab at this?

**Comment by sappelhoff** [comment]
I can give it a shot, but we will definitely need a full pass of mne-bids (preferably by @choldgraf) to integrate iEEG  properly.

Note that iEEG will probably also support the [NWB](https://github.com/NeurodataWithoutBorders) and [MEF3](https://github.com/msel-source) file formats, which are not yet implemented in MNE-Python. So we won't be able to cover these for now.

**Comment by jasmainak** [comment]
iEEG is already implemented. So, it would be good to add just the tests (and any small related fixes). I would ideally not want to have it conflict too much with #99 and #106 . Thanks a lot for taking a shot at it !

**Comment by jasmainak** [comment]
I agree we'll need a PR which does a full-pass down the line, but I would say it's not a blocker for our release at the moment. If we have the tests, I'm happy for now :)
