### ISSUE TITLE
measurement date always tuple now

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#80]
with https://github.com/mne-tools/mne-python/pull/5500 the measurement date is always a tuple. This (correctly) messes up a few tests.
I saw that with 9ee36dd9ab8b77ab0415b4b9e048ede662310dfa @sappelhoff added a fix in one spot, but I was thinking it might be good to have this fix pushed through separately so that other PR's can be rebased and continue without having to wait for #78 
I can make a PR with the changes if you think it would be good to get it fixed ASAP (the goal is to keep this repo compatible with the master branch of mne-python anyway, not the public release right?)

**Comment by sappelhoff** [comment]
+1 for changing travis to run with mne master :-) ... or at least some hash of the master branch that is more recent than MNE-Python 0.16.

A bit like we are doing it with the BIDS-validator (which could also be "update", i.e., a newer hash for testing in this PR)

**Comment by monkeyman192** [comment]
I think it *is* is running with master, that's the problem and the reason the validation checks are failing... (hence the point of me making a PR to get tests to pass in mne-bids...)

**Comment by sappelhoff** [comment]
Mmh this line says we are running on the 0.16 maintenance branch:

https://github.com/mne-tools/mne-bids/blob/e03f013cfc897d116ce4d67d7bce6204d94a40a7/.travis.yml#L21

But I actually don't know what's happening on that branch

**Comment by monkeyman192** [comment]
Travis is, but appveyor which is the one that is failing is on the current master branch:
https://github.com/mne-tools/mne-bids/blob/master/appveyor.yml#L19
Travis should probably be updated to point to this too I guess...

**Comment by jasmainak** [comment]
okay to use `mne-python` master ...

**Comment by teonbrooks** [comment]
I suggest that we do freeze mne-bids with a version of mne-python at the point of release sometime in the future.

**Comment by jasmainak** [comment]
I agree with @teonbrooks that we should not force users to use bleeding edge `mne` ...

**Comment by monkeyman192** [comment]
is it possible to get it to test with a specific older version (say 0.16) and the most recent master version?
That way we maintain backward compatibility for users whilst ensuring that we maintain compatibility with any updates from mne as they come out

**Comment by jasmainak** [comment]
yep I think it's possible ... but we'll increase testing time. For now I'd say we can do it on a case-by-case basis. We don't have that many users yet to increase the maintenance burden too much
