### ISSUE TITLE
Allow write_raw_bids to save custom Raw objects loaded from more obscure filetypes

### ISSUE THREAD

**Issue by AKSoo** [mne-tools/mne-bids#803]
#### Describe the problem
Currently, `write_raw_bids` simply refuses to work with preloaded Raw objects to "prevent surprises". However, this feels like a heavy-handed solution that limits the function to file types MNE knows how to read. MNE allows users to create [objects from scratch](https://mne.tools/stable/auto_tutorials/simulation/10_array_objs.html) precisely for cases when they are working with obscure filetypes or synthetic data.

From looking at the code, I can't see why `preload` has to be false.

#### Describe your solution
Add a boolean parameter (say `custom`) that disables the `preload` check.

#### Describe possible alternatives
If there really is a good reason to reject preloaded Raw objects that I missed, alternative `write_raw_bids` function for custom Raw objects could be added.

**Comment by hoechenberger** [comment]
Hello and thanks for sharing your thoughts!

This has been discussed in #714; the reason for only supporting non-preloaded data is to avoid writing derivative data, which is currently not officially supported in MNE-BIDS (and not properly specified in the BIDS specification). 

IMHO the clean solution to the issue you describe is to add file format support upstream to MNE-Python for the particular formats in question, so you don't have to manually construct `Raw` from scratch.

**Comment by jasmainak** [comment]
another reason is that historically `mne-bids` copies the files in their original format. Since MNE lacks a function to write in format other than fif, the user may get the impression they changed the file while in reality it was just copied over. If you want to disable the `preload` check for some cases, you should have `format='fif'` or `format='bv'` only

**Comment by AKSoo** [comment]
> another reason is that historically `mne-bids` copies the files in their original format. Since MNE lacks a function to write in format other than fif, the user may get the impression they changed the file while in reality it was just copied over.

I think my solution of adding some parameter that explicitly disables `preload` check and saves preloaded objects could actually help with that. The default value would maintain the current behavior, but users who explicitly changed the parameter know what they are getting. Users may want to save preloaded object instead for various reasons.

**Comment by jasmainak** [comment]
out of curiosity, what file format are you dealing with?

**Comment by AKSoo** [comment]
> out of curiosity, what file format are you dealing with?

`.rhd` files which seem to be used exclusively by Intan Technologies. They provide open source [Python file readers](https://intantech.com/downloads.html?tabSelect=Software&yPos=0) that reads data into NumPy data structures.

**Comment by AKSoo** [comment]
> IMHO the clean solution to the issue you describe is to add file format support upstream to MNE-Python for the particular formats in question, so you don't have to manually construct `Raw` from scratch.

MNE actually recommends just building RawArray objects for uncommon file types: mne-tools/mne-python#5360. They don't seem interested in implementing this file format.

**Comment by agramfort** [comment]
this question comes back too often

maybe we can allow a param to write_raw_bids to allow writing preloaded data
that would be False by default and with a clear message

"BIDS is presently focussing on raw and non-preprocessed data. For this
reason we prevent writing preloaded data that have been potentially
modified. If you still want to write such a file to BIDS you can set the
parameter
`allow_preloaded=True` to be allowed to write your data."

thoughts?

>

**Comment by hoechenberger** [comment]
This would also immediately enable some sort of `derivatives` support, which … I am in support of. :) So that's a +1 from me.

**Comment by agramfort** [comment]
it seems @sappelhoff is also convinced so let's proceed

**Comment by jasmainak** [comment]
+1 from me as well

**Comment by hoechenberger** [comment]
This was closed via #819
