### ISSUE TITLE
MNE-BIDS Inspector modifies raw data – should we stop doing this?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#805]
During a discussion on data processing with @SophieHerbst, @crsegerie, and @agramfort we also talked about altering some metadata via the MNE-BIDS Inspector. Currently, it can be used to change the bad channel selection and annotations.

We're sometimes working with BIDS datasets that contain all sidecars, but the raw data is merely symlinked to the original (non-BIDS) data. In situations like these, one wouldn't want the Inspector to modify the raw, but only the respective sidecars when saving changes.

Now I looked into the code of the Inspector and we're actually **always** updating both, sidecars **and** raw data:
https://github.com/mne-tools/mne-bids/blob/79c7889e0e7b569d2ca6c45b7f09e6d6afa844a7/mne_bids/inspect.py#L151-L157

Questions:

- Should we entirely remove the ability to modify the raw data, so the Inspector could only alter sidecars?
- Or could another alternative be to check whether the data is stored in a symlinked file, and if yes, to not update it (and only alter the sidecars); and if it's not a symlink, we keep doing what we currently do (alter both, raw and sidecars)
- Or we could add a parameter to `inspect_dataset()` to control this

cc @sappelhoff

**Comment by sappelhoff** [comment]
related: https://github.com/bids-standard/bids-specification/pull/761

I think the best way would be to allow control over this via a parameter, but at the same time have the default from your point 2:

> check whether the data is stored in a symlinked file, and if yes, to not update it (and only alter the sidecars); and if it's not a symlink, we keep doing what we currently do (alter both, raw and sidecars)

**Comment by agramfort** [comment]
to me we should update the sidecar files only. They store what is the
closest to the truth and the raw
data should not be altered.

my 2c

>

**Comment by hoechenberger** [comment]
I can live with either approach. I'm sensing that @sappelhoff is leaning towards "modify the raw too to keep it in sync with the sidecars, unless this turns out to be super tricky", right? 😅

**Comment by sappelhoff** [comment]
> I can live with either approach. I'm sensing that @sappelhoff is leaning towards "modify the raw too to keep it in sync with the sidecars, unless this turns out to be super tricky", right?

right :-)

**Comment by hoechenberger** [comment]
Reconciliation attempt: when the user closes the Inspector and has modified the data, ask whether to save the changes to both raw & sidecars or to save to sidecars only. We already have a dialog box, maybe I can simply add a checkbox or something.

Thoughts?

**Comment by sappelhoff** [comment]
Would be fine with me 👍

**Comment by hoechenberger** [comment]
Actually I was mistaken here, it appears we're NOT modifying raw data at all, only the sidecars. It would take a bit of effort and time to add support for updating the raw too. As I'm happy with just updating the sidecars, I'll just close this issue for now.
