### ISSUE TITLE
update json files

### ISSUE THREAD

**Issue by LinaTeichmann1** [mne-tools/mne-bids#811]
Hi all, 

I'm trying to update the json file that is created with mne-bids following this example: https://mne.tools/mne-bids/dev/auto_examples/update_bids_datasets.html#sphx-glr-auto-examples-update-bids-datasets-py 

This is what I added to my code after write_raw_bids(...):
`sidecar_path = bids_path.copy().update(extension='.json')`
`entries = {'PowerLineFrequency': 60}`
`update_sidecar_json(sidecar_path,entries)`

However, I get this error:
~/anaconda3/envs/mne/lib/python3.9/site-packages/mne_bids/sidecar_updates.py in update_sidecar_json(bids_path, entries, verbose)
    109 
    110     # load in sidecar filepath
--> 111     with open(fpath, 'r') as tmp_f:
    112         sidecar_json = json.load(
    113             tmp_f, object_pairs_hook=OrderedDict)
**IsADirectoryError: [Errno 21] Is a directory: '/System/Volumes/Data/.../bids/sub-01/meg/sub-01_task-o_run-01_meg.ds'**

It looks like the problem is that the CTF data is a directory and not a file. Any advice on how I could still add things to the json file would be greatly appreciated :)

Thanks, 
Lina

**Comment by adam2392** [comment]
Hi Lina,

You probably want to change the `bids_path` to the json file, so something along the lines of:

```
bids_path.update(extension='.json')

update_sidecar_json(bids_path, entries)
```

Lmk if that works?

**Comment by LinaTeichmann1** [comment]
Hi Adam, 

Thanks for the quick rely. Unfortunately, it did not work. It gives me the same error back. This is what is in bids_path for me: 
`
bids_path
BIDSPath(
root: /System/Volumes/Data/.../bids
datatype: meg
basename: sub-01_task-o_run-01)`

and bids_path.extension is now set to '.json'. Error is still #21 IsADirectoryError...

Thanks, 
Lina

**Comment by adam2392** [comment]
Hmm not sure then... Can you copy/paste the full working example and also if possible provide a link to the dataset, then other people can chime in to see what the issue might be?

**Comment by LinaTeichmann1** [comment]
Yes of course. Here is an example dataset: https://osf.io/esdz7/?view_only=178f5ecc1e7a4958ba34ac5be8999bfc and the working example code is here:

https://github.com/LinaTeichmann1/example2/blob/5d6918df2bf61f5ea5bfdbb3b7bc1f1797384ffb/update_json_example.py#L1-L19

Thanks so much for having a look!

**Comment by adam2392** [comment]
You must specify the `suffix`. 

If you don't specify the `suffix`, then the path is `'/Users/adam2392/Downloads/example/sub-01/meg/sub-01_task-o_run-01.json`, which does not exist and there is no way to identify the file uniquely, so `mne-bids` defaults to trying to find the data file.

```
# working try
sidecar_path = bids_path.copy().update(suffix='meg', extension='.json')
entries = {'PowerLineFrequency': 60}
update_sidecar_json(sidecar_path, entries)
```

cc: @hoechenberger @sappelhoff @agramfort tbh not sure if this should be considered a bug, or if maybe just a lack of documentation. 

Imo when suffix is not set, but inferred it all works fine and great, unless they explicitly want another file (e.g. sidecar json, channels tsp, etc.)

**Comment by hoechenberger** [comment]
I've said it before, my personal opinion is that we should stop doing so much wizardry in trying to guess what the user could've meant; instead, error out early if the specified BIDSPath does not exist and be done with it. But that's just me…

**Comment by LinaTeichmann1** [comment]
Amazing! thank you so much for helping me with this -- works like a charm! 

Cheers, 
Lina

**Comment by adam2392** [comment]
I think IIRC we had an implementation standstill due to apathy and time constraints :p. I think because there are a lot of unit tests and documentation to update as a result.

I'm in favor of doing so, but don't think I have time until end of summer.

**Comment by hoechenberger** [comment]
> we had an implementation standstill due to apathy and time constraints

Daaaamn, the truth sometimes hits me real hard 🙈😁

**Comment by jasmainak** [comment]
close issue since user request was addressed?

**Comment by hoechenberger** [comment]
Good call @jasmainak, but feel free to reopen if needed
