### ISSUE TITLE
Release 0.8 ? 

### ISSUE THREAD

**Issue by christinerogers** [mne-tools/mne-bids#816]
Hi, 
I'm wondering if 0.8 might be released within the next month? 

We'd love to use some recent changes used on main for a new tool(*)
especially datatype handling #774 and casing #765

Linking to an MNE-BIDS release instead of main would be ideal, if that's possible soon. 

Thanks very much,
 -- Christine . Rogers [at] McGill.ca 
Montreal Neurological Institute | github.com/aces/LORIS 
cc @laemtl

(*) We're deploying an open gui tool to help users convert EEG to BIDS, starting with EDF for EEG and iEEG (stereo) - basically a python/js wrapper on MNE-BIDS.  Will be looking for feedback soon and of course any contributions, unfortunately just missed the timeline for sharing it at OHBM BrainHack.

**Comment by hoechenberger** [comment]
Hello Christine,

your tool sounds amazing, this could potentially help a lot of users on their journey to BIDS land 😍

I think we could cut a release rather soon … in fact, our `main` branch is practically always "release-ready", and it's really just a matter of us actually going through the process of cutting a release.

@sappelhoff Any objections on releasing within the next week?

**Comment by sappelhoff** [comment]
No objections, on the contrary - I briefly discussed this with @christinerogers on the brainhack mattermost and think it'd be good to do a release (if everybody agrees and we get potential blockers out of the way)

**Comment by christinerogers** [comment]
Thanks!   
Tagging also my colleague @laemtl who has been working on the specific code issues.  

And thanks @hoechenberger - We're excited to see how it will go with our first batch of users and definitely plan for it to be useful to the larger community.

**Comment by sappelhoff** [comment]
@agramfort @hoechenberger should I do the release in the next days? Or are there some PRs that you definitely want to get in?

**Comment by agramfort** [comment]
Wait for the fix with trans  and landmarks

**Comment by hoechenberger** [comment]
Yes I'd vote for those fixes!

**Comment by hoechenberger** [comment]
From my end, all is good to make the 0.8 release now!

**Comment by sappelhoff** [comment]
cool! I'll see whether I can get to #829 and #831 soon, and then make a release.

**Comment by agramfort** [comment]
no objection to release now on my end

>

**Comment by sappelhoff** [comment]
in progress now

**Comment by sappelhoff** [comment]
I don't think I can/should make the release :rofl: The navbar is gone from our docs. I just noticed it now and I have no idea how long it's been missing, and how to get it back. https://mne.tools/mne-bids/dev/index.html

**Comment by sappelhoff** [comment]
Not done yet, but it's looking better. Will continue later.

**Comment by sappelhoff** [comment]
https://pypi.org/project/mne-bids/0.8/ :tada:

**Comment by sappelhoff** [comment]
cc @christinerogers

**Comment by agramfort** [comment]
Tweet ?

**Comment by sappelhoff** [comment]
https://twitter.com/stefanappelhoff/status/1415605870197628930

**Comment by sappelhoff** [comment]
I used the second half of your favourite quote @agramfort :smile:

**Comment by christinerogers** [comment]
Thanks very much to your team! 
 Looking forward to deploying with this new release (we'll let you know if any issues are spotted re #774 and #765) 
and will share our converter gui tool for beta testing when ready.
