### ISSUE TITLE
AnatomicalLandmarkCoordinates in RAS or VOX?

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#821]
we write AnatomicalLandmarkCoordinates in RAS in the MRI sidecar .json file e.g. for storing the trans file. See:

https://mne.tools/mne-bids/dev/auto_examples/convert_mri_and_trans.html

yet the standard says apparently it should be in voxels see:

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomical-landmarks

I bumped into the issue as this file is actually in voxel and I thought it was a bug with the dataset:

https://openneuro.org/datasets/ds000117/versions/1.0.4/file-display/sub-01:ses-mri:anat:sub-01_ses-mri_acq-mprage_T1w.json

are we the ones wrong with mne_bids?

cc @sappelhoff @robertoostenveld @jasmainak

**Comment by agramfort** [comment]
still investigating ... maybe there is no bug ...

**Comment by sappelhoff** [comment]
The `AnatomicalLandmarkCoordinates` are possible for MEG, EEG, iEEG, and MRI: You are looking at the MRI spec, where it has to be specified in voxels.

For all others, it has to be specified according to `AnatomicalLandmarkCoordinateSystem`, see: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson (scroll down).

It doesn't line up perfectly between MRI and the rest, unfortunately.

**Comment by sappelhoff** [comment]
Is this still an issue @agramfort ?

**Comment by agramfort** [comment]
all good now with #827
