### ISSUE TITLE
bidspath example contains runtimewarning

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#829]
https://mne.tools/mne-bids/dev/auto_examples/bidspath.html#bidspath-example

> /home/circleci/project/mne_bids/path.py:587: RuntimeWarning: Could not locate a data file of a supported format. This is likely a problem with your BIDS dataset. Please run the BIDS validator on your data. (root=my_bids_root, basename=sub-123_ses-test). []
  warn(msg)
  
and there are 2 more of those. At least it should be discussed in the example why there is such a warning.

**Comment by sappelhoff** [comment]
this is related to #712 #721 and the fetching behavior of `BIDSPath.fpath`

**Comment by hoechenberger** [comment]
Shall we finally kill off all the BIDSPath "trying to guess what the user meant" magic? :)

**Comment by sappelhoff** [comment]
> Shall we finally kill off all the BIDSPath "trying to guess what the user meant" magic? :)

yes :100: Let's do it in 0.9 :pray:
