### ISSUE TITLE
write_raw_bids() should raise if no task is provided

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#841]
@dnacombo and I created an entire BIDS dataset and we unfortunately forgot to pass a `task` entity to the `BIDSPath` passed to `write_raw_bids()`. Now we'll have to rename everything … shouldn't have happened in the first place – `task` is required by BIDS!

**Comment by hoechenberger** [comment]
I was just thinking about specifically adding a test to write_raw_bids, not to BIDSPath. This will avoid collateral damage, no?

**Comment by sappelhoff** [comment]
doing it in BIDSPath is probably stricter and better in terms of other functions "inheriting" this check ... but yeah, it could be inflexible and do more harm. I am fine with adding the check to write_raw :+1:
