### ISSUE TITLE
Question: What is the proper way to use -trans.fif file with multiple run/sessions?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-bids#847]
Hi,

I am unclear on how to use the `get_anat_landmarks` and `write_anat` functions. Specifically, `get_anat_landmarks` requests `raw.info`, which is subject/session/run specific, but I *guess* the landmarks are just subject specific? 

What is the recommended way to save landmarks? Use any (random session/run) `raw` from each subject? 
```python
landmarks = get_anat_landmarks(
    t1_fname,               # one for each subject
    info=raw.info,          # one for each subject/session/run
    trans=trans,            # only one per subject/session?
    ...
)

# We use the write_anat function
t1w_bids_path = write_anat( # on per subject IIUC 
    image=t1_fname,
    bids_path=t1w_bids_path,
    landmarks=landmarks,  
)
```

Thanks!

**Comment by agramfort** [comment]
if you have one anat and two sessions it's still a pb I think. I have a
dataset with exactly this issue.

Now regarding runs it should not be a problem. The runs should have the
same digitization and assuming
this is not head movement between runs it's the same forward. ok for you in
this case?

**Comment by kingjr** [comment]
thanks @agramfort for the swift response.

> if you have one anat and two sessions it's still a pb I think. I have a dataset with exactly this issue.

ok

> Now regarding runs it should not be a problem. The runs should have the same digitization and assuming this is not head movement between runs it's the same forward. ok for you in this case?

Not a good assumption IMO, subjects are typically asked to take a break/place themselves correctly in between runs.

**Comment by agramfort** [comment]
>
> Not a good assumption IMO, subjects are typically asked to take a
> break/place themselves correctly in between runs.
>

with neuromag we have maxfilter that realigns all runs to the same head
position. So it's ok but I hear your concern.
You would have one forward matrix per run?

**Comment by kingjr** [comment]
> You would have one forward matrix per run?

This is KIT data, so no maxfilter. I think it would be the same on another dataset I'm working with (CTF). I'm happy to run by the one-forward-matrix-assumption for now, but I think this will likely need a fix in the long-run.

**Comment by agramfort** [comment]
>
> This is KIT data, so no maxfilter. I think it would be the same on another
> dataset I'm working with (CTF). I'm happy to run by the
> one-forward-matrix-assumption for now, but I think this will likely need a
> fix in the long-run.
>

mne-bids is not a problem in this case no?
you can get a trans per run. What should we fix here?

maxfilter support for KIT data has been experimented by @larsoner already

**Comment by kingjr** [comment]
> mne-bids is not a problem in this case no? you can get a trans per run. What should we fix here?

Maybe I'm not clear about where the trans information is stored, but I have the impression you can't specify a landmark per per run, because `write_anat` does not write a session-specific file. However, it's true that landmarks should not vary across essions. So I guess I should take a random trans file to retrieve the landmark? 

> maxfilter support for KIT data has been experimented by @larsoner already

Shouldn't we favour releasing raw as opposed to maxfiltered data?

**Comment by agramfort** [comment]
>
> Maybe I'm not clear about where the trans information is stored, but I
> have the impression you can't specify a landmark per per run, because
> write_anat does not write a session-specific file. However, it's true
> that landmarks should not vary across essions. So I guess I should take a
> random trans file to retrieve the landmark?
>

yes. Any trans should do it.


> maxfilter support for KIT data has been experimented by @larsoner
> <https://github.com/larsoner> already
>
> Shouldn't we favour releasing raw as opposed to maxfiltered data?
>
yes we should release in BIDS the raw data. But you can then process them
the way you want.

in the https://github.com/mne-tools/mne-bids-pipeline/ we align all runs to
one head position.
