### ISSUE TITLE
get_anat_landmarks() should accept BIDSPath as image param

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#851]
The `image` parameter of `mne_bids.get_anat_landmarks()` currently cannot be a `BIDSPath`, even though it would feel very natural to pass a `BIDSPath` here. In fact, that's precisely what I did, only to run into an issue with `nibabel` I believe (I don't have the error message at hand). Workaround for me was to pass `image=bids_path.fpath`, but that's really something we could do automatically, don't you think?

cc @alexrockhill

**Comment by alexrockhill** [comment]
Yes, sound very reasonable and like a quick PR. I can do it if you're busy

**Comment by hoechenberger** [comment]
That would be great! But no pressure :)

**Comment by alexrockhill** [comment]
Ah in writing the tests, I think the reason it's not that way already is it that the image shouldn't likely be in BIDS format yet because you're going to pass it to `write_anat`. Similarly `write_anat` doesn't accept a `BIDSPath` either because it's a bit circular to ask for a BIDSPath when the goal of the function is to write something in BIDS. I can still make the PR and I think it's fine to support this but it makes confusing tests where you write to BIDS and then use that BIDS directory to write another one.

**Comment by hoechenberger** [comment]
Hello Alex, thanks for taking a stab at this!

I think I know what you mean, but let me explain my use case:

We have converted a dataset with MEG and MRI scans to BIDS. At the time of conversion, no coregistration had been done (the data was taken "straight from the lab", so to speak), hence the anatomical landmarks weren't available for the MR images.

After the BIDS conversion, I ran FreeSurfer's `recon-all` and performed the coregistration with MNE. Now I want to store my shiny new MRI anatomical landmarks in the existing BIDS dataset. This is important both for the sake of "completeness" and also to allow me to easily anonymize the data later on.

So after the coregistration, I take the trans and ask `get_anat_landmarks()` for the MRI landmarks, which I then pass to `mne_bids.update_anat_landmarks()` to update the MRI sidecar file. Here's the respective snippet from my code:

```python
        logger.info(f'Launching coregistration for subject: {subject}')
        bids_path_raw = mne_bids.BIDSPath(root=bids_root, subject=subject,
                                          datatype='meg', suffix='meg',
                                          run='01',
                                          task='tiwm', extension='.fif')
        bids_path_t1 = bids_path_raw.copy().update(
            datatype='anat', suffix='T1w', run=None, task=None,
            extension='.nii.gz'
        )

        fs_subject = f'sub-{subject}'

        mne.bem.make_scalp_surfaces(
            subject=fs_subject,
            subjects_dir=fs_subjects_dir,
            force=True,
            overwrite=True
        )

        coreg_frame = mne.gui.coregistration(
            inst=bids_path_raw.fpath,  
            subject=fs_subject,
            subjects_dir=fs_subjects_dir,
            head_high_res=True,
            scale_by_distance=False,
            mark_inside=True,
            height=1000,
            advanced_rendering=True
            # advanced_rendering=False
        )

        trans = mne.Transform(fro='head', to='mri',
                              trans=coreg_frame.model.head_mri_t)
        info = mne.io.read_info(bids_path_raw.fpath)

        mri_landmarks = mne_bids.get_anat_landmarks(
            image=bids_path_t1.fpath,
            info=info,
            trans=trans,
            fs_subject=fs_subject,
            fs_subjects_dir=fs_subjects_dir
        )

        mne_bids.update_anat_landmarks(
            bids_path=bids_path_t1,
            landmarks=mri_landmarks
        )
```
I think it becomes clear here that it would be nice if I could pass `bids_path_t1` directly to `get_anat_landmarks()`.

I do see the difficulty you're experiencing with the test. I'm wondering if it's related to the fact that, as you state, currently `get_anat_landmarks()` is getting tested in `test_write.py`, and is mentally coupled with `write_anat()`. I'm wondering if it could make sense to move `get_anat_landmarks()` outside of `write.py` and into a new module, `anat.py`. This would help clear up the mental model (at least the **my** mental model, haha)

WDYT?

**Comment by hoechenberger** [comment]
Actually. Let's just leave it as-is. I'm happy with the changes from #852. No need to get caught up in unrewarding, unnecessary work ;)

**Comment by alexrockhill** [comment]
Yeah sounds reasonable, after writing that I realized, `get_anat_landmarks` was split off from `write_anat` and they will probably be used slightly differently and not always one before the other. It doesn't make sense to have a BIDSPath for `write_anat` but it does I think for `get_anat_landmarks` in case it's used after like you did.
