### ISSUE TITLE
Too much verbosity in `write_raw_bids`

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#861]
I'm not sure if anyone else shares this opinion, but I think there is so much text output to the console in `write_raw_bids` that important information is likely to get lost in the deluge. `verbose=False` isn't very appealing either because it is nice to get some information. Would it be more helpful to users to print that a sidecar or data file was successfully written, maybe with a few key attributes that you would want to know were written correctly?

**Comment by hoechenberger** [comment]
+1000, and I think @adam2392 agrees too

I think this should be tackled as part of #773

**Comment by agramfort** [comment]
+1e6

>

**Comment by sappelhoff** [comment]
I am also in favor 💯🤠

**Comment by alexrockhill** [comment]
Maybe we could add a function or keyword argument to print all the text written to the console as that has been helpful to me at times and I assume that's why it was made that way in the first place. Something like `print_dir_tree` perhaps but more like `print_subject_details` or something that prints all the meta files and subject-specific files that have to do with that subject for debugging. Also, this part that @adam2392 wrote could be part of it as well to somehow guide you through filling in `n/a`s.

```
# Now it's time to manually check the BIDS directory and the meta files to add
# all the information that MNE-BIDS could not infer. For instance, you must
# describe ``iEEGReference`` and ``iEEGGround`` yourself.
# It's easy to find these by searching for ``"n/a"`` in the sidecar files.
#
# ``$ grep -i 'n/a' <bids_root>``

```
