### ISSUE TITLE
`copyfile_*` fails in `write_raw_bids` when `overwrite=True` and `src==dest`

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#867]
#### Describe the bug
I am trying to append annotations to the events.tsv file. I found that the easiest way to do so is to simply do: i) read_raw_bids, ii) append annotations to the read in raw object and then iii) write_raw_bids again.

However, if I'm writing to the exact same location, then the file actually is removed. I think this is perhaps hidden behavior of `shuttle.copyfile(src, dest)`, where if src and dest are the same, then the file is deleted.

#### Steps to reproduce
```
raw = read_raw_edf(<some_edf_file>)
bids_path = BIDSPath(root=root, subject='001', datatype='eeg')
output_bids_path = write_raw_bids(raw, bids_path)

raw = read_raw_bids(output_bids_path)
write_raw_bids(raw, output_bids_path)
```

#### Expected results
At the very least, an error should be raised, and the file shouldn't be deleted.

Otherwise, if the file already exists, then copy somewhere temporarily and then copy to the same place again? The con is that one writes twice now.

#### Actual results
File is deleted, and the program errors.

#### Additional information
〈Replace this text with information about your system. For example through
using MNE-Python and running `mne.sys_info()` and pasting the output here.〉

**Comment by hoechenberger** [comment]
According to the Python docs:

> If src and dst specify the same file, SameFileError is raised.

So if the file disappears then this is not due to `copyfile`, but the deletion must occur somewhere else

**Comment by sappelhoff** [comment]
I can't replicate this issue on mne-bids and mne-python `main`:

```python
import os
import mne
from mne_bids import BIDSPath, write_raw_bids, read_raw_bids


testing = mne.datasets.testing.data_path()
fin = os.path.join(testing, "EDF", "test_generator_2.edf")
root = os.path.join(os.path.expanduser("~"), "Desktop", "mne_bids_issue-867")
os.makedirs(root, exist_ok=True)
raw = mne.io.read_raw_edf(fin)
bids_path = BIDSPath(root=root, subject='001', datatype='eeg')
output_bids_path = write_raw_bids(raw, bids_path)

raw = read_raw_bids(output_bids_path)
write_raw_bids(raw, output_bids_path)
```

It raises a `FileExistsError`, as expected (see Richards comment above)

**Comment by hoechenberger** [comment]
> It raises a `FileExistsError`, as expected (see Richards comment above)

No, I expected a `SameFileError` based on the Python docs 😅😅😅

**Comment by hoechenberger** [comment]
> > It raises a `FileExistsError`, as expected (see Richards comment above)
> 
> No, I expected a `SameFileError` based on the Python docs 😅😅😅

Ah no, wait, only for `copyfile` I would expect this 😁
