### ISSUE TITLE
Duplicate Event Reporting in tsv output

### ISSUE THREAD

**Issue by jstout211** [mne-tools/mne-bids#872]
#### Describe the bug
The events.tsv written with write_raw_bids() - has duplicate entries for every event.  These duplicates are not in the raw datasets.  
This is happening for both mne(v0.23)/mne-bids(0.8) and mne(v0.24dev)/mne-bids(0.9dev) environments.

events =
...
       [737241,      0,      2],
       [738957,      0,      1],
       [739200,      0,      1],
       [740107,      0,      3],
       [744144,      0,      2],
       [745937,      0,      1],
       [746805,      0,      3],
       [749707,      0,      2],
       [751367,      0,      1]])

TSV_file: 
307.18375	0.0	deviant	2	737241
307.18375	0.0	deviant	2	737241
307.89875	0.0	button	1	738957
307.89875	0.0	button	1	738957
308.0	0.0	button	1	739200
308.0	0.0	button	1	739200
308.3779166666667	0.0	standard	3	740107
308.3779166666667	0.0	standard	3	740107
310.06	0.0	deviant	2	744144
310.06	0.0	deviant	2	744144
310.8070833333333	0.0	button	1	745937
310.8070833333333	0.0	button	1	745937
311.16875	0.0	standard	3	746805
311.16875	0.0	standard	3	746805
312.3779166666667	0.0	deviant	2	749707
312.3779166666667	0.0	deviant	2	749707
313.06958333333336	0.0	button	1	751367
313.06958333333336	0.0	button	1	751367

#### Steps to reproduce
```
import os
import os.path as op

import mne
from mne.datasets.brainstorm import bst_auditory
from mne.io import read_raw_ctf

from mne_bids import BIDSPath, write_raw_bids

data_path = bst_auditory.data_path()

subject = 'bst_auditory'
subjects_dir = op.join(data_path, 'subjects')

raw_fname1 = op.join(data_path, 'MEG', subject, 'S01_AEF_20131218_01.ds')

raw = read_raw_ctf(raw_fname1)
events, event_ids = mne.events_from_annotations(raw)

bids_dir = './bids_out'
if not os.path.exists(bids_dir): os.mkdir(bids_dir)


output_path = bids_dir
raw = read_raw_ctf(raw_fname1)  
raw.info['line_freq'] = 50 

events, event_ids = mne.events_from_annotations(raw)

sub = '0' 
ses = '01'
task = 'somatosensory'
run = '01'
bids_path = BIDSPath(subject=sub, session=ses, task=task,
                     run=run, root=bids_dir, suffix='meg')
write_raw_bids(raw, bids_path, events_data=events, 
               event_id=event_ids, overwrite=True)

```

#### Expected results
1 entry per event

#### Actual results
2 entries per event

#### Additional information
Platform:      Linux-5.4.0-81-generic-x86_64-with-glibc2.10
Python:        3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0]
Executable:    /home/jstout/miniconda3/envs/enigma/bin/python
CPU:           x86_64: 20 cores
Memory:        125.5 GB

mne:           0.23.0
numpy:         1.20.1 {blas=openblas, lapack=openblas}
scipy:         1.6.1
matplotlib:    3.3.4 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.24.1
numba:         0.53.0
nibabel:       3.2.1
nilearn:       0.7.1
dipy:          1.4.0
cupy:          Not found
pandas:        1.2.3
mayavi:        Not found
pyvista:       0.29.0 {pyvistaqt=0.3.0, OpenGL 4.5.0 NVIDIA 460.91.03 via Quadro RTX 8000/PCIe/SSE2}
vtk:           9.0.1
PyQt5:         5.15.4

**Comment by agramfort** [comment]
you already have the annotations in raw.annotations

if you pass events and event_id you write the annotations twice.

just do not pass events or do raw.set_annotations() # to remove them

**Comment by jstout211** [comment]
Yes, this did work.  Thanks for heads up.  

Appreciate the help
