### ISSUE TITLE
Add `suffix` to entities property in BIDSPath

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#879]
get_entities_from_fname returns 'suffix', so BIDSPath.entities should also return suffix.

**Comment by hoechenberger** [comment]
The suffix is not an entity, so strictly speaking `get_entities_from_fname()` actually should lose its ability to return the suffix

maybe we should allow to control this behavior via a kwarg

**Comment by sappelhoff** [comment]
> The suffix is not an entity, so strictly speaking get_entities_from_fname() actually should lose its ability to return the suffix

agreed, that's unnecessarily confusing. we should have a different way to get the suffix

**Comment by adam2392** [comment]
Perhaps it should be `get_suffix_from_fname()` and `BIDSPath.entities` should remove the `suffix` then, and only access the `suffix` from `BIDSPath.suffix`?

**Comment by hoechenberger** [comment]
Or we should have `get_properties_from_fname` or something, which returns a dict with keys `entities`, `suffix`?

**Comment by adam2392** [comment]
It begs the question, should we have a function called, `get_bids_path_from_fname` as well? 

```
fname = some_path.rglob('*.edf')[0]

# to use read_raw_bids, I need to convert to BIDSPath
bids_path = get_bidspath_from_fname(fname)
raw = read_raw_bids(bids_path)
```

??

**Comment by hoechenberger** [comment]
> get_bids_path_from_fname

After thinking about this for approx. 2.8 seconds, I'm loving this idea! Maybe that's the only one we'd need!

**Comment by adam2392** [comment]
Are you suggesting remove get entities from frame altogether?

Thoughts? @sappelhoff @jasmainak @agramfort

**Comment by sappelhoff** [comment]
I don't like it that `get_entities_from_fname` returns a suffix, and I think that should be fixed, maybe through something like `get_properties_from_fname` like Richard suggested.

I am also +1 for a `get_bids_path_from_fname`, but not sure if having that would want us to entirely drop `get_entities_from_fname`

**Comment by jasmainak** [comment]
I like `get_bids_path_from_fname`. For dropping `get_entities_from_fname` no opinion as it's part of the public API. As before, I recommend deprecation cycle from now on :-)

**Comment by adam2392** [comment]
I think, let's keep `get_entities_from_fname` since it is still useful in its own right by getting entities directly from a filename.

Alright, I'll add a `get_bids_path_from_fname` when I have time.
