### ISSUE TITLE
EEGLAB: allow to copy .fdt files and update the pointer in corresponding .set

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#88]
EEGLAB files are MATLAB files ... albeit with a `.set` extension instead of the usual `.mat`. The EEGLAB files can contain the EEG data in a matlab struct field called `data`. However, this `data` field can alternatively contain a link to an accompanying (separate) `.fdt` (=FloatDaTa) file. 

Currently MNE-BIDS only allows the standalone `.set` files and thorws an error when an `.set`+`.fdt` combination is used. This should be fixed, see:

https://github.com/mne-tools/mne-bids/blob/7403fc56b33bfe9b61e2cd7ee214ab9ad24312b0/mne_bids/utils.py#L497-L505

**Comment by jasmainak** [comment]
+1 sounds like an easy fix ...
