### ISSUE TITLE
[ENH] implement coordsystem.json and electrodes.tsv for (i)EEG

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#89]
Currently the `mne_bids._coordystem_json` function is only working for MEG:

https://github.com/mne-tools/mne-bids/blob/7403fc56b33bfe9b61e2cd7ee214ab9ad24312b0/mne_bids/mne_bids.py#L615-L619

for EEG, the coordystem specifications are slightly different, see: 

- https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit#heading=h.becxwmq8vdr6

Also, an `electrodes.tsv` file is needed to then make use of the coordsystem in EEG:

- https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit#heading=h.lk6gn8gxt597

Both should be added to MNE-BIDS.

BONUS: Make it work for iEEG as well ;-)

cc @choldgraf

**Comment by choldgraf** [comment]
I agree! I think the main reason that I didn't push on this before was because it was unclear how the whole coordsystem debate would settle in the specification. Do you think we now have a clear idea of how these will be defined for (i)EEG?

**Comment by sappelhoff** [comment]
> Do you think we now have a clear idea of how these will be defined for (i)EEG?

Unfortunately, there seem to be a few differences between iEEG and EEG, as we can also see in the JSON schemas used in the validator:
- EEG: https://github.com/INCF/bids-validator/blob/master/validators/schemas/coordsystem_eeg.json
- iEEG: https://github.com/INCF/bids-validator/blob/master/validators/schemas/coordsystem_ieeg.json

in EEG, we basically have the following:

x,y,z positions of electrodes in space are described in an `electrodes.tsv` file.

To interpret these positions we have `coordsystem.json`, with the fields:
-  "EEGCoordinateSystem"
-  "EEGCoordinateUnits"
-  "EEGCoordinateSystemDescription"

All of that can be used to refer to a T1 MRI scan via the `IntededFor` key pointing to the respective scan.

Lastly, for anatomical landmarks, we have a couple of keys following the same structure as above.

I am so far pretty happy with this way how to do things ... what issues do you have?

**Comment by sappelhoff** [comment]
Once https://github.com/mne-tools/mne-python/pull/6402 is merged in MNE-Python, I will probably be able to tackle this issue for EEG data.

I have some digitization data for BrainVision EEG :-)

To Do
- [ ] get functionality in MNE-Python to read "CapTrack" `.bvct` files
- [ ] figure out how I can distinguish between "Montages" and "DigMontages" if I have EEG data
- [ ] convert any DigMontage to FIF Coordinate system
- [ ] write the converted coord system as an `electrodes.tsv` and `coordsystem.json` file for EEG

I am not fit to do this for iEEG - I'll leave that to iEEG users :wink:

**Comment by adam2392** [comment]
> I am not fit to do this for iEEG - I'll leave that to iEEG users 😉

I am an iEEG user :p, but we will have to see if I am up to the task. I would be interested in attempting to take this on for iEEG data.

**Comment by jasmainak** [comment]
That would be great, if you can try `mne-bids` on iEEG data and see what are the pain points!

**Comment by adam2392** [comment]
@sappelhoff @jasmainak Just want to clarify, would it be best to piggy back off #263 code wip, or start my own from the master branch?

It looks like the main functionality developed in #263 is what @sappelhoff mentioned as scalp EEG. Seems like there are a lot of nuances there mainly due to montage system and head shape customizations (I believe). 

 On the other hand iEEG is pretty straightforward generally. All that would be required is a reference image (e.g. preop T1 MRI, postop T1MRI, or postop CT; op = implantation procedure), the units (e.g. mm), and you're good to go. I think this should honestly be fairly straightforward and I have some coord data I can test w/.

Another point I was wondering is, that in general to get the iEEG coords, you use a affine registration scheme to map coords from CT -> T1 MRI. Would it be useful to store this 4x4 matrix in the coord_system data structure for ieeg?

**Comment by sappelhoff** [comment]
> would it be best to piggy back off #263 code wip, or start my own from the master branch?

if you want to focus on iEEG exclusively, then starting from `master` may be better ... :thinking: 

regarding your second question:

> Would it be useful to store this 4x4 matrix in the coord_system data structure for ieeg?

-> this is a BIDS question, not an mne-bids question. :-) We try to focus on what's supported in the [specification](https://bids-specification.readthedocs.io/en/stable/), so please verify with iEEG-BIDS people first.
