### ISSUE TITLE
Simplify storage of empty-room data

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#895]
Currently, storing empty-room data is unnecessarily complicated and error-prone.

Current approach:

- manually create a `BIDSPath` with `subject='emptyroom'`, `task='noise'`, and `session='YYYYMMDD'` (meaning one first has to manually construct the date/session string)
- pass this `BIDSPath` and the empty-room raw to `write_raw_bids`

Problems:

- `write_raw_bids` special-handles the `emptyroom` subject
- this is not documented anywhere
- if there's a typo in the subject name, the empty-room-special-handling branches of code will be omitted and the user won't be notified, as empty-room data will be treated like regular experimental data
- inconsistent behavior when the user requests anonymization: suddenly, `write_raw_bids` starts fiddling with `bids_path.session` to ensure that `daysback` is applied there as well, meaning that the data is written to a session directory that differs from what the user explicitly passed
- before we anonymize, we demand that empty-room session and the date in `raw.info` are the same and raise an exception otherwise; again, this behavior is not documented

Proposal:

- Add a kwarg `is_emptyroom` to `write_raw_bids`; if `True`, automatically set `subject`, `task`, `session` (and ignore values potentially present in `bids_path`)

Problem with proposal:

- We already have a kwarg `emptyroom`, which could lead to confusion. We could rename it to `emptyroom_bids_path` or `er_bids_path`, though?

Alternatives:

- Add a dedicated `write_raw_bids_emptyroom` function. Seems overkill?

**Comment by agramfort** [comment]
can you paste how the user code  looks now and how it would look like with
your proposal?

>

**Comment by hoechenberger** [comment]
Current approach (important bits indicated by the pointing fingers):
```python
from pathlib import Path

import mne
from mne.datasets import sample

from mne_bids import (write_raw_bids, BIDSPath)

data_path = Path(sample.data_path())
raw_fname = data_path / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
er_raw_fname = data_path / 'MEG' / 'sample' / 'ernoise_raw.fif'
bids_root = data_path.parent /  'MNE-sample-data-bids'

raw = mne.io.read_raw_fif(raw_fname)
raw_er = mne.io.read_raw_fif(er_raw_fname)
raw.info['line_freq'] = 60
raw_er.info['line_freq'] = 60


bids_path = BIDSPath(
    subject='01',
    task='audiovisual',
    root=bids_root,
    suffix='meg',
    extension='.fif',
    datatype='meg'
)

# 👇 👇 👇
er_date = raw_er.info['meas_date'].strftime('%Y%m%d')
bids_path_er = bids_path.copy().update(
    subject='emptyroom',
    task='noise',
    session=er_date
)
write_raw_bids(raw=raw_er, bids_path=bids_path_er, overwrite=True)
# 👆 👆 👆

write_raw_bids(
    raw=raw, bids_path=bids_path, empty_room=bids_path_er, overwrite=True
)
```

The highlighted region would be simplified to the following:
```python
# 👇 👇 👇
write_raw_bids(
    raw=raw_er, bids_path=bids_path_er, is_empty_room=True,
    overwrite=True
)
# 👆 👆 👆
```
No need to fiddle with session name, subject, and task anymore.

**Comment by agramfort** [comment]
I am convinced !

**Comment by hoechenberger** [comment]
Just started working on this an wasn't super happy with how it turned out; bumping this to the 0.10 milestone and will confine myself to only renaming the existing `write_raw_bids()` parameter `empty_room` to something more explicit
