### ISSUE TITLE
command line interface for mne-bids

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#9]
Title says it all

**Comment by teonbrooks** [comment]
I started to work on this but just bumped up against `event_id`, which is a dict. how to handle this?

**Comment by jasmainak** [comment]
hum

I could live with a hack for now. Let the user pass the dict as a string and use `json.loads()`

**Comment by choldgraf** [comment]
+1 to letting it be a path to a json file that'd get loaded with `json.load` and, if it's not a valid file, attempted to load with `loads`

**Comment by teonbrooks** [comment]
I will finish this sometime this week
