### ISSUE TITLE
ImportError: cannot import name '_check_load_mat'

### ISSUE THREAD

**Issue by nblauch** [mne-tools/mne-bids#90]
Hi, I am attempting to use mne-bids for the first time. 

The command 'import mne_bids' throws the error:
ImportError: cannot import name '_check_load_mat'

I am using python3.6 with anaconda3. 

Any help is appreciated. Thanks
-Nick

**Comment by jasmainak** [comment]
Hi Nick, can you share the full traceback with us?

Mainak

**Comment by jasmainak** [comment]
And what version of `mne` are you using?

**Comment by nblauch** [comment]
Thx for quick reply. My mne is the version shipped with the mne envrionment from 'curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml'. This appears to be 0-16.2

Traceback (most recent call last):

  File "<ipython-input-9-b553cc368f26>", line 1, in <module>
    import mne_bids

  File "/home/nicholasblauch/anaconda3/envs/mne/lib/python3.6/site-packages/mne_bids/__init__.py", line 6, in <module>
    from .mne_bids import raw_to_bids  # noqa

  File "/home/nicholasblauch/anaconda3/envs/mne/lib/python3.6/site-packages/mne_bids/mne_bids.py", line 28, in <module>
    from .utils import (make_bids_filename, make_bids_folders,

  File "/home/nicholasblauch/anaconda3/envs/mne/lib/python3.6/site-packages/mne_bids/utils.py", line 22, in <module>
    from mne.io.eeglab.eeglab import _check_load_mat

ImportError: cannot import name '_check_load_mat'

**Comment by jasmainak** [comment]
I see. I think you might need bleeding edge `mne`. Sorry about this. You can install it by using the following command:

```sh
$ pip install git+https://github.com/mne-tools/mne.git#egg=mne
```

To check that it worked, you can do:

```sh
$ python -c "import mne; print(mne.__version__)"
```

Hopefully this will work for you. We'll work on removing dependency on bleeding edge MNE in the meanwhile. Let us know if it solves your problem.

**Comment by nblauch** [comment]
Nearly worked. Just needed to first do `$ pip uninstall mne` and change your pip install to `$ pip install git+https://github.com/mne-tools/mne-python.git#egg=mne` . 

Thanks Mainak. Cheers.

**Comment by jasmainak** [comment]
ha, indeed. Looking forward to more bug reports :)
