### ISSUE TITLE
mne_bids.get_entity_vals broken

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#907]
@hoechenberger @adam2392  this commit:

https://github.com/mne-tools/mne-bids/commit/893f9be2e277f1fa52c685f9dede8dcc469c4684

broke the mne bids pipeline where we use this option written in the doc:

```
    root : path-like
        Path to the "root" directory from which to start traversing to gather
        BIDS entities from file- and folder names. This will commonly be the
        BIDS root, but it may also be a subdirectory inside of a BIDS dataset,
        e.g., the ``sub-X`` directory of a hypothetical subject ``X``.
```

see the "may also be a subdirectory inside of a BIDS dataset,"

what was the issue with the other behavior?

**Comment by hoechenberger** [comment]
Oh. The issue was / is that we want to exclude certain subdirectories like derivatives, sourcedata etc. 

Previously we silently ignored derivatives

But I see the issue you're having 

Let's have a call?

**Comment by hoechenberger** [comment]
I had a call with @agramfort and will propose a fix later today.
