### ISSUE TITLE
[MAINT] Switch anonymize dict to TypedDict

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#913]
The dict keeps getting larger :) I'd propose to switch to a TypedDict now (with `total=False`)

_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-bids/pull/890#discussion_r748056370_

**Comment by sappelhoff** [comment]
- Once we drop support for Python 3.7 (TypedDict available starting with 3.8; https://docs.python.org/3/whatsnew/3.8.html#typing)
- see: https://peps.python.org/pep-0589/
- here: https://github.com/mne-tools/mne-bids/blob/213c3789390dfacc285418d8f54c6575ca104e7f/mne_bids/write.py#L2837-L2841

**Comment by sappelhoff** [comment]
closing this as subsumed by:

- https://github.com/mne-tools/mne-bids/issues/533
