### ISSUE TITLE
[MAINT] Fix installation page

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#915]
FYI: https://mne.tools/mne-bids/dev/install.html still shows diff dependencies then what's in the setup.cfg.

PS: Also, I'm down to move away from python 3.7 at some point that MNE does: https://github.com/mne-tools/mne-python

**Comment by hoechenberger** [comment]
We still have this issue for the latest stable and dev versions;
https://mne.tools/mne-bids/stable/install.html

@sappelhoff Care to take a look?
