### ISSUE TITLE
Supporting CNTs (Neuroscan) files

### ISSUE THREAD

**Issue by yjmantilla** [mne-tools/mne-bids#922]
#### Describe the problem

Hi mne-bids team. I was wondering if there was any reason for not supporting CNTs. I have run into some problems when using ``write_raw_bids`` and I noticed it was not on the list of eeg extensions:

https://github.com/mne-tools/mne-bids/blob/4c0755c6eb567c7840d70acf06f22201c5e75c65/mne_bids/config.py#L49-L55

Is there a reason for not supporting it beyond not being included on this dictionary?

**Comment by agramfort** [comment]
.cnt is not a format parf of the BIDS standard

https://bids-specification.readthedocs.io/en/bep-009/04-modality-specific-files/03-electroencephalography.html

**Comment by yjmantilla** [comment]
Thanks @agramfort , I mean as an input format (that is, I want to convert from cnt to any of the accepted bids formats).

Right now I think it is giving an error when it extracts the .cnt extesion and is not able to pass the ALLOWED_EXTENSIONS check:

https://github.com/mne-tools/mne-bids/blob/4c0755c6eb567c7840d70acf06f22201c5e75c65/mne_bids/write.py#L1365-L1383

Maybe I'm doing something wrong, Im just opening the file with the ``read_raw`` mne function and passing the Raw object to the  ```write_raw_bids`` function .

**Comment by yjmantilla** [comment]
Here is a colab with the replication of the error I get:

https://colab.research.google.com/drive/1cKaSnQglJwdLL-isNBlN6z5p_LixvkJN?usp=sharing

**Comment by hoechenberger** [comment]
@sappelhoff WDYT?

**Comment by sappelhoff** [comment]
Hi @yjmantilla :)

I think if we are supporting Nihon Kohden and Persyst, we might as well support CNT ... as long as all of these non-supported file formats get auto-converted into a BIDS supported format. Could be an added feature in a PR?

**Comment by agramfort** [comment]
sounds like a plan !

>

**Comment by yjmantilla** [comment]
@sappelhoff Thanks!

I could test what happens if one naively just adds the .cnt format to the MANUFACTURERS dictionary, and start from there what would be required to accept support cnt .
