### ISSUE TITLE
Anonymize Dataset Requires Destination Folder to not exist?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#923]
@hoechenberger 

I was trying out the anonymize_dataset for a set of subjects I wanted to then upload to openneuro. I only need to run it on a subset of subjects, so what I did was: 

- create a full copy of the original dataset
- delete the subset of subjects that weren't de-identified already
- then try to run `anonymize_dataset`

However, if I feed in `bids_root_out` as an existing folder it results in an error. Is this by design? If not, I'm wondering if we can perhaps allow the folder to already exist?

**Comment by hoechenberger** [comment]
> if I feed in `bids_root_out` as an existing folder it results in an error. Is this by design?

Yes, it's be design and was briefly touched upon in https://github.com/mne-tools/mne-bids/pull/893#discussion_r744104513

The thing is that it would be painful to support incremental anonymization, as we'd need to ensure that the same `daysback` and original subject name -> anonymized subject name mappings are being used.

If you have any ideas how to improve things, let's discuss!
