### ISSUE TITLE
MNE IO error for MEG empty room measurement info

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids#927]
Hi, I believe this [addition](https://github.com/mne-tools/mne-bids/commit/d1fb506e391742e048d02e0eb6d6bb4193d3dae7#r61723254) is causing issues for reading accompanying ERM data with wrt `cHPI` data in the BIDS metadata.

> Traceback (most recent call last):
> File "/Users/ktavabi/Github/mne-study-template/config.py", line 2279, in wrapper
> out = func(*args, **kwargs)
> File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/_01_maxfilter.py", line 140, in run_maxwell_filter
> raw_er = import_er_data(
> File "/Users/ktavabi/Github/mne-study-template/config.py", line 2921, in import_er_data
> raw_er = _load_data(cfg, bids_path_er_in)
> File "/Users/ktavabi/Github/mne-study-template/config.py", line 2695, in _load_data
> raw = read_raw_bids(bids_path=bids_path)
> File "/Users/ktavabi/Github/mne-bids/mne_bids/read.py", line 628, in read_raw_bids
> raw = _handle_info_reading(sidecar_fname, raw, verbose=verbose)
> File "/Users/ktavabi/Github/mne-bids/mne_bids/read.py", line 320, in _handle_info_reading
> raw.info['hpi_subsystem'] = None
> File "/Users/ktavabi/Github/mne-python/mne/io/meas_info.py", line 761, in setitem
> raise RuntimeError(self._attributes[key])
> RuntimeError: hpi_subsystem cannot be set directly.
> /Users/ktavabi/Github/mne-python/mne/io/meas_info.py(761)setitem()
> raise RuntimeError(self._attributes[key])

**Comment by hoechenberger** [comment]
Hello, thanks for reporting this! Which version of MNE-BIDS are you using? I think this problem should not be present with MNE-BIDS 0.9 🤔

**Comment by agramfort** [comment]
is it a new error we have now?

>

**Comment by hoechenberger** [comment]
I thought that we shouldn't see this with 0.9, but I haven't had the time to try to reproduce yet

@ktavabi if you could share a file and minimal working example that reproduces the issue, it would be of great help 👍👍👍

**Comment by ktavabi** [comment]
Sorry, @hoechenberger, you are correct. I was on a rouge `master` branch. Thanks.

**Comment by hoechenberger** [comment]
Great to hear this has been resolved, then! 😊
