### ISSUE TITLE
split fif file

### ISSUE THREAD

**Issue by dnacombo** [mne-tools/mne-bids#939]
Reading a large fif file, mne-bids seems to look for an oddly named companion:

/network/lustre/iss01/cenir/analyse/meeg/EMPTY/sourcedata/sub-Paris_ses-201811270935SOMALS2_task-EmptyRoom_meg.fif
mne-bids then looks for a companion named 
/network/lustre/iss01/cenir/analyse/meeg/EMPTY/sourcedata/sub-Paris_ses-201811270935SOMALS2_task-EmptyRoom_meg.fi-2.fif

There seems to be an issue accounting for file extension.
Note: the first file is a symlink, it case that matters...

**Comment by hoechenberger** [comment]
Ouch! What's the actual name of the companion file?

Can you do:

```python
import mne

raw = mne.io.read_raw('/network/lustre/iss01/cenir/analyse/meeg/EMPTY/sourcedata/sub-Paris_ses-201811270935SOMALS2_task-EmptyRoom_meg.fif')
print(raw.filenames)
```
and share the output with us? Thank you!

**Comment by dnacombo** [comment]
Hey,
The companion file is called emptyroom-1.fif in the target directory.

I fixed it by adding symlinks to the other parts as
/network/lustre/iss01/cenir/analyse/meeg/EMPTY/sourcedata/sub-Paris_ses-201811270935SOMALS2_task-EmptyRoom_meg-1.fif
/network/lustre/iss01/cenir/analyse/meeg/EMPTY/sourcedata/sub-Paris_ses-201811270935SOMALS2_task-EmptyRoom_meg-2.fif

Don't ask me why this recording is so looong...

Thanks

**Comment by hoechenberger** [comment]
I wonder if some files were renamed after first writing them. Normally MNE tracks the filenames in `raw.filenames` 🤔

**Comment by hoechenberger** [comment]
If you want, you can also share these files with me so I can have a look!

**Comment by hoechenberger** [comment]
Closing, but feel free to re-open if the issue pops up again!
