### ISSUE TITLE
Hyperlink's not working

### ISSUE THREAD

**Issue by Swastyy** [mne-tools/mne-bids#970]
#### Describe the bug
None of the links provided [here](https://github.com/mne-tools/mne-bids/blob/maint/0.9/doc/whats_new.rst#id119) is working.

#### Steps to reproduce
〈Replace this text with a code snippet or minimal working example [MWE] to
replicate your problem, using one of the [datasets shipped with MNE-Python],
preferably the one called [sample].
If you can't replicate on a built-in dataset, provide also
a link to a small, anonymized portion of your data that does yield the error.〉

[MWE]: https://en.wikipedia.org/wiki/Minimal_Working_Example
[built-in datasets]: https://mne.tools/dev/overview/datasets_index.html
[sample]: https://mne.tools/dev/overview/datasets_index.html#sample

#### Expected results
〈Replace this text with a clear and concise description of what you expected to
happen.〉

#### Actual results
〈Replace this text with the actual output, traceback, screenshot, or other
description of the results.〉

#### Additional information
〈Replace this text with information about your system. For example through
using MNE-Python and running `mne.sys_info()` and pasting the output here.〉

**Comment by agramfort** [comment]
the page you point to in the source page of this rendered HTML doc page
https://mne.tools/mne-bids/stable/whats_new.html
