### ISSUE TITLE
Cut release

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#972]
I'd love to cut a 0.10 release within the next few days for inclusion in the MNE-Python 1.0 installers.

I don't see any blockers in the current [list of milestone tasks](https://github.com/mne-tools/mne-bids/milestone/10).

Only thing I'd love to get merged before the release is #969 **edit** and #968, but I need to put some work into this and convince @agramfort that we want to have this 😁 But I'm quite confident I can do that. 👍

cc @larsoner

**Comment by larsoner** [comment]
It would be nice to include https://github.com/mne-tools/mne-bids/pull/406 if possible!

**Comment by sappelhoff** [comment]
Nirs is not yet officially included in bids, but adding experimental support wouldn't hurt, I think!

**Comment by hoechenberger** [comment]
Alright, this is the last remaining issue on our 0.10 mailestone plan!

**Comment by sappelhoff** [comment]
ship it!!! :rocket:
