### ISSUE TITLE
Problem with accentuated characters

### ISSUE THREAD

**Issue by christian-oreilly** [mne-tools/mne-bids#987]
#### Describe the bug
This issue is similar to the bug fixed in #172. In .json files loaded with MNE-BIDS, different fields may have non-UTF-8 characters, like accentuated characters. These would appear in many institutions or person names, e.g., for French names. For example, MNE-BIDS crashes when important data from that open-access dataset: https://search.kg.ebrains.eu/instances/Dataset/1e5ec1d6-a17d-46ed-8e8b-05c2673dbc0e It crashed because the .json file contains:

      {
      ...
	      "InstitutionName": "Hôpital Pierre Wertheimer",
      ...
      }

That is not a problem specific to MNE-BIDS. The following code reproduce the error triggered by MNE-BIDS when using `read_raw_bids(...)` on this dataset:

      import json
      json.loads(open("/Users/christianoreilly/Downloads/sub-071_task-MCSE_ieeg.json").read())

produces

    ---------------------------------------------------------------------------
    UnicodeDecodeError                        Traceback (most recent call last)
    /var/folders/_r/pjcpg0r91hd_pj072jq4zws00000gn/T/ipykernel_7841/70971748.py in <module>
    ----> 1 json.loads(open("/Users/christianoreilly/Downloads/sub-071_task-MCSE_ieeg.json", encoding='utf-8').read())
    
    ~/opt/anaconda3/lib/python3.8/codecs.py in decode(self, input, final)
        320         # decode input (taking the buffer into account)
        321         data = self.buffer + input
    --> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
        323         # keep undecoded input until the next call
        324         self.buffer = data[consumed:]
    
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 45: invalid continuation byte

This is an issue that is likely to be common in many non-English speaking countries. We cannot expect the JSON files containing information like institution names across the world to be limited to the English character subsets, so MNE-BIDS should probably aim to support this use case.

#### Additional information
      Platform:      macOS-10.16-x86_64-i386-64bit
      Python:        3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ]
      Executable:    /Users/christianoreilly/opt/anaconda3/bin/python
      CPU:           i386: 16 cores
      Memory:        64.0 GB
      
      mne:           0.23.4
      numpy:         1.22.2 {}
      scipy:         1.6.2
      matplotlib:    3.4.2 {backend=module://matplotlib_inline.backend_inline}
      
      sklearn:       0.24.2
      numba:         0.53.1
      nibabel:       3.2.1
      nilearn:       Not found
      dipy:          1.4.1
      cupy:          Not found
      pandas:        1.4.1
      mayavi:        Not found
      pyvista:       0.32.1 {OpenGL 4.1 ATI-4.7.103 via AMD Radeon Pro 5500M OpenGL Engine}
      vtk:           9.0.3
      PyQt5:         5.9.2

**Comment by hoechenberger** [comment]
Hello @christian-oreilly,

the JSON standard demands that the file be encoded in UTF-8; otherwise it's not valid JSON.

Now, this does **not** mean that accents etc. are not supported – quite the opposite.

In fact, we **do** test certain parts of MNE-BIDS for working with non-ASCII characters, e.g.:
https://github.com/mne-tools/mne-bids/blob/d717ea749fc6618f5a62156c3e8fb8f6af9cdbc8/mne_bids/tests/test_write.py#L2879-L2883



> MNE-BIDS crashes when important data from that open-access dataset: https://search.kg.ebrains.eu/instances/Dataset/1e5ec1d6-a17d-46ed-8e8b-05c2673dbc0e

I cannot access the dataset. Could you please share the entire traceback?

Are you perhaps working on Windows? Because then, I have a suspicion, because …



> ```
>   import json
>   json.loads(open("/Users/christianoreilly/Downloads/sub-071_task-MCSE_ieeg.json").read())
> ```

… this is actually **bound** to fail on Windows, while it will work on Linux and macOS.

Background is that the default charset on on Windows is not UTF-8, but CP1252. So if you don't specify an encoding, your example is bound to fail. This should work:

```python
import json
json.loads(open("/Users/christianoreilly/Downloads/sub-071_task-MCSE_ieeg.json", encoding='utf-8').read())
```

My suspicion is that we simply forgot in one line of MNE-BIDS to add the encoding. To check this assumption, however, I need the full traceback.

Best wishes,

Richard

**Comment by hoechenberger** [comment]
Looking at your paths and at the error message again, it appears you're working on macoS?

Could you perhaps share the affected JSON file with me?

**Comment by hoechenberger** [comment]
> the JSON standard demands that the file be encoded in UTF-8; otherwise it's not valid JSON.

Actually I just looked at the JSON standard again and it says the encoding "SHALL" be UTF-8, not "MUST".

However, the BIDS specification is very clear on this:

> JSON files MUST be in UTF-8 encoding.

https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#keyvalue-files-dictionaries

So I assume that the dataset you're using doesn't conform to the BIDS specification.

**Comment by hoechenberger** [comment]
> > the JSON standard demands that the file be encoded in UTF-8; otherwise it's not valid JSON.
> 
> Actually I just looked at the JSON standard again and it says the encoding "SHALL" be UTF-8, not "MUST".

… with the exception for operating in a non-closed ecosystem:

> JSON text exchanged between systems that are not part of a closed
>    ecosystem MUST be encoded using UTF-8 [[RFC3629](https://datatracker.ietf.org/doc/html/rfc3629)].

https://datatracker.ietf.org/doc/html/rfc8259

So based on that … the data you're trying to read is most likely not valid JSON.

**Comment by hoechenberger** [comment]
@christian-oreilly Could you by any chance run the [BIDS validator](https://bids-standard.github.io/bids-validator/) on the dataset to check whether it's valid BIDS?

**Comment by christian-oreilly** [comment]
@hoechenberger Sorry for the slow feedback. First, I noticed this error while working with a student on her project, so I have not downloaded the corresponding dataset myself and I don't have the full stack, but the dataset is available upon request at the URL provided in the report. Even if I downloaded it, I am not sure I would have the right to redistribute directly.

However, I asked the student to share the JSON file and I suppose that there is no harm in sharing directly that file: [sub-071_task-MCSE_ieeg.json.txt](https://github.com/mne-tools/mne-bids/files/8358184/sub-071_task-MCSE_ieeg.json.txt) I added a .txt extension for GitHub to accept it. The issue is with the ô character, even when using 

```
import json
json.loads(open("/Users/christianoreilly/Downloads/sub-071_task-MCSE_ieeg.json", encoding='utf-8').read())
```
which generate:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-8-055122671214> in <module>
      1 import json
----> 2 json.loads(open("/home/christian/Downloads/sub-071_task-MCSE_ieeg.json", encoding='utf-8').read())

~/anaconda3/lib/python3.8/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 45: invalid continuation byte
```
Note that 0xf4 is not the utf-8 encoding for ô; the page https://www.compart.com/en/unicode/U+00F4 gives as utf-8 encoding: `0xC3` `0xB4`. `0x00F4` would be the utf-16 encoding. When trying to load with utf-16 encoding, it seems to manage this character corectly, just to crash further down with:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-14-72ea2418c620> in <module>
----> 1 open("/home/christian/Downloads/sub-071_task-MCSE_ieeg.json.txt", encoding='utf-16').read()

~/anaconda3/lib/python3.8/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

~/anaconda3/lib/python3.8/encodings/utf_16.py in _buffer_decode(self, input, errors, final)
     59         if self.decoder is None:
     60             (output, consumed, byteorder) = \
---> 61                 codecs.utf_16_ex_decode(input, errors, 0, final)
     62             if byteorder == -1:
     63                 self.decoder = codecs.utf_16_le_decode

UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 1078: truncated data
```

Further, when copying the JSON string from the file into a notebook and directly loading it as json (showing just the relevant part)
```
json.loads('''{
	"InstitutionName": "Hôpital Pierre Wertheimer"
}''')
```
it works fine. So, I am not sure what the problem is with that file, but I think you are probably right that the problem lies with the generation of these .json files more than with MNE. You can probably close the ticket as this problem would better be reported to the database owners than to mne-bids.

**Comment by agramfort** [comment]
I tried to download the files but I fail to download more than one file at
a time.

anyone I can ping about this?

**Comment by agramfort** [comment]
ok I managed to download one subject and test the data with the
bids-validator:

 2: [ERR] JSON files must be valid utf-8. (code: 123 - INVALID JSON
ENCODING)
./sub-001/ieeg/sub-001_task-LEC1_ieeg.json

if I remove the ô in "Hôpital" than it works. So the file is not valid
according to the standard

**Comment by christian-oreilly** [comment]
Yes, that was also our get-around to work with this dataset (manually replace the ô by o). I thought that the issue was that MNE-BIDS was not supporting non-ascii-characters, but apparently, it is a problem by how they (at HBP) encoded these files.

**Comment by christian-oreilly** [comment]
Just emailed curation-support@ebrains.eu to let them know about the issue.

**Comment by hoechenberger** [comment]
I believe it's a latin-1 charset. The providers of the dataset need to fix it... I don't think there is nothing much we can do... except allowing for a custom specification of the encodings, but this will be useless unless those who create the dataset also specify which encodings were used.

**Comment by eapapp** [comment]
Thank you all for identifying and brainstorming this issue, and in particular @christian-oreilly for letting us at EBRAINS know. We have identified 575 JSON files in this dataset with the wrong encoding, and updated those to UTF-8. I think that solves the issue.

**Comment by hoechenberger** [comment]
Amazing!! 👌

**Comment by christian-oreilly** [comment]
Great! I think this issue can be closed now, but I'll let @hoechenberger or @agramfort take this action in case you guys think that some changes to mne-bids should be done regarding this issue. Aside from crashing more gracefully in case of incompatible encoding, I don't think much more can be done on mne-bids side if similar issues arising in the future.
