### ISSUE TITLE
minor: sort scans.tsv by acquisition time?

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#992]
Currently we don't do that, but I think it'd make sense to sort the rows in scans.tsv by `acquisition_time`

**Comment by adam2392** [comment]
Say multiple scans are labeled in different run orders relative to their acquisition time, it'd be nice to also fire a warning in this case.

**Comment by hoechenberger** [comment]
> Currently we don't do that, but I think it'd make sense to sort the rows in scans.tsv by `acquisition_time`

I don't see any harm in this, so why not… but I personally would always open this file in Pandas or Excel or so and sort it the way I want

**Comment by sappelhoff** [comment]
reconsidering ... I don't know why I thought this was worthwhile.
